= About the XML Configuration File
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: configuration, deploy, mule

All Mule applications, domain and policies are configured via an XML DSL. Their XML file specifies the resources that compose the artifact. https://www.w3.org/TR/xmlschema-1/#xsi_schemaLocation[Schemas] define the configurable attributes of these resources that are referenced in the XML Configuration file. This is how a Mule artifacts both validate and define its functional components and their configuration.

== XML Schema

XML schemas are used to validate functional components in a Mule artifact. They are specified in the header.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
        xmlns:jms="http://www.mulesoft.org/schema/mule/jms"
        xmlns:file="http://www.mulesoft.org/schema/mule/file"
        xsi:schemaLocation="
        http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
        http://www.mulesoft.org/schema/mule/jms http://www.mulesoft.org/schema/mule/jms/current/mule-jms.xsd
        http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd">
----

[NOTE]
Mule domains feature the `mule-domain` tag instead of `mule`.

Be sure to specify all the necessary schema files. This can be time-consuming when setting up the configuration file by hand, but importing schema files provides the following time-saving benefits:

* Auto-completion and context-specific help in your favorite IDE
* Design-time configuration validation
* Typed properties

[NOTE]
Anypoint Studio will add the required schemas as components are introduced.


== Namespaces

Each Mule module or connector has its own XML schema, including Mule core for it's community and enterprise versions. When you import a schema, it has its own namespace.

To use the standard Mule elements, import the CE and EE namespaces:

* http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd

* http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd

=== Default Namespace

Typically, you set the Mule core schema as the default namespace for your configuration file. This means that any XML element without a prefix will come from the Mule core schema. To set the default namespace schema, specify `xmlns` immediately followed by the URL of the Mule schema, without the colon or namespace prefix you set in the previous example (e.g., `xmlns` instead of `xmlns:jms`):

[source,xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">
   ...config...
</mule>
----

== Merging Configuration Files

If you have multiple configuration files, you can import them into one configuration file so that you only have to specify one configuration.
This is useful to extract connector configurations or other global elements. For example:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns=http://www.mulesoft.org/schema/mule/core ....>

    <import file="global-prod-configurations.xml" />
    <import file="global-error-handler.xml" />
...
----

These imports can also be dynamic when combined with properties:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns=http://www.mulesoft.org/schema/mule/core ....>

    <global-property name="env" value="dev"/>
    <import file="global-${env}-configurations.xml" />
...
----

== Declaring Multiple Configurations

You can also keep your files separate as long as you declare them as part of your application
configurations. This is useful when each configuration file is relatively unrelated to the others. Configurations are
declared on the application descriptor file, `mule-artifact.json`, within the `configs` section. For example, four configuration files are declared here:

[source,json,linenums]
----
{
  "configs": [
    "http-api.xml", "jms-messaging-api.xml", "monitoring-tools.xml", "core-functionality.xml"
  ],
  "redeploymentEnabled": true,
  "name": "retail-api",
  "minMuleVersion": "4.1.1",
  "requiredProduct": "MULE_EE",
  "classLoaderModelLoaderDescriptor": {
    "id": "mule",
    "attributes": {
      "exportedResources": []
    }
  },
  "bundleDescriptorLoader": {
    "id": "mule",
    "attributes": {}
  }
}
----

[NOTE]
Anypoint Studio will handle the application descriptor automatically.

== See Also

* xref:shared-resources.adoc[Mule Domains]
* xref:api-manager::custom-policy-getting-started.adoc[Mule Custom Policies]
* xref:configuring-properties.adoc[Configuring Properties]
* xref:intro-packaging.adoc[Packaging Applications]
