= Advanced Mule Concepts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: advanced, mule, concepts, runtime, engine

After you become familiar with the basics of Mule application development and Mule runtime engine (Mule) concepts, you can focus on more advanced features, such as the execution engine, the classloading isolation mechanism, and the distributed file polling feature.

This section covers some advanced Mule topics that will be useful once you are familiar with the basics of Mule application development and Mule runtime engine concepts.

Learn about the xref:execution-engine.adoc[execution engine] to understand how Mule runtime engine processes the operations in a Mule application flow, and to understand how to change the thread pools if needed. Mule runtime engine uses execution metadata provided by operations in a flow to perform autotuning.

The xref:about-classloading-isolation.adoc[classloading isolation] mechanism implemented in Mule 4 is designed to make upgrades easier by preventing components from exposing their internal resources. All components interact with each other through their defined APIs so that only exposed resources can be accessed by other components. Classloading isolation ensures that a component's internal content is protected and can be changed any time, without affecting other components.

Mule 4 supports xref:distributed-file-polling.adoc[distributed file polling], which allows connectors to read files from certain directories as they are created. Distributed file polling also makes it possible to poll files in all cluster nodes.

You can refer to the xref:mule-4-api-javadoc.adoc[Javadocs] for Mule Kernel (the community edition of Mule runtime engine) to learn definitions for classes, fields, and data types.

You can see a list of xref:third-party-software-in-mule.adoc[third-party software] that is included as part of Mule runtime engine as internal dependencies.
