= Advanced Mule Concepts
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: advanced, mule, concepts, runtime, engine

This section covers some advanced Mule topics that will be useful once you are familiar with the basics of Mule application development and Mule runtime engine concepts.

Learn about the xref:execution-engine.adoc[Execution Engine] to understand how the Mule runtime engine processes the operations in a Mule application’s flow, and understand how to change the thread pools if needed. Mule runtime engine uses execution metadata provided by operations in a flow to perform auto-tuning.

The xref:about-classloading-isolation.adoc[Classloading Isolation] mechanism implemented in Mule 4 is designed to make upgrades easier by preventing components from exposing their internal resources. All components interact with each other through their defined APIs, meaning that only exposed resources can be accessed by other components. Classloading isolation ensures that a component's internal content is protected and can be changed anytime without affecting other components. 

Mule 4 supports xref:distributed-file-polling.adoc[Distributed File Polling], which allows connectors to read files from certain directories as they are created, and it also makes it possible to poll files in all cluster nodes.

You can check the xref:mule-4-api-javadoc.adoc[Javadocs] for the Mule Kernel, the Community Edition of the Mule runtime engine, to see definitions for classes, fields and their data types.

You can see a list of xref:third-party-software-in-mule.adoc[Third-party software] that is included as part of Mule runtime engine as internal dependencies.


the original motivation of classloading isolation is to make upgrades easier by not allowing a component to expose its internals which may change, and components to interact between themselves through a well defined, complete and as-minimal-as-possible api.
