= All Flow Control Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, components, elements, flow control

[WARNING]
====
With the release of Anypoint Studio May 2014 with 3.5.0 Runtime, and its new Scatter-Gather flow control, comes the *deprecation of the All flow control*. Applications that use the All flow control will continue to work with the 3.5.0 Enterprise Runtime, but the flow control is no longer available in the Studio palette to add to applications.

Access the documentation for the xref:3.7@scatter-gather.adoc[Scatter-Gather flow control] to take advantage of the newly-designed functionality.
====

*Purpose:* Sends the same message to multiple target message processors.

*Discussion:* Use the All Flow Control to route or broadcast the same message to more than one processor component.

In many cases, All sends messages to connectors. If the connector has a filter associated to it, then the message must pass through the filtering criteria in order for the connector to receive it.

If the targets receiving messages from the All Flow Control also return messages, then these return messages, if any, are aggregated together and collectively form the response.