= Alternate Ways of Running Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This section describes ways of running Mule other than from the command prompt.

== Running Mule From the IDE

. Choose *File > New > Project*, expand the Mule folder and select *Mule Project*, and then click *Next*.
. Enter a name for the project, ensuring that there is no space in the project name. If you want to put the project in a location other than the default workspace, clear the *Use default location* check box and specify a new file location.
. Click *Finish* so the Mule IDE will generate your project.

== Running Mule Programmatically in Java

To run Mule from any Java application, you can call one of its configuration builders. To use Mule XML configuration:

[source,text,linenums]
----
DefaultMuleContextFactory muleContextFactory = new DefaultMuleContextFactory();
SpringXmlConfigurationBuilder configBuilder = new SpringXmlConfigurationBuilder("mule-config.xml");
muleContext = muleContextFactory.createMuleContext(configBuilder);
----

Make sure you store a reference to the MuleContext, as you will need it to stop Mule.

If you have multiple configuration files, you can provide a comma-separated list or an array of configuration files:

[source,text,linenums]
----
SpringXmlConfigurationBuilder configBuilder =
     new SpringXmlConfigurationBuilder(new String[] { "mule-config.xml", "another-config.xml" });
----

You then call the start method to start the server:

[source,text,linenums]
----
muleContext.start();
----