= Anypoint Connectors (for Mule 3)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Connectors are extensions of Mule that let you work with external systems such as Salesforce, 
ServiceNow, Workday, Twitter, and more to send and receive information from these systems to create something new.

Anypoint Connectors let you connect Mule applications to APIs and resources. You can use connectors within your 
Mule applications to send and receive data over a protocol, or to and from an API.

You can create applications in Anypoint Studio by installing a connector from Anypoint Exchange, 
and then dragging the connector to the Studio canvas. 

When you add a connector to the start of a flow, it's known as a message processor
because it starts the Mule flow by receiving information from the connector's resource. For example, 
when a Salesforce user updates a sales opportunity, the connector application can receive 
the information and direct it to a database or to another connector for processing. 

Similarly, you can use the HTTP connector as the message processor so that users can send information to your 
Studio application using a web browser, Postman, or the curl command.

The list of https://www.mulesoft.com/exchange/?search=Mule%203&type=connector[Mule 3 connectors in Exchange] 
provide descriptions and helpful links that help you understand how each works.

In addition, Exchange provides Mule 3 https://www.mulesoft.com/exchange/?search=Mule%203&type=template[templates] and https://www.mulesoft.com/exchange/?search=Mule%203&type=example[examples] that let you jump start application development.


[IMPORTANT]
====
For Mule 4 connectors, see xref:connectors::index.adoc[Connectors and Modules (for Mule 4)].
====

== Install a Connector

. In Anypoint Studio, click the Exchange icon in the Studio taskbar.
. Click Login in Anypoint Exchange.
. Search for the connector and click Install.
. Follow the prompts to install the connector.

== How to Use a Connector

For a tutorial on basic connector usage, see the xref:general:getting-started:anypoint-connector.adoc[Anypoint Connector quickstart].

You can import additional connectors into your Studio project, or manually create applications using connectors, outside of the Studio development environment, by adding them as Maven dependencies, or including the required connector libraries with your project.

== Connector Support Categories

MuleSoft provides different. See https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[Connector Support Policies] depending on which connector you use. 

[%header,cols="2*a"]
|===
|Type |Description
|*Community*
|

MuleSoft or members of the MuleSoft community write and maintain the https://anypoint.mulesoft.com/exchange/?search=community[Community connectors] Connectors built by the community or MuleSoft are generally open-source, although each package may vary. Partner-built connectors may not be open-source. Contact the partner directly for more information. You do not need any special account or license to use a Community connector.

|*MuleSoft Certified*
|

https://anypoint.mulesoft.com/exchange/?search=mulesoft-certified[MuleSoft Certified connectors] are developed by MuleSoft’s partners and developer community and are reviewed and certified by MuleSoft. For support, customers should contact the MuleSoft partner that created the MuleSoft Certified connector.

|*Select*
|

MuleSoft maintains https://anypoint.mulesoft.com/exchange/?search=select[Select connectors]. Connectors included in the open source Mule distribution can be used by everyone, however support is only included in an Anypoint Platform subscription. To use all other Select Connectors and access support, you must have an active Anypoint Platform subscription.

|*Premium*
|

MuleSoft maintains https://anypoint.mulesoft.com/exchange/?search=premium[Premium connectors]; you must have an active CloudHub Premium plan or an Enterprise subscription with an entitlement for the specific connector you wish to use.
|===

== Develop Your Own Connector

You can also create a xref:publishing-and-consuming-apis-with-mule.adoc[REST or SOAP API connector], or create your own connectors using xref:3.8@connector-devkit::index.adoc[Anypoint Connector DevKit]. For more information on integration solutions, see the https://www.mulesoft.com/platform/cloud-connectors[Anypoint Connectors] product site.

== See Also

* If you need help with a connector, search http://forums.mulesoft.com[MuleSoft's Forums] for solutions and ideas.
* Review the https://support.mulesoft.com/s/knowledge[MuleSoft Knowledge Base articles].
