= Application Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== General Definition

A Mule application is either a:

* *Zip* file. Yes, that's a regular archive with a 'zip' extension.
* Unpacked version of the same zip (exploded app)

This deployment unit encapsulates everything an application would need to function, such as libraries, custom code, configuration, deployment descriptor and any environment properties accompanying the application. There is also a way to share libraries between applications via the *domain* xref:deployment-descriptor.adoc[deployment descriptor] attribute, which provides for smaller application archives at the expense of a dependency on container being properly setup.

== Application structure

A Mule _application_ has a structured layout under `$MULE_HOME/apps`.

Mule will support both packaged and exploded deployment.

[source,text,linenums]
----
/
 \- classes                 // application-specific expanded resources (e.g. logging configuration files, properties, etc
 |- lib                     // application-specific jars
 |- mule-config.xml         // Main Mule configuration file, also monitored for changes
 |- mule-deploy.properties  // Application deployment descriptor (optional)
 |- mule-app.properties     // custom properties to be added to the registry instance used by the application (optional)
----