= OAuth Authorization Grant Types
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: http, authentication, security, users, connectors, anypoint, studio, oauth

There are four types of authorization grants that an OAuth consumer (that is, a client app) can use to obtain access to a protected resource from an OAuth service provider.

. <<Authorization Code>>

. <<Implicit>>

. <<Resource Owner Password Credentials>>

. <<Client Credentials>>

The sections below describe of each type of authorization grant according to the level of security, in descending order. Refer to the xref:mule-secure-token-service.adoc[Mule Secure Token Service] document for additional details regarding OAuth roles and the OAuth dance.

== Authorization Code

The Authorization Code grant type uses an *authorization server* (responsible for confirming and granting permission to access the protected resource) and a *resource server* (responsible for providing access to the protected resource). Though described as independent servers, the authorization and resource servers actually reside on the same Mule server. With this grant type, a client app must ask for a service provider’s permission to ask for protected resources. Then it can ask for the protected resources.

An OAuth dance that involves an Authorization Code grant type works as follows:

. Client app wants to use a protected resource housed by the service provider, so the client initiates a request to access the resource.

. Client app calls the service provider's authorization server, providing its client ID to confirm that it is a registered client of the service provider.

. Client app uses a login page supplied by the service provider to ask that the resource owner authenticate itself to the service provider.

. After confirming that the client ID is valid (that is, the client app had previously registered with the service provider), and authenticating the resource owner's login credentials, the service provider returns an authorization code.

. Client app calls the authorization server again, and provides its authorization code, client ID (again), and client secret.

. Service provider returns a token in which it specifies the scope of access.

. Client app calls the resource server, providing the token, to request the protected resource.

. Service provider delivers the protected resource.

The Authorization Code grant type is especially secure, because it authenticates the client and transmits the token without exposing the token to unauthorized parties, including the resource owner.

== Implicit

As with the Authorization Code grant type, an Implicit grant type involves both an authorization server and a resource server. However, rather than taking the extra steps to authenticate a client application by using an authorization code and client secret, the service provider:

* Authenticates a client based upon its client ID.

* Provides the token to access the protected resource.

An OAuth dance that involves an Implicit Grant type works as follows:

. Client app wants to access a protected resource housed by the service provider, so the client initiates a request to access the resource.

. Client app calls the service provider's authorization server, providing its client ID to confirm that it is a registered client of the service provider.

. Client app uses a login page supplied by the service provider to ask that the resource owner authenticate itself to the service provider.

. After confirming that the client ID is valid (that is, the client app had previously registered with the service provider), and authenticating the resource owner's login credentials, the service provider returns an authorization code.

. Client app calls the resource server, providing the token, to request the protected resource.

. Service provider delivers the protected resource.

A simplified version of Authorization Code grant type, the Implicit grant type optimizes performance for browser clients that use a scripting language, such as Javascript. However, this grant type can expose the token to the resource owner or the resource owner's user-agent.

== Resource Owner Password Credentials

With the Resource Owner Password Credentials grant type, a client application demands that the resource owner share their service provider login credentials. The client app then uses these credentials to access the service provider and log into the resource owner's account. The service provider accepts the valid login credentials and grants the client app full access to the resource owner's account. The resource owner, in this case, must trust the client app not to abuse their trust in sharing access to private data.

This type of authorization, optimizes performance at the expense of sharing secure access credentials.

An OAuth dance that uses the resource owner password's credentials works as follows:

. Resource owner provides access credentials to the client app.

. Client app calls the service provider to request a token. During the call, the client provides the client ID to confirm that it is a registered client of the service provider, and also provides the access credentials for the protected resource.

. Service provider authenticates the client app and validates the access credentials. Then it issues a token.

. Client app calls the resource server, providing the token, to request access to the protected resource.

. Service provider delivers the protected resource.

== Client Credentials

With the Client Credentials grant type, a client app requests access to data that is not associated with a particular resource owner. Because no protected resources are involved, a service provider must only verify the client as valid. This type of OAuth interaction is sometimes referred to as "two-legged OAuth" because it involves only two roles: the service provider and a client app.  The other three authorization types involve a third role, the resource owner. Thus, they are sometimes referred to as "three-legged OAuth".

This authorization grant typically applies when the the client is also the resource owner.

An OAuth dance that uses the Client Credentials grant type works as follows:

. Client app calls the authorization server, providing a client ID to confirm that it is a registered client of the service provider.

. After confirming that the client ID is valid (that is, the client app had previously registered with the service provider), the service provider returns a token.

. Client app calls the resource server, providing the token, to request the protected resource.

. Client app retrieves the protected resource.
