= FAQ: How to Handle Failures During a Batch Job
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When processing a batch job instance, a processor inside a batch step may fail or raise an error. There are three options for handling errors at a record-level:

. *Finish processing* Stop the execution of the current job instance. Finish the execution of the records currently in-flight, but do not pull any more records from the queues and set the job instance into a `FAILURE` state. The On Complete phase is invoked.
. *Continue processing* the batch regardless of any failed records, using the `acceptExpression` and `acceptPolicy` attributes to instruct subsequent batch steps how to handle failed records
. *Continue processing* the batch regardless of any failed records (using the `acceptExpression` and `acceptPolicy` attributes to instruct subsequent batch steps how to handle failed records), until the batch job accumulates a *maximum number of failed records* at which point the execution will halt just like in option 1.

By default, Mule's batch jobs follow the first error handling strategy which halts the batch instance execution. The above behavior is controlled through the `maxFailedRecords` attributes

[%header,cols="30a,40a,30a"]
|===
|Failed Record Handling Option 2+^|Batch Job
| | *Attribute* | *Value*
| Stop processing when a failed recod is found
| `maxFailedRecords`|`0`
| Continue processing indefinitely, regardless of the number of failed records
| `maxFailedRecords` |`-1`
| Continue processing until reaching maximum number of failed records
| `maxFailedRecords` | `integer`
|===

[source,xml,linenums]
----
<batch:job jobName="Batch1" maxFailedRecords="0">
----

== Crossing the Max Failed Threshold

When a batch job accumulates enough failed records to cross the the `maxFailedRecords` threshold, Mule aborts processing for any remaining batch steps, skipping directly to the On Complete phase.

For example, if you set the value of `maxFailedRecords` to "10" and a batch job accumulates 10 failed records in the first of three batch steps, Mule does not attempt to process the batch through the remaining two batch steps. Instead, it aborts further processing and skips directly to On Complete to report on the batch job failure.

If a batch job _does not_ accumulate enough failed records to cross the `maxFailedRecords` threshold, _all_ records – successes and failures – continue to flow from batch step to batch step; use filters to control which records each batch step processes.

== See Also

* xref:filter-records-batch-faq.adoc[FAQ: How to Filter Records in a Batch Step]