= Batch Processors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: connectors, anypoint, studio, batch, batch processing

[NOTE]
Batch processing is exclusive to Mule Enterprise runtimes.

Mule allows you to process messages in batches. +
Within an application, you can initiate a batch job scope that splits large or streamed messages into individual records, performs actions upon each record, reports on the results, and potentially pushes the processed output to other systems or queues.

//_TODO: Check this
// *Are there any message processors that you cannot use in batch processing?* +
// The only element you cannot use in batch processing is a *request-response inbound connector.* Otherwise, you are free to leverage any and all Mule message processors to build your batch processing flow.

Batch processing is particularly useful when:

* Integrating data sets, small or large, streaming or not, to parallel process records.

* Synchronizing data sets between business applications, such as syncing contacts between NetSuite and Salesforce in "near real-time" data integration.

* Extracting, transforming and loading (ETL) information into a target system, such as uploading data from a flat file (CSV) to Hadoop.

* Handling large quantities of incoming data from an API into a legacy system.

== See Also

* xref:batch-job-concept.adoc[Batch Job Component]

// broken: * link:batch-phases-concept[About Batch Phases]
