= To Configure Custom Business Events
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use Custom Business Event (`tracking:custom-event`) components to add metadata and Key Performance Indicators (KPIs) to your flow.

. In your Mule app, add the Custom Business Event component to a flow.
. Click to open the component.
. Type values for Display Name and Event Name.
. Optionally, add Key Performance Indicators (KPIs) to capture information from the message payload:
+
* Name (`key`) for the PKI (`tracking:meta-data` element).
+
Enter a name that can be used in the search interface of Runtime Manager, and a value, which may be any Mule expression.
+
* Expression / Value (`value`) for the PKI.
+
Examples for a list of PKIs:
+
[%header,cols="2*a"]
|===
|Name |Expression/Value
|Employee ID |`#[payload['ID']]`
|Employee Email |`#[payload['Email']]`
|Employee Git ID |`#[payload['GITHUB_ID']]`
|===

Note that key/value pairs can vary according to your business needs. Additional examples:

[%header,cols="2*a"]
|===
|Name |Expression/Value
|`price` |`700`
|price-after-discount |`#[groovy:payload.price]`
|price-after-discount |`'The price for the item is: ' #[groovy:payload.price]``
|===

== See Also

xref:business-events.adoc[About Business Events]

////
// TODO: IS THIS ALLOWED IN 4.0?
== Sharing PKIs

In Studio, you can create a

[source,xml,linenums]
----
<tracking:custom-event-template name="template">
  <tracking:meta-data key="tier-level" value="platinum" />
  <tracking:meta-data key="price-after-discount" value="#[groovy:payload.price]" />
</tracking:custom-event-template>

<flow name="flow">
  <tracking:custom-event event-name="event1" inherits="template" />
  <tracking:custom-event event-name="event2" inherits="template" />
</flow>
----

And you can define how conditional custom events are fired. The code below shows how to do this:

[source,xml,linenums]
----
<choice>
  <when expression="INVOCATION:debugflag = on" evaluator="header">
    <tracking:custom-event event-name="success" />
  </when>
  <otherwise>
    <tracking:custom-event event-name="failure" />
  </otherwise>
</choice>
----

In this last example, a custom event with the event name "success" is fired if the debug flag is on when the message processor is invoked. Otherwise, a custom event with the event name "failure" is fired.
////

////
// TODO: IS THIS REALLY NEEDED? IT'S NOT VISIBLE IN THE 3.9 DOCS.

`tracking:custom-event`: The top-level element for the Custom Business Event component.

[source,xml,linenums]
----
<flow name="flow">
...
  <tracking:custom-event event-name="Retrieved Employee">
  </tracking:custom-event>
...
</flow>
----

When you define a custom event, you can also add metadata. Use DataWeave in the value to capture information from the message payload.

[source,xml,linenums]
----
include::_sources/business-events_1.xml[]
----

You can even add text to the expression language, as shown in the following example:

[source,xml,linenums]
----
include::_sources/business-events_2.xml[lines="15..18"]
----
////

////
// TODO: THIS NEEDS TO BE EXPLAINED BETTER OR REMOVED
You can also set up your flow so that metadata can be shared among events. See the XML tab for details on how to set up the `tracking:custom-event-template` global element in your flow.

You can also trigger conditional custom events to help track how messages are processed through your flow. For example, you could set up a choice router in your flow.
////