= Business Events
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: business-events-best-practices.adoc

Mule applications can collect business event information about flows and message processors that handle your business transactions. This information can include transaction execution time, errors, results (successful completion or failure), and message payload information.

Transactions are logical groupings of related events that often correspond to a business view of the system. These are represented by event groupings at the flow level.

Events map to message processors and connectors and are the low-level details of a transaction. Events can also be exceptions and custom events. All events that are not custom, are considered default events.

[NOTE]
Batch processors do not support the use of Business Events.

== Business Event Types

There are two types of business events that you can track: Default events and Custom events.

Default event tracking is supported by all connectors and selected message processors. Enabling default events for these elements enables you to perform advanced debugging at runtime. Default event tracking can be enabled at the flow level or the message processor level. +
See xref:business-events-in-components.adoc[Default Event Tracking] for configuration details.

Custom event tracking is supported by the Custom Business Event Component. Custom events are always tracked once configured. Custom events enable you to track high-level activities in your flow that are relevant to your business. +
See xref:business-events-custom.adoc[Custom Business Event Component] for configuration details.

== Monitoring Business Events

You can enable Insight in Runtime Manager to monitor business events at runtime. These events can help you analyze the root cause of failures, isolate performance bottlenecks, and test for compliance with company procedures.

Certain default events are tracked automatically once Insight is enabled, but others need to be enabled in your application before they are tracked.

== Best Practices For Business Events

* Enable default events only for processes that have particular value to you. Determine which stages within a business transaction you need to track, and enable tracking for those stages before deployment. +
Tracking all possible events is also an option, but this generates unnecessary info that you have to filter or query to find the important events you need to analyze.
* Use custom events to track key process indicators. For example: "Total Order Amount" or "Tracking Number" to surface the high-level business activities in your flow.
* Customize the transaction ID so that meaningful information, such as an order number, an employee identification number, or a shipment tracking number, is displayed for a transaction. This practice makes analysis and debugging easier and more intuitive at runtime, whether you are using Mule Management Console or CloudHub.

== See Also

* xref:about-mule-event.adoc[Mule Events]
* xref:transaction-management.adoc[Transaction Management]
* xref:business-events-in-components[Default Event Tracking]
* xref:business-events-custom.adoc[Custom Business Event Component]
