= Custom Business Event Component
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use Custom Business Event (`tracking:custom-event`) components to add metadata and Key Performance Indicators (KPIs) to your flow.

. In the Mule Pallete, add you  app, add the Custom Business Event component to a flow.
. Click to open the component.
. Type values for Display Name and Event Name.
. Optionally, add Key Performance Indicators (KPIs) to capture information from the message payload:
+
* Name (`key`) for the KPI (`tracking:meta-data` element).
+
Enter a name that can be used in the search interface of Runtime Manager, and a value, which may be any Mule expression.
+
* DataWeave Expression / Value (`value`) for the KPI.
+
Examples for a list of KPIs:
+
[%header,cols="2*a"]
|===
|Name |Expression/Value
|Employee ID |`#[payload['ID']]`
|Employee Email |`#[payload['Email']]`
|Employee Git ID |`#[payload['GITHUB_ID']]`
|===

Note that key/value pairs can vary according to your business needs. Additional examples:

[%header,cols="2*a"]
|===
|Name |Expression/Value
|`price` |`700`
|`price-after-discount` |`#[vars.price]`
|`order-id` | `#[payload.order.header.orderID]`
|===

== See Also

xref:business-events.adoc[Business Events]
