= About Best Practices for Business Events
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, studio, esb, business events

There are a number of recommended practices for setting up your Business Event Tracking in your Mule app.

* Enable default events only for processes that have particular value to you. Determine which stages within a business transaction that you want to track, and enable tracking for those stages before deployment. Tracking all possible events is also an option, but you have to spend more time at runtime filtering or querying to find the events you really need to analyze.
* Use custom events to track key process indicators, for example, "Total Order Amount" or "Tracking Number" to surface the high-level business activities in your flow.
* Customize the transaction ID so that meaningful information, such as an order number, an employee identification number,  or a shipment tracking number, is displayed for a transaction. This makes analysis and debugging easier and more intuitive at runtime, whether you are using Mule Management Console or CloudHub.

== See Also

xref:business-events.adoc[About Business Events]