= Enable Business Events
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, studio, esb, business events

Event tracking requires some processing and network overhead to aggregate and store the events that the Mule servers generate, so by default, tracking is not enabled for connectors or message processors that support it. However, enabling tracking for default events is very simple. You just need to explicitly configure the scope for tracking the default events. You can configure the scope either:

* At the flow level.
* At the message processor (connector or component) level, which takes precedence over the flow level setting.

////
[NOTE]
====
Message processor or connector level configuration takes precedence over flow level configuration.

* if you want to enable all default events for a specific flow:

* if you want to enable default events for a specific message processor (in this case, the All router):

* if you want to enable all default events for a specific flow, but not for a specific message processor (in this case, the All router):
====
////

[events_tracking_flow_level]
== Enabling Event Tracking at the Flow Level

To enable default event tracking for elements in a flow that allow event tracking.

Note that you can disable tracking for specific processors or connectors to override the flow-level enablement.

. From a Mule app, click to open the flow component.
. Enable default Business Events by selecting this:
+
* Enable Default Events Tracking using one of these options:
+
* In the UI, you can check the Enable Default Events Tracking checkbox.
* In the Studio XML, you can add this attribute to the `flow` element, for example:
+
`<flow name="testFlow" tracking:enable-default-events="true">`
+
. Optionally, set an identifier for all tracked events pertaining to this flow so that meaningful information, such as an order number, is displayed for a transaction.
+
* In the UI, you can check Use Transaction ID and supply an ID.
* In the Studio XML, you can add a child element to the `flow` element that looks like this:
+
[source,xml,linenums]
----
<flow name="flow">
  ...
  <tracking:transaction id="#[expression]" />
  ...
</flow>
----
+
. Save your settings.

[event_tracking_processor_level]
== Enabling Event Tracking at the Message Processor Level

You can enable event tracking on individual connectors and components that support event tracking. Not all processors support default event tracking. If the checkbox is not present in a message processor or connector, default tracking is not supported.

. Click to open a message processor in a Mule flow.
. Select Enable Default Events Tracking.
+
Note that you can also do enable tracking through the Studio XML for the component, for example:
+
[source,xml,linenums]
----
<flow name="flow">
  ...
    <choice doc:name="Choice" tracking:enable-default-events="true"/>
  ...
</flow>
----

[events_transaction_id]
== Customizing the Transaction ID

You can define a Transaction ID so that meaningful information, such as an order number, is displayed for a transaction when you analyze tracked events at runtime. If you do not customize the Transaction ID, Mule assigns a numeric transaction ID by default. To make the ID more user-friendly for your business needs, you can customize through a DataWeave expression.

It is good practice to make sure that your custom ID is unique for each transaction in your application. The following example sets up a unique ID based on a unique order ID extracted from a payload.

// tab was here

[source,xml,linenums]
----
<flow name="flow">
...
  <tracking:transaction id="#[payload.orderId]" />
...
</flow>
----

== See Also

xref:business-events.adoc[Business Events]
