= Invalidate Cache Entries
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can invalidate a cache key or a complete cache by using the Invalidate Key and Invalidate Cache components respectively.
Invalidate cache entries when you want the Cache Scope to execute all processors to generate a response, instead of returning a cached response for the existing entry.

== Invalidate a Cache Key

Use the Invalidate Key component to invalidate the specified cache key in the referenced caching strategy.

=== Configure the Invalidate Key Component

To invalidate a cache key:

. In *Anypoint Studio*, drag the *Invalidate Key* component to your flow.
. Open the *Invalidate Key* properties.
. Specify the *Caching Strategy* where the cache key to invalidate is stored.
. Select the method for generating the cache key to search and invalidate.

Ensure that the method selected for generating the cache key in the Invalidate Component is the same used in the referenced Caching Strategy, otherwise the cache keys might not match and the process won't work as expected.

=== Example Invalidate Key Configuration

[source, xml, linenums]
----
<!-- Caching strategy configuration -->
<ee:object-store-caching-strategy name="myCachingStrategy" keyGenerationExpression="#[payload.key]" />

<flow name="cacheFlow">
  <ee:cache cachingStrategy-ref="myCachingStrategy">
      <!-- Processing logic to be cached -->
  </ee:cache>
</flow>

<flow name="invalidateItemFlow">
  <!-- Invalidate Key component configuration -->
  <ee:invalidate-key cachingStrategy-ref="myCachingStrategy" keyGenerationExpression="#[payload.key]" />
</flow>
----

== Invalidate a Complete Cache

Use the Invalidate Cache component to invalidate the complete cache in the referenced caching strategy.

=== Configure the Invalidate Cache Component

To invalidate a complete cache:

. In *Anypoint Studio*, drag the *Invalidate Cache* component to your flow.
. Open the *Invalidate Cache* properties.
. Specify the *Caching Strategy* to invalidate.

=== Example Invalidate Cache Configuration

[source, xml, linenums]
----
<!-- Caching strategy configuration -->
<ee:object-store-caching-strategy name="myCachingStrategy" />

<flow name="cacheFlow">
  <ee:cache cachingStrategy-ref="myCachingStrategy">
      <!-- Processing logic to be cached -->
  </ee:cache>
</flow>

<flow name="invalidateCompleteCacheFlow">
  <!-- Invalidate Cache component configuration -->
  <ee:invalidate-cache cachingStrategy-ref="myCachingStrategy" />
</flow>
----

== See Also

* xref:cache-scope-to-configure.adoc[Configure the Cache Scope]
* xref:cache-scope-strategy.adoc[Set Up a Caching Strategy]
