= Invalidate Cache Entries
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can invalidate a cache key or a complete cache by using the Invalidate Key and Invalidate Cache components respectively.
Invalidate cache entries when you want the Cache Scope to recalculate the value for those cache entries.

== Invalidate a Cache Key

Use the Invalidate Key component to invalidate the specified cache key in the referenced caching strategy.

=== Configure the Invalidate Key Component

To invalidate a cache key:

. In *Anypoint Studio*, drag the *Invalidate Key* component to your flow.
. Open the *Invalidate Key* properties.
. Specify the *Caching Strategy* where the cache key to invalidate is stored.
. Optionally, select the method for generating the cache key.

=== Example Invalidate Key Configuration

[source, xml, linenums]
----
<!-- Caching strategy configuration -->
<ee:object-store-caching-strategy name="myCachingStrategy" keyGenerationExpression="#[payload.key]" />

<flow name="cacheFlow">
  <ee:cache cachingStrategy-ref="myCachingStrategy">
      <!-- Processing logic inside the Cache Scope -->
  </ee:cache>
</flow>

<flow name="invalidateItemFlow">
  <!-- Invalidate Key component configuration -->
  <ee:invalidate-key cachingStrategy-ref="myCachingStrategy" keyGenerationExpression="#[payload.key]" />
</flow>
----

== Invalidate a Complete Cache

Use the Invalidate Cache component to invalidate the complete cache in the referenced caching strategy.

=== Configure the Invalidate Cache Component

To invalidate a complete cache:

. In *Anypoint Studio*, drag the *Invalidate Cache* component to your flow.
. Open the *Invalidate Cache* properties.
. Specify the *Caching Strategy* to invalidate.

=== Example Invalidate Cache Configuration

[source, xml, linenums]
----
<!-- Caching strategy configuration -->
<ee:object-store-caching-strategy name="myCachingStrategy" />

<flow name="cacheFlow">
  <ee:cache cachingStrategy-ref="myCachingStrategy">
      <!-- Processing logic inside the Cache Scope -->
  </ee:cache>
</flow>

<flow name="invalidateCompleteCacheFlow">
  <!-- Invalidate Cache component configuration -->
  <ee:invalidate-cache cachingStrategy-ref="myCachingStrategy" />
</flow>
----

== See Also

* xref:cache-scope-to-configure.adoc[Configure the Cache Scope]
* xref:cache-scope-strategy.adoc[Set Up a Caching Strategy]
