= To Configure the Cache Scope
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

. In your Mule app, add a Cache scope to a flow.
. Click to open the General tab for the Cache scope.
. Configure the Cache scope:
+
* Provide a Display Name.
* Select a Caching Strategy.
+
Examples:
+
** From the UI: `My_Caching_Strategy`
** In the Studio XML: `cachingStrategy-ref="My_Caching_Strategy"`
+
MuleSoft recommends that you reference a Caching Strategy that uses an ObjectStore instead of using the default in a production environment.
+
If you need to create a Caching Strategy, see the procedure in <<See Also>>.
+
. Opt to set up a filter for specific payloads if you need one.
+
Example that uses a DataWeave expression: `filterExpression="#[user.isPremium()]"`
+
If the message matches the expression(s), Mule executes the Caching Strategy.
+
If the message does not match expression(s), Mule processes the message through all message processors within the Cache scope but never saves or produces cached responses.

== See Also

xref:cache-scope-strategy.adoc[To Set Up a Caching Strategy]

xref:cache-scope.adoc[About the Cache Scope]

////
// TODO
* To Set up a Caching Strategy
* To Configure a Response Generator
* To Configure a Consumable Message Filter
////