= To Deploy a Mule Application to CloudHub (Mule Maven Plugin)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Prerequesites

To successfully deploy your Mule application to CloudHub, consider the following requirements:

* The host and port number of your HTTP Listener flow sources are properly configured. +
 If you are using the HTTP Listener as sources for your flow, you need to set its host to *0.0.0.0* and its port to *${http.port}*. +
CloudHub then dynamically allocates a port at deployment time.
* All your external classes and resources are properly declared in the `mule-artifact.json` file of your Mule application. +
 Due to Mule 4.x classloading isolation mechanism, all external classes and resources must be explicitly declared in the "exportedPackages" and "exportedResources" fields on the mule-artifact.json file before packaging and deploying the application. +
+
See the xref:how-to-export-resources.adoc[How to Export Resources] task to learn more about working with external resources in your Mule application.

== Deploying to CloudHub

. Make sure you added the Mule Maven Plugin to your pom.xml file.
. Inside the plugin you element, add a configuration for your CloudHub deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <cloudHubDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${mule.version}</muleVersion>
            <username>${username}</username>
            <password>${password}</password>
            <applicationName>${cloudhub.application.name}</applicationName>
            <environment>${environment}</environment>
            <properties>
                <key>value</key>
            </properties>
        </cloudHubDeployment>
    </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your own CloudHub information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,console,linenums]
----
> mvn clean package deploy -DmuleDeploy
----

== Redeploying to CloudHub

To redeploy the application, run the same command as you did to deploy. +
CloudHub rewrites the application you had deployed.

== Encrypting credentials

To use encrypted credentials when deploying to CloudHub you need to set up your Maven master encrypted password and your settings-security.xml file.

. Create a master password for your Maven configuration.

+
----
> mvn --encrypt-master-password <yourMasterPassword>
----
+
Maven returns your master password encrypted:
+
----
{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}
----
. Create a settings-security.xml file in your ~/.m2 repository and add your encrypted master password.

+
[source,xml,linenums]
----
<settingsSecurity>
  <master>{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}</master>
</settingsSecurity>
----
. Encrypt your Anypoint platform password:

+
----
> mvn --encrypt-password <yourAnypointPlatformPassword>
----
+
Maven returns your Anypoint platform password encrypted:
+
----
{HTWFGH5BG9QmvJ1B=}
----
. Add your encrypted Anypoint Platform password to your settings.xml file in the <server> section:
+
[source,xml,linenums]
----
<settings>
...
  <servers>
...
    <server>
      <id>my.anypoint.credentials</id>
      <username>my.anypoint.username</username>
      <password>{HTWFGH5BG9QmvJ1B=}</password>
    </server>
...
  </servers>
...
</settings>
----
. In your the configuration deployment, reference the credentials id injecting the server id:

[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <cloudHubDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${mule.version}</muleVersion>
            <server>my.anypoint.credentials</server>
            <applicationName>${cloudhub.application.name}</applicationName>
            <environment>${environment}</environment>
            <properties>
                <key>value</key>
            </properties>
        </cloudHubDeployment>
    </configuration>

</plugin>
----

NOTE: Make sure that username and password are not set in the deployment configuration, as they have precedence over the defined server id.

== See Also

* xref:cloudhub-deployment-mmp-reference.adoc[CloudHub Deployment Reference (Mule Maven Plugin)]
* xref:add-mmp-task.adoc[To Add the Mule Maven Plugin to a Project]