= Choosing Between Flows and Patterns
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Because of the emphasis on ease of use, simplicity, and flexibility that guided the creation of Mule 3, a number of choices are open at the outset.

== Choosing Configuration Patterns and Flows

Take a look at xref:using-mule-configuration-patterns.adoc[configuration patterns] and xref:using-flows-for-service-orchestration.adoc[flows].

Mule 3 includes a number of configuration patterns designed to solve common integration problems with minimal XML. These patterns are similar to Enterprise Integration Patterns which are also widely supported in Mule but tackle bigger use cases, like creating a web service proxy. Take a moment to inspect the list of patterns.

If your project a more complex set of operations, you might want to consider flows, which are introduced in Mule 3

For more information about patterns, read the xref:general-configuration-reference.adoc[General Configuration Reference]

[IMPORTANT]
Unable to render{children}. Page not found: Configuration Reference

* xref:using-flows-for-service-orchestration.adoc[Using Flows for Service Orchestration]
* xref:using-mule-configuration-patterns.adoc[Using Mule Configuration Patterns]