= Choosing Between Flows, Patterns, or Services
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Because of the emphasis on ease of use, simplicity, and flexibility that guided the creation of Mule 3, a number of choices are open at the outset.

== Choosing Configuration Patterns and Flows

Take a look at xref:using-mule-configuration-patterns.adoc[configuration patterns] and xref:using-flows-for-service-orchestration.adoc[flows]. These will allow you to go faster and further than you could using services alone. If you're a new user, start first by looking at configuration patterns.

Mule 3 includes a number of configuration patterns designed to solve common integration problems with minimal XML. These patterns are similar to Enterprise Integration Patterns which are also widely supported in Mule but tackle bigger use cases, like creating a web service proxy. Take a moment to inspect the list of patterns.

If your project requires a more complex set of operations, you might want to consider flows, which are introduced in Mule 3.

For more information about patterns, read the xref:configuration-reference.adoc[Configuration Reference].

* xref:asynchronous-reply-router-configuration-reference.adoc[Asynchronous Reply Router Configuration Reference]
* xref:catch-all-strategy-configuration-reference.adoc[Catch-all Strategy Configuration Reference]
* xref:component-configuration-reference.adoc[Component Configuration Reference]
* xref:endpoint-configuration-reference.adoc[Endpoint Configuration Reference]
* xref:exception-strategy-configuration-reference.adoc[Exception Strategy Configuration Reference]
* xref:filters-configuration-reference.adoc[Filters Configuration Reference]
* xref:global-settings-configuration-reference.adoc[Global Settings Configuration Reference]
* xref:inbound-router-configuration-reference.adoc[Inbound Router Configuration Reference]
* xref:model-configuration-reference.adoc[Model Configuration Reference]
* xref:notifications-configuration-reference.adoc[Notifications Configuration Reference]
* xref:outbound-router-configuration-reference.adoc[Outbound Router Configuration Reference]
* xref:properties-configuration-reference.adoc[Properties Configuration Reference]
* xref:security-manager-configuration-reference.adoc[Security Manager Configuration Reference]
* xref:service-configuration-reference.adoc[Service Configuration Reference]
* xref:transactions-configuration-reference.adoc[Transactions Configuration Reference]
* xref:bpm-configuration-reference.adoc[BPM Configuration Reference]

== Choosing Services

Mule's service-based architecture is well-suited for many scenarios where you are using Mule as a service container and exposing services over one or more endpoints. If you're familiar with using previous versions of Mule, you can continue - with very few changes - doing things the same way.

* xref:using-flows-for-service-orchestration.adoc[Using Flows for Service Orchestration]
* xref:using-mule-services.adoc[Using Mule Services]
* xref:using-mule-configuration-patterns.adoc[Using Mule Configuration Patterns]