= Choosing Between Flows and Patterns
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, studio, esb, flows, patterns

Because of the emphasis on ease of use, simplicity, and flexibility that guided the creation of Mule 3, a number of choices are open at the outset.

== Choosing Configuration Patterns and Flows

Take a look at xref:configuration-patterns.adoc[configuration patterns] and xref:3.6@using-flows-for-service-orchestration.adoc[flows].

Mule 3 includes a number of configuration patterns designed to solve common integration problems with minimal XML. These patterns are similar to Enterprise Integration Patterns which are also widely supported in Mule but tackle bigger use cases, like creating a web service proxy. Take a moment to inspect the list of patterns.

If your project requires a more complex set of operations, you might want to consider flows, which are introduced in Mule 3.

For more information about patterns, read the xref:3.6@general-configuration-reference.adoc[General Configuration Reference].

* xref:3.7@bpm-configuration-reference.adoc[BPM Configuration Reference]
* xref:3.6@component-configuration-reference.adoc[Component Configuration Reference]
* xref:3.6@endpoint-configuration-reference.adoc[Endpoint Configuration Reference]
** xref:3.6@mule-endpoint-uris.adoc[Mule Endpoint URIs]
* xref:3.7@exception-strategy-configuration-reference.adoc[Exception Strategy Configuration Reference]
* xref:3.6@filters-configuration-reference.adoc[Filters Configuration Reference]
* xref:3.7@global-settings-configuration-reference.adoc[Global Settings Configuration Reference]
* xref:3.6@notifications-configuration-reference.adoc[Notifications Configuration Reference]
* xref:3.7@properties-configuration-reference.adoc[Properties Configuration Reference]
* xref:3.7@security-manager-configuration-reference.adoc[Security Manager Configuration Reference]
* xref:3.6@transactions-configuration-reference.adoc[Transactions Configuration Reference]

* xref:3.6@using-flows-for-service-orchestration.adoc[Using Flows for Service Orchestration]
* xref:configuration-patterns.adoc[Using Mule Configuration Patterns]