= Component Authorization Using Spring Security
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: authorization, spring, spring security

You can configure authorization over Mule components using Spring Security features, such as the Authentication Manager or securing components in asynchronous systems, so that users with different roles can only invoke certain operations.


== Secure Components Using Spring Security Authentication Manager

The Authentication Manager is responsible for passing requests through a chain of Authentication Provider objects. To secure calls to flow components, you must add the configured `authenticationManager` to the application context.

The following example defines roles specified to access protected processors, if such roles are also specified in the `requiredAuthorities` field of the specific component:

[source,xml,linenums]
----
  <ss:authentication-manager alias="authenticationManager">
    <ss:authentication-provider>
      <ss:user-service id="userService">
        <ss:user name="admin" password="admin" authorities="ROLE_ADMIN" />
        <ss:user name="joe" password="secret" authorities="ROLE_ADMIN" />
        <ss:user name="anon" password="anon" authorities="ROLE_ANON" />
        <ss:user name="user" password="password" authorities="ROLE_ANON" />
        <ss:user name="ross" password="ross" authorities="ROLE_ANON" />
        <ss:user name="marie" password="marie" authorities="ROLE_ANON" />
      </ss:user-service>
    </ss:authentication-provider>
  </ss:authentication-manager>
----

The following example references the previously defined `authenticationManager` to only allow users with `ROLE_ADMIN` roles access the operation:

[source,xml,linenums]
----
	<spring:security-manager>
		<spring:delegate-security-provider name="memory-provider" delegate-ref="authenticationManager" />
	</spring:security-manager>

	<flow name="protectedFlow">
		<http:listener doc:name="Listener" config-ref="HTTP_Listener_config" path="/" />
		<http:basic-security-filter doc:name="Basic security filter" realm="mule" />
		<spring:authorization-filter requiredAuthorities="ROLE_ADMIN" />

		<ee:transform doc:name="Transform Message">
			<ee:message>
				<ee:set-payload><![CDATA[%dw 2.0
				output application/json
				---
				{
					"status": "ok"
				}]]>
				</ee:set-payload>
			</ee:message>
		</ee:transform>
	</flow>
----

== Secure Components in Asynchronous Systems

Spring Security strategies are useful for asynchronous systems, since to set the authentication on more than one thread you have to add a security property to the security provider.
In the following example, the value `MODE_GLOBAL` is the security property added:

[source,xml,linenums]
----
    <mule-ss:security-manager>
        <mule-ss:delegate-security-provider name="memory-dao" delegate-ref="authenticationManager">
            <mule-ss:security-property name="securityMode" value="MODE_GLOBAL"/>
        </mule-ss:delegate-security-provider>
    </mule-ss:security-manager>
----
