= Compatibility
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Users run Mule on many different operating systems in combination with a variety of messaging platforms and application servers.

== Platforms Compatible with MuleSoft

This section describes the platform software compatible with the current version of Mule ESB.

If you have run Mule successfully with additional platforms, please mailto:documentation@mulesoft.com[let us know].

=== Operating System Compatibility

Among the operating systems MuleSoft uses to validate the current release are:

* Both the 32- and 64-bit versions of the following Windows releases: XP, 2003, 2008 and 7
* Mac OS 10.6
* The following 64-bit releases of Linux RHEL: 5.3, 6.1, and 7.1
* Ubuntu Server 11.04 (64-bit)
* HP-UX 11i V3

Additionally, members of the Mule community have reported success deploying Mule with the following operating systems:

* Windows: 2000 and Vista
* Linux: Debian and SUSE
* Solaris
* AIX

=== Application Server Compatibility

Users have reported success deploying MuleSoft ESB with:

* Tomcat
* Tcat Server
* JBoss
* WebSphere
* WebLogic
* Geronimo
* Jetty.

=== Messaging Platform Compatibility

MuleSoft is compatible with JMS from any vendor.

Additionally, users have reported successful integration via Active MQ, Open MQ, Rabbit MQ, Mule MQ, TIBCO EMS, TIBCO Rendezvous, Oracle AQ, and IBM WebSphere MQ.

=== Java

Users have reported success with JVMs from Oracle (Sun), JRockit, IBM, and OpenJDK.

You must also install JDK6, as explained below.

== Setting up your Mule Environment

Before installing and running Mule, you must install the following software on your system:

=== Java

Install one of the following versions of the http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Developer Kit]:

* Standard Edition 1.6.0_26 (also known as JDK SE 6 Update 26) or more recent
* Enterprise Edition 1.6u3 (JDK EE 6 Update 3) or more recent

Run the installer, following the instructions that appear on the screen.

For further details, consult: xref:installing-and-endorsing-the-jdk.adoc[Installing and Endorsing the JDK]

=== Maven (Optional But Recommended)

. Download the Maven distribution from the http://maven.apache.org/[Maven web site] and unpack it to any folder (for example, `C:\Apache`). MuleSoft ESB 3.2 users should use Maven 3.
. Create a Maven repository directory with no spaces in the path, such as `c:\.m2\repository` on Windows. (If Windows Explorer does not allow you to create the .m2 folder name, use the `mkdir` command in a console window instead.)
. Open the `settings.xml` file in your Maven `conf` directory (e.g., `c:\apache-maven-3.0.3\conf`) and specify the repository directory. For example:

[source,xml,linenums]
----
<localRepository>c:/.m2/repository</localRepository>
----

Ensure that this entry is not commented out in this file.