= Complete Installation Manual
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The version number of Mule ESB refers to the version of the runtime product. Note that Mule Studio, Mule ESB's designtime GUI interface, releases versions independent of Mule ESB, thus does not accurately reflect the version of the core product.

The following procedure outlines the steps to take in both Mule Studio and Mule Standalone to determine the version number of the runtime product.

== Mule Studio

This procedure assumes that you have already launched Mule Studio and have opened a new or existing project. If you have not yet opened your first project in Studio, click *File > New > Mule Project* and observe the default value in the *Server Runtime* field in the wizard.

. In the *Package Explorer*, click the expanded arrow next to the name of one of your projects to expand to folder.
. Double-click the `mule-project.xml` file to open it in a new tab in the canvas.
. Note the *Server Runtime* version in the *Runtime* column at right.

== Mule Standalone

. Run Mule Standalone from the command line.
+
. For more details:
+
.. Open a new command line.
+
*PC*: Open the *Console* +
*Mac*: Open the *Terminal* application (Applications > Utilities > Terminal).
+
.. Access the directory and folder in which downloaded Mule. For example, type
+
`cd /Users/aaron/Downloads/mule-standalone-3.3.1/`
+
.. Start Mule. For example, type
+
`./bin/mule`
+
. After Mule starts, scroll up in the command line window to find the `Mule ESB and Integration Platform` where Mule displays the version.