= Compatibility
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Users run Mule ESB on many different operating systems in combination with a variety of messaging platforms and application servers. This page describes the platform software compatible with the current version of Mule ESB.

See xref:hardware-and-software-requirements.adoc[Hardware and Software Requirements] for information about hardware, operating systems, JDEs, and other software required to run Mule ESB, Mule Management Console, or Mule Studio.

xref:installing.adoc[Which version of Mule an I using?]

== Application Servers

The current release of Mule ESB supports the following application servers:

* Tcat Server
* Jetty 8
* JBoss 6.1 (Enterprise)
* JBoss 7 (Community)
* Tomcat 7
* WebSphere 7, 8
* WebLogic 11g, 12c

Additionally, users have reported success deploying Mule ESB with the following application servers:

* Geronimo

== Messaging Platforms

The current release of Mule ESB supports the following messaging platforms:

* ActiveMQ 5
* IBM WebSphere MQ 6, 7
* Oracle AQ
* RabbitMQ 2.8.7

Additionally, users have reported successful integration via the following messaging platforms:

* Open MQ
* TIBCO EMS
* TIBCO Rendezvous
* Hornet MQ

== Database Servers

The current release of Mule ESB supports the following database servers:

* Oracle 11g
* SQL Server 2012
* MySQL 5.6
* DB2 10

Additionally, members of the community have reported success integrating with the following database servers:

* Derby
* PostgreSQL

== See Also

* xref:hardware-and-software-requirements.adoc[Hardware and Software Requirements]
* xref:downloading-and-launching-mule-esb.adoc[download, install, and launch]
* xref:installing-an-enterprise-license.adoc[Enterprise Edition license].
* xref:studio-in-eclipse.adoc[Mule Studio as an Eclipse plug-in]