= Complete Installation Manual
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

For quick-start installation instructions that cover just the essentials installing the Mule development environment, go to xref:hello-mule.adoc[Hello, Mule!], which leads you through a basic installation — and helps you write your first Mule application, as well.

If, on the other hand, you need to troubleshoot your installation or are planning a complex, mission-critical deployment, the following documents provide detailed installation-related information:

* xref:hello-mule.adoc[Hello, Mule!]
* xref:compatibility.adoc[Compatibility]
* xref:choosing-your-development-environment.adoc[Choosing Your Development Environment]
* xref:downloading-mule-esb-3.adoc[Downloading Mule ESB 3]
* xref:installing-mule-esb-3-infrastructure.adoc[Installing Mule ESB 3 Infrastructure]
* xref:installing-mule-esb-3-and-the-mule-ide.adoc[Installing Mule ESB 3 and the Mule IDE]
* xref:installing-a-commercial-license.adoc[Installing a Commercial License]
* xref:running-mule-esb-3.adoc[Running Mule ESB 3]
* xref:stopping-mule-esb-3.adoc[Stopping Mule ESB 3]



[TIP]
====
*Did you know . . .*
MuleSoft has released Studio GA, a powerful new interface for Mule ESB that can cut your development time by half or more. You can model, debug, and deploy your applications all within the rich, yet flexible Studio environment.

Studio provides two-way (i.e., graphical and code-based) editing, which means that developers no longer have to trade ease-of-use against fine-grained control over their development projects. Any changes you make in one mode appear instantly in the other.

Mule Enterprise and Mule iON developers can fine-tune their applications in the advanced Studio XML editor, then re-deploy them on whichever version of Mule those applications were originally developed.

Studio installation is almost instantaneous, and a pair of tutorials can get you up and running in less than 40 minutes.

Let’s get Kicking!
====