= Configuring Security
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, studio, esb, on premises, on premise, security, amc, aes

Mule ESB allows you to authenticate requests via connectors using transport-specific or generic authentication methods. It also allows you to control method-level authorization on your components. The Security Manager is responsible for authenticating requests based on one or more security providers.

For information on the elements you can configure for the Security Manager, see xref:security-manager-configuration-reference.adoc[Security Manager Configuration Reference]. The following sections provide links to information on configuring different types of security managers.

[NOTE]
====
*New Anypoint Enterprise Security Features*

In addition to the security features described on this page, Mule offers six new security features:

* Mule Secure Token Service (STS) Oauth 2.0 Provider

* Mule Credentials Vault

* Mule Message Encryption Processor

* Mule Digital Signature Processor

* Mule Filter Processor

* Mule CRC32 Processor

For more information on these features and instructions for downloading them, see xref:anypoint-enterprise-security.adoc[Anypoint Enterprise Security].
====

== Spring Security 3.0

Spring Security is the next version of Acegi and provides a number of authentication and authorization providers such as JAAS, LDAP, CAS (Yale Central Authentication service), and DAO. The following topics will help you get started securing your flows using Spring Security:

* xref:configuring-the-spring-security-manager.adoc[Configuring the Spring Security Manager]

* xref:component-authorization-using-spring-security.adoc[Component Authorization Using Spring Security]

* xref:setting-up-ldap-provider-for-spring-security.adoc[Setting up LDAP Provider for Spring Security]

== WS-Security and SAML

WS-Security is a standard protocol for applying security to Web services. It contains specifications on how integrity and confidentiality in a SOAP message can be enforced via XML signatures and binary security tokens such as X.509 certificates and Kerberos tickets as well as encryption headers. It ensures end-to-end security by working in the application layer as opposed to the transport layer. Mule provides the following resources for WS-Security:

* xref:enabling-ws-security.adoc[Enabling WS-Security] - Describes how to secure your CXF connectors with WS-Security.

* xref:saml-module.adoc[SAML Module] - Mule now supports the SAML standard for exchange of security information between systems. This module is available in the enterprise edition of Mule as of version 2.2.3

== Other Security Integration

Mule also supports the following security technologies:

* xref:encryption-strategies.adoc[Encryption Strategies] - Secure your messages by encrypting them.

* xref:pgp-security.adoc[PGP Security] - Secure your messages by encrypting them with PGP.

* xref:jaas-security.adoc[Jaas Security]