= General Operations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This page details Operations from the Cryptography module that are independent of the encryption strategy used.

== Checksum Overview

Checksum operation allows to ensure messages' integrity. The operation act as an enricher to generate a checksum to a message when it enters a system, then act as a filter to verify the checksum when the message leaves the system (using the Validate Checksum operation). If the entry and exit values do not match, an `CRYPTO:VALIDATION` error is raised.

This pair of operations allows the user to verify that a message remains intact between a sender and a receiver. Because it does not itself provide encryption or append a signature to the message, you can use it in conjunction with other security features. 

[[calculateChecksum]]
== Calculate Checksum
`<crypto:calculate-checksum>`

+++
Calculate the checksum of a given content or value, which can be an expression. The hashing algorithm can also be selected.
+++

==== Parameters
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
| Name | Type | Description | Default Value | Required
| Algorithm a| Enumeration, one of:

** `CRC32`
** `MD2`
** `MD5`
** `SHA_1`
** `SHA_256`
** `SHA_512` |  +++the checksum algorithm+++ |  `SHA_256` | {nbsp}
| Content a| Binary |  +++The content for calculating the checksum+++ |  `#[payload]` | {nbsp}
| Target Variable a| String |  +++The name of a variable on which the operation's output will be placed+++ |  | {nbsp}
| Target Value a| String |  +++An expression that will be evaluated against the operation's output and the outcome of that expression will be stored in the target variable+++ |  `#[payload]` | {nbsp}
|===

==== Output Type

String

==== Throws
* `CRYPTO:CHECKSUM` {nbsp}


[[validateChecksum]]
== Validate Checksum
`<crypto:validate-checksum>`

+++
Validate the checksum of the content or value against an expected checksum (previously calculated using the Calculate Checksum operation).
+++

==== Parameters
[cols=".^20%,.^20%,.^35%,.^20%,^.^5%", options="header"]
|===
| Name | Type | Description | Default Value | Required
| Algorithm a| Enumeration, one of:

** `CRC32`
** `MD2`
** `MD5`
** `SHA_1`
** `SHA_256`
** `SHA_512` |  +++The checksum algorithm+++ |  `SHA_256` | {nbsp}
| Value a| Binary |  +++The content for calculating the checksum+++ |  `#[payload]` | {nbsp}
| Expected a| String |  +++The expected checksum as an hexadecimal string+++ |  | *x*{nbsp}
|===

==== Throws
* `CRYPTO:MISSING_KEY` {nbsp}
* `CRYPTO:VALIDATION` {nbsp}
