= About the Cryptography Module
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: cryptography, module, sign, encrypt, pgp, jce, AES

This module provides cryptography capabilities to a Mule application. Its main features include:

* Symmetric encryption and decryption of messages.
* Asymmetric encryption and decryption of messages.
* Message signing and signature validation of signed messages.

This module supports three different strategies to encrypt and sign your messages:

* xref:cryptography-pgp.adoc[PGP]: Signature/encryption using PGP.
* xref:cryptography-xml.adoc[XML]: For signing or encrypting XML documents or elements.
* xref:cryptography-jce.adoc[JCE]: For using a wider range of cryptography capabilities as provided by the Java Cryptography Extension.

Additionally, this module offers two general operations to calculate and validate stream checksums. +
See xref:cryptography-reference.adoc[General Operations] for more information.

== Using the Extension in Anypoint Studio 7

You can use this extension by adding it as a dependency in your Mule app.

[[install-crypto-module]]
=== Installing the Extension

. Open your Mule project in Anypoint Studio.
. Go to the Mule Palette.
. Select **Search in Exchange**, and search for the Cryptography Module.
. Add the extension.
. You can now search in the mule Palette for operations of the Cryptography module.

== Security Provider

By default the security provider is Bouncy Castle. If you do not configure `mule.security.provider=BC`, the module attempts to add Bouncy Castle as a provider when `mule.security.model` is not FIPS140-2.