= Troubleshoot Cryptography connector

To troubleshoot Anypoint Connector for Cryptography (Cryptography Connector), become familiar with the information about app logs, PGP protocol, attached and detached signature, and interpreting commonly thrown messages.

== Check the app log

If you encounter problems while running your Mule runtime engine (Mule) app, check the app log as follows:
If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.
If you’re running the app using Mule from the command line, the app log is visible in your OS console.
Unless the log file path is customized in the app’s log file log4j2.xml, view the app log in the default location MULE_HOME/logs/<app-name>.log.

== Enable Cryptography connector debug logging

To begin troubleshooting Email Connector, enable debug logging to see the exact error messages:

1. Access Anypoint Studio and navigate to the Package Explorer view.
2. Open your application’s project name.
3. Open the src/main/resources path folder.
4. Open the log4j2.xml file inside the folder.
5. Add the following line:

    <AsyncLogger name=”com.mulesoft.modules.cryptography" level="DEBUG" />

6. Save your changes.
7. Click the project name in Package Explorer and then click Run > Run As > Mule Application.

== Troubleshoot PGP Encrypt and Decrypt

You have to add the receiver public keyring  to the module configuration in order to encrypt the message.
And to decrypt the message you have to add the receiver private keyring to the module configuration.

== Troubleshoot PGP Signature

You have to add the sender private keyring to the module configuration in order to create a signature.
And to validate a signature you need to add the sender public keyring to the module configuration.

There are two PGP Signature Operations, PGP Sign and PGP Binary Sign. The PGP Sign produces an armored signature (ASCII format) and PGP Sign produces a Binary Signature.

There are two types of signatures:

- Attached signature: Given a signed document, you can either check the signature or check the signature and recover the original document.

- Detached signature: The signature, and the document are created separately.

Currently, the module only supports validation of detached signatures.

== Understand Common Throws

Here is a list of common throw messages and how to interpret them.

* CRYPTO:PARAMETERS

 Wrong or invalid parameters given to operation.

* CRYPTO:MISSING_KEY

 A key required for the operation was not found.

* CRYPTO:PASSPHRASE

 The password for unlocking a key is wrong.

* CRYPTO:CHECKSUM

 Error when calculating a checksum.

* CRYPTO:TRANSFORMATION

 Error when transforming binary to armored.

* CRYPTO:VALIDATION

 The signature could not be validated against the data.

== See Also

* https://help.mulesoft.com[MuleSoft Help Center]
* xref:cryptography-reference.adoc[Cryptography Reference]







