= CXF Module Configuration Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This page provides reference information about the elements and attributes you can configure for the xref:cxf-module-reference.adoc[CXF Module Reference].

[cols="1*a",grid=none]
|===
|
xslt: Read http://www.mulesource.org/xslt/mule/schemadoc/3.1/individual-transport-or-module-wiki.xsl error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/tools/schemadocs/src/main/resources/xslt//individual-transport-or-module-wiki.xsl
|
xslt: Read http://www.mulesource.org/xslt/mule/schemadoc/3.1/individual-transport-or-module-wiki.xsl error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/tools/schemadocs/src/main/resources/xslt//individual-transport-or-module-wiki.xsl
|
xslt: Read http://www.mulesource.org/xslt/mule/schemadoc/3.1/individual-transport-or-module-wiki.xsl error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/tools/schemadocs/src/main/resources/xslt//individual-transport-or-module-wiki.xsl
|===

== Common CXF Elements

Following are the sub-elements you can set on CXF service and client. For further information on CXF interceptors, see the http://cxf.apache.org/docs/interceptors.html[CXF documentation].

[%header,cols="20,80"]
|===
|Name |Description
|databinding |The databinding implementation that should be used. By default, this is JAXB for the JAX-WS frontend and Aegis for the simple frontend. This should be specified in the form of a Spring bean.
|features |Any CXF features you want to apply to the client/server. See the CXF documentation for more information on features.
|inInterceptors |Additional incoming interceptors for this service.
|inFaultInterceptors |Additional incoming fault interceptors.
|outInterceptors |Additional outgoing interceptors.
|outFaultInterceptors |Additional outgoing fault interceptors.
|===

=== Interceptors example

[source,xml,linenums]
----
<cxf:jaxws-client serviceClass="com.mulesoft.example.HelloWorld"
                  operation="sayHello" port="HelloWorldPort">
    <cxf:inInterceptors>
        <spring:bean class="org.apache.cxf.interceptor.LoggingInInterceptor"/>
    </cxf:inInterceptors>
    <cxf:outInterceptors>
        <spring:bean class="org.apache.cxf.interceptor.LoggingOutInterceptor"/>
    </cxf:outInterceptors>
</cxf:jaxws-client>
----

=== Databinding example

[source,xml,linenums]
----
<cxf:simple-service>
    <cxf:aegis-databinding>
        <spring:property name="configuration">
            <spring:bean class="org.apache.cxf.aegis.type.TypeCreationOptions" />
        </spring:property>
    </cxf:databinding>
</cxf:simple-service>
----

=== Features example

[source,xml,linenums]
----
<cxf:jaxws-service serviceClass="com.mulesoft.mule.example.security.Greeter">
    <cxf:features>
        <spring:bean class="org.mule.module.cxf.feature.PrettyLoggingFeature" />
    </cxf:features>
</cxf:jaxws-service>
----