= Map Data with DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, as

This DataWeave example uses the DataWeave `map` function to iterate through an array of books and perform a series of tasks on each.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The example uses these DataWeave functions:

* `map` to go through each object in the `books` array.
* `as` to coerce the price data into a Number type, which ensures that the transformation generates the correct type for each element.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-ex1/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/map-ex1/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/map-ex1/out.json[]
----

[TIP]
Note that when a book has multiple authors, `item.author` evaluates to the entire array of authors instead of a single name.


== Using Default Values


The following example performs the same transformation as above, but it doesn't explicitly define the properties "item" and "index". Instead, it calls them through the default names: `$` and `$$` respectively.


[[ex02]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-ex2/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/map-ex2/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/map-ex2/out.json[]
----



== Related Examples

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]

* xref:dataweave-cookbook-map-object-elements-as-an-array.adoc[Map Object Elements as an Array]

* xref:dataweave-cookbook-map-an-object.adoc[Map an Object]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
