
= Text Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, text, text/plain, text/plain

MIME type: `text/plain`

ID: `text`
The Text Plain format represents text as a string.

Note that DataWeave parses, encodes, and stores this format into RAM memory.

[[examples]]
== Example

This example shows how DataWeave represents Text Plain data.

=== Input

The Plain Text data serves as the input payload to the DataWeave source.

[source,txt,linenums]
----
This is text plain
----

=== Source

The DataWeave script transforms the Text PLain input payload to the DataWeave (dw) format and MIME type. It returns a string.

[source,dataweave,linenums]
----
output application/dw
---
payload
----

=== Output

Because the DataWeave (dw) output is a string, it is wrapped in quotation marks.

[source,dataweave,linenums]
----
"This is text plain"
----

// CONFIG PROPS GET APPENDED BELOW /////////////////////////////////


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for this format.


[[reader_properties]]
=== Reader Properties

There are no reader properties for this format.

 
[[writer_properties]]
=== Writer Properties

This format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|Size of the buffer writer.
|`deferred`  |`Boolean`|`false`|Generates the output as a data stream when set to `true`, and defers the script's execution until consumed.

Valid values are `true` or `false`.
|`encoding`  |`String`|`null`|The character set to use for the output, such as UTF-8.
|===


[[mime_types]]
== Supported MIME Types

This format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`text/plain`
|===
