= Merge Fields from Separate Objects
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, filter, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, contains, as

The DataWeave examples merge fields from separate input arrays. The first (`firstInput`) is a DataWeave variable that lists price by book ID, and the second (`secondInput`) lists authors by book ID. Each book has a unique `bookId` key.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The DataWeave scripts produce the same output. Both scripts use two `map` functions with a filter, and one of them also creates an alias for the `bookId`:

* The first `map` function iterates over the elements of the `firstInput`
array. As the function evaluates each element, a second `map` function uses a filter to identify any elements in the second array (`secondInput`) that match the `filter` criteria (`secondInput filter ($.*bookId contains firstInputValue.bookId)`). The filter returns an element from `secondInput` that contains a `bookId` value that matches the `bookId` value in the `firstInput` element.
* The second `map` function evaluates that filtered element and then uses `secondInputValue.author` to select and populate the value of its `"author"` field in the object `{author : secondInputValue.author}`.
* `filter` limits the scope of the second `map` function to objects in the `secondInput` that share the same `bookId`.


[[ex1]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/merge-multiple-payloads-ex1/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/merge-multiple-payloads-ex1/out.json[]
----

As the next script shows, you can also write the same script using an `id` alias (created with `using (id = firstInputValue.bookId)`). The alias replaces the  selector expression, `firstInputValue.bookId`, which is longer.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/merge-multiple-payloads-ex2/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/merge-multiple-payloads-ex2/out.json[]
----

Both scripts produce the same output.


== See Also

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[Reference Multiple Inputs]

* xref:dataweave-cookbook-zip-arrays-together.adoc[Zip Arrays Together]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
