= Conditionally Reduce a List through a Function
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping


This DataWeave example flattens the input to something simpler. For each element
in the input, it conditionally includes a `contentTypes` field only in case it
has any values. It then rearranges this content into a more readable shape.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The examples use these functions:

* `map` to go through every element in the input array.
* `reduce` to aggregate the multiple elements in the `tags` array into one field.
* `splitBy` to parse the values in the "tags" array, so as to only select the first part of each string (through `[0]`) and discard the second.
* `++` to concatenate these elements into one single string, with commas as separators.
* `if` include the last field only if the `contentTypes` array is bigger than 0.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/conditional-list-reduction-via-function/transform.dwl[]
----

.Input JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/conditional-list-reduction-via-function/inputs/input.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/conditional-list-reduction-via-function/out.json[]
----

== See Also

* xref:dataweave-cookbook-exclude-field.adoc[Exclude Fields from the Output]

* xref:dataweave-cookbook-output-a-field-when-present.adoc[Output a Field When Present]

* xref:dataweave-cookbook-use-constant-directives.adoc[Use Constant Directives]

* xref:dataweave-cookbook-define-function-to-flatten-list.adoc[Define a Function that Flattens Data in a List]

* xref:dataweave-cookbook-pass-functions-as-arguments.adoc[Pass Functions as Arguments]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
