= Remove Objects Containing Specified Key-Value Pairs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example removes all objects that contain a set of key-value pairs from an array of objects.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]


This example uses the following functions:

* `filter` iterates over objects within an input array to return an object that matches the result of an expression. Each object the input array contains a set of key-value pairs. The expression uses the `contains` function and the `not` operator.
* `contains` identifies the key-value pairs specified in the `dropThese` variable. This variable is an array of objects containing the key-value pairs to remove.
+
`not` negates the result of the `contains` function to make `filter` remove the key-value pairs identified in `dropThese` from the final output. (Without `not`, the result produces an array of objects with only the undesired key-value pairs.)

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/remove-objects/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/remove-objects/inputs/payload.json[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/remove-objects/out.json[]
----

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
