= Look Up Data in a CSV File
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This DataWeave example uses the `map` function to return the country code and calling code stored in a CSV file to the specified input phone numbers.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

Given the following JSON input phone numbers as the payload:

[source,JSON,linenums]
----
[
   "54112724555",
   "16298765432"
]
----

And the CSV file in a var called `country_codes` with the following values:

[source,CSV,linenums]
----
CALLING_CODE,COUNTRY_CODE
1,US
7,RU
54,AR
20,EG
32,BE
33,FR
505,NI
506,CR
1876,JM
1905,CA
1939,PR
262262,RE
262269,YT
.,.
.,.
----

The following DataWeave script reads the input payload phone numbers, and uses the function `lookupCountrCode` to search the country code and calling code in the variable `country_code` Subsequently, uses the `map` function to match the country code and calling code to the phone number, and returns the filtered results in an array of JSON objects:

//MANUAL TESTING REQUIRED FOR NOW (NEED TO TEST WITH XLSX FILE)
.DataWeave Script:
[source,dataweave, linenums]
----
%dw 2.0
output application/json

var codeByCode = vars.country_code groupBy ((item, index) -> item.CALLING_CODE)
/**
* Returns the country code or null if not found
*/
fun lookupCountrCode(phoneNumber:String): String | Null =
    //map the each sub part to a country code or null
    (0 to 6 map ((index) ->  codeByCode[phoneNumber[0 to index]])
            //Filter non null and take the first this will return null if the array is empty
            filter ((item, index) -> item != null))[0]

---
payload map ((item, index) -> lookupCountrCode(item))
----

//MANUAL TESTING REQUIRED (FOR NOW)
.Sample Output (JSON):
[source,JSON,linenums]
----
[
  [
    {
      "CALLING_CODE": "54",
      "COUNTRY_CODE": "ARG"
    }
  ],
  [
    {
      "CALLING_CODE": "1",
      "COUNTRY_CODE": "US"
    }
  ]
]
----

== See Also

* xref:dataweave-formats.adoc[Supported Data Formats]
