= Troubleshooting a Failing DataWeave Script
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping
:page-aliases: dataweave-troubleshooting.adoc

When you troubleshoot a failing script, one challenge to reproducing an error is having the same inputs the script had
when it executed, especially in production environments where inputs can
change unexpectedly.

== Dumping Input Context and the Script into a Folder

In Mule 4.2.1, DataWeave introduced an experimental feature that enables you
to dump the input context and the failing script into a folder so that you
can track the failing script along with the data that makes the script fail.
This is particularly useful to check that the input data received is valid, as
often a correct script will fail because of an upstream component generating
invalid data.

To use this feature:

. Set the following system property to enable the dump feature:
+
`-M-Dcom.mulesoft.dw.dump_files=true`
+
. [Optional] Specify the path in which to generate the dump files:
+
`-M-Dcom.mulesoft.dw.dump_folder=<path_to_folder>`
+
The default directory is `/tmp`.

== DataWeave Exceptions

=== Incorrect Arguments

When a function is called with the incorrect kind of argument, it throws the
exception, `org.mule.weave.v2.exception.UnsupportedTypeCoercionException`.
Causes of this exception include:

* <<null_arg_not_accepted>>
* <<mimetype_unset>>

[[null_arg_not_accepted]]
==== Function Does Not Accept Null Argument

The most common cause of this exception occurs when one of the arguments is
`Null` and the function does not accept `Null` as an argument. This issue
results in an error message similar to the following:

[source,weave,linenums]
----
You called the function '++' with these arguments:
  1: Null (null)
  2: String (" A text")

But it expects one of these combinations:
  (Array, Array)
  (Date, Time)
  (Date, LocalTime)
  (Date, TimeZone)
  (LocalDateTime, TimeZone)
  (LocalTime, Date)
  (LocalTime, TimeZone)
  (Object, Object)
  (String, String)
  (Time, Date)
  (TimeZone, LocalDateTime)
  (TimeZone, Date)
  (TimeZone, LocalTime)

4| payload.message ++ " A text"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Trace:
  at main::++ (line: 4, column: 1)
  at main::main (line: 4, column: 17)
----

One way to resolve this issue uses the `default` operator. For example,
using `payload.message default "" ++ " A text"` appends empty text when the
when the message is null.

[[mimetype_unset]]
==== MIME Type Is Not Set

When the MIME type is not set, you receive an error message similar to the
following:

[source,weave, linenums]
----
You called the function 'Value Selector' with these arguments:
  1: String ("{message: 123}")
  2: Name ("message")

But it expects one of these combinations:
  (Array, Name)
  (Array, String)
  (Date, Name)
  (DateTime, Name)
  (LocalDateTime, Name)
  (LocalTime, Name)
  (Object, Name)
  (Object, String)
  (Period, Name)
  (Time, Name)

4| payload.message
   ^^^^^^^^^^^^^^^
Trace:
  at main::main (line: 4, column: 1)
----

When no MIME type is set on the payload, the MIME type defaults to
`application/java`, and the content is handled as a `String` instead of a
JSON object.

=== Stack Overflow

When a function recurses too deeply, an errors like the following is thrown:

[source,weave, linenums]
----
org.mule.runtime.api.el.ExpressionExecutionException: Stack Overflow. Max stack is 256
----

The maximum stack can be customized using the property `com.mulesoft.dw.stacksize`.

== Output Mismatch When Undefined

Unlike transformations, DataWeave expressions do not require defining an output. However, this just means the output will be inferred based on the expression and the variables used. Occasionally, this will create a mismatch between the inferred type and the expected type. To solve this issue, the output should be made explicit. Common examples of this situation occur when:

* <<xml_extraction>>
* <<multipart_handling>>
* <<manipulating_text>>

[[xml_extraction]]
=== Extracting Data from an XML

When extracting a String, for example, out of an XML payload with the expression `payload.order.product.model` DataWeave will infer an XML output considering the payload format. In those cases an error similar to the following one will be seen:

[source,weave, linenums]
----
"Trying to output non-whitespace characters outside main element tree (in prolog or epilog), while writing Xml at ." evaluating expression: "payload.order.product.model".
----

As mentioned, the output in this case needs to be made explicit: `output text/plain --- payload.order.product.model`.

[[multipart_handling]]
=== Handling Multipart Entries

Another usual error happens while dealing with multipart data, which has a very specific structure. Consider a multipart payload and the expression `dw::core::Objects::keySet(payload.parts)`, without an output DataWeave can only infer, based on the payload type, that multipart content is desired. An error similar to this will be thrown in that case:

[source,weave, linenums]
----
"Expecting type is {
  preamble?: String,
  parts: {
    _*: {
      headers: Object,
      content: Any
    }
  }
} but got Array, while writing MultiPart.
Trace:
  at main (Unknown)" evaluating expression: "dw::core::Objects::keySet(payload.parts)".
----

To solve this, a proper output should be defined, for example: `output application/json --- dw::core::Objects::keySet(payload.parts)`

[[manipulating_text]]
=== Manipulating Text Data

In this case, text data is used to create a more complex object. However, because we only have a text payload and no output, DataWeave will infer text should be used as well. The expression `payload splitBy ' '`, for example, will fail with an error similar to:

[source,weave, linenums]
----
"Text plain writer is unable to write Array.
Reason:
Cannot coerce Array (org.mule.weave.v2.model.values.ArrayValue$ArraySeqArrayValue@21bec687) to String
Trace:
  at main (Unknown), while writing TextPlain.
Trace:
  at main (Unknown)" evaluating expression: "payload splitBy ' '".
----

Making the output explicit solves the issue: `output application/java --- payload splitBy ''`
