= Set Default Values with DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, examples
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-defaults.adoc

Use one of the following methods to set default values when a payload value is absent or when the value is `null`:

* Using the `default` keyword
* Setting the default in an `if-else` or `else-if` statement
* Using `else` when pattern matching

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

== Example of Using the Keyword default to Set a Default Value

[[ex01]]
Consider a Mule application that expects a JSON input with fields `id` and `name` to do a transformation.
You can configure default values for these fields in case the fields are not present, or their value is `null`. For example:

//Note to writer: ex1 dwl is also used for ex2
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/defaults-ex1/transform.dwl[]
----

If the Mule application receives a JSON message with values set for the `id` and `name` fields, then the DataWeave  transformation matches field `id` to `userId` and field `name` to `userName`.

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex1/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex1/out.json[]
----

[[ex02]]
However, if the Mule application receives a JSON message without the expected fields, or the fields have `null` values, then the transformation uses the configured default values for fields `userId` and `userName`.

////
// NOTE: Uses identical script
//
//.DataWeave Script:
//[source,DataWeave,linenums]
//----
//include::partial$cookbook-dw/defaults-ex2/transform.dwl[]
//----
////

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex2/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex2/out.json[]
----

[[ex03]]
== Example of Using if-else and else-if Statements to Set Default Values

Another method for providing a default value is using xref:dataweave-flow-control.adoc#control_flow_if_else[if-else] and xref:dataweave-flow-control.adoc#control_flow_else_if[else-if].

The following example sets `United States` as the default value for `userLocation` if it is not present, or its value is `null`, in the JSON input message:

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/defaults-ex3/transform.dwl[]
----

If the Mule application receives a JSON message with a value set for the `location` field, then the DataWeave  transformation matches field `location` to `userLocation`.

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex3/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex3/out.json[]
----

However, if the Mule application receives a JSON message without the expected field, or the field is `null`, then the transformation uses the configured default value for field `userLocation`.

[[ex04]]
.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex4/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex4/out.json[]
----

[[ex05]]
== Example of Using Matching Patterns to Set Default Values

In xref:dataweave-pattern-matching.adoc[pattern-matching scripts], DataWeave
`case` statements end with an `else` expression that can serve as the default
to return if all preceding `case` expressions return `false`.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/defaults-ex5/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/defaults-ex5/out.json[]
----
