= Using `lookup` To Call External Flows
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

From a DataWeave transform, you can trigger the calling of a different flow in your Mule application, and whatever the flow returns is what the expression returns.

You can do this through the following expression:

`lookup("flowName",$)`

Which takes two parameters:

* The name of the flow that must be called
* The payload to send to this flow

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
  a: lookup("mySecondFlow",{b:"Hello"})
}
----

.Mule Flow
[source,xml,linenums]
----
<flow name="mySecondFlow">
    <set-payload doc:name="Set Payload" value="#[payload.b + ' world!' ]"/>
</flow>
----

.Output
[source,json,linenums]
----
{
  "a": "Hello world!"
}
----

Please note that only the payload returned by the invoked flow will be assigned.

[WARNING]
====
Always keep in mind that a functional language like DataWeave expects the invocation of the `lookup` function to _not_ have side effects.
As such, the internal workings of the DataWeave engine might cause a `lookup` function to be invoked in parallel with other `lookup`s, or not invoked it at all.

The recommended way to invoke flows is with the Flow Ref (`flow-ref`) component, using the `target` attribute to put the result of the flow in a `var` and then referencing that `var` from within the DataWeave script.
====

Note that `lookup` function does not support calling subflows.

== See Also

* xref:dw-functions.adoc[DataWeave Core Functions]
* xref:dataweave-types.adoc[DataWeave Types]
* xref:dataweave-selectors.adoc[DataWeave Selectors]