
= Binary Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, binary, application/octet-stream, application/x-binary, application/octet-stream

MIME type: `application/octet-stream`

ID: `binary`

The Binary data format handles binary content, such as an image or PDF. Such content is represented as a `Binary` type.

Note that Binary content is stored into RAM memory.


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the Binary format.


[[reader_properties]]
=== Reader Properties

There are no reader properties for Binary data.

 
[[writer_properties]]
=== Writer Properties

The Binary format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|The size of the buffer writer
|`deferred`  |`Boolean`|`false`|Indicates if the output should be deferred. Valid Options: `true` or `false`
|===


[[mime_types]]
== Supported MIME Types

The Binary format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/octet-stream`
|`application/x-binary`
|===
