= Examples: Regrouping Fields
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, groupby, mapobject

These examples take input that is grouped under one field and transform it into a new structure that groups data under another field.

Both examples use these functions:

* `groupBy` to organize the fields by `subject`
* `mapObject` and `map` to map the fields from the input to the new hierarchy.

== Example: XML to JSON

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
classrooms: payload..*teacher groupBy $.subject mapObject ((teacherGroup, subject) -> {
   class: {
     name: subject,
     teachers: { (teacherGroup map {
       teacher:{
           name: $.name,
           lastName: $.lastName
       }
     })
   }
  }
})
----

.Input XML
[source,xml,linenums]
----
<school>
    <teachers>
        <teacher>
            <name>Mariano</name>
            <lastName>De Achaval</lastName>
            <subject>DW</subject>
        </teacher>
        <teacher>
            <name>Emiliano</name>
            <lastName>Lesende</lastName>
            <subject>DW</subject>
        </teacher>
        <teacher>
            <name>Leandro</name>
            <lastName>Shokida</lastName>
            <subject>Scala</subject>
        </teacher>
    </teachers>
</school>
----

.Output JSON
[source,json,linenums]
----
{
  "classrooms": {
    "class": {
      "name": "Scala",
      "teachers": {
        "teacher": {
          "name": "Leandro",
          "lastName": "Shokida"
        }
      }
    },
    "class": {
      "name": "DW",
      "teachers": {
        "teacher": {
          "name": "Mariano",
          "lastName": "De Achaval"
        },
        "teacher": {
          "name": "Emiliano",
          "lastName": "Lesende"
        }
      }
    }
  }
}
----

== Example: JSON to JSON

This DataWeave example changes the hierarchy of a JSON object. The output groups fields by `language` and adds a new element, `attendees`, that contains the names of attendees for each course.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
"langs" : payload.langs groupBy $.language mapObject ((nameGroup, language) -> {
     "language" : language,
     "attendees" :
     (nameGroup map {
           name: $.name
     })
})
----

.Input JSON
[source,json,linenums]
----
{
  "langs": [
    {
      "name": "Alex",
      "language": "Java"
    },
    {
      "name": "Kris",
      "language": "Scala"
    },
    {
      "name": "Jorge",
      "language": "Java"
    }
  ]
}
----

.Output JSON
[source,json,linenums]
----
{
  "langs": {
    "language": "Scala",
    "attendees": [
      {
        "name": "Kris"
      }
    ],
    "language": "Java",
    "attendees": [
      {
        "name": "Alex"
      },
      {
        "name": "Jorge"
      }
    ]
  }
}
----

== Related Examples

* xref:dataweave-cookbook-map.adoc[Mapping Data]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[Reference Multiple Inputs]

* xref:dataweave-cookbook-define-function-to-flatten-list.adoc[Defining a Function that Flattens Data in a List]

* xref:dataweave-cookbook-zip-arrays-together.adoc[Zip Arrays Together]

== See Also

* xref:dataweave-types.adoc[DataWeave Value Types]

// * link:dw-functions-core[DataWeave Core Functions]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]