= Precedence in DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


DataWeave expressions are compiled in a specific order. The result of
a compilation of something at one level can serve as input for expressions
in higher levels, but not at lower levels.
//LINK TO DW 1.0 LANDING PAGE IN MULE 3.9 DOCS:
include::partial$dataweave1-links.adoc[tag=dataweave1LandingPage]

== Order of Compilation

The following table orders operators and functions from first compiled (1) to
last compiled (10):

[%header,cols="1,8"]
|===
| Level
| Operator or Function

| 1
a|
* `using`: For initializing local variables in a DataWeave script.
* Unary DataWeave operators at this level:
** `.^`: Schema selector.
** `.#`: Namespace selector.
** `..`: Descendants selector.
** `not`: Logical operator for negation.
** `.@`: All attribute selector, for example, in a case that uses the
expression `payload.root.a.@` to return the attributes and values of the
input payload `<root> <a attr1="foo" attr2="bar" /></root>` within the
array of objects `{ "attr1": "foo", "attr2": "bar" }`.

| 2
a|
* `as`: Used for type coercion.

| 3
a|
* `&#42;`: Multiply.
* `/`: Divide.

| 4
a|
* `+`: Add.
* `-`: Subtract.
* `>>`: Prepend data.
* `<<`: Append data.

| 5
a|
* `&gt;`: Greater than or equal to.
* `=`: Equal to.
* `&lt;`: Less than or equal to.
* `<`: Less than.
* `>`: Greater than.
* `is`: Compare type, for example, used in
xref:dataweave-cookbook-remove-certain-xml-attributes.adoc[Remove Specified XML Attributes].

| 6
a|
* `!=`: Not equal to.
* `~=`: Contains.
* `==`: Equality operator that tries to coerce one value to the type of the
other when the types are different.

| 7
a|
* `and`: Logical `and` operator.

| 8
a|
* `or`: Logical `or` operator.

| 9
a|
* `default`: For setting a default value.
* `case` and `else`: For pattern matching.
* DataWeave functions at this level:
** `matches`
** `match`
** `map`
** `mapObject`
** `groupBy`
** `filter`
* Binary DataWeave selectors at this level:
** `.@keyName` and `.*@`: Binary DataWeave attribute selectors.
** `.*`: Multi-value selector.
** `.^`: Metadata selector.
** `.&`: Key-value pair selector.
** `[?()]`: Filter selector.
* `.keyName`: Value selector.
* `[<index> to <index>]`: Range selector

| 10
a|
* `if else`: Conditional expression used for flow control in DataWeave.
|===

== Order of Chained Function Calls

When functions are chained together in a series, the functions are processed
in order from the first to the last function specified in the chain.

For example, the following script acts on the input array of objects defined
by the variable `flights`. The script first calls `filter` to return an array
that filters out all `price` values that are less than 500. Then it calls
`orderBy` to return an array that reorders the objects found in the input 
from the lowest to the highest `price` value. Finally, it calls `groupBy`
to group the input array of objects alphabetically by `toAirport` value.

.DataWeave Script:
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
var flights = [
  { "toAirport": "SFO", "price": 550, "airline": "American" },
  { "toAirport": "MUA", "price": 200, "airline": "American" },
  { "toAirport": "SFO", "price": 300, "airline": "American" },
  { "toAirport": "CLE", "price": 600, "airline": "American" },
  { "toAirport": "CLE", "price": 190, "airline": "American" },
  { "toAirport": "SFO", "price": 400, "airline": "American" }
]
---
flights filter $.price < 500 orderBy $.price groupBy $.toAirport
----

The result is an object that contains a collection of key-value pairs.

.Output:
----
{
  "CLE": [
    {
      "toAirport": "CLE",
      "price": 190,
      "airline": "American"
    }
  ],
  "SFO": [
    {
      "toAirport": "SFO",
      "price": 300,
      "airline": "United"
    },
    {
      "toAirport": "SFO",
      "price": 400,
      "airline": "American"
    }
  ],
  "MUA": [
    {
      "toAirport": "MUA",
      "price": 200,
      "airline": "American"
    }
  ]
}
----

The order of the function calls is important. For example, the rearranged
expression `flights groupBy $.toAirport filter $.price < 500 orderBy $.price`,
returns an error because the `groupBy` returns an object, and `filter`
expects an array. The resulting error is
`Expecting Type: Array&gt;T&lt;, but got: {String: Array&lt;{|toA... airline: String|}&gt;}`.


== See Also

* xref:dw-core.adoc[Core (dw::Core) functions]
* xref:dw-operators.adoc[DataWeave Operators]
* xref:dataweave-selectors.adoc[DataWeave Selectors]
* xref:dataweave-variables.adoc[DataWeave Variables]
* xref:dataweave-flow-control.adoc[Flow Control in DataWeave]
* xref:dataweave-pattern-matching.adoc[Pattern Matching in DataWeave]
* xref:dataweave-types-coercion.adoc[Type Coercion with DataWeave]
