= DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datawave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

== Overview

The xref:dataweave-language-introduction.adoc[DataWeave Language] is a simple, powerful tool used to query and transform data inside of Mule. It can be implemented to:

* graphically map fields by dragging one attribute to another, just like you were able to with the now deprecated xref:6@studio::datamapper-user-guide-and-reference.adoc[DataMapper], or
* leverage its powerful object-oriented language that's specially designed to make writing transformations quick, without compromising maintainability.

DataWeave supports a variety of transformations: simple *one-to-one*, *one-to-many* or *many-to-one* mappings from an assortment of data structures, and can complete more elaborate mappings including normalization, grouping, joins, partitioning, pivoting and filtering. With DataWeave and Mule Expression Language (MEL), you can take your application's data transformation ability to the next level.

You can also call upon the power of DataWeave language within _other_ components by using xref:mel-dataweave-functions.adoc[Mule Expression Language DataWeave Functions].

The language is tightly integrated with Mule and Anypoint Studio. Use the *Transform Message* component, which allows you to use the language to query and transform data through DataWeave. Any mappings you perform through the graphical interface will be expressed in DataWeave code in real-time.

* Read all about how to leverage the Anypoint Studio UI on xref:6@studio::transform-message-component-concept-studio.adoc[About Transform Message Component]
* Read all about how to implement this same component through XML on xref:dataweave-xml-reference.adoc[DataWeave XML Reference]

[NOTE]
DataWeave supports *DataSense*, which allows you to leverage metadata from connectors, schemas and sample documents in order to design your transformations more easily. DataSense assists you in design time by providing a live stream of content types while you are coding, scaffolding your mappings to help make writing transformations fast and easy.

[TIP]
====
DataWeave replaces xref:6@studio::datamapper-user-guide-and-reference.adoc[DataMapper]. MuleSoft recommends you use DataWeave, if possible, to avoid future obsolescence.

If you have projects that employ the deprecated DataMapper, a migration tool is now included in Studio, which assists in converting a DataMapper map to DataWeave: Right click on a DataMapper, select *Migrate to DataWeave*, and follow the instructions.

See xref:dataweave-migrator.adoc[DataWeave Migrator].
====

== Dataweave Reference Material

* xref:dataweave-quickstart.adoc[DataWeave Quickstart Guide]
* xref:dataweave-language-introduction.adoc[DataWeave Language Introduction]
* xref:dataweave-xml-reference.adoc[DataWeave XML Reference]
* xref:dataweave-examples.adoc[DataWeave Examples]
* xref:dataweave-operators.adoc[DataWeave Operators]
* xref:dataweave-types.adoc[DataWeave Types]
* xref:dataweave-formats.adoc[DataWeave Formats]
* xref:dataweave-selectors.adoc[DataWeave Selectors]
* xref:dataweave-memory-management.adoc[DataWeave Memory Management]
* xref:dataweave-migrator.adoc[DataWeave Migrator Tool]
* xref:dataweave-flat-file-schemas.adoc[DataWeave Flat File Schemas]
* xref:dataweave-troubleshooting.adoc[Troubleshooting Dataweave]

== General MuleSoft Resources





* https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[Mule Support License]