= Change the Value of a Field
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, rename, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, update
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-change-time-zone.adoc

The following DataWeave examples show how to use `update` and `mask` to change the values of some XML elements.

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

[[ex01]]
== Example: Using Update to Change Values

This example uses:

* `update` to update specified fields of the payload with new values
* single-value (`.`) and multi-value (`.*`) selectors to navigate the payload and select the fields to update

The following script shows how the `update` operator works. The example creates a new `users` list by updating each `user` in the payload with a new `user`. The transformation converts `first_name`, `middle_name` and `last_name` to uppercase values:

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex1/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex1/inputs/payload.xml[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex1/out.xml[]
----

[[ex02]]
== Example: Using Mask to Change Values

DataWeave provides a simple way to mask values, without specifying the path to each field:

* `mask` updates all simple elements that match the selected name throughout the input with the specified mask.

The following example masks the `ssn` and `password` values with a set of asterisks (`\****`):

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex2/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex2/inputs/payload.xml[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/change-value-of-a-field-ex2/out.xml[]
----

== Related Examples

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-output-a-field-when-present.adoc[Output a Field When Present]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
