= Format According to Type
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-format-according-to-type.adoc

This DataWeave example applies changes to the keys in an object, depending on
the type of their corresponding values. When the element is an array, the keys
are pluralized. When it's a number, they are set to camel case. In any other
case they are capitalized. +

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The example uses:

* `mapObject` to go through each element in the payload.
* `if` to check that an element is of a given type.
* `camelize` from the String library to apply a camel case format to strings (all words stringed together, using upper case letters to mark separations).
* `capitalize` from the String library to apply a capitalized format to strings (all words are separate and start with an upper case letter).
* `pluralize` from the String library to change singular words into plural.


[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/format-according-to-type/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/format-according-to-type/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/format-according-to-type/out.json[]
----

== Related Examples

* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Output Self-closing XML tags]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
