= Fixed Width Format

MIME Type: `application/flatfile`

ID: `flatfile`

Fixed width types are technically considered a type of Flat File format, but
when selecting this option, the Transform component offers you settings that are
better tailored to the needs of this format.

NOTE: Fixed width in DataWeave supports files of up to 15 MB, and the memory requirement is roughly 40 to 1. For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your TPS needs for large fixed width files. This is not an exact figure; the value might vary according to the complexity of the mapping instructions.

////////////////////////////////////////////////////////////////////////////

[[properties_fixed_width]]
== Configuration Properties

DataWeave supports the following configuration properties for the Fixed Width format.

=== Reader Properties (for Fixed Width)

//TODO: CONSIDER INCLUDE FOR READER PROPS
DataWeave accepts optional parameters that provide instructions for reading input data.
For details, see xref:dataweave-formats-flatfile.adoc[Flat File Format].

Note that schemas with type `Binary` or `Packed` do not allow for the detection
of line breaks, so setting `recordParsing` to `lenient` only allows for long
records to be handled, not short ones. These schemas only work with certain
single-byte character encodings (so not with UTF-8 or any multibyte format).

== Writer Properties (for Fixed Width)

//TODO: CONSIDER INCLUDE FOR WRITER PROPS
DataWeave accepts optional parameters that provide instructions for writing output data. For details. see xref:dataweave-formats-flatfile.adoc[Flat File Format]. All of the properties are optional.

A DataWeave output directive might look like this:

.Example: output Directive
[source,text,linenums]
----
output application/flatfile schemaPath="src/main/resources/schemas/payment.ffd", encoding="UTF-8"
----

[[mime_type_fixed_width]]
== Supported MIME Types (for Fixed Width)

The Fixed Width format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`*/flatfile`
|===
