= Transform XML to JSON
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-perform-basic-transformation.adoc

These simple DataWeave examples change the XML input to JSON output. Note that more complex transformations usually require the use of the `map` or `mapObject` function.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The following DataWeave script maps the names (or keys) for the output fields to values of the input fields. The input fields are specified with selector expressions without any functions. The script also changes the order and names of some of the fields.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/out.json[]
----

In the following example, the DataWeave script transforms the XML containing multiple XML nodes with the same key into a valid JSON creating an array instead of creating JSON nodes with the same key.

[[ex02]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation-ex2/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation-ex2/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation-ex2/out.json[]
----

== Related Examples

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-map.adoc[Map Data with DataWeave]

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]



== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
