= DataWeave Selectors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

DataWeave 2.0 selectors traverse the structures of objects and arrays and
return matching values.

A selector always operates within a context, which can be a reference to
a variable, an object literal, an array literal, or the invocation of a
DataWeave function.

[NOTE]
====
For examples that use the selectors described below, see
xref:dataweave-cookbook-extract-data#[Extract Data].
====

[%header,cols="30,30,40"]
|===
|Selector Type |Syntax |Return Type

| Single-value | `.keyName` | Any type of value that belongs to a matching key
| Multi-value | `.*keyName` | Array of values of any matching keys
| Descendants | `..keyName` | Array of values of any matching descendant keys
| Key-value pair | `.&keyName` | Object with the matching key
| Index | `[<index>]` | Value of any type at selected array index
| Range | `[<index> to <index>]`| Array with values from selected indexes
| XML attribute | `@`, `.@keyName` | String value of the selected attribute
| Namespace | `keyName.#` | String value of the namespace for the selected key
| Key present | `keyName?`, `keyName.@type?` | Boolean (`true` if the
  selected key of an object or XML attribute is present, `false` if not)
| Assert present | `keyName!` | String: Exception message if the key is not present
| Filter |`keyName[?(boolean_expression)]` | Array or object
  containing key-value pairs _if_ the DataWeave expression returns `true`. Otherwise,
  returns `null`.

| Metadata | `.^someMetadata` a|
Returns the value of specified metadata for a Mule payload, variable, or
attribute. The selector can return the value of class (`.^class`),
content length (`.^contentLength`), encoding
(`.^encoding`), mime type (`.^mimeType`), media type (`.^mediaType`),
 raw  (`.^raw`), and custom (`.^myCustomMetadata`) metadata. For details, see
xref:dataweave-cookbook-extract-data#selector_metadata[Extract Data].

|===

[[selectors_variables]]
== Use of Selectors on Content Stored in Variables

All selectors work with the
xref:dataweave-variables-context.adoc[predefined Mule Runtime variables],
such as `payload` and `attributes`, and with
xref:dataweave-variables.adoc[DataWeave variables]. For example, assuming a
DataWeave variable defined as
`var myVar = { "id" : "1234", "name" : "somebody" }`, the DataWeave expression
`myVar.name` returns the value of `"name"`, which is `"somebody"`.

You can select xref:about-mule-event.adoc[Mule event] data by using
Mule Runtime variables.

Extracted values are handled as a literal values (as opposed to
variables, for example) of one of the supported DataWeave value types.

[cols="1,4", options="header"]
|===
| Data to extract | Syntax

| *Payload*
a| `payload`, for example: `payload.name`

If the `payload` is `{"name" : "somebody"}`, `payload.name` returns `"somebody"`.

For more on the Mule payload, see
xref:about-mule-message#_message_payload[Message Payload].

| *Attribute*
a| `attributes.<myAttributeName>`

For examples, see xref:about-mule-message#_attributes[Attributes].

| *Variable*
a|

`<myVariableName>`

To avoid name collisions, you can prepend `variables`:

`variables.<myVariableName>`

For more on Mule variables, see xref:about-mule-variables.adoc[Variables in Mule Apps].

| *Error object*

a| `error`

For information on errors in the flow, you can use `#[error.cause]`.

| *Flow*
a| `flow`

For the flow name in the Logger: `#[flow.name]`

Note that `flow.name` does not work in some Core components, such as Set Payload and Transform Message.

For more on flows, see xref:about-flows.adoc[Flows and Subflows].
|===
