= Set a Default Value
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, examples

You can provide a default values in a few ways:

* Using the `default` keyword.
* Setting the default in an `if-else` or `else-if` statement.
* Using `else` when pattern matching.

== Using the Key Word default

This example uses default to set a default value for a payload in case
the payload value is null.

.DataWeave Script:
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---

(payload.someField default "my default value")
----

.Output
[source,JSON,linenums]
----
"mydefaultvalue"
----

== Setting a Default Within if-else and else-if Statements

You can use
xref:dataweave-flow-control.adoc#control_flow_if_else[if-else]
and
xref:dataweave-flow-control.adoc#control_flow_else_if[else-if]
statements to specify a default value.

The following example uses the string `"value is even"` as its default.

.DataWeave Script:
[source,DataWeave, linenums]
----
%dw 2.0
var myVar = (1 + 1)
output application/json
---
if (isOdd(myVar) == true) "value is odd"
else "value is even"
----

.Output:
[source,JSON,linenums]
----
"value is even"
----

== Setting a Default When Matching Patterns

In xref:dataweave-pattern-matching.adoc[pattern-matching scripts], DataWeave
`case` statements end with an `else` expression that can serve as the default
to return if all preceding `case` expressions return `false`.

.DataWeave Script:
[source,DataWeave, linenums]
----
%dw 2.0
var myVar = "someString"
output application/json
---
myVar match {
    case myVarOne if (myVar == "some") -> ("some" ++ "is myVar")
    case myVarOne if (myVar == "strings") -> ("strings" ++ "is myVar")
    else -> myVar ++ " is myVar"
}
----

.Output:
[source,JSON,linenums]
----
"someString is myVar"
----
