= Flat File Format

MIME Type: `application/flatfile`

ID: `flatfile`

The Flat File format supports multiple types of fixed width records within a single message. The schema structure allows you to define how different record types are distinguished, and how the records are logically grouped.

NOTE: Flat File in DataWeave supports files of up to 15 MB, and the memory requirement is roughly 40 to 1. For example, a 1-MB file requires up to 40 MB of memory to process, so it's important to consider this memory requirement in conjunction with your TPS needs for large flat files. This is not an exact figure; the value might vary according to the complexity of the mapping instructions.

[[examples]]
== Example: Specify a Flat File Schema

This example shows a DataWeave script that outputs data in the Flat File format.
Notice that it uses the `schemaPath` and `structureIndent` writer properties.

[source,dataweave,linenums]
----
%dw 2.0
output application/flatfile schemaPath="src/main/resources/test-data/QBReqRsp.esl", structureIdent="QBResponse"
---
payload
----


// CONFIG PROPS ///////////////////////////////////////////////////////

// Flat File config properties are shared with COBOL Copybook and Fixed Width.
include::partial$dataweave-formats-flatfile-config.adoc[]


[[mime_type]]
== Supported MIME Types

The Flat File format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`*/flatfile`
|===
