= Newline Delimited JSON Format (ndjson)

MIME type: `application/x-ndjson`

ID: `ndjson`

DataWeave represents the Newline Delimited JSON format (ndjson) as an array of objects. Each line of the ndjson format is mapped to one object in the array.

The following parser strategies are supported by the ndjson reader:

* In-memory
* Streaming

For details, see xref:dataweave-formats.adoc#dw_readers_writers[DataWeave Readers].

[[examples]]
== Examples

The following examples show uses of the ndjson format.

* <<example1>>
* <<example2>>

[[example1]]
=== Example: Transform ndjson to the DataWeave Format (dw)

This example shows how DataWeave represents simple ndjson input.

==== Source

The DataWeave script transforms the ndjson input to the DataWeave (dw) format and MIME type.

[source,ndjson,linenums]
----
%dw 2.0
output application/dw
---
{"name": "Leandro","lastName": "Shokida"}
{"name": "Mariano","lastName": "De Achaval"}
----

==== Output

The DataWeave (dw) format outputs the ndjson input into an array of comma-separated objects.

[source,weave,linenums]
----
[
    {"name": "Leandro","lastName": "Shokida"},
    {"name": "Mariano","lastName": "De Achaval"}
]
----

[[example2]]
=== Example: Use the `skipInvalid`

This example shows that the ndjson reader ignores all lines of ndjson data that are invalid if `skipInvalid=true`.

==== Input

The input to the DataWeave source includes valid and invalid lines of ndjson data. Assume that the input is from a file `myInput.ndjson`.

.myInput.ndjson:
[source,ndjson,linenums]
----
{"name": "Christian"
{"name": "Mariano"}
{"name": "Tomo"
{"name": "Shoki"}
----

==== Source

The DataWeave script inputs the contents of the input file `myInput.ndjson`, applies the `skipInvalid=true` reader property, and transforms the input to the JSON format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
var myInput = readUrl('classpath://myInput.ndjson', 'application/x-ndjson, {skipInvalid=true})
output application/json
---
myInput
----

==== Output

The JSON output is an array of the valid objects from the ndjson input.

[source,weave,linenums]
----
[
  {
    "name": "Mariano"
  },
  {
    "name": "Shoki"
  }
]
----


// CONFIG PROPS ///////////////////////////////////////////////////////

[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the Newline Delimited JSON format (ndjson).

=== Reader Properties

The ndjson format accepts properties that provide instructions for reading input data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `ignoreEmptyLine` | `Boolean` | `true` | Ignores any empty line. Valid values are `true` or `false`.
| `skipInvalid` | `Boolean` | `false` | Skips data that is not valid ndjson. Valid values are `true` or `false`.
|===

=== Writer Properties

The ndjson format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `bufferSize` | `Number` | `8192` | Size of the writer buffer.
| `deferred` | `Boolean` | `false` | Property for deferred output. Valid values are `true` or `false`.
| `encoding` | `String` | `'UTF-8'` | Encoding for the ndjson reader to use.
| `skipNullOn` | `String` | `null` | Valid values are `arrays` or `objects`.
| `writeAttributes` | `Boolean` | `false` | Valid values are `true` or `false`.
|===

[[mime_type]]
== Supported MIME Types

The Newline Delimited JSON format (ndjson) supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/x-ndjson`
|`application/x-ldjson`
|===
