= Include XML Namespaces
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

You can define different namespaces in the header and then reference them on
each tag.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

Starting in the Mule 4.2.1 release, DataWeave also supports dynamically
generated namespace keys and attributes.

The following example uses:

* `ns` for namespace definitions in the header
* `@` to define other attributes in an XML element

[[ex1]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/include-xml-namespaces-ex1/transform.dwl[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/include-xml-namespaces-ex1/out.xml[]
----

== Dynamically Generated Namespace Values

_Support starting in Mule version 4.2.1_

Using input defined in the DataWeave variables, the DataWeave functions in the
following example output values for namespace keys and attributes.

[[ex2]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/include-xml-namespaces-ex2/transform.dwl[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/include-xml-namespaces-ex2/out.xml[]
----


== See Also

* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Output Self-closing XML tags]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
