= Map Objects Key
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, as

This DataWeave example uses the `mapObject` function to iterate through an array of objects and appends a new object that matches the value of the specified criteria.

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The input consists of a JSON object with sheets. The value of every sheet (for example, `(sheet)1`, `(sheet)2`) is an array of objects. The DataWeave script adds another object `append` as the last item to the matched sheet array if the sheet number equals to the value of the `Id` key of the `append` object.
The example uses the function `fun extractNumber` to extract the sheet number from the sheet page name `pageName`.
Then the DataWeave function `mapObject` iterates over every sheet in the root, and if the `extractNumber` equals to the `append.Id` value, the function adds the `append` object to the matched sheet object.


[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-an-object-key/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/map-an-object-key/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/map-an-object-key/out.json[]
----


== Related Examples

* xref:dataweave-cookbook-map.adoc[Map Data with DataWeave]

* xref:dataweave-cookbook-map-object-elements-as-an-array.adoc[Map Object Elements as an Array]

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
