
= Text Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, text, text/plain, text/plain

MIME type: `text/plain`

ID: `text`

The Text Plain format represents text as a string.

Note that DataWeave parses, encodes, and stores this format into RAM memory.

[[examples]]
== Example

This example shows how DataWeave represents Text Plain data.

=== Input

The Plain Text data serves as the input payload to the DataWeave source.

[source,txt,linenums]
----
This is text plain
----

=== Source

The DataWeave script transforms the Text PLain input payload to the DataWeave (dw) format and MIME type. It returns a string.

[source,dataweave,linenums]
----
output application/dw
---
payload
----

=== Output

Because the DataWeave (dw) output is a string, it is wrapped in quotation marks.

[source,dataweave,linenums]
----
"This is text plain"
----


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the Text format.


[[reader_properties]]
=== Reader Properties

There are no reader properties for Text data.

 
[[writer_properties]]
=== Writer Properties

The Text format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|The size of the buffer writer
|`deferred`  |`Boolean`|`false`|Indicates if the output should be deferred. Valid Options: `true` or `false`
|`encoding`  |`String`|`null`|The charset name to be used by this writer to encode the strings.
|===


[[mime_types]]
== Supported MIME Types

The Text format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`text/plain`
|===
