= Select XML Elements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure

DataWeave provides a number of xref:dataweave-selectors.adoc[selectors] for traversing the structure of input data and returning matching values. The following examples use a single-value DataWeave selector (`.`) to extract XML data.

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The XML markup language requires a single root element. In the following example, the selector on the root (`language`) is able to extract the child element because the child has no siblings.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01/inputs/payload.xml[]
----

.Output XML:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01/out.xml[]
----

[[ex01b]]
To return all subelements of the root element in a valid XML structure with a single root, the following script uses a DataWeave key to specify a new element name (`myroot`) and selects the root (`root`) to return its value. A script that fails to return a  single XML root produces the following error: `Trying to output non-whitespace characters outside main element tree (in prolog or epilog)...`.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01b/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01b/inputs/payload.xml[]
----

.Output XML:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex01b/out.xml[]
----

[[ex02]]
The following example uses the name of the child element (`name`) with the single-value selector to select its value. Notice how `payload.language.name` navigates to the child element. The script also provides a root element for the value so that DataWeave can construct valid XML.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex02/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex02/inputs/payload.xml[]
----

.Output XML:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex02/out.xml[]
----

[[ex03]]
The following example uses an index to select the second child element from the input XML. Notice that DataWeave treats child elements as indices of an array, so it can select the second child by using the index `language[1]`. The result is a single XML element, so it is not necessary to construct a root node for it.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex03/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex03/inputs/payload.xml[]
----

.Output XML:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex03/out.xml[]
----

[[ex04]]
If multiple child elements of the input have the same name, you use the index to select the value of the child. The following example selects a subelement of a child element.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex04/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex04/inputs/payload.xml[]
----

.Output XML:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-element-ex04/out.xml[]
----
