= Dynamically Map Based on a Definition
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-map-based-on-an-external-definition.adoc

You can create a transformation that can dynamically change what it does depending on a definition input. This DataWeave example receives both a payload input, and a variable named `mapping` that specifies how to rename each field and what default value to use in each.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The example uses the following:

* A `map` function to go through all of the elements in the input array. Also a second `map` function to go through each field in each element.
* A custom function that applies the changes specified in the `mapping` variable.
* `default` to set a default value, that comes from the `mapping` variable.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/map-based-on-an-external-definition/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/map-based-on-an-external-definition/inputs/payload.xml[]
----

.Input Mule Event Variable (JSON):
[source,json,linenums]
----
include::partial$cookbook-dw/map-based-on-an-external-definition/inputs/vars/mappings.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/map-based-on-an-external-definition/out.json[]
----


== Related Examples

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]

* xref:dataweave-cookbook-exclude-field.adoc[Exclude Fields from the Output]

* xref:dataweave-cookbook-output-a-field-when-present.adoc[Output a Field When Present]

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
