
= Ndjson Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, ndjson, application/x-ndjson, application/x-ldjson, application/x-ndjson

MIME type: `application/x-ndjson`

ID: `ndjson`

DataWeave represents the Newline Delimited JSON format (ndjson) as an array of objects. Each line of the ndjson format is mapped to one object in the array.

The following parser strategies are supported by the ndjson reader:

* In-memory
* Streaming

For details, see xref:dataweave-formats.adoc#dw_readers_writers[DataWeave Readers].

[[examples]]
== Examples

The following examples show uses of the ndjson format.

* <<example1>>
* <<example2>>

[[example1]]
=== Example

This example shows how DataWeave represents a simple ndjson input.

==== Input

[source,ndjson,linenums]
----
{"name": "Leandro","lastName": "Shokida"}
{"name": "Mariano","lastName": "De Achaval"}
----

==== Source

The DataWeave script transforms the ndjson input to the DataWeave (dw) format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
payload
----

==== Output

The DataWeave (dw) format outputs the ndjson input into an array of comma-separated objects.

[source,weave,linenums]
----
[
    {"name": "Leandro","lastName": "Shokida"},
    {"name": "Mariano","lastName": "De Achaval"}
]
----

[[example2]]
=== Example

This example shows that the ndjson reader ignores all lines of ndjson data that are invalid if `skipInvalid=true`.

==== Input

The input to the DataWeave source includes valid and invalid lines of ndjson data. Assume that the input is from a file `myInput.ndjson`.

.myInput.ndjson:
[source,ndjson,linenums]
----
{"name": "Christian"
{"name": "Mariano"}
{"name": "Tomo"
{"name": "Shoki"}
----

==== Source

The DataWeave script inputs the contents of the input file `myInput.ndjson`, applies the `skipInvalid=true` reader property, and transforms the input to the JSON format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
var myInput = readUrl('classpath://myInput.ndjson', 'application/x-ndjson, {skipInvalid=true})
output application/json
---
myInput
----

==== Output

The JSON output is an array of the valid objects from the ndjson input.

[source,weave,linenums]
----
[
  {
    "name": "Mariano"
  },
  {
    "name": "Shoki"
  }
]
----


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for this format.


[[reader_properties]]
=== Reader Properties

This format accepts properties that provide instructions for reading input data.


[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`ignoreEmptyLine`  |`Boolean`|`true`|Ignores any empty line.
 Valid values are `true` or `false`.
|`skipInvalid`  |`Boolean`|`false`|Skips invalid records. If any record is not a valid json value it will ignore it.
 Valid values are `true` or `false`.
|===

[[writer_properties]]
=== Writer Properties

This format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|Size of the buffer writer.
|`deferred`  |`Boolean`|`false`|When set to `true`, DataWeave generates the output as a data stream, and the script's execution is deferred until it is consumed.
 Valid values are `true` or `false`.
|`encoding`  |`String`|`'UTF-8'`|Encoding to be used by this writer.
|`skipNullOn`  |`String`|`null`|Skips null values on the specified data structure. By default it doesn't skip
 Valid values are `arrays` or `objects`.
|`writeAttributes`  |`Boolean`|`false`|If a key has attributes, it will put them as children key-value pairs of the key that contains them. The attribute key name will start with @.
 Valid values are `true` or `false`.
|===


[[mime_types]]
== Supported MIME Types

This format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/x-ndjson`
|`application/x-ldjson`
|===
