= DataWeave Language
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datawave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

DataWeave is the MuleSoft expression language for accessing and transforming data received through a Mule app. DataWeave is tightly integrated with Mule runtime, which runs the scripts and expressions in your Mule app.

DataWeave acts on data in the Mule event. Most commonly, you use it to access and transform data in the message payload. For example, after a component in your app retrieves data from one system, you can use DataWeave to modify and output selected fields in that data to a new data format, then use another component in your app to pass on that data to another system.

The simple example below demonstrates a few important features of the DataWeave language:

* Data transformation from one format to another. The example transforms `application/json` input to `application/xml` output.
* Data selectors that access fields within an input data structure. The script selects keys in a JSON object from the message payload input (for example, with `payload.title`) and then outputs their values.
* Use of a core DataWeave function on the value of an input field `upper(payload.author)`.

.Input Payload
[source,json,linenums]
----
{
  "title": "Java 8 in Action",
  "author": "Mario Fusco",
  "year": 2014
}
----

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
{
  order: {
    'type': 'Book',
    'title': payload.title,
    'author': upper(payload.author),
    'year': payload.year
  }
}
----

.Output Payload
[source,xml,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<order>
  <type>Book</type>
  <title>Java 8 in Action</title>
  <author>MARIO FUSCO</author>
  <year>2014</year>
</order>
----

Far more complex data manipulation and transformations are possible.

DataWeave supports several file input and output formats in addition to XML and JSON. It provides a number of functions for manipulating data and includes selectors for accessing fields in the data structure. It can handle a number of data types in addition to arrays, key-value pairs, Java objects, strings, and numbers. It also supports type coercion, and the creation and use of your own functions, data types, and variables in your scripts.

You write DataWeave expressions and scripts within message processors (components, connectors, or modules) when creating apps in Anypoint Studio or Design Center, or as handwritten XML configuration files.

* The Transformer component is for creating scripts that perform data transformations, whether simple format conversions or complex data extraction and transformation processes.
+
See xref:transform-component-about.adoc[Transform Message Component].
+
* Many Mule message processors support DataWeave expressions, allowing you to access and use core DataWeave functions on parts of the Mule event that you need.
+
See the inline DataWeave script examples for Set Payload in xref:dataweave-language-introduction.adoc[DataWeave Scripts]. For other examples, see the `message` attribute in  xref:logger-component-reference.adoc[Logger Component] examples, Set Payload (`<ee:set-payload>`) and Set Variable components in the xref:for-each-scope-concept.adoc[For Each Scope] examples, and xref:connectors::file/file-write.adoc[<file:content>] in the File Connector documentation.

////
TODO: NEED TO MOVE SOME OF THIS TO ITS OWN TOPIC AND TO RESOLVE OVERLAP WITH OTHER CONTENT TO AVOID DUPLICATION. SOME OF IT TALKS ABOUT STUFF NOT YET INTRODUCED. OTHER MIGHT BE A BIT TOO TECHNICALLY DETAILED FOR THIS DW LANDING PAGE. Since this page has to be read by DW novices who are not necessarily true developers, we should keep this DW landing page more general.
== How DataWeave Determines the Data Type

To understand how DataWeave determines the data type of inputs and outputs, it helps to understand how DataWeave works inside Mule runtime.

=== Input

Mule has an special object called a `TypedValue`. This class represents a `Pair<Object,DataType> Being DataType = Pair<MimeType,Encoding>`.

All variables and the payload are `TypedValue`. The `TypedValue` can also be present in a more nested places. For example, the List operation in the File connector returns a `List<TypedValue>`, so the payload is `TypedValue<List<TypedValue, DataType>, DataType<Java>>`. This allows DataWeave to list diferent types of files (JSON, XML, CSV, and so on) for DataWeave to read.

=== DataType

DataWeave uses the `DataType` part to determine what reader to use based on the MimeType and how to configure that reader (encoding, reader properties) based on the MimeType properties.

=== Output

DataWeave always outputs a `TypedValue`. The interesting part is how DataWeave inferes the DataType part that drives what writer to use.

You can manually specify the DataType on the script with the `output` directive.

If the script that is being executed is assigned to a Message Processing field, the engine will provide DataWeave the hint what is the expected type based on the metadata of that field. For example, if it is a Pojo then DW will know what class to instanciate and will know that it need to use the Java Writer, so you don't need to know all that internal details.

When DataWeave cannot determine the `DataType`, it does the following:

* Looks at the script and see what inputs are used. If all inputs are of the compatible or the same `DataType`, DataWeave uses that `DataType`. For example, if in your script, you put `<set-payload value="#[payload.foo]/>` DataWeave examines the `DataType` of the payload. If the payload is JSON, DataWeave will use the JSON writer. If you have more than one input used and they are from different DataTypes an error is going to be thrown. For example, `<set-payload value="#[payload.foo ++ vars.bar]/>` being `vars.bar` of type XML and `payload` of type JSON. Sometimes, specifically with XML, you may write an expression on a set payload and it will fail because it is actually an invalid XML structure.

* If no input is being used, the Java writer is used  `<set-payload value="#[{a: true}]/>`  is going to output a `java.util.Map` with a entry ("a", true).

* For the Logger message processor, DataWeave has a special feature to avoid errors. DataWeave tries to use the logic under #3 but if it fails because that writer can not emit that DataStructure then DataWeave will use the DataWeave writer that can write out any Data Structure possible.
////

== See Also

* xref:about-mule-event.adoc[Mule Events]
* xref:dataweave-formats.adoc[Formats Supported by DataWeave]
* xref:dataweave-selectors.adoc[DataWeave Selectors]
* xref:dataweave-language-introduction.adoc[DataWeave Scripts]
* xref:about-components.adoc[Core Components]
* xref:connectors::index.adoc[Connectors and Modules]
