= Format According to Type
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example applies changes to the keys in an object, depending on the type of their corresponding values. When the element is an array, the keys are pluralized. When it's a number, they are set to camel case. In any other case they are capitalized.


This example uses:

* `mapObject` to go through each element in the payload.
* `if` to check that an element is of a given type.
* `camelize` from the String library to apply a camel case format to strings (all words stringed together, using upper case letters to mark separations).
* `capitalize` from the String library to apply a capitalized format to strings (all words are separate and start with an upper case letter).
* `pluralize` from the String library to change singular words into plural.



.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
import * from dw::core::Strings
output application/json
---
payload mapObject ((elementValue, elementKey) -> {
  (if (elementValue is Array)
      pluralize(elementKey)
    else if(elementValue is Number)
      camelize(elementKey)
    else capitalize(elementKey)) : elementValue
})
----

.Input
[source,json,linenums]
----
{
  "VersionNo": 1.6,
  "StoreOfOrigin": "SFO",
  "Item":
    [
      {
        "ID":"34546315801",
        "DeliveryMethod":"AIR",
        "Quantity":8
      },
      {
        "ID":"56722087289",
        "Boxes": 3,
        "DeliveryMethod":"GROUND",
        "Quantity":2
      }
    ]
  }
----



.Output
[source,json,linenums]
----
{
  "versionNo": 1.6,
  "Store Of Origin": "SFO",
  "Items": [
    {
      "ID": "34546315801",
      "DeliveryMethod": "AIR",
      "Quantity": 8
    },
    {
      "ID": "56722087289",
      "Boxes": 3,
      "DeliveryMethod": "GROUND",
      "Quantity": 2
    }
  ]
}
----

== Related Examples


* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Output Self-closing XML tags]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]



== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
