= DataWeave Memory Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, streaming, weaveoutputhandler

When processing large files through DataWeave in Mule runtime engine, there are a few things you can set up to fine-tune how much memory will be used and when.

[[buffersize]]
== RAM vs Disk Usage

DataWeave uses disk data storage to avoid running out of memory. The files created are placed in a default temporary directory. If you want to store those files in a custom directory instead, you can specify the directory by using the `java.io.tmpdir` property.

Two types of DataWeave files are generated, both with names beginning with `dw-buffer-`: +

* `dw-buffer-output-${count}.tmp` +
Used to store the output of a transformation when the result is bigger than the threshold *1572864 bytes*.
To change this threshold value, add the system property `com.mulesoft.dw.buffersize` and assign it the number of bytes you want as your new threshold. Because you can define system properties in several ways, see xref:configuring-properties.adoc#system-properties[system properties] for further details.
Mule runtime engine deletes the file when the value is no longer referenced, JVM GC collects it or when the Mule Event finishes executing.

* `dw-buffer-index-${count}.tmp` +
Used to store index information of a value being read. This file helps DataWeave access data quickly. Mule runtime engine deletes the file when the execution of the transformation ends or, in a streaming use case like the foreach loop, when the stream ends (when foreach finishes its execution).

== See Also



* xref:dataweave-language-introduction.adoc[DataWeave Scripts]
* xref:dataweave-selectors.adoc[DataWeave Selectors]
