= Add and Subtract Time
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example shows multiple addition and subtraction operations that
deal with date and time types.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The examples use:

* `as` function to coerce a String to Period type
* `P<date>T<time>` for the Period data type, which provides designators for years, months, days, hours, minutes, and seconds +
For example, `|P2Y9M1D|` refers to a period of two years, nine months, and one day, and `|PT5H4M3S|` indicates a time period of five hours, four minutes, and three seconds.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/add-and-subtract-time/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/add-and-subtract-time/out.json[]
----

== See Also

* xref:dataweave-types.adoc#dw_type_dates_period[Period]

* xref:dataweave-cookbook-parse-dates.adoc[Parse Dates]

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
