= Use Regular Expressions in DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, as

Several DataWeave functions accept regular expressions as arguments. You can use them to return or check for matches. You can also construct regular expressions that incorporate DataWeave expressions that include functions and variables.

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

[[ex01]]
== Return Matches from a String

This example uses regular expressions in a number of DataWeave functions to returns matches to an input variable "mycompany.com".

* `contains` returns `true` based a regular expression that matches part of the  the input string.
* `find` returns an array of indices that specify the matching locations in the input string. This function treats the input string as a string array.
* `match` returns an array of substrings that match the regular expression.
* `matches` returns `true` because the regular expression matches the input string exactly.
* `replace` returns a URL that changes `.com` in the input string to `.net`, based on the regular expression `\..*m`.
* `scan` returns an subarray of comma-separated substrings to which the regular expression match.
* `splitBy` splits an input string into an array substrings based on the `.` in the input.   

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/use-regular-expressions-ex01/transform.dwl[]

----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/use-regular-expressions-ex01/out.json[]
----

For function documentation, see:

* xref:dw-core-functions-contains.adoc[contains]
* xref:dw-core-functions-find.adoc[find]
* xref:dw-core-functions-match.adoc[match]
* xref:dw-core-functions-matches.adoc[matches]
* xref:dw-core-functions-replace.adoc[replace]
* xref:dw-core-functions-scan.adoc[scan]
* xref:dw-core-functions-splitby.adoc[splitby]

[[ex01]]
== Return Matches from a String

This example constructs a regular expression by using the DataWeave concatenate function (`++`) to incorporate a DataWeave variable into a regular expression.
The regular expression matches "somebiz". The example uses `replace` and `with` to replace "somebiz" with "abcd".

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/use-regular-expressions-ex02/transform.dwl[]

----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/use-regular-expressions-ex02/out.json[]
----

== See Also

* xref:dataweave-types.adoc#dw_type_regex[Regex (dw::Core Type)]

* xref:dw-core-types.adoc[Core Types (dw::Core)]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
