= Text Plain Format

MIME Type: `text/plain`

ID: `text`

The Text Plain format represents text as a string.

Note that DataWeave parses, encodes, and stores this format into RAM memory.

[[examples]]
== Example

This example shows how DataWeave represents Text Plain data.

=== Input

The Plain Text data serves as the input payload to the DataWeave source.

[source,txt,linenums]
----
This is text plain
----

=== Source

The DataWeave script transforms the Text PLain input payload to the DataWeave (dw) format and MIME type. It returns a string.

[source,dataweave,linenums]
----
output application/dw
---
payload
----

=== Output

Because the DataWeave (dw) output is a string, it is wrapped in quotation marks.

[source,dataweave,linenums]
----
"This is text plain"
----


// CONFIG PROPS ///////////////////////////////////////////////////////

[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the Text Plain format.

=== Reader Properties

There are no reader properties for Text Plain data.

=== Writer Properties

The Text Plain format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `bufferSize` | `Number` | `8192` | Size of the writer buffer.
| `deferred` | `Boolean` | `false` | Property for deferred output.
  Valid values are `true` or `false`.
| `encoding` | `String` | `null` | Encoding for the writer to use.
|===

[[mime_type]]
== Supported MIME Types

The Text Plain format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`text/plain`
|===
