= Flatten Elements of Arrays
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

DataWeave can flatten subarrays of an array and collections of key-value pairs
within DataWeave objects, arrays, and subarrays.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

== Flatten Subarrays with Key-Value Pairs into an Array of Objects

This example shows how `flatten` acts on key-value pairs of the input array
defined by the variable `arrayOne`. Notice that every key-value pair in the
array becomes a separate DataWeave object.

The example uses this function:

* `flatten` to move the elements from the subarrays to the parent array,
eliminate the subarrays, and covert all key-value pairs into a list of objects
within the parent array.

[[ex1]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/extract-data-ex1/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/extract-data-ex1/out.json[]
----

== Flatten Combined Arrays

Like the previous DataWeave example, the following returns an array that combines and flattens the
elements from two arrays. This second example applies the selector `fruit`
to select only the values of the key `fruit` and to exclude other values in
the array.

This example uses:

* `++` to combine the objects of two arrays (`arrayOne` and `arrayTwo`) into
a single array.
* `flatten` to flatten the combined array into a list of key-value pairs.

[[ex2]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/extract-data-ex2/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/extract-data-ex2/out.json[]
----

The only difference between the <<ex2, previous example>> and the
following example is the addition of the `.fruit` selector to the body expression
to select all the `fruit` values and to exclude values
of the `notfruit` keys from the output array.

[[ex3]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/extract-data-ex3/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/extract-data-ex3/out.json[]
----

The next example uses `..*fruit` as a selector in the body expression instead
of `.fruit` to return all nested `fruit` values in the flattened array. It also
flattens three combined arrays instead of two.

[[ex4]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/extract-data-ex4/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/extract-data-ex4/out.json[]
----

== Flatten Subarrays into the Parent Array

This example shows how the `flatten` function acts on a variety of data types,
including numbers, DataWeave objects, subarrays, a string, a `null` value, and
and a key-value pair. Notice that elements of the subarrays become elements of
the parent array, and the subarrays are no longer present.

The example uses this function:

* `flatten` to flatten the subarrays into their parent arrays.

[[ex5]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/extract-data-ex5/transform.dwl[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/extract-data-ex5/out.json[]
----

== See Also

* xref:dw-core-functions-flatten.adoc[flatten]

* xref:dataweave-cookbook-define-function-to-flatten-list.adoc[Define a Function That Flattens Data in a List]

* xref:dataweave-selectors.adoc[Selectors]
