
= Java Properties Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, properties, */x-java-properties, */properties, text/x-java-properties

MIME type: `text/x-java-properties`

ID: `properties`

The Text Java Properties format parses any Java properties file. This format represents simple key-value pairs. DataWeave represents these pairs as an object with string values.

[[examples]]
== Example: Represent a properties File in the DataWeave Format (dw)

This example shows how DataWeave represents a properties file.

=== Input

The following `text/x-java-properties` data is from a properties file. The file contains key-value pairs that provide host and port values. This content serves as the input payload to the DataWeaave script.

[source,properties,linenums]
----
host=localhost
port=1234
----

=== Source

The DataWeave script transforms the `text/x-java-properties` input payload to the DataWeave (dw) format and MIME type. It returns a string.

[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
payload
----

=== Output

The output is an object in the DataWeave (dw) format. The object contains a collection of key-value pairs that match the `text/x-java-properties` input. Notice that the output wraps the values in quotation marks.

[source,dataweave,linenums]
----
{
    host: "localhost",
    port: "1234"
}
----


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the Java Properties format.


[[reader_properties]]
=== Reader Properties

There are no reader properties for Java Properties data.

 
[[writer_properties]]
=== Writer Properties

The Java Properties format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|The size of the buffer writer
|`deferred`  |`Boolean`|`false`|Indicates if the output should be deferred. Valid Options: `true` or `false`
|`encoding`  |`String`|`null`|The charset name to be used by this writer to encode the strings.
|===


[[mime_types]]
== Supported MIME Types

The Java Properties format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`*/x-java-properties`
|`*/properties`
|===
