= Select XML Elements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure

You can use DataWeave to select elements from an XML input.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The following examples uses a single-value DataWeave selector (`.`) to extract the value of an XML element.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/select-xml-node-ex01/transform.dwl[]
----

.Input XML Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/select-xml-node-ex01/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/rselect-xml-node-ex01/out.xml[]
----

The XML markup language requires a single root node. If an XML element has more than one child node and you want to extract one of those children, your script must specify a new node with a DataWeave key and use a DataWeave selector on the name of the subelement or an index (such as `[1]`) to select the value of the child element. The following examples illustrate these options.

[[ex02]]
The following example specifies a new element name (`newname`) to use for the XML element and uses a DataWeave selector to select the value of a child element from the input XML.
You can use any valid element name, including the name in the input.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/rename-keys-ex02/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex02/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex02/out.xml[]
----

[[ex03]]
The following example uses an index to select the value of the second child element from the input XML, and it specifies an element name that matches the input element name (`version`). Notice that DataWeave treats the child elements as indices of an array, so it selects the second child by using the index `language[1]`.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/rename-keys-ex03/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex03/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex03/out.xml[]

[[ex04]]
If multiple child elements of the input have the same name, you must use the index to select the value of the child. Once you select that element, you can use use selectors on it. The following examples selects a subelement of a child element.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/rename-keys-ex04/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex04/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex04/out.xml[]

[[ex05]]
To select all child elements, you can provide a new element name and select the parent element.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/rename-keys-ex05/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex05/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/rename-keys-ex05/out.xml[]


== See Also

* xref:dataweave-selectors.adoc[Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
