= Binary Format

MIME Type: `application/octet-stream`

ID: `binary`

The Binary data format handles binary content, such as an image or PDF. Such text is represented as `Binary` type.

Note that Binary content is stored into RAM memory.

[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for Avro.

=== Reader Properties (for Binary)

There are no reader properties for Binary data.

=== Writer Properties (for Binary)

The Binary writer accepts optional parameters that provide instructions for writing Binary output data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `bufferSize` | `Number` | `8192` | Size of the buffer writer.
| `deferred` | `Boolean` | `false` | Property for deferred output.
  Valid values are `true` or `false`.
|===

[[mime_type]]
== Supported MIME Types

The Binary format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/octet-stream`
|`application/x-binary`
|===
