= Output Self-closing XML Tags
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

For XML, DataWeave by default outputs every value within an opening and closing tag, even if the tag contains no value (for example, `<element2></element2>`).

To output empty tags as a self-closing XML element (for example, `<element2/>`), you can set the `inlineCloseOn="empty"` output directive in the DataWeave header.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/xml inlineCloseOn="empty"
---
payload
----

.Input JSON
[source,json,linenums]
----
{
  "customer":{
    "userName": "John Doe",
    "password":{},
    "status":"active",
    "lastLogin":{}
  }
}
----

.Output XML
[source,xml,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<customer>
  <userName>John Doe</userName>
  <password/>
  <status>active</status>
  <lastLogin/>
</customer>
----

////
NOT CLEAR WHY THIS CONTENT WAS ON THIS PAGE:

1. inlineCloseOn is not valid for JSON.
2. We're talking about XML tags here, not JSON.

PROBABLY CHOPPED UP EXAMPLE INCORRECTLY.
TODO: NEED TO FIND REST OF CONTENT AND FIX.

removeAttribute(payload, "password")
----

{
  "parentchild":{

    "child":{},
    "child2":{},
    "child3":{}
  }
}
----
////

== Related Examples

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

* xref:dataweave-cookbook-remove-certain-xml-attributes.adoc[Remove Specified XML Attributes]

* xref:dataweave-cookbook-include-xml-namespaces.adoc[Include XML Namespaces]

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
