= YAML Format

MIME Type: `application/yaml`

ID: `yaml`

Values in the YAML data format map one-to-one with DataWeave values.
DataWeave natively supports all of the following YAML types:

* `String`
* `Boolean`
* `Number`
* `Nil`
* `Mapping`
* `Sequences`

[[examples]]
== Example: Represent YAML in the DataWeave Format (dw)

This example shows how DataWeave represents YAML values.

=== Input

The following YAML snippet serves as the input payload for the DataWeave source
in this example.

[source,yaml,linenums]
----
american:
  - Boston Red Sox
  - Detroit Tigers
  - New York Yankees
national:
  - New York Mets
  - Chicago Cubs
  - Atlanta Braves
----

=== Source

The DataWeave script transforms the YAML encoded input payload to the DataWeave (dw) format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
payload
----

=== Output

The following output shows how the YAML input is represented in the DataWeave (`dw`) format.

[source,dataweave,linenums]
----
{
  "american": [
    "Boston Red Sox",
    "Detroit Tigers",
    "New York Yankees"
  ],
  "national": [
    "New York Mets",
    "Chicago Cubs",
    "Atlanta Braves"
  ]
}
----


// CONFIG PROPS ///////////////////////////////////////////////////////

[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the YAML format.

=== Reader Properties

The YAML format accepts properties that provide instructions for reading input data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
| `maxEntityCount` | `Number` | `1` | The maximum number of entity expansions. The limit is provided to avoid the billion laughs attack, a denial-of-service attack.
|===

=== Writer Properties

The YAML format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `bufferSize` | `Number` | `8192` | Size of the writer buffer.
| `deferred` | `Boolean` | `false` | Property for deferred output.
  Valid values are `true` or `false`.
| `encoding` | `String` | `UTF-8` | Encoding for the writer to use.
| `skipNullOn` | `String` | `null` | Skips `null` values in the specified data
structure. Valid values are `arrays`, `objects`, or `everywhere`. The writer does not skip such values unless you set the property.
|===

[[mime_type]]
== Supported MIME Types

The YAML format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/yaml`
|`text/yaml`
|`application/x-yaml`
|`text/x-yaml`
|===
