= Binary Format

MIME Type: `application/octet-stream`

ID: `binary`

The Binary data format handles binary content, such as an image or PDF. Such content is represented as a `Binary` type.

Note that Binary content is stored into RAM memory.


// CONFIG PROPS ///////////////////////////////////////////////////////

[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for this format.

=== Reader Properties

There are no reader properties for Binary data.

=== Writer Properties

The Binary format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
| Parameter | Type | Default | Description
| `bufferSize` | `Number` | `8192` | Size of the writer buffer.
| `deferred` | `Boolean` | `false` | Property for deferred output.
  Valid values are `true` or `false`.
|===

[[mime_type]]
== Supported MIME Types

The Binary format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/octet-stream`
|`application/x-binary`
|===
