= DataWeave Memory Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, streaming, weaveoutputhandler

When processing large files through DataWeave in Mule, there are a few things you can set up to fine-tune how much memory will be used and when.

[[buffersize]]
== RAM vs Disk Usage

DataWeave uses disk for storing information and not running out of memory. The files that are going to be created are going to be placed on the temporary directory, which can be specified using the `java.io.tmpdir` property if a custom directory is desired instead of the system default. 
All DataWeave files are going to have the prefix `dw-buffer-` and there are two kind of files that are being generated.
-  `dw-buffer-output-${count}.tmp` is used to store the output of a transformation when the result is bigger than the threadshold *1572864 bytes*.
To change the threshold value at which memory is no longer used as a buffer, you must add the system property `com.mulesoft.dw.buffersize` and assign it the number (in bytes) of your new threshold.  System properties may be defined in several ways. See xref:configuring-properties.adoc#system-properties[system properties] for more details on how to set them.
This file is going to be deleted by the Mule Runtime when, the value is no longer referenced and JVM GC collects it or when the Mule Event finishes executing.

- `dw-buffer-index-${count}.tmp` is used to store index information of a value being read. This file helps DataWeave access data quickly. This file is going to be deleted when the execution of the transformation ends or in the case of a streaming use case like
the foreach, when the stream ends, meaning when the foreach finishes its execution.

== See Also



* xref:dataweave-language-introduction.adoc[DataWeave Scripts]
* xref:dataweave-selectors.adoc[DataWeave Selectors]
