= Change the Value of a Field
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, rename, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, mapobject, unless, otherwise

This DataWeave example changes the values of some XML elements. Here, it changes the values of keys containing sensitive data to a set of asterisks (`\****`).

It uses these functions:

* `mapObject` to go through the users in the input. When on each user, it uses two other `mapObject` functions to go through the fields in both personal information and the login information.
* `if` and `else` to mask the values of the `ssn` and `password` keys.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
users: { (payload.users mapObject (userObject) -> {
    user: {
         personal_information: userObject.personal_information mapObject (value, key) ->
         {
            (if (key ~= "ssn") (key): "****"  else (key): value)
         },
         login_information: userObject.login_information mapObject (value, key) ->
         {
            (if (key ~= "password") (key): "****" else (key): value)
         }
      }
   })
}
----

.Input XML
[source,xml,linenums]
----
<users>
    <user>
        <personal_information>
            <first_name>Emiliano</first_name>
            <middle_name>Romoaldo</middle_name>
            <last_name>Lesende</last_name>
            <ssn>001-08-84382</ssn>
        </personal_information>
        <login_information>
            <username>3miliano</username>
            <password>mypassword1234</password>
        </login_information>
    </user>
    <user>
        <personal_information>
            <first_name>Mariano</first_name>
            <middle_name>Toribio</middle_name>
            <last_name>de Achaval</last_name>
            <ssn>002-05-34738</ssn>
        </personal_information>
        <login_information>
            <username>machaval</username>
            <password>mypassword4321</password>
        </login_information>
    </user>
</users>
----

.Output XML
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<users>
  <user>
    <personal_information>
      <first_name>Emiliano</first_name>
      <middle_name>Romoaldo</middle_name>
      <last_name>Lesende</last_name>
      <ssn>****</ssn>
    </personal_information>
    <login_information>
      <username>3miliano</username>
      <password>****</password>
    </login_information>
  </user>
  <user>
    <personal_information>
      <first_name>Mariano</first_name>
      <middle_name>Toribio</middle_name>
      <last_name>de Achaval</last_name>
      <ssn>****</ssn>
    </personal_information>
    <login_information>
      <username>machaval</username>
      <password>****</password>
    </login_information>
  </user>
</users>
----



////
Without explicitly defined keys:

%dw 2.0
output application/xml
---
users: { (payload.users mapObject {
    user: {
         personal_information: $.personal_information mapObject {
              ($$): $ unless $$ ~= "ssn" otherwise "****"
         },
         login_information: $.login_information mapObject {
            ($$): $ unless $$ ~= "password" otherwise "****"
         }
      }
   })
}

////


== Related Examples

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-output-a-field-when-present.adoc[Output a Field When Present]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

// * link:dw-functions-core[DataWeave Core Functions]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
