= Parse Dates with DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

These DataWeave examples define a function (`fun`) in the DataWeave header to normalize date separators (`/`, `.`, and `-`) within different date formats so that all of them use the same separator (`-`).
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The examples use these functions:

* `replace` so that all dates match a single pattern.
* `mapObject` to run through the the `date` elements. The script applies the normalizing function to each `date`.
* `as` (in the second DataWeave script) to change the data type of the values to a Date type with a specific date format.


== Example: Returns Dates as String Types

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/parse-dates-ex1/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/parse-dates-ex1/inputs/payload.xml[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/parse-dates-ex1/out.xml[]
----

== Example: Returns Dates as Date Types

[[ex02]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/parse-dates-ex2/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/parse-dates-ex2/inputs/payload.xml[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/parse-dates-ex2/out.xml[]
----

////
TODO: NEED TO GET THIS TO WORK BEFORE PUBLISHING!
== Example: Using Conditional Date Parsing

Suppose that you want to include a date field that admits different formats, and want DataWeave to be able to parse each accordingly. For this example, imagine that you want to accept these three formats:

* Sun, 06 Nov 1994 08:49:37 GMT = `E, d LLL u H:m:s O`
* Sun Nov 6 08:49:37 1994 = `cccc, d-LLL-u H:m:s O`
* Sunday, 06-Nov-94 08:49:37 GMT = `E LLL d H:m:s u`

Start out by writing a regular expression to match each of them:

* Sun, 06 Nov 1994 08:49:37 GMT = `/^[A-z][A-z][A-z],/`
* Sun Nov 6 08:49:37 1994 = `/^[A-z][A-z][A-z]\s/`
* Sunday, 06-Nov-94 08:49:37 GMT = This will be the default

You can use these regular expressions in a DW xref:dataweave-types.adoc#functions-and-lambdas[function] that first evaluates a string to see which regular expression it matches, and then converts it through the the corresponding function. This function should do the following:

. Take the input string as argument
. Match it with regular expressions in order to determine which format it's in
. Run the coerce to date function with the corresponding properties
. Return a date time object

=== Transformation Example


.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
var parseDate = (dateStr) -> (
  if (dateStr contains /^[A-z][A-z][A-z],/)
    dateStr as Localdatetime {format: "E, d LLL u H:m:s O"}
  else if (dateStr contains /^[A-z][A-z][A-z]\s/)
      (dateStr as Localdatetime {format: "E LLL d H:m:s u"})
    else dateStr as Localdatetime {format: "cccc, d-LLL-u H:m:s O"})
---
date: parseDate(payload.dateString)
----
////

== See Also

* xref:dataweave-cookbook-add-and-subtract-time.adoc[Add and Subtract Dates]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[Reference Multiple Inputs]

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
