= Work with Multipart Data
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, date, time

The following example iterates over a multipart payload and extracts data from each part.

The example uses the following functions:

* `read` (in the script's header) reads the multipart content from a `multi` variable that sets the boundary to `34b21`.
* `mapObject` iterates over the parts in the multipart data returned by `read` and returns the index and `name` key of each part within a JSON object.

.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/work-with-multipart-data/transform.dwl[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/work-with-multipart-data/out.json[]
----

For additional examples, see xref:dataweave-formats-multipart.adoc#examples[Multipart Format (Form Data)] examples and functions referenced in xref:dw-multipart.adoc[Multipart (dw::module::Multipart)].


== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
