= Example: Pick Top Elements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This example sorts an array of candidates by the score they got in a test, then picks only the ones with the best score, as many as there are open positions to fill.


This example uses the following:

* `map` to go through each of the candidates in the input.
* `orderBy` to order the list of candidates according to their score.
* `[n to n]` to select only a section of the full array of candidates. As the array in ordered in ascending order, the top candidates are at the end of the array, so you must use negative indexes. With the provided input, it selects from -3 to -1, -1 being the last index in the array.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
    TopCandidateList: (payload.candidates map ((candidate) -> {
        firstName: candidate.name,
        rank: candidate.score
    }) orderBy $.rank) [ -payload.availablePositions to -1]
}
----


.Input
[source,json,linenums]
----
{
 "availablePositions": 3,
 "candidates":
    [
      {
        "name":"Gunther Govan",
        "score":99
      },
       {
        "name":"Michael Patrick",
        "score":35
      },
      {
        "name":"Amalia Silva",
        "score":96
      },
       {
        "name":"Tom Mathews",
        "score":40
      },
      {
        "name":"Simon Wilson",
        "score":84
      },
      {
        "name":"Janet Nguyen",
        "score":52
      }
    ]
}
----



.Output
[source,json,linenums]
----
{
  "TopCandidateList": [
    {
      "firstName": "Simon Wilson",
      "rank": 84
    },
    {
      "firstName": "Amalia Silva",
      "rank": 96
    },
    {
      "firstName": "Gunther Govan",
      "rank": 99
    }
  ]
}
----




== Related Examples

* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Outputting self-closing XML tags]

* xref:dataweave-cookbook-remove-certain-xml-attributes.adoc[Remove Certain XML Attributes]


== See Also


// * link:dw-functions-core[DataWeave Core Functions]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]