= Call Java Methods with DataWeave
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

From a DataWeave statement, you can call Java methods from any Java class that's in your Mule project. Note that you can only call Static methods via DataWeave (methods that belong to a Java class, not methods that belong to a specific instance of a class).
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

== Call a Java Method

Before you can call a method, you must first import the class it belongs to into your DataWeave code. You can import Java classes just as you import DataWeave modules by including `java!` into the statement.

For example, below is a simple Java class with a single method that appends a random number at the end of a string. Assume that you created this class as part of a Java package named `org.mycompany.utils` in your Mule project's `src/main/java` folder.

[source,java,linenums]
----
package org.mycompany.utils;

import java.util.Random;

public class MyUtils {

	public static String appendRandom(String base) {
		return base + new Random().nextInt();
	}

}
----

You can call the method `appendRandom()` from DataWeave code, in any of the following ways.

* Import the class and then refer to the method:
+
[source,dataweave,linenums]
----
%dw 2.0
import java!org::mycompany::utils::MyUtils
output application/json
---
{
	a: MyUtils::appendRandom("myString")
}
----

* Import one or more methods instead of the whole class:
+
[source,dataweave,linenums]
----
%dw 2.0
import java!org::mycompany::utils::MyUtils::appendRandom
output application/json
---
{
	a: appendRandom("myString")
}
----

* If the method is a static method, import and call it in a single line:
+
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
	a: java!org::mycompany::utils::MyUtils::appendRandom(vars.myString)
}
----

All three methods return the variable value with a random string appended:

[source,json,linenums]
----
{
  "a":"myString969858409"
}
----

== Instantiate a Java Class

Through DataWeave code, you can instantiate a new object of any class. Note
that after creating an instance, you can't call its instance methods through
DataWeave. However, you can reference its variables.

This simple Java class has a method and a variable.

[source,java,linenums]
----
package org.mycompany.utils;
public class MyClass {

	private String foo;
	 public MyClass(String foo) {
		 this.foo = foo;
	}

	 public String getFoo() {
		return foo;
	}

}
----

To create the `MyClass` example in a Studio project:

. Create a project for the class in Studio by clicking *New* -> *Mule Project*
and providing a name, such as *my-app*, and clicking *Finish*.
. From *my-app*, create the `org.mycompany.utils` package by right-clicking
*src/main/java* from Studio's *Package Explorer*, selecting *New* -> *Package*,
and naming the package `org.mycompany.utils`.
. Create the `MyClass` class in the your new `org.mycompany.utils` package by right-clicking
*org.mycompany.utils*, selecting *New* -> *Class*, naming that class `MyClass`, and clicking
*Finish*.
. In the *MyClass.java* tab that opens in Studio, copy, paste, and save the
contents of `MyClass`.

The following DataWeave example imports `MyClass`, creates a new instance of
the class, and calls its instance variable `foo`. (Note that it is not possible
for DataWeave to call the object's private `getFoo()` method.)

[source,dataweave,linenums]
----
%dw 2.0
import java!org.mycompany.utils::MyClass
output application/json
---
{
	a: MyClass::new("myString").foo
}
----

To add this DataWeave example to your Studio project:

. Returning to `my-app.xml` in *src/main/mule*, drag a Transform Message
component into the project's canvas, and click to open it.
. In the component's *Transform Message* tab, replace the entire script
in the source code area (on the right) with the DataWeave script (above).
. Save your changes and click *Preview* (located farthest right on the tab) to view the following
output:
+
[source,json,linenums]
----
{
  "a":"myString"
}
----

Note that the XML for the Transform Message configuration in the Mule flow
looks something like this:

[source,xml,linenums]
----
<flow name="my-appFlow" >
	<ee:transform doc:name="Transform Message" >
		<ee:message >
			<ee:set-payload ><![CDATA[%dw 2.0
import java!org::mycompany::utils::MyClass
output application/json
---
{
a: MyClass::new("myString").foo
}]]></ee:set-payload>
		</ee:message>
	</ee:transform>
</flow>
----

== See Also

* xref:dataweave-formats.adoc[DataWeave Output Formats and Writer Properties]
