= Merge Multiple Payloads
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, filter, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, contains, as

This DataWeave example deals with an input that contains a collection of payloads. The first payload lists price by book, the second lists authors by book, where each book can be identified by a unique `bookId` key. This transformation merges both payloads into one, matching their keys, where one book may have several authors.


[NOTE]
Note that this is not the same as having as an input a single payload that consists of an array. Here, there are multiple separate payload elements within one single Mule Event object. This kind of data structure can be produced, for example, by a scatter-gather component.

It uses these functions:

* `map` goes through the elements of the first payload (`payload[0]`). While on each element, a second `map` function goes through the elements of the second payload (`payload[1]`) that match the filter criteria.
* `using` defines a shorter alias within the scope of the main `map` function.
* `filter` limits the scope of the second `map` function to only objects that share the same `bookId` as is currently being processed by the first `map` function. In that way, only relevant authors for each are listed in the output.



.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---

payload[0]  map (bookListing) -> using (id = bookListing.bookId) {
	bookId:	id,
    title:  bookListing.title,
	price: 	bookListing.price as Number,
	(payload[1] filter ($.*bookId contains id)  map (bookAuthor) -> {
		author:bookAuthor.author
   })
}
----

////
This is not the same as the original example. Like that it's not too different from the "group by" example, except that it does things in a less efficient way.

The whole point of this example is that the input is in separate objects.


.Input
[source,json,linenums]
----
{
  "Book Price by ID" : [
    {
      "bookId": 101,
      "title": "Some Book",
      "price" : 7.15
    },
    {
      "bookId": 102,
      "title": "Another Book",
      "price" : 40.75
    }],
  "Book Author by ID"  : [
    {
      "bookId": 101,
      "author"  : "Some Body"
    },
    {
      "bookId": 102,
      "author"  : "Some Body Else"
    }]
}
----
////

.Input 1 for Collection - Payload[0]
[source,json,linenums]
----
[
  { "bookId":"101",
    "title":"world history",
    "price":"19.99"
  },
  {
    "bookId":"202",
    "title":"the great outdoors",
    "price":"15.99"
  }
]
----

.Input 2 for Collection - Payload[1]
[source,json,linenums]
----
[
  {
    "bookId":"101",
    "author":"john doe"
  },
  {
    "bookId":"202",
    "author":"jane doe"
  }
]
----




.Output
[source,json,linenums]
----
[
  {
    "bookId": "101",
    "title": "world history",
    "year": "2017",
    "isbn": "11111",
    "price": "19.99",
    "author": "john doe"
  },
  {
    "bookId": "202",
    "title": "the great outdoors",
    "year": "2016",
    "isbn": "22222",
    "price": "15.99",
    "author": "jane doe"
  }
]
----





////
.Output
[source,json,linenums]
----
[
  {
    "bookId": 101,
    "title": "Some Book",
    "price": 7.15,
    "author": "Some Body"
  },
  {
    "bookId": 102,
    "title": "Another Book",
    "price": 40.75,
    "author": "Some Body Else"
  }
]
----
////
////
Note that the *sample data* section of the Transform component does not allow you to provide it a collection of multiple payloads as a sample. The only way to test this example is running it.
////

== Related Examples

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[Reference Multiple Inputs]

* xref:dataweave-cookbook-zip-arrays-together.adoc[Zip Arrays Together]

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]
* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
