= Change the Value of a Field
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, rename, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, update

This DataWeave example changes the values of some XML elements. Here, it changes
the values of keys containing sensitive data to a set of asterisks (`\****`).
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The example uses:

* `update` to update specified fields of the payload with new values
* single-value (`.`) and multi-value (`.*`) selectors to navigate the payload and select the fields to update

The following script shows how the `update` operator works. The example creates a new `users` list by updating each `user` in the payload with a new `user`. The `ssn` and `password` values within each `user` become `\****`.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
payload update {
        case user at .users.*user -> user update {
                case .personal_information.ssn -> "****"
                case .login_information.password -> "****"
        }
}
----

.Input XML
[source,xml,linenums]
----
<users>
    <user>
        <personal_information>
            <first_name>Emiliano</first_name>
            <middle_name>Romoaldo</middle_name>
            <last_name>Lesende</last_name>
            <ssn>001-08-84382</ssn>
        </personal_information>
        <login_information>
            <username>3miliano</username>
            <password>mypassword1234</password>
        </login_information>
    </user>
    <user>
        <personal_information>
            <first_name>Mariano</first_name>
            <middle_name>Toribio</middle_name>
            <last_name>de Achaval</last_name>
            <ssn>002-05-34738</ssn>
        </personal_information>
        <login_information>
            <username>machaval</username>
            <password>mypassword4321</password>
        </login_information>
    </user>
</users>
----

.Output XML
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<users>
  <user>
    <personal_information>
      <first_name>Emiliano</first_name>
      <middle_name>Romoaldo</middle_name>
      <last_name>Lesende</last_name>
      <ssn>****</ssn>
    </personal_information>
    <login_information>
      <username>3miliano</username>
      <password>****</password>
    </login_information>
  </user>
  <user>
    <personal_information>
      <first_name>Mariano</first_name>
      <middle_name>Toribio</middle_name>
      <last_name>de Achaval</last_name>
      <ssn>****</ssn>
    </personal_information>
    <login_information>
      <username>machaval</username>
      <password>****</password>
    </login_information>
  </user>
</users>
----

The `update` operator provides a general way to change the value of a field. However, note that DataWeave provides a simpler way to mask values, without specifying the path to each sensitive field:

* `mask` updates all simple elements that match the selected name throughout the input with the desired mask.

The following example updates the input payload with the specified mask values:

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/xml
---
(payload mask "ssn" with "****") mask "password" with "****"
----


== Related Examples

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-output-a-field-when-present.adoc[Output a Field When Present]

* xref:dataweave-cookbook-insert-attribute.adoc[Insert an Attribute into an XML Tag]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
