= Pass Functions as Arguments
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example defines a base function in the header that receives two arguments: a function and an element to apply it on. The base function the applies the received function onto the keys of the received element and also to every one of its child elements recursively. In this case, the function sent sets all keys to lower case.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The example uses the following:

* A custom function that is applied recursively, ie: it calls itself for each child in the element it receives originally.
* `mapObject` to sort through each child of the element.
* `lower` from the Strings library to make every Key in the input lower case.
* `is` to check if the passed element is of type `Object` (and therefore has children).
* `if` and `else` to only have the function call itself when a condition is met, and to otherwise end the recursive loop for that branch.


[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/pass-functions-as-arguments/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/pass-functions-as-arguments/inputs/payload.xml[]
----

.Output XML:
[source,xml,linenums]
----
include::partial$cookbook-dw/pass-functions-as-arguments/out.xml[]
----


== Related Examples

* xref:dataweave-cookbook-define-a-custom-addition-function.adoc[Define a Custom Addition Function]

* xref:dataweave-cookbook-map-based-on-an-external-definition.adoc[Dynamically Map Based On a Definition]

* xref:dataweave-cookbook-define-function-to-flatten-list.adoc[Define a Function that Flattens Data in a List]

* xref:dataweave-cookbook-conditional-list-reduction-via-function.adoc[Conditionally Reduce a List through a Function]


== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
