= Insert Attributes to an XML Tag
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example uses `@(key:value)` syntax (for example, `@(loc: "US")`) to inject attributes to XML tags. The example populates the "title" tag with two attributes, and each of the "author" tags with one too.

It uses these functions:

* `mapObject` to go through each of the books in the input.
* `map` to go through the authors in each book.

.DataWeave
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
bookstore: payload.bookstore mapObject (book) -> {
      book : {
      title @(lang: "en", year: book.year): book.title,
      price: book.price,
      (book.*author map
      author @(loc: "US"): $)
    }
}
----


.Input
[source,xml,linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<bookstore>
  <book>
    <title>Everyday Italian</title>
    <year>2005</year>
    <price>30</price>
    <author>Giada De Laurentiis</author>
  </book>
  <book>
    <title>Harry Potter</title>
    <year>2005</year>
    <price>29.99</price>
    <author>J K. Rowling</author>
  </book>
  <book>
    <title>XQuery Kick Start</title>
    <year>2003</year>
    <price>49.99</price>
    <author>James McGovern</author>
    <author>Per Bothner</author>
    <author>Kurt Cagle</author>
    <author>James Linn</author>
    <author>Vaidyanathan Nagarajan</author>
  </book>
  <book>
    <title>Learning XML</title>
    <year>2003</year>
    <price>39.95</price>
    <author>Erik T. Ray</author>
  </book>
</bookstore>
----



.Output XML
[source,xml,linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<bookstore>
  <book>
    <title lang="en" year="2005">Everyday Italian</title>
    <price>30</price>
    <author loc="US">Giada De Laurentiis</author>
  </book>
  <book>
    <title lang="en" year="2005">Harry Potter</title>
    <price>29.99</price>
    <author loc="US">J K. Rowling</author>
  </book>
  <book>
    <title lang="en" year="2003">XQuery Kick Start</title>
    <price>49.99</price>
    <author loc="US">James McGovern</author>
    <author loc="US">Per Bothner</author>
    <author loc="US">Kurt Cagle</author>
    <author loc="US">James Linn</author>
    <author loc="US">Vaidyanathan Nagarajan</author>
  </book>
  <book>
    <title lang="en" year="2003">Learning XML</title>
    <price>39.95</price>
    <author loc="US">Erik T. Ray</author>
  </book>
</bookstore>
----




== Related Examples

* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Output Self-closing XML tags]

* xref:dataweave-cookbook-remove-certain-xml-attributes.adoc[Remove Specified XML Attributes]

* xref:dataweave-cookbook-include-xml-namespaces.adoc[Include XML Namespaces]

== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
