= Set Reader and Writer Configuration Properties
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, dataweave, data weave, output structure, mime type, mime

DataWeave provides configuration properties for data formats, such as JSON (`application/json`) and XML (`application/xml`). The properties change the behavior of DataWeave readers and writers for those formats. For example, the default separator for a CSV reader is a comma (`,`). You can use the format's `separator` property to identify a different separator for CSV content.

//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

== Use a Writer Property in an Output Directive

The following example shows how to append writer properties to the DataWeave `output` directive.

DataWeave scripts

The following examples set the `output` directive in this manner:

* xref:dataweave-formats-avro.adoc#examples[Avro example] that uses `schemaUrl`
* xref:dataweave-formats-excel.adoc#example2[Excel (XLSX) example] that uses `header=true`.
* xref:dataweave-formats-flatfile#examples[Flat File] example that uses `schemaPath`
*

== Use a Reader Property in a File Read Operation

TODO

.More Examples:

* https://docs.mulesoft.com/mule-runtime/4.3/dataweave-formats-csv#example2 CSV example that uses streaming=true; header=true
* xref:dataweave-formats-json.adoc#example3[JSON example} that uses `streaming=true`


.More Examples:

* xref:dataweave-formats-json.adoc#example3[JSON Example]
*


== Use Reader and Writer Properties in DataWeave Functions

TODO

The DataWeave


== Use a Mule Variable as a Configuration Value

The following Mule flow transforms comma-separated CSV data into pipe-separated (`|`) CSV data. Instead of setting a literal value in the script, the example selects the pipe value from a xref:about-mule-variables.adoc[Mule variable], which is part of a Mule event that travels through data-processing components in the flow.

The Scheduler component (`<scheduler/>`) generates a Mule event each time it triggers the flow.

The Set Variable component (`<set-variable/>`) in the example creates a Mule variable named `delimiter` with the value `'|'`. In Studio, the value is created as an *fx* expression (`value="#['|']"`), rather than a simple string (`value="'|'"`).

The Transform Message component (`<ee:transform-message/>`) contains a DataWeave script
that reads comma-separated CSV input and uses the Mule variable to write pipe-separated CSV output.

The Logger component (`<logger/>`), which is set to `payload`, writes the pipe-separated output as INFO in its `LoggerMessageProcessor` message: `macaroni | rigatoni | ravioli | spaghetti`.

//STUDIO FLOW: ONLY PARTIALLY AUTOMATED
.Mule Flow:
[source,xml,linenums]
----
<flow name="docs-9783-dwvars-dukeFlow" >
  <scheduler doc:name="Scheduler" >
    <scheduling-strategy >
      <fixed-frequency frequency="45" timeUnit="SECONDS"/>
    </scheduling-strategy>
  </scheduler>
  <set-variable value="#['|']" doc:name="Set Variable" variableName="delimiter" />
  <ee:transform doc:name="Transform Message" >
    <ee:message>
      <ee:set-payload><![CDATA[%dw 2.0
var myVar = read("macaroni , rigatoni , ravioli , spaghetti", "application/csv" , {"header":false, separator:','})
output application/csv with binary
---
write(myVar, "application/csv", {"header":false, "separator":vars.delimiter})]]></ee:set-payload>
    </ee:message>
  </ee:transform>
  <logger level="INFO" doc:name="Logger" message="#[payload]"/>
</flow>
----

To provide comma-separated input for the example, the script in the Transform Message component uses a xref:dw-core-functions-read.adoc[read] function as a value to a DataWeave variable, `myVar`:

`var myVar = read("macaroni , rigatoni , ravioli , spaghetti", "application/csv" , {"header":false, separator:','})`

To write pipe-separated the output, the DataWeave xref:dw-core-functions-write.adoc[write] function in the body of the script changes the comma-separated input to pipe-separated output. To select the pipe value from the Mule variable (`delimiter`), the function passes the writer property configuration `"separator":vars.delimiter` as an argument:

`var myVar = write(myVar, "application/csv", {"header":false, "separator":vars.delimiter})`

The script uses the following DataWeave `output` directive in the script's header: `output application/csv with binary`.

The `output` directive uses `application/csv` as the MIME type to return the data in the CSV format. The directive appends `with binary` to send the binary output from the `write` function to the binary writer. _Without_ `with binary`, DataWeave would attempt to use the CSV writer and produce the following issue: `CSV Structure should be and Array<Object> or Object but got String, while writing CSV.`

Note that if you want to see pipe-separated content from the Tranform Message component's *Preview* screen in the Studio UI, you must create sample data for it:

. Double-click the Transform Message component from the *Message Flow* area of the Studio app.
. Right-click *delimiter: _String_* in the *Context* tab, which is located on the bottom left of the configuration UI for the component.
. Select *Edit Sample Data* to open a *vars-delimiter* tab.
. Replace any content in the *vars-delimiter* with the following sample data for the `delimiter` value: `"|"`. You must put the delimiter in quotation marks.

For further guidance with sample data, see xref:stransform-preview-transformation-output-studio-task.adoc[Previewing the Output of a Transformation].

== See Also

* xref:dataweave-formats.adoc[DataWeave Formats]
* xref:about-components.adoc[Core Components]
* xref:dataweave-cookbook.adoc[DataWeave Cookbook]


////
Missing Examples:
* https://docs.mulesoft.com/mule-runtime/4.3/dataweave-formats-binary
* https://docs.mulesoft.com/mule-runtime/4.3/dataweave-formats-copybook
* https://docs.mulesoft.com/mule-runtime/4.3/dataweave-formats-dw
* xref:dataweave-formats-csv.adoc#examples[CSV Examples]
* xref:dataweave-formats-excel.adoc#examples[Excel (XLSX) Examples]
////
