= Format Dates and Times
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping, date, time
// :page-aliases: 4.3@mule-runtime::dataweave-cookbook-format-dates.adoc

You can use DataWeave to change the format of date and time input.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

[[ex01]]
== Change Date and Time Formats

You can combine formatting characters, such as `MM` and `dd`, to write supported date and time formats. The example uses the `as` operator to write the dates and times as a string.

.Transform
[source,dataweave,linenums]
----
include::partial$cookbook-dw/format-dates-ex01/transform.dwl[]
----

.Output
[source,json,linenums]
----
include::partial$cookbook-dw/format-dates-ex01/out.json[]
----

[[ex02]]
== Create a Custom Date Format as a DataWeave Type

For multiple, similar conversions in your script, you can define a custom type as a directive in the header and set each date to that type. Names of DataWeave type are case-sensitive.

.DataWeave Script
[source,dataweave,linenums]
----
include::partial$cookbook-dw/format-dates-ex02/transform.dwl[]
----

.Output
[source,json,linenums]
----
include::partial$cookbook-dw/format-dates-ex02/out.json[]
----

[[ex03]]
== Use Date and Time Formatting Characters

DataWeave supports the use of formatting characters, such as the `u` (for the year), `M`, and `d` in the date format `uuuu-MM-dd`. These characters are based on the Java 8 `java.time.format` package.

The following example formats the output of the `now` DataWeave function to show
supported letters:

.DataWeave Script
[source,dataweave,linenums]
----
include::partial$cookbook-dw/format-dates-ex03/transform.dwl[]
----

Notice the use of the syntax to format the date or time.

.Output
----
include::partial$cookbook-dw/format-dates-ex03/out.json[]
----

== Related Examples

* xref:dataweave-cookbook-parse-dates.adoc[Parse Dates with DataWeave]

* xref:dataweave-cookbook-add-and-subtract-time.adoc[Add and Subtract Time]

* xref:dataweave-cookbook-change-time-zone.adoc[Change a Time Zone]

== See Also

* xref:dataweave-types.adoc#dw_type_dates[Date and Time (dw::Core Types)]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
