= Extract Data
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, metadata, dataweave, data weave, datawave, datamapper, dwl, dfl, dw, payload, attribute, variable, flow, error, message

DataWeave can select data from objects, arrays, and variables that store them,
both
xref:dataweave-variables-context.adoc[predefined Mule Runtime variables]
and in xref:dataweave-variables.adoc[DataWeave variables]. You can use selectors
in Mule modules, connectors, and components that accept DataWeave expressions.

[NOTE]
In Design Center, be sure to set the field in which you are using DataWeave
selectors to accept functions (`fx`).

== Using Selectors on Arrays and Objects

When referencing an array or object, you can use selector expressions to extract
specific values from within a data structure.

Note that Studio and Design Center require DataWeave expressions to reside
between square brackets that are preceded by a hash (or pound) symbol,
for example:

```
#[input_data.input_key]
```

[cols="1,5", options="header"]
|===
| Data to extract | Examples

| *Single value* (`.`)
a|`.` selector acts on arrays and objects.

* Selecting a `name` value from an object:
+
```
{ "id" : "1234", "name" : "me" }.name
```
+
Returns `"somebody"`.
+
* Selecting a `name` value from an array:
+
```
[ { "id" : "1234", "name" : "me" } ].name
```
+
```
[ { "id" : "1234" }, { "name" : "me" } ].name
```
+
Each example returns `[ "me" ]`.
+
* Selecting the first `name` value:
+
```
{ user : "a", "user" : "b" }.user
```
+
Only returns the first `name` value, `"a"`.

| *Multiple values*  (`*`)
a|
`*` selector acts on arrays and objects.

* Selecting all `user` values from an array:
+
```
[ { "user" : "a", "user" : "b" } ].*user
```
+
Returns `["a", "b"]`.

* Selecting all `user` values from an object:
+
```
{ user : "a", "user" : "b" }.*user
```
+
Returns: `["a", "b"]`

* Selecting all `user` values from the `users` key:
+
```
{ "users" : [ { "user" : "a" }, { "user" : "b" } ] }.users.*user`
```
+
Returns: `[ "a", "b" ]`

| *Descendants* (`..`)
a|
`..` selector acts on arrays and objects.

* Selecting descendants of `c` key:
+
```
{ "user" : [{ "a" : "b"}, {"c" : [ {"aa" : "bb"}, { "cc": "dd" } ] } ] , "user" : "d" }..c
```
+
Returns `[ [ { "aa": "bb" }, { "cc": "dd" } ] ]`.

| *Index* (`[]`)
a|
`[]` selector acts on indices of an array.

* Selecting an index from an array:
** `[1,2,3,4][0]` returns `[1]`
+
The index of the first element in an array is always `0`.
+
** `[1,2,3,4][4]` returns `[3]`
|===

== Using Selectors on Content Stored in Variables

All of the selectors work with the built-in Mule runtime variables, such as
`payload` and `attributes`, and with DataWeave variables, such as
`var myVar = { "id" : "1234", "name" : "somebody" }`, for example:

* `myVar.name` to return `"somebody"`

You can select xref:about-mule-event.adoc[Mule event] data by using
Mule Runtime variables.

Extracted values are handled as a literal values (as opposed to
variables, for example) of one of the supported DataWeave value types.

[cols="1,4", options="header"]
|===
| Data to extract | Syntax

| *Payload*
| `#[payload]` or `payload`

| *Attribute*
| `#[attributes.<myAttributeName>]` or
  `attributes.<myAttributeName>`

a| *Variable*
   To avoid name collisions, you can prepend `variables`, as shown.
a| `#[<myVariableName>]` or
   `#[variables.<myVariableName>]`

Within *fx* fields: `<myVariableName>` or `variables.<myVariableName>`

a| *Error object*
+
For information on errors in the flow, you can use `#[error.cause]`.
| `#[error]` or `error` within fx fields

| *Flow*
a| `\#[flow]`

For the flow name in the Logger: `#[flow.name]`

Note that `flow.name` does not work in some Core components, such as Set Payload and Transform Message.
| `flow`
|===

[NOTE]
In Design Center, be sure to set the field in which you are using DataWeave selectors to accept functions (`fx`).

== Related Examples

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-perform-basic-transformation.adoc[Transform XML to JSON]

* xref:dataweave-cookbook-reference-multiple-inputs.adoc[Reference Multiple Inputs]

* xref:dataweave-cookbook-merge-multiple-payloads.adoc[Merge Multiple Payloads]

== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
