= Transform XML to JSON
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure

This simple DataWeave example changes the XML input to JSON output by using selector expressions without any functions. It also changes the order and names of some of the fields. Note that more complex transformations usually require the use of the `map` or `mapObject` function.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

The DataWeave script maps the names (or keys) for the output fields to values of the input fields. The input fields are specified with selector expressions.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/transform.dwl[]
----

.Input XML Payload:
[source,xml,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/inputs/payload.xml[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/perform-basic-transformation/out.json[]
----

== Related Examples

* xref:dataweave-cookbook-extract-data.adoc[Extract Data]

* xref:dataweave-cookbook-map.adoc[Map Data with DataWeave]

* xref:dataweave-cookbook-rename-keys.adoc[Rename Keys]



== See Also

* xref:dataweave-types.adoc[DataWeave Types]

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
