= Pick Top Elements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This DataWeave example sorts an array of candidates by the score they got in a test, then picks only the ones with the best score, as many as there are open positions to fill.
//LINK TO DW 1.0 EXAMPLES:
include::partial$dataweave1-links.adoc[tag=dataweave1Examples]

This example uses the following:

* `map` to go through each of the candidates in the input.
* `orderBy` to order the list of candidates according to their score.
* `[n to n]` to select only a section of the full array of candidates. As the array in ordered in ascending order, the top candidates are at the end of the array, so you must use negative indexes. With the provided input, it selects from -3 to -1, -1 being the last index in the array.

[[ex01]]
.DataWeave Script:
[source,dataweave,linenums]
----
include::partial$cookbook-dw/pick-top-elements/transform.dwl[]
----

.Input JSON Payload:
[source,json,linenums]
----
include::partial$cookbook-dw/pick-top-elements/inputs/payload.json[]
----

.Output JSON:
[source,json,linenums]
----
include::partial$cookbook-dw/pick-top-elements/out.json[]
----




== Related Examples

* xref:dataweave-cookbook-output-self-closing-xml-tags.adoc[Output Self-closing XML tags]

* xref:dataweave-cookbook-remove-certain-xml-attributes.adoc[Remove Specified XML Attributes]


== See Also

* xref:dataweave-selectors.adoc[DataWeave Selectors]

* xref:dataweave-cookbook.adoc[DataWeave Cookbook]
