
= URL Encoded Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, urlencoded, application/x-www-form-urlencoded, application/x-www-form-urlencoded

MIME type: `application/x-www-form-urlencoded`

ID: `urlencoded`

URL encoded data represents a collection of key-value pairs. DataWeave represents these values as an object in which each value is a string.

[[examples]]
== Examples

The following examples show uses of the URL Encoded format:

* <<example1>>
* <<example2>>
* <<example3>>
* <<example4>>

[[example1]]
=== Example: Represent URL Encoded Data in the DataWeave (dw) Format

This example shows how DataWeave represents simple URL encoded data.

==== Input

The URL encoded data serves as input payload to the DataWeave source.

[source,form-urlencoded,linenums]
----
name=Mariano&lastName=de+Achaval
----

==== Source

The DataWeave script transforms the URL encoded input payload to the DataWeave (dw) format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
payload
----

==== Output

The output is a DataWeave object that contains a collection of key-value pairs from the input.

[source,dataweave,linenums]
----
{
    "name": "Mariano",
    "lastName": "de Achaval"
}
----

[[example2]]
=== Example: Generate URL Encoded Data from a JSON Object

This example shows how to generate URL Encoded data.

==== Input

The JSON object serves as the input payload to the DataWeave source.

[source,json,linenums]
----
{
  "name": "Mariano"
}
----

==== Source

The DataWeave script selects the value of the `name` key in the input payload
and transforms all values of the object in the body of the script to the
`urlencoded` format.

[source,dataweave,linenums]
----
%dw 2.0
output urlencoded
---
{
    name: payload.name,
    age: 37
}
----

==== Output

The output is URL encoded data that is constructed from the key-value pairs
in the body of the DataWeave script.

[source,form-urlencoded,linenums]
----
name=Mariano&age=37
----

//NOT NEW
[[example3]]
=== Example: Generate URL Encoded Data from a Collection of Key-Value Pairs

This DataWeave script produces the URL encoded output.

==== Source

The DataWeave script transforms the format of the JSON input found within the body of the script into the URL Encoded format.

[source,dataweave,linenums]
----
%dw 2.0
output application/x-www-form-urlencoded
---
{
  "key" : "value",
  "key 1": "@here",
  "key" : "other value",
  "key 2%": null
}
----

==== Output

The output shows the input data in the URL Encoded format.

[source,text,linenums]
----
key=value&key+1=%40here&key=other+value&key+2%25
----

//NOT NEW
[[example4]]
=== Example: Transform URL Encoded Data to the Text Plain Format

This example transforms URL Encoded input into the Text Plain format and MIME type.

==== Source

The DataWeave script reads the URL Encoded data and concatenates values of the selected keys.

[source,dataweave,linenums]
----
%dw 2.0
var myData  read('key=value&key+1=%40here&key=other+value&key+2%25', 'application/x-www-form-urlencoded')
output text/plain
---
myData.*key[0] ++ myData.'key 1'
----

==== Output

The output is in Text Plain format.

[source,text,linenums]
----
value@here
----


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the URL Encoded format.


[[reader_properties]]
=== Reader Properties

There are no reader properties for URL Encoded data.

 
[[writer_properties]]
=== Writer Properties

The URL Encoded format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|The size of the buffer writer
|`deferred`  |`Boolean`|`false`|Indicates if the output should be deferred. Valid Options: `true` or `false`
|`encoding`  |`String`|`null`|The charset name to be used by this writer to encode the strings.
|===


[[mime_types]]
== Supported MIME Types

The URL Encoded format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/x-www-form-urlencoded`
|===
