
= YAML Format
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: format, yaml, application/yaml, text/yaml, application/x-yaml, text/x-yaml, application/yaml

MIME type: `application/yaml`

ID: `yaml`

Values in the YAML data format map one-to-one with DataWeave values.
DataWeave natively supports all of the following YAML types:

* `String`
* `Boolean`
* `Number`
* `Nil`
* `DataMapping`
* `Sequences`

[[examples_yaml]]
== Example: Represent YAML in the DataWeave Format (dw)

This example shows how DataWeave represents YAML values.

=== Input

The following YAML snippet serves as the input payload for the DataWeave source
in this example.

[source,yaml,linenums]
----
american:
  - Boston Red Sox
  - Detroit Tigers
  - New York Yankees
national:
  - New York Mets
  - Chicago Cubs
  - Atlanta Braves
----

=== Source

The DataWeave script transforms the YAML encoded input payload to the DataWeave (dw) format and MIME type.

[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
payload
----

=== Output

The following output shows how the YAML input is represented in the DataWeave (`dw`) format.

[source,dataweave,linenums]
----
{
  "american": [
    "Boston Red Sox",
    "Detroit Tigers",
    "New York Yankees"
  ],
  "national": [
    "New York Mets",
    "Chicago Cubs",
    "Atlanta Braves"
  ]
}
----


[[properties]]
== Configuration Properties

DataWeave supports the following configuration properties for the YAML format.


[[reader_properties]]
=== Reader Properties

The YAML format accepts properties that provide instructions for reading input data.


[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`maxEntityCount`  |`Number`|`1`|The maximum number of entity expansions. The limit is in place to avoid Billion Laughs attacks.
|===

[[writer_properties]]
=== Writer Properties

The YAML format accepts properties that provide instructions for writing output data.

[cols="1,1,1,3a", options="header"]
|===
|Parameter |Type |Default|Description
|`bufferSize`  |`Number`|`8192`|The size of the buffer writer
|`deferred`  |`Boolean`|`false`|Indicates if the output should be deferred. Valid Options: `true` or `false`
|`encoding`  |`String`|`'UTF-8'`|The charset name to be used by this writer to encode the strings.
|`skipNullOn`  |`String`|`null`|Indicates where is should skips null values if any or not. By default it doesn't skip. Valid Options: `arrays` or `objects` or `everywhere`
|`writeDeclaration`  |`Boolean`|`true`|Indicates whether to write the header declaration or not. Valid Options: `true` or `false`
|===


[[mime_types]]
== Supported MIME Types

The YAML format supports the following MIME types.

[cols="1", options="header"]
|===
| MIME Type
|`application/yaml`
|`text/yaml`
|`application/x-yaml`
|`text/x-yaml`
|===
