= Debugging Outside Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: debugging, debug

////
In Anypoint Studio, you can use the xref:7@studio::visual-debugger-concept.adoc[Studio Visual Debugger]
 to help you troubleshoot your app. If you're creating your Mule app outside Studio, you can resort to the following options:
////

In Anypoint Studio, you can use the Studio Visual Debugger to help you troubleshoot your app. If you're creating your Mule app outside Studio, you can debug it when running from Eclipse or when running Mule standalone.

== Debugging an app when Running From Eclipse

Select the *Debug As > Mule Server* start-up mode from your configuration file. Any breakpoint you set in your custom code or Mule's source code  suspends the execution and takes you to Eclipse's Debug perspective.

== Debugging an app when Running Mule Standalone

You can start Mule with the *-debug* option to activate remote debugging, as shown in this Linux example:

----
$MULE_HOME/bin/mule -debug
----

With this option, Mule starts normally and displays the following message in the console:

----
Listening for transport dt_socket at address: 5005
----

Mule is now remotely debuggable on port 5005. To use another port or configure the JVM to wait until a remote debugger gets attached, follow these steps:

. In the Mule start-up script that is relevant for your operating system, change the parameters found in the JPDA_OPTS property.

. Switch to Eclipse, and select *Run > Debug Configurations*.

. Create a *Remote Java Application* configuration that uses port 5005.

. To step debug with the source code attached, add the source code of your Mule local instance as an external archive on the second tab of the configuration panel.

. Click the *Debug* button at the lower right corner of the configuration screen.
+
The local Mule instance resumes its start-up sequence. You can step debug when the start-up sequence completes.
