= Debugging Outside Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: debugging, debug


To troubleshoot a Mule app in Anypoint Studio, you can use the xref:latest@studio::visual-debugger-concept.adoc[Studio Visual Debugger]. This lets you set breakpoints to stop execution and check events.

If you're creating your Mule app outside of Studio, you can either use MUnit to test your app, or you can activate remote debugging.

== Use MUnit to Test an App

MUnit is a Mule application testing framework that allows you to build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

For more information, see the MUnit documentation on https://docs.mulesoft.com.

== Activate Remote Debugging

You can start Mule with the *-debug* option to activate remote debugging, as shown in this Linux example:

----
$MULE_HOME/bin/mule -debug
----

With this option, Mule starts normally and logs the following message in the console:

----
Listening for transport dt_socket at address: 5005
----

Mule is now remotely debuggable on port 5005. If you want to use another port or configure the JVM to wait until a remote debugger gets attached, follow these steps:

. In the Mule start-up script that is relevant for your operating system, change the parameters found in the JPDA_OPTS property.

. Switch to Eclipse, and select the the *Run > Debug Configurations* menu. From there, create a *Remote Java Application* configuration that uses port 5005.

. Add the source code of your Mule local instance as an external archive on the second tab of the configuration panel.

. Click the *Debug* button at the lower right corner of the configuration screen. The local Mule instance  resumes its start-up sequence and you can debug the app step-by-step.
