= Dependency Injection
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: dependency injection, esb, deploy

This guide helps you use https://en.wikipedia.org/wiki/Dependency_injection[dependency injection]. For registry information, see xref:unifying-the-mule-registry.adoc[Unifying the Mule Registry].

*Notes*:

* MuleSoft supports Dependency Injection as defined in https://jcp.org/en/jsr/detail?id=330[JSR-330]
* You can inject objects either by using the @Inject annotation or with http://www.tutorialspoint.com/spring/spring_bean_definition.htm[Spring Beans]
* You can inject objects that might not be in the registry, but the values to be injected are in the registry
* By default Mule has only one registry (starting with 3.7), but if you add more registries, you cannot do cross-registry injections

== Using Dependency Injection

To use dependency injection to wire objects in the registry together, you can inject dependencies into objects that are not necessarily registered. For example, suppose you are building a custom component which uses the  http://en.wikipedia.org/wiki/Command_pattern[command design pattern], and suppose that you have a command that requires the MuleContext, the ObjectStoreManager, and the QueueManager while also carrying a custom state which prevents you from making that instance reusable (as it’s often the case with the command pattern).

The command object looks like this:

[source,java,linenums]
----
public class MyCommand implements Command {
    @Inject
    private MuleContext muleContext;

    @Inject
    private ObjectStoreManager objectStoreManager;

    @Inject
    private QueueManager queueManager;

    private String userId;
    private String moreNotReusableStuff;

    public void execute() {
      // Magic happens here
    }
}
----

You can view https://gist.github.com/marianogonzalez/cf7c7c78e9aee0ba2bc6#file-gistfile1-java[gistfile1.java] in https://github.com/[GitHub].

You only need one instance of each of those commands per MuleEvent your component receives.

Register the instance of dependency injection as follows:

[source,java,linenums]
----
Command command = muleContext.getInjector().inject(new MyCommand());
----

You can view  https://gist.github.com/marianogonzalez/da1f8207d9e193a6057e#file-gistfile1-java[gistfile1.java] in https://github.com/[GitHub]

Starting with 3.7, there is a new API in Mule called `Injector` which is capable of injecting dependencies into a JSR-330 annotated object. Injected instances do not go into the registry because of it.

== See Also

* http://blogs.mulesoft.com/dev/mule-dev/sneak-peek-mule-3-7-deepest-internals/[A sneak peek into Mule 3.7’s deepest internals]
* http://blogs.mulesoft.com/mule-3-6-library-upgrades/[Library upgrades in Mule ESB 3.6]
* http://blogs.mulesoft.com/dev/mule-dev/mule-3-6-xml-xpath-xslt-xquery3/[You’re into XML? Mule now supports XPath, XSLT and XQuery 3.0]
* http://blogs.mulesoft.com/dev/api-dev/mule-how-to-batch-enabled-cloud-connector/[Mule How-to: Build a Batch Enabled Cloud Connector]