= Deploy Applications to CloudHub
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can deploy applications to CloudHub using any of the following tools:

* Anypoint Studio +
See xref:studio::deploy-mule-application-task.adoc[Deploy a Mule Application to CloudHub] for instructions.
* Anypoint CLI +
See the xref:runtime-manager::anypoint-platform-cli-commands.adoc#deploy-to-cloudhub[runtime-mgr cloudhub-application deploy] command documentation for instructions.
* Mule Maven Plugin +
Follow the instructions in this article to deploy to CloudHub using Mule Maven Plugin.

== Prerequisites

The following are the prerequisites to deploy to CloudHub using the Mule Maven plugin.

=== Add the Mule Maven Plugin to your Project

include::partial$mmp-concept.adoc[tag=addMuleMavenPluginToAProject]

=== Configure the HTTP Listener

The host and port number of your HTTP Listener flow sources must be properly configured.

If you are using the HTTP Listener as source for your flow, you need to set its host to *0.0.0.0* and its port to *${http.port}*. CloudHub then dynamically allocates a port at deployment time.

=== Declare External Classes and Resources.

Declare all your external classes and resources in the `mule-artifact.json` file of your Mule application.

Due to the Mule 4 classloading isolation mechanism, all external classes and resources must be explicitly declared in the `exportedPackages` and `exportedResources` fields on the `mule-artifact.json` file before packaging and deploying the app.
+
See xref:how-to-export-resources.adoc[Export Resources] to learn more about working with external resources in your Mule application.

== Deploy Using Mule Maven Plugin

The Mule Maven plugin enables you to deploy Mule applications to CloudHub using the command line. Follow the next steps to deploy applications to CloudHub:

. Make sure you added the Mule Maven plugin to your `pom.xml` file.
. Inside the `plugin` element, add a configuration for your CloudHub deployment, replacing the placeholder values with your CloudHub information:
+
[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
  <configuration>
    <cloudHubDeployment>
      <uri>https://anypoint.mulesoft.com</uri>
      <muleVersion>${app.runtime}</muleVersion>
      <username>${username}</username>
      <password>${password}</password>
      <applicationName>${cloudhub.application.name}</applicationName>
      <environment>${environment}</environment>
      <properties>
        <key>value</key>
      </properties>
    </cloudHubDeployment>
  </configuration>
</plugin>
----
+
. From the command line in your project's folder, package the app and execute the deploy goal:
+
[source,console,linenums]
----
mvn clean package deploy -DmuleDeploy
----

== Redeploy to CloudHub

To redeploy a Mule application using Mule Maven plugin, run the same command as you did to deploy. +
CloudHub rewrites the app you had deployed.

=== Undeploy from CloudHub

To undeploy a Mule application using Mule Maven plugin, run the following command:

[source,console,linenums]
----
mvn mule:undeploy
----

The undeploy command also deletes the app in Mule Maven plugin 3.3.0 and later versions.

=== CloudHub Deployment Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`cloudHubDeployment` | Top-Level Element.
| `uri` | Your Anypoint Platform URI. +
If not set, by default this value is set to +https://anypoint.mulesoft.com+.
| `muleVersion` | The Mule version that will run in your CloudHub instance. +
You need to ensure that this value is equal to or higher than the minimum required Mule version of your application.
| `username` | Your CloudHub username.
| `password` | Your CloudHub password.
| `applicationName` | The name of your application in CloudHub. +
This name is part of the domain of your deployed app. For example, naming your application application-1 makes your app's public domain +application-1.cloudhub.io+.
| `artifact` | Absolute file location of the JAR to be deployed. +
If not set, by default it is the location of the JAR generated at the package phase
| `environment` | The CloudHub environment to which you want to deploy. This value must match any environment configured in your CloudHub account. +
For Example:
[source,xml,linenums]
----
<environment>Sandbox</environment>
----
include::partial$mmp-concept.adoc[tag=propertiesParameterDescription]
| `workers` | The number of workers. +
By default, it is set to 1.
| `workerType` | Size of each worker. +

Accepted values are:

MICRO (0.1 vCores) +
SMALL (0.2 vCores) +
MEDIUM (1 vCore ) +
LARGE (2 vCores) +
XLARGE (4 vCores) +
XXLARGE (8 vCores) +
4XLARGE (16 vCores)

The default value is MICRO.
| `region` | Region of worker clouds.

Accepted values are:

* us-east-1      -  US East (N. Virginia)
* us-west-2      -  US West (Oregon)
* eu-west-1      -  EU (Ireland)
* ap-southeast-2 -  Asia Pacific (Sydney)
* ap-southeast-1 -  Asia Pacific (Singapore)
* us-west-1      -  US West (N. California)
* eu-central-1   -  EU (Frankfurt)
* ap-northeast-1 -  Asia Pacific (Tokyo)
* eu-west-2      -  EU (London)
* ca-central-1   -  Canada (Central)
* sa-east-1      -  South America (São Paulo)
* us-east-2      -  US East (Ohio)

The default value is  us-east-1.
include::partial$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::partial$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::partial$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::partial$mmp-concept.adoc[tag=serverParameterDescription]
include::partial$mmp-concept.adoc[tag=skipParameterDescription]
|===

== See Also

* xref:mmp-concept.adoc[Mule Maven Plugin Reference]
