= Deploy Applications to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In addition to using Anypoint Runtime Manager, to deploy applications to Anypoint Runtime Fabric, you can also deploy applications by using the Mule Maven plugin. To do so, you must meet certain prerequisites, and configure your Runtime Fabric deployment strategy in your project's `pom.xml` file.

== Prerequisites

* Ensure that the Mule Maven Plugin is added to your project
+
See xref:mmp-concept.adoc#add-mmp[Add the Mule Maven Plugin to a Mule Project] for instructions.
* You understand and have available the number of resources required to deploy to Runtime Fabric +
See xref:runtime-fabric::deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric] for more information.
* The application is already published in Exchange +
** To do this from Studio, see xref:studio::export-to-exchange-task.adoc[Publishing a Project to Exchange]. +
** To do this using Maven, see xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].
+
[NOTE]
Studio allows you to select only two project types when uploading an application to Exchange: `example` and `template`. To specify a different project type, publish your application using Maven.

[[deploying-to-rtf]]
== Configure the Runtime Fabric Deployment Strategy

Inside the `plugin` element, add a configuration for your Runtime Fabric deployment, replacing the following placeholder values with your Runtime Fabric information:

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
  <configuration>
    <runtimeFabricDeployment>
      <uri>https://anypoint.mulesoft.com</uri>
      <muleVersion>${app.runtime}</muleVersion>
      <username>${username}</username>
      <password>${password}</password>
      <applicationName>${runtime.fabric.application.name}</applicationName>
      <environment>${environment}</environment>
      <provider>${provider}</provider>
      <properties>
        <key>value</key>
      </properties>
      <deploymentSettings>
        <publicUrl>${app.url}</publicUrl>
        <cpuReserved>500m</cpuReserved>
        <memoryReserved>800Mi</memoryReserved>
      </deploymentSettings>
    </runtimeFabricDeployment>
  </configuration>
</plugin>
----

== Deploy to Runtime Fabric

From the command line in your project's folder, package the application and execute the deploy goal:

[source,bash,linenums]
----
mvn clean package deploy -DmuleDeploy
----

== Redeploy to Runtime Fabric

To redeploy the application, run the same command as you did to deploy. +
Runtime Fabric rewrites the application you had deployed.

== Runtime Fabric Deployment Parameters Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`runtimeFabricDeployment` | Top-Level Element
| `uri` | Your Anypoint Platform URI +
If not set, defaults to +https://anypoint.mulesoft.com+.
| `muleVersion` | The Mule version that will run in your Runtime Fabric instance +
Must be the same or later than the minimum required Mule version for your application.
| `username` | Your Anypoint Platform username
| `password` | Your Anypoint Platform password
| `applicationName` | The name of your application deployed in Exchange +
This name is part of the domain of your deployed app.
| `target` | The Runtime Fabric target name where to deploy the app
| `provider` | Set to `MC`, for Runtime Fabric
| `environment` | Target Anypoint Platform environment +
This value must match an environment configured in your Anypoint Platform account, as shown here: +
[source,xml,linenums]
----
<environment>Sandbox</environment>
----
include::partial$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::partial$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::partial$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::partial$mmp-concept.adoc[tag=serverParameterDescription]
include::partial$mmp-concept.adoc[tag=propertiesParameterDescription]
include::partial$mmp-concept.adoc[tag=skipParameterDescription]
| `deploymentSettings` | Any of the parameters documented in xref:mmp-concept.adoc#deploymentsettings-reference[deploymentSettings Reference]
|===

=== deploymentSettings Parameters Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
| `clusteringEnabled` | Enables clustering across two or more replicas of the application; default is `false`. +
Here is an example:
[source,xml,linenums]
----
<deploymentSettings>
    <clusteringEnabled>true</clusteringEnabled>
</deploymentSettings>
----
| `replicationFactor` | The number of instances for your application. Default is `1`. +
Here is an example:
[source,xml,linenums]
----
<deploymentSettings>
    <replicationFactor>2</replicationFactor>
</deploymentSettings>
----
| `lastMileSecurity` | Enable Last-Mile security to forward HTTPS connections to be decrypted by this application +
This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources. Default is `false`.
[source,xml,linenums]
----
<deploymentSettings>
    <lastMileSecurity>true</lastMileSecurity>
</deploymentSettings>
----
| `memoryReserved` | Amount of memory to be allocated for each replica of the application. Default value is 700 MB.
[source,xml,linenums]
----
<deploymentSettings>
    <memoryReserved>100Mi</memoryReserved>
</deploymentSettings>
----
This allocates 100 MB of memory per replica.
| `memoryMax` | Maximum memory allocated per application replica. Value must be equal to or greater than memoryReserved, if configured.
[source,xml,linenums]
----
<deploymentSettings>
    <memoryMax>200Mi</memoryMax>
</deploymentSettings>
----
This allocates 200 MB maximum memory for each replica.
| `cpuReserved` | Number of cores allocated per application replica. Default is 0.5 vCores.
[source,xml,linenums]
----
<deploymentSettings>
    <cpuReserved>500m</cpuReserved>
</deploymentSettings>
----
This allocates 0.5 vCores per replica.
| `cpuMax` | Amount of max cores to be allocated for each replica of the application +
If a cpuReserved configuration is present, ensure that this value is equal or higher.

[source,xml,linenums]
----
<deploymentSettings>
    <cpuMax>1000m</cpuMax>
</deploymentSettings>
----
This allocates a maximum of 1 vCore per replica.
| `publicUrl` | URL of the deployed application:

[source,xml,linenums]
----
<deploymentSettings>
    <publicUrl>myapp.anypoint.com</publicUrl>
</deploymentSettings>
----
|===

== Encrypt Credentials

include::partial$mmp-concept.adoc[tag=encryptCredentials]
+
[source,xml,linenums]
----
<plugin>
  ...
  <configuration>
    ...
    <runtimeFabricDeployment>
      ...
      <server>my.anypoint.credentials</server>
      ...
    </runtimeFabricDeployment>
    ...
  </configuration>
  ...
<plugin>
----
+
NOTE: Make sure that the username and password are not set in the deployment configuration, or they will overwrite the defined server ID.

== See Also

* xref:runtime-fabric::deploy-to-runtime-fabric.adoc[Deploy Applications to Runtime Fabric Using Runtime Manager]
* xref:mmp-concept.adoc[Mule Maven Plugin]
