= Deploy Mule Applications
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: deploy, deploying, cloudhub, on premises, on premise

All Mule Applications are deployed to a Mule runtime engine instance. MuleSoft supports three different deployment targets: CloudHub, Anypoint Runtime Fabric, and on-premises Mule instances.

However, depending on the deployment target you chose, the installation of Mule runtime engine might be required and the tools available to deploy applications differ:

[%header,cols="1a,2a,3a"]
|===
|Deployment Target | Available deployment tools | Mule runtime engine installation
|CloudHub |
* Anypoint Studio
* Anypoint Runtime Manager
* Anypoint Platform CLI
* Mule Maven plugin
|
* No installation of Mule runtime engine is required, CloudHub workers take care of Mule instances

|Anypoint Runtime Fabric |
* Anypoint Runtime Manager
* Anypoint Runtime Manager (Anypoint PCE)
* Mule Maven plugin
|
* No Installation of Mule runtime engine is required, Anypoint Runtime Fabric internally take care of Mule instances
* Installation of Anypoint Runtime Fabric in your desired infrastructure is required

|On-premises |
* Anypoint Studio
* Anypoint Runtime Manager
* Anypoint Runtime Manager (Anypoint PCE)
* Anypoint Platform CLI
* Mule Maven plugin
|
* Installation of Mule runtime engine is required
* You are responsible of the installation and configuration of your Mule instances

|===

== See Also

* xref:runtime-manager::cloudhub.adoc[CloudHub]
* xref:runtime-fabric::index.adoc[Anypoint Runtime Fabric]
* xref:runtime-manager::index.adoc[Anypoint Runtime Manager]
* xref:private-cloud::index.adoc[Anypoint Platform Private Cloud Edition]
* xref:shared-resources.adoc[Shared Resources]
* xref:mule-high-availability-ha-clusters.adoc[Mule High Availability Clusters]
