= Deploy Mule Applications
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: deploy, deploying, cloudhub, on premises, on premise
:page-aliases: application-deployment.adoc

All Mule applications are deployed to a Mule runtime engine instance. MuleSoft supports three different deployment targets: CloudHub, Anypoint Runtime Fabric, and on-premises Mule instances.

When you deploy applications to CloudHub or to Anypoint Runtime Fabric, these services take care of the Mule runtime engine instances needed to run applications.

If you deploy applications on-premises, the installation of Mule runtime engine is required. +
See xref:mule-deployment-model.adoc[On-Premises Deployment Model] for more information about characteristics specific to on-premises deployments.

In addition, the tools available to deploy applications to each of the deployment targets differ:

[%header,cols="1a,2a,3a"]
|===
|Deployment Target | Available Deployment Tools | Mule Runtime Engine Installation
|CloudHub |
* Anypoint Studio
* Anypoint Runtime Manager
* Anypoint Platform CLI
* Mule Maven plugin
|
* No installation of Mule runtime engine is required, because CloudHub workers start Mule instances as part of the deployment process.


|Anypoint Runtime Fabric |
* Anypoint Runtime Manager
* Runtime Manager in Anypoint Platform Private Cloud Edition
* Mule Maven plugin
|
* No installation of Mule runtime engine is required, because Anypoint Runtime Fabric internally starts Mule instances as part of the deployment process.
* Installation of Anypoint Runtime Fabric in your desired infrastructure is required

|On-premises |
* Anypoint Studio
* Anypoint Runtime Manager
* Runtime Manager in Anypoint Platform Private Cloud Edition
* Anypoint Platform CLI
* Mule Maven plugin
|
* Installation of Mule runtime engine in your desired infrastructure is required.
* You are responsible for the installation and configuration of your Mule instances.

|===

== See Also

* xref:runtime-manager::cloudhub.adoc[CloudHub]
* xref:runtime-fabric::index.adoc[Anypoint Runtime Fabric]
* xref:runtime-manager::index.adoc[Anypoint Runtime Manager]
* xref:private-cloud::index.adoc[Anypoint Platform Private Cloud Edition]
* xref:shared-resources.adoc[Shared Resources]
* xref:mule-high-availability-ha-clusters.adoc[Mule High Availability Clusters]
