= Deploy Applications to Runtime Fabric
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can deploy applications to Runtime Fabric using any of the following tools:

* Anypoint Runtime Manager +
See xref:runtime-fabric::deploy-to-runtime-fabric.adoc[Deploy Mule Applications to Runtime Fabric]for instructions.
* Mule Maven Plugin +
Follow the instructions in this article to deploy to Runtime Fabric using Mule Maven Plugin.

== Prerequisites

The following are the prerequisites to deploy to Runtime Fabric using the Mule Maven plugin.

===== Add the Mule Maven Plugin to your Project

include::partial$mmp-concept.adoc[tag=addMuleMavenPluginToAProject]

===== Verify Resources Required for Deployment

Before deploying an application to Runtime Fabric, check the number of resources required. +
See xref:runtime-fabric::deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric] for more information.

===== Publish the Application to exchange

The application must be published in Exchange. +
To do this from Studio, see xref:studio::export-to-exchange-task.adoc[Publishing a Project to Exchange]. +
To do this using Maven, see xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].

[NOTE]
Studio allows you to select only two project types when uploading an application to Exchange: `example` and `template`. To specify a different project type, publish your application using Maven.

[[deploying-to-rtf]]
== Deploy Using Mule Maven Plugin

Follow the next steps to deploy applications to Runtime Fabric using the Mule Maven Plugin:

. Make sure you added the Mule Maven plugin to your `pom.xml` file.
. Inside the `plugin` element, add a configuration for your Runtime Fabric deployment, replacing the placeholder values with your Runtime Fabric information:
+
[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
  <configuration>
    <runtimeFabricDeployment>
      <uri>https://anypoint.mulesoft.com</uri>
      <muleVersion>${app.runtime}</muleVersion>
      <username>${username}</username>
      <password>${password}</password>
      <applicationName>${runtime.fabric.application.name}</applicationName>
      <environment>${environment}</environment>
      <provider>${provider}</provider>
      <properties>
        <key>value</key>
      </properties>
      <deploymentSettings>
        <publicUrl>${app.url}</publicUrl>
        <cpuReserved>500m</cpuReserved>
        <memoryReserved>800Mi</memoryReserved>
      </deploymentSettings>
    </runtimeFabricDeployment>
  </configuration>
</plugin>
----
+
. From the command line in your project's folder, package the application and execute the deploy goal:
+
[source,bash,linenums]
----
mvn clean package deploy -DmuleDeploy
----

== Redeploy to Runtime Fabric

To redeploy the application, run the same command as you did to deploy. +
Runtime Fabric rewrites the application you had deployed.

== Runtime Fabric Deployment Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`runtimeFabricDeployment` | Top-Level Element.
| `uri` | Your Anypoint Platform URI. +
If not set, by default this value is set to +https://anypoint.mulesoft.com+.
| `muleVersion` | The Mule version that will run in your Runtime Fabric instance. +
You need to ensure that this value is equal to or higher than the minimum required Mule version of your application.
| `username` | Your Anypoint Platform username.
| `password` | Your Anypoint Platform password.
| `applicationName` | The name of your application deployed in Exchange. +
This name is part of the domain of your deployed app.
| `target` | The Runtime Fabric target name where to deploy the app.
| `provider` | Provider type. Set to MC ("MC" specifies Runtime Fabric).
| `environment` | The Anypoint Platform environment to which you want to deploy. This value must match any environment configured in your Anypoint Platform account. +
For Example:
[source,xml,linenums]
----
<environment>Sandbox</environment>
----
include::partial$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::partial$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::partial$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::partial$mmp-concept.adoc[tag=serverParameterDescription]
include::partial$mmp-concept.adoc[tag=propertiesParameterDescription]
include::partial$mmp-concept.adoc[tag=skipParameterDescription]
| `deploymentSettings` | See the xref:mmp-concept.adoc#deploymentsettings-reference[deploymentSettings Reference] table below for a complete list of parameters that can be configured inside this element.
|===

=== deploymentSettings Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
| `clusteringEnabled` | Enable Mule clustering across each replica of the application. It requires to have at least two replicas. +
By default, is set to false. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <clusteringEnabled>true</clusteringEnabled>
</deploymentSettings>
----
| `replicationFactor` | The number of instances for your application. +
By default, it is set to 1. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <replicationFactor>2</replicationFactor>
</deploymentSettings>
----
| `lastMileSecurity` | Enable Last-Mile security to forward HTTPS connections to be decrypted by this application. +
This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources. +
By default, is set to false. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <lastMileSecurity>true</lastMileSecurity>
</deploymentSettings>
----
| `memoryReserved` | Amount of memory to be allocated for each replica of the application. If not present, the default value is 700MB. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <memoryReserved>100Mi</memoryReserved>
</deploymentSettings>
----
This will set 100MB of memory to each replica.
| `memoryMax` | Amount of max memory to be allocated for each replica of the application. If a memoryReserved configuration is present, ensure that this value is equal or higher. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <memoryMax>200Mi</memoryMax>
</deploymentSettings>
----
This will set 200MB of memory max to each replica.
| `cpuReserved` | Amount of cores to be allocated for each replica of the application. If not present, the default value is 0.5 vCores. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <cpuReserved>500m</cpuReserved>
</deploymentSettings>
----
This will set 0.5 vCores for each replica.
| `cpuMax` | Amount of max cores to be allocated for each replica of the application. If a cpuReserved configuration is present, ensure that this value is equal or higher.
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <cpuMax>1000m</cpuMax>
</deploymentSettings>
----
This will set a max of 1 vCores to each replica.
| `publicUrl` | Url of the deployed application.
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <publicUrl>myapp.anypoint.com</publicUrl>
</deploymentSettings>
----
|===

== See Also

* xref:mmp-concept.adoc[Mule Maven Plugin]
