= Deploying Mule ESB 3
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As of version 3.1, Mule standalone can run multiple applications. This means you can include the same name spaces within different applications and they will neither collide nor share information.

* In effect, it's now an app server.
* In addition, Mule checks for new apps (in the apps directory) and will start them.
* It will also restart apps if it detects that they have changed, meaning you can drop a revised version of an existing, running application into the /apps directory, Mule will stop the existing app and restart using the new files.
* This results in one fewer reason to run Mule inside a container.

* xref:deployment-scenarios.adoc[Deployment Scenarios]
* xref:mule-deployment-model.adoc[Mule Deployment Model]
* xref:configuring-logging.adoc[Configuring Logging]
* xref:mule-server-notifications.adoc[Mule Server Notifications]
* xref:profiling-mule.adoc[Profiling Mule]
* xref:hardening-your-mule-installation.adoc[Hardening your Mule Installation]
* xref:configuring-mule-for-different-deployment-scenarios.adoc[Configuring Mule for Different Deployment Scenarios]