= Distributed File Polling
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: file polling, cluster

*_Enterprise Edition_*

Some connectors, such as the File connector or FTP connector, regularly poll directories and read certain files as they are created in the directories polled. These files may reside on a remote file system, including file systems of nodes belonging to a Mule High Availability (HA) Cluster.

In the current version, file polling for clusters' distributed file systems makes it possible to poll files in all cluster nodes. Enabled by default, this feature is used by the following connectors:

* xref:connectors::file/file-connector.adoc[File Connector]
* xref:connectors::ftp/ftp-connector.adoc[FTP Connector]
* xref:connectors::sftp/sftp-connector.adoc[SFTP Connector]

== See Also
* xref:creating-and-managing-a-cluster-manually.adoc[Creating and Managing a Cluster Manually]
//* xref:mule-high-availability-ha-clusters.adoc[Mule High Availability (HA) Cluster]
* xref:migration-connectors-file.adoc[Migrating File Connector]
* xref:migration-connectors-ftp-sftp.adoc[Migrating FTP and SFTP Connectors]
