= Distributed File Polling
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: file polling, cluster

*_Enterprise Edition_*

Some endpoints, such as the xref:file-connector.adoc[File Endpoint] or xref:ftp-connector.adoc[FTP Endpoint], regularly poll directories and read certain files as they are created in the directories polled. These files may reside on a remote file system, including file systems of nodes belonging to a xref:mule-high-availability-ha-clusters.adoc[Mule High Availability (HA) Cluster].

Up to Mule 3.3.x, all file poll requests sent to a cluster were channeled through a single node in that cluster. This ensured file consistency by avoiding the possibility of file system sync issues, but had the disadvantage of introducing a bottleneck, reducing the performance of the cluster.

In the current version file polling for clusters' distributed file systems makes it possible to poll files in all cluster nodes. Enabled by default, this feature is used by the following endpoints:

* xref:file-connector.adoc[File Endpoint]
* xref:ftp-connector.adoc[FTP Endpoint]
* xref:sftp-connector.adoc[SFTP Endpoint]

== Requirement

To use distributed file polling, the flow's xref:flow-processing-strategies.adoc[Processing Strategy] must be synchronous. If the processing strategy is asynchronous, Mule will automatically disable distributed file polling, and revert to the old behavior.

You can create and configure clusters with the graphical interface available in the xref:3.8@mule-management-console::index.adoc[Mule Management Console], or manually by xref:3.8@mule-management-console::creating-or-disbanding-a-cluster.adoc[editing the cluster configuration file.] For additional configuration options, including cluster network parameters, see xref:creating-and-managing-a-cluster-manually.adoc[Creating and Managing a Cluster Manually].