= Distributed File Polling
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: file polling, cluster

*_Enterprise Edition_*

Some endpoints, such as the File Endpoint or FTP Endpoint, regularly poll directories and read certain files as they are created in the directories polled. These files may reside on a remote file system, including file systems of nodes belonging to a Mule High Availability (HA) Cluster.

Up to Mule 3.3.x, all file poll requests sent to a cluster were channeled through a single node in that cluster. This ensured file consistency by avoiding the possibility of file system sync issues, but had the disadvantage of introducing a bottleneck, reducing the performance of the cluster.

In the current version file polling for clusters' distributed file systems makes it possible to poll files in all cluster nodes. Enabled by default, this feature is used by the following endpoints:

* xref:connectors::file/file-connector.adoc[File Endpoint]
* xref:connectors::ftp/ftp-connector.adoc[FTP Endpoint]
* xref:connectors::sftp/sftp-connector.adoc[SFTP Endpoint]

== See Also
* xref:creating-and-managing-a-cluster-manually.adoc[Creating and Managing a Cluster Manually].
//* xref:mule-high-availability-ha-clusters.adoc[Mule High Availability (HA) Cluster]
* xref:migration-connectors-file.adoc[Migrating File Connector]
* xref:migration-connectors-ftp-sftp.adoc[Migrating FTP and SFTP Connectors]
