= Downloading Mule ESB 3
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This section describes how to download Mule ESB 3.

== Understanding Which Mule ESB 3 Distribution Is Best For You

There are three types of Mule distributions. The distribution you choose depends on your business needs and current phase of development.

* *MuleSoft supported release (Mule Enterprise)*: the latest, fully tested release of Mule created by MuleSoft that includes premium features not found in the community release. Mule Enterprise provides access to technical support, maintenance patches, and the MuleSoft knowledge base, and is suitable for development, pre-production, and production environments alike. You can download and install the 30-day trial of Mule Enterprise http://www.mulesoft.com/mule-esb-enterprise-trial-download[here].
* *Latest stable community release*: the latest stable community release of Mule. Community releases go through several iterations of community QA before release. If you are using a community release and encounter a significant issue that you cannot resolve, you may wish to consider Mule Enterprise with premium support from MuleSoft. You can download the community release [here].
* *Snapshot release*: the latest Mule distribution built against the very latest code base ("the bleeding edge"). Snapshot releases may be unstable, so they are intended for development environments only, not for production environments. Additionally, snapshot releases do not include any documentation. You can download the latest snapshot release [here].

You can also check out the source code and build Mule yourself. For complete information on how to check out the Mule source code from Subversion and build Mule, see [Setting Up the Development Environment] and [Building from Source].

== Getting Mule from the Download Server

. Download Mule.
. Click the link next to the release you want to download. Use the `.zip` links for installing on Windows and the `.tar.gz` links for installing on Linux/UNIX. The latest releases are at the top of the page.
. On Linux/UNIX, if you prefer to download through a shell instead of a browser or need to download to a remote computer without X-Windows, you can download the distribution using your download tool. For example to download the Mule 3.1.2 snapshot using `wget`, you would enter the following command all on one line:

[source,text,linenums]
----
wget http://snapshots.dist.codehaus.org/mule/org/mule/distributions/mule-standalone/3.
----