= countBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[countby1]]
== countBy<T&#62;&#40;array: Array<T&#62;, matchingFunction: &#40;T&#41; &#45;&#62; Boolean&#41;: Number

Counts the elements in an array that return `true` when the matching function is applied to the value of each element.


=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `array` | The input array that contains elements to match.
| `matchingFunction` | A function to apply to elements in the input array.
|===

=== Example

This example counts the number of elements in the input array ([1, 2, 3, 4]) that
return `true` when the function `(($ mod 2) == 0)` is applied their values. In this
case, the values of _two_ of the elements, both `2` and `4`, match because
`2 mod 2 == 0` and `4 mod 2 == 0`. As a consequence, the `countBy` function returns `2`.
Note that `mod` returns the modulus of the operands.

==== Source

[source,DataWeave, linenums]
----
 %dw 2.0
 import * from dw::core::Arrays
 output application/json
 ---
{ "countBy" : [1, 2, 3, 4] countBy (($ mod 2) == 0) }
----

==== Output

[source,JSON,linenums]
----
{ "countBy": 2 }
----


[[countby2]]
== countBy&#40;array: Null, matchingFunction: &#40;Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `countBy` to work with a `null` value.

