= takeWhile
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[takewhile1]]
== takeWhile<T&#62;&#40;array: Array<T&#62;, condition: &#40;item: T&#41; &#45;&#62; Boolean&#41;: Array<T&#62;

Selects elements from the array while the condition is met but
stops the selection process when it reaches an element that
fails to satisfy the condition.


To select all elements that meet the condition, use the `filter` function.

_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `array` | The array of elements.
| `condition` | The condition (or expression) used to match an element in the array.
|===

=== Example

This example iterates over the elements in the array and selects only those
with an index that is `&lt;= 1` and stops selecting elements when it reaches
one that is greater than `2`. Notice that it does not select the second `1` because
of the `2` that precedes it in the array. The function outputs the result into an array.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
var arr = [0,1,2,1]
---
arr takeWhile $ <= 1
----

==== Output

[source,json,linenums]
----
[
  0,
  1
]
----


[[takewhile2]]
== takeWhile&#40;array: Null, condition: &#40;item: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `takeWhile` to work with a `null` value.

