= takeWhile
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[takewhile1]]
== takeWhile&#40;Array<T&#62;, &#40;item: T&#41; &#45;&#62; Boolean&#41;: Array<T&#62;

Selects elements from the array while the condition is met but 
stops the selection process when it reaches an element that 
fails to satisfy the condition.

To select all elements that meet the condition, use the `filter` function.


_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `array` | The array of elements.
| `condition` | The condition (or expression) used to match an element in the array.
|===

=== Example

This example iterates over the elements in the array and selects only those
where the index is `&lt;= 2`. It stops selecting elements when it reaches an 
element that is greater than 2. Notice that it does not select the 3 because 4 
precedes 3 in the array. The function outputs the result into an array.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
var arr = [0,1,2,4,3]
---
arr takeWhile $ <= 2
----

==== Output

[source,json,linenums]
----
[
  0,
  1,
  2
]
----

