= outerJoin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[outerjoin1]]
== outerJoin<L <: Object, R <: Object&#62;&#40;left: Array<L&#62;, right: Array<R&#62;, leftCriteria: &#40;leftValue: L&#41; &#45;&#62; String, rightCriteria: &#40;rightValue: R&#41; &#45;&#62; String&#41;: Array<{ l?: L, r?: R }&#62;

Joins two array of objects by a given `ID` criteria.


`outerJoin` returns an array with all the `left` items, merged by ID
with the `right` items in cases where any exist, and it returns `right`
items that are not present in the `left`.

_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `left` | The left-side array of objects.
| `right` | The right-side array of objects.
| `leftCriteria` | The criteria used to extract the ID for the left collection.
| `rightCriteria` | The criteria used to extract the ID for the right collection.
|===

=== Example

This example shows how join behaves. Notice that the output includes
objects where the values of the input `user.id` and `product.ownerId` match,
and it includes objects where there is no match for the value of the
`user.id` or `product.ownerId`.

==== Source

[source,DataWeave, linenums]
----
 %dw 2.0
 import * from dw::core::Arrays
 var users = [{id: "1", name:"Mariano"},{id: "2", name:"Leandro"},{id: "3", name:"Julian"},{id: "5", name:"Julian"}]
 var products = [{ownerId: "1", name:"DataWeave"},{ownerId: "1", name:"BAT"}, {ownerId: "3", name:"DataSense"}, {ownerId: "4", name:"SmartConnectors"}]
 output application/json
 ---
 outerJoin(users, products, (user) -> user.id, (product) -> product.ownerId)

----

==== Output

[source,json,linenums]
----
[
  {
    "l": {
      "id": "1",
      "name": "Mariano"
    },
    "r": {
      "ownerId": "1",
      "name": "DataWeave"
    }
  },
  {
    "l": {
      "id": "1",
      "name": "Mariano"
    },
    "r": {
      "ownerId": "1",
      "name": "BAT"
    }
  },
  {
    "l": {
      "id": "2",
      "name": "Leandro"
    }
  },
  {
    "l": {
      "id": "3",
      "name": "Julian"
    },
    "r": {
      "ownerId": "3",
      "name": "DataSense"
    }
  },
  {
    "l": {
      "id": "5",
      "name": "Julian"
    }
  },
  {
    "r": {
      "ownerId": "4",
      "name": "SmartConnectors"
    }
  }
]
----

