= partition
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[partition1]]
== partition<T&#62;&#40;array: Array<T&#62;, condition: &#40;item: T&#41; &#45;&#62; Boolean&#41;: { success: Array<T&#62;, failure: Array<T&#62; }

Separates the array into the elements that satisfy the condition from those
that do not.


_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `array` | The array of elements to split.
| `condition` | The condition (or expression) used to match an element in the array.
|===

=== Example

This example partitions numbers found within an input array. The
even numbers match the criteria set by the lambda expression
`(item) -> isEven(item)`. The odd do not. The function generates the
`"success"` and `"failure"` keys within the output object.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
var arr = [0,1,2,3,4,5]
---
arr partition (item) -> isEven(item)
----

==== Output

[source,json,linenums]
----
{
  "success": [
    0,
    2,
    4
  ],
  "failure": [
    1,
    3,
    5
  ]
}
----


[[partition2]]
== partition&#40;array: Null, condition: &#40;item: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `partition` to work with a `null` value.

