= indexWhere
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[indexwhere1]]
== indexWhere<T&#62;&#40;array: Array<T&#62;, condition: &#40;item: T&#41; &#45;&#62; Boolean&#41;: Number

Returns the index of the first occurrence of an element that matches a
condition within the array. If no element matches the condition, the function returns `-1`.


_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `array` | The array of elements.
| `condition` | The condition (or expression) used to match an element in the array.
|===

=== Example

This example returns the index of the value from the input array that
matches the condition in the lambda expression,
`(item) -> item startsWith "Jul"`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
var users = ["Mariano", "Leandro", "Julian"]
---
users indexWhere (item) -> item startsWith "Jul"
----

==== Output

[source,json,linenums]
----
2
----


[[indexwhere2]]
== indexWhere&#40;array: Null, condition: &#40;item: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `indexWhere` to work with a `null` value.

