= writeLinesWith
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[writelineswith1]]
== writeLinesWith&#40;content: Array<String&#62;, charset: String&#41;: Binary

Writes the specified lines and returns the binary content.


_Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `content` | Array of items to write.
| `charset` | String representing the encoding to use when writing.
|===

=== Example

This example inserts a new line (`\n`) after each iteration. Specifically,
it uses `map` to iterate over the result of `to(1, 10)`, `[1,2,3,4,5]`, then
writes the specified content ("Line $"), which includes the unnamed variable
`$` for each number in the array.

Note that without `writeLinesWith  "UTF-8"`, the expression
`{ lines: to(1, 10) map "Line $" }` simply returns
an array of line numbers as the value of an object:
`{ "lines": [ "line 1", "line 2", "line 3", "line 4",  "line 5" ] }`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
output application/json
---
{ lines: to(1, 10) map "Line $" writeLinesWith  "UTF-8" }
----

==== Output

[source,JSON,linenums]
----
{
  "lines": "Line 1\nLine 2\nLine 3\nLine 4\nLine 5\n"
}
----

