= indexOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[indexof1]]
== indexOf&#40;array: Array, value: Any&#41;: Number

Returns the index of the _first_ occurrence of the specified element in this array, or -1 if this list does not contain the element.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `array` | The array of elements to search.
| `value` | The value to search.
|===

=== Example

This example shows how `indexOf` behaves given different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: ["a","b","c","d"] indexOf "c",
  notPresent: ["x","w","x"] indexOf "c",
  presentMoreThanOnce: ["a","b","c","c"] indexOf "c",
}
----

==== Output

[source,Json,linenums]
----
{
   "present": 2,
   "notPresent": -1,
   "presentMoreThanOnce": 2
 }
----


[[indexof2]]
== indexOf&#40;theString: String, search: String&#41;: Number

Returns the index of the *first* occurrence of the specified String in this String.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| theString | The String where to search.
| search | The String to search.
|===

=== Example

This example shows how the `indexOf` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: "abcd" indexOf "c",
  notPresent: "xyz" indexOf "c",
  presentMoreThanOnce: "abcdc" indexOf "c",
}

----

==== Output

[source,Json,linenums]
----
{
   "present": 2,
   "notPresent": -1,
   "presentMoreThanOnce": 2
 }
----


[[indexof3]]
== indexOf&#40;array: Null, value: Any&#41;: Number

Helper method to make indexOf null friendly

