= filter
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[filter1]]
== filter&#40;Array<T&#62;, &#40;item: T, index: Number&#41; &#45;&#62; Boolean&#41;: Array<T&#62;

Filters a list (array) by applying an expression that returns only the matching
items from the list.


The expression must return `true` or `false`. If the expression returns `true`
for an element, the element remains in the list. If it returns `false` for
an element, the element gets filtered out of the results.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `items` | The list (array) to filter.
| `criteria` | Function that receives an `item` and `index` and returns true if the element should be kept.
|===

=== Example

This example returns an array of all elements greater than `2`.

==== Source

[source,DataWeave, linenums]
----
[9,2,3,4,5] filter (myitem, myindex) -> (myitem > 2)
----

==== Output

[source,JSON,linenums]
----
[9,3,4,5]
----

=== Example

This example returns an array of all elements found at an index
greater than `2`.

==== Source

[source,DataWeave, linenums]
----
[9,2,3,4,5] filter ((myitem, myindex) -> (myindex > 2))
----

==== Output

[source,JSON,linenums]
----
[4,5]
----

=== Example

This example returns an array of all elements found at an index (`&#36;&#36;`)
greater than `1` where the value of the element is less than `5`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
[9, 2, 3, 4, 5] filter (($$ > 1) and ($ < 5))
----

==== Output

[source,JSON,linenums]
----
[3,4]
----


[[filter2]]
== filter&#40;Null, &#40;item: Nothing, index: Nothing&#41; &#45;&#62; Boolean&#41;: Null

Helper function that allows `filter` to work with null values.

