= distinctBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[distinctby1]]
== distinctBy(Array<T>, (item: T, index: Number) -> Any): Array<T>

Returns unique values from a list (array) that might have duplicates.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The list (`Array` type).
| `criteria` | The `item` and/or `index` used to return.
|===

=== Example

This example removes duplicates of `"Kurt Cagle"` from an input array.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
var record =  {
  "title": "XQuery Kick Start",
  "author": [
    "James McGovern",
    "Per Bothner",
    "Kurt Cagle",
    "James Linn",
    "Kurt Cagle",
    "Kurt Cagle",
    "Kurt Cagle",
    "Vaidyanathan Nagarajan"
  ],
  "year":"2000"
}
---
{
    "book" : {
      "title" : record.title,
      "year" : record.year,
      "authors" : record.author distinctBy $
    }
}
----

==== Output

[source,JSON,linenums]
----
{
  "book": {
    "title": "XQuery Kick Start",
    "year": "2000",
    "authors": [
      "James McGovern",
      "Per Bothner",
      "Kurt Cagle",
      "James Linn",
      "Vaidyanathan Nagarajan"
    ]
  }
}
----


[[distinctby2]]
== distinctBy(Null, (item: Nothing, index: Nothing) -> Any): Null

Helper function that allows *distinctBy* to work with null values.


[[distinctby3]]
== distinctBy({ (K)?: V }, (value: V, key: K) -> Any): Object

Removes duplicate key-value pairs from an Object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `object` | The object from which to remove the key-value pairs.
| `criteria` | The `key` and/or `value` used to identify the key-value pairs to remove.
|===

=== Example

This example removes duplicates (`<author>James McGovern</author>`)
from `<book/>`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
{
   book : {
     title : payload.book.title,
     authors: payload.book.&author distinctBy $
   }
}
----

==== Input

[source,XML,linenums]
----
<book>
  <title> "XQuery Kick Start"</title>
  <author>James Linn</author>
  <author>Per Bothner</author>
  <author>James McGovern</author>
  <author>James McGovern</author>
  <author>James McGovern</author>
</book>
----

==== Output

[source,XML,linenums]
----
<book>
  <title> "XQuery Kick Start"</title>
  <authors>
      <author>James Linn</author>
      <author>Per Bothner</author>
      <author>James McGovern</author>
  </authors>
</book>
----
