= flatMap
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[flatmap1]]
== flatMap<T, R&#62;&#40;@StreamCapable items: Array<T&#62;, mapper: &#40;item: T, index: Number&#41; &#45;&#62; Array<R&#62;&#41;: Array<R&#62;

Iterates over each item in an array and flattens the results.


Instead of returning an array of arrays (as `map` does when you iterate over
the values within an input like `[ [1,2], [3,4] ]`), `flatMap` returns a
flattened array that looks like this: `[1, 2, 3, 4]`. `flatMap` is similar to
`flatten`, but `flatten` only acts on the values of the arrays, while
`flatMap` can act on values and indices of items in the array.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The array to map.
| `mapper` | Expression or selector for an `item` and/or `index` in the array to flatten.
|===

=== Example

This example returns an array containing each value in order. Though it names
the optional `index` parameter in its anonymous function
`(value, index) -> value`, it does not use `index` as a selector for the
output, so it is possible to write the anonymous function using
`(value) -> value`. You can also use an anonymous parameter for the
value to write the example like this: `[ [3,5], [0.9,5.5] ] flatMap &#36;`.
Note that this example produces the same result as
`flatten([ [3,5], [0.9,5.5] ])`, which uses `flatten`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
[ [3,5], [0.9,5.5] ] flatMap (value, index) -> value
----

==== Output

[source,JSON,linenums]
----
[ 3, 5, 0.9, 5.5]
----


[[flatmap2]]
== flatMap<T, R&#62;&#40;@StreamCapable value: Null, mapper: &#40;item: Nothing, index: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `flatMap` to work with a `null` value.

