= then
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[then1]]
== then&#40;value: Null, callback: &#40;previousResult: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `then` to work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._


[[then2]]
== then<T, R&#62;&#40;previous: T, callback: &#40;result: T&#41; &#45;&#62; R&#41;: R

This function works as a pipe that passes the value returned from the
preceding expression to the next (a callback) only if the value returned
by the preceding expression is not `null`.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `previous` | The value of the preceding expression.
| `callback` | Callback that processes the result of `previous` if the result is not `null`.
|===

=== Example

This example shows how to use `then` to chain and continue processing
the result of the previous expression.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
    "chainResult": ["mariano", "de Achaval"]
            reduce ((item, accumulator) -> item ++ accumulator)
            then ((result) -> sizeOf(result)),
    "referenceResult" : ["mariano", "de Achaval"]
                         map ((item, index) -> upper(item))
                         then {
                            name: $[0],
                            lastName: $[1],
                            length: sizeOf($)
                        },
    "onNullReturnNull": []
                reduce ((item, accumulator) -> item ++ accumulator)
                then ((result) -> sizeOf(result))
}
----

==== Output

[source,Json,linenums]
----
{
   "chainResult": 17,
   "referenceResult": {
     "name": "MARIANO",
     "lastName": "DE ACHAVAL",
     "length": 2
   },
   "onNullReturnNull": null
 }
----

