= mapObject
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[mapobject1]]
== mapObject<K, V&#62;&#40;@StreamCapable object: { &#40;K&#41;?: V }, mapper: &#40;value: V, key: K, index: Number&#41; &#45;&#62; Object&#41;: Object

Iterates over an object using a mapper that acts on keys, values, or
indices of that object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `object` | The object to map.
| `mapper` | Expression or selector that provides the `key`, `value`, or `index` used for mapping the specified object into an output object.
|===

=== Example

This example iterates over the input `{ "a":"b","c":"d"}` and uses the
anonymous mapper function (`(value,key,index) -> { (index) : { (value):key} }`)
to invert the keys and values in each specified object and to return the
indices of the objects as keys. The mapper uses named parameters to identify
the keys, values, and indices of the input object. Note that you can write
the same expression using anonymous parameters, like this:
`{"a":"b","c":"d"} mapObject { (&#36;&#36;&#36;) : { (&#36;):&#36;&#36;} }`

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{"a":"b","c":"d"} mapObject (value,key,index) -> { (index) : { (value):key} }
----

==== Output

[source,JSON,linenums]
----
{ "0": { "b": "a" }, "1": { "d": "c" } }
----

=== Example

This example increases each price by 5 and formats the numbers to always
include 2 decimals.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/xml
---
{
    prices: payload.prices mapObject (value, key) -> {
        (key): (value + 5) as Number {format: "##.00"}
    }
}
----

==== Input

[source,XML,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<prices>
    <basic>9.99</basic>
    <premium>53</premium>
    <vip>398.99</vip>
</prices>
----

==== Output

[source,XML,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<prices>
  <basic>14.99</basic>
  <premium>58.00</premium>
  <vip>403.99</vip>
</prices>
----


[[mapobject2]]
== mapObject&#40;value: Null, mapper: &#40;value: Nothing, key: Nothing, index: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `mapObject` to work with a `null` value.


=== Example

Using the previous example, you can test that if the input of the `mapObject`
is `null`, the output result is `null` as well. In XML `null` values are
written as empty tags. You can change these values by using the writer
property `writeNilOnNull=true`.

==== Input

[source,XML,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<prices>
</prices>
----

==== Output

[source,XML,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<prices>
</prices>
----

