= find
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[find1]]
== find<T&#62;&#40;@StreamCapable&#40;&#41; elements: Array<T&#62;, elementToFind: Any&#41;: Array<Number&#62;

Returns indices of an input that match a specified value.


This version of the function returns indices of an array. Others return
indices of a string.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `elements` | An array with elements of any type.
| `elementToFind` | Value to find in the input array.
|===

=== Example

This example finds the index of an element in a string array.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
["Bond", "James", "Bond"] find "Bond"
----

==== Output

[source,JSON,linenums]
----
[0,2]
----


[[find2]]
== find&#40;@StreamCapable&#40;&#41; text: String, matcher: Regex&#41;: Array<Array<Number&#62;&#62;

Returns the indices in the text that match the specified regular expression
(regex), followed by the capture groups.


The first element in each resulting sub-array is the index in the text that
matches the regex, and the next ones are the capture groups in the regex
(if present).

Note: To retrieve parts of the text that match a regex. use the `scan` function.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A string.
| `matcher` | A Java regular expression for matching characters in the `text`.
|===

=== Example

This example finds the beginning and ending indices of words that contain `ea`

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
"I heart DataWeave" find /\w*ea\w*(\b)/
----

==== Output

[source,JSON,linenums]
----
[ [2,7], [8,17] ]
----


[[find3]]
== find&#40;@StreamCapable&#40;&#41; text: String, textToFind: String&#41;: Array<Number&#62;

Lists indices where the specified characters of a string are present.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A source string.
| `textToFind` | The string to find in the source string.
|===

=== Example

This example lists the indices of "a" found in "aabccdbce".

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"aabccdbce" find "a"
----

==== Output

[source,JSON,linenums]
----
[0,1]
----


[[find4]]
== find&#40;@StreamCapable&#40;&#41; text: Null, textToFind: Any&#41;: Array<Nothing&#62;

Helper function that enables `find` to work with a `null` value.

