= Core Types (dw::Core)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

|===
a| Type a| Definition a| Description

a| Any
a| `type Any = Any`
a| The top-level type. `Any` extends all of the system types, which
means that anything can be assigned to a `Any` typed variable.


a| Array
a| `type Array = Array`
a| Array type that requires a `Type(T)` to represent the elements of the list.
Example: `Array<Number>` represents an array of numbers, and `Array<Any>`
represents an array of any type.


a| Binary
a| `type Binary = Binary`
a| A blob.


a| Boolean
a| `type Boolean = Boolean`
a| A `Boolean` type of `true` or `false`.


a| CData
a| `type CData = String {cdata: true}`
a| XML defines a `CData` custom type that extends from `String` and is used
to identify a CDATA XML block.

It can be used to tell the writer to wrap the content inside CDATA or to
check if the input string arrives inside a CDATA block. `:cdata` inherits
from the type `:string`.

*Source*

[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
{
  "users" :
  {
    "user" : "Mariano" as CData,
    "age" : 31 as CData
  }
}
----

*Output*

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<users>
  <user><![CDATA[Mariano]]></user>
  <age><![CDATA[31]]></age>
</users>
----


a| Comparable
a| `type Comparable = String &#124; Number &#124; Boolean &#124; DateTime &#124; LocalDateTime &#124; Date &#124; LocalTime &#124; Time &#124; TimeZone`
a| A union type that represents all the types that can be compared to each other.


a| Date
a| `type Date = Date`
a| A date represented by a year, month, and day. For example: `&#124;2018-09-17&#124;`


a| DateTime
a| `type DateTime = DateTime`
a| A `Date` and `Time` within a `TimeZone`. For example: `&#124;2018-09-17T22:13:00Z&#124;`


a| Dictionary
a| `type Dictionary = { _?: T }`
a| Generic dictionary interface.


a| Enum
a| `type Enum = String {enumeration: true}`
a| This type is based on the
https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html[Enum Java class].

It must always be used with the `class` property, specifying the full Java
class name of the class, as shown in the example below.

*Source*

[source,DataWeave, linenums]
----
%dw 2.0
output application/java
---
"Male" as Enum {class: "com.acme.GenderEnum"}
----


a| Iterator
a| `type Iterator = Array {iterator: true}`
a| This type is based on the
https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html[iterator Java class].
The iterator contains a collection and includes methods to iterate through
and filter it.

Just like the Java class, `Iterator` is designed to be consumed only once. For
example, if you pass it to a
https://docs.mulesoft.com/mule-runtime/4.1/logger-component-reference[Logger component],
the Logger consumes it, so it becomes unreadable by further elements in the flow.


a| Key
a| `type Key = Key`
a| A key of an `Object`.


a| LocalDateTime
a| `type LocalDateTime = LocalDateTime`
a| A `DateTime` in the current `TimeZone`. For example: `&#124;2018-09-17T22:13:00&#124;`


a| LocalTime
a| `type LocalTime = LocalTime`
a| A `Time` in the current `TimeZone`. For example: `&#124;22:10:18&#124;`


a| NaN
a| `type NaN = Null {NaN: true}`
a| `java.lang.Float` and `java.lang.Double` have special cases for `NaN` and `Infinit`.
DataWeave does not have these concepts for its number multi-precision nature.
So when it is mapped to DataWeave values, it is wrapped in a Null with a Schema marker.


a| Namespace
a| `type Namespace = Namespace`
a| A `Namespace` type represented by a `URI` and a prefix.


a| Nothing
a| `type Nothing = Nothing`
a| Bottom type. This type can be assigned to all the types.


a| Null
a| `type Null = Null`
a| A Null type.


a| Number
a| `type Number = Number`
a| A number type: Any number, decimal, or integer is represented by the Number` type.


a| Object
a| `type Object = Object`
a| Type that represents any object, which is a collection of `Key` and value pairs.


a| Period
a| `type Period = Period`
a| A period.


a| Range
a| `type Range = Range`
a| A `Range` type represents a sequence of numbers.


a| Regex
a| `type Regex = Regex`
a| A regex type.


a| SimpleType
a| `type SimpleType = String &#124; Boolean &#124; Number &#124; DateTime &#124; LocalDateTime &#124; Date &#124; LocalTime &#124; Time &#124; TimeZone &#124; Period`
a| A union type that represents all the simple types.


a| String
a| `type String = String`
a| These are the native types of DataWeave.

They are the only types that allow the `???` definition.


a| Time
a| `type Time = Time`
a| A time in a specific `TimeZone`. For example: `&#124;22:10:18Z&#124;`


a| TimeZone
a| `type TimeZone = TimeZone`
a| A time zone.


a| Type
a| `type Type = Type`
a| A type in the DataWeave type system.


a| Uri
a| `type Uri = Uri`
a| A URI.

|===
