= log
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[log1]]
== log&#40;String, T&#41;: T

Without changing the value of the input, `log` returns the input as a system
log.


Use this function to help with debugging DataWeave scripts. A Mule app
outputs the results through the `DefaultLoggingService`, which you can see
in the Studio console.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `prefix` | An optional string that typically describes the log.
| `value` | The value to log.
|===

=== Example

This example logs the specified message. Note that the `DefaultLoggingService`
in a Mule app that is running in Studio returns the message
`WARNING - "Houston, we have a problem," adding the dash `-` between the
prefix and value. The Logger component's `LoggerMessageProcessor` returns
the input string `"Houston, we have a problem."`, without the `WARNING` prefix.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
log("WARNING", "Houston, we have a problem.")
----

==== Output

[source,XML,linenums]
----
WARNING - "Houston, we have a problem."
----

