= toLocalDateTime
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[tolocaldatetime1]]
== toLocalDateTime&#40;str: String, format: String &#124; Null = null, locale: String &#124; Null = null&#41;: LocalDateTime

Transforms a `String` value into a `LocalDateTime` value
and accepts a format and locale.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `str` | The `String` value to transform into a `LocalDateTime` value.
| `format` | The formatting to use on the `LocalDateTime` value.
             A `null` value has no effect on the `LocalDateTime` value.
             This parameter accepts Java character patterns based
             on ISO-8601. A `LocalDateTime` value, such as
             `2011-12-03T10:15:30.000000` has
             the format `uuuu-MM-dd HH:mm:ss`.
| `locale` | Optional ISO 3166 country code to use, such as `US`,
             `AR`, or `ES`. A `null` or absent value uses your
             JVM default.
|===

=== Example

This example shows how `toLocalDateTime` behaves with different inputs.
It produces output in the `application/dw` format.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Coercions
output application/dw
---
{
  a: toLocalDateTime("2015-10-01T23:57:59"),
  b: toLocalDateTime("2003-10-01 23:57:59","uuuu-MM-dd HH:mm:ss")
}
----

==== Output

[source,DataWeave,linenums]
----
{
  a: |2015-10-01T23:57:59|,
  b: |2003-10-01T23:57:59| as LocalDateTime {format: "uuuu-MM-dd HH:mm:ss"}
}
----

