= filter
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[filter1]]
== filter&#40;Array<T&#62;, &#40;item: T, index: Number&#41; &#45;&#62; Boolean&#41;: Array<T&#62;

Iterates over an array and applies an expression that returns matching values.


The expression must return `true` or `false`. If the expression returns `true`
for a value or index in the array, the value gets captured in the output array.
If it returns `false` for a value or index in the array, that item gets
filtered out of the output. If there are no matches, the output array will
be empty.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `items` | The array to filter.
| `criteria` | Boolean expression that selects an `item` and/or `index`.
|===

=== Example

This example returns an array of values in the array that are greater than `2`.

==== Source

[source,DataWeave, linenums]
----
[9,2,3,4,5] filter (value, index) -> (value > 2)
----

==== Output

[source,JSON,linenums]
----
[9,3,4,5]
----

=== Example

This example returns an array of all values found at an index greater than `2`.

==== Source

[source,DataWeave, linenums]
----
[9,2,3,4,5] filter ((value, index) -> (index > 2))
----

==== Output

[source,JSON,linenums]
----
[4,5]
----

=== Example

This example returns an array of all items found at an index (`&#36;&#36;`)
greater than `1` where the value of the element is less than `5`. Notice that
it is using anonymous parameters as selectors instead of using named
parameters in an anonymous function.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
[9, 2, 3, 4, 5] filter (($$ > 1) and ($ < 5))
----

==== Output

[source,JSON,linenums]
----
[3,4]
----


=== Example

This example reads a JSON array that contains objects with `user` and `error` keys, and uses the `filter` function to return only the objects in which the value of the `error` key is `null`.


==== Source
[source,DataWeave, linenums]
----
%dw 2.0
output application/json

var users = [
   {
      "user": {
         "name": "123",
         "lastName": "Smith"
      },
      "error": "That name doesn't exists"
   },
   {
      "user": {
         "name": "John",
         "lastName": "Johnson"
      },
      "error": null
   }
]
---
users filter ((item, index) -> item.error == null)
----

==== Output
[source,JSON,linenums]
----
[
  {
    "user": {
      "name": "John",
      "lastName": "Johnson"
    },
    "error": null
  }
]
----

=== Example

This example reads a JSON array and uses the `filter` function to extract the phone numbers which are active.

==== Input
[source,JSON, linenums]
----
{
  "Id": "1184001100000000517",
  "marketCode": "US",
  "languageCode": "en-US",
  "profile": {
  "base": {
     "username": "TheMule",
     "activeInd": "R",
     "phone": [
       {
          "activeInd": "Y",
          "type": "mobile",
          "primaryInd": "Y",
          "number": "230678123"
       },
       {
         "activeInd": "N",
         "type": "mobile",
         "primaryInd": "N",
         "number": ""
       }
      ]
    }
  }
 }
----

==== DataWeave Script
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
    id: payload.Id,
    markCode: payload.marketCode,
    languageCode: payload.languageCode,
    username: payload.profile.base.username,
    phoneNumber: {(payload.profile.base.phone filter ($.activeInd == "Y" and $.primaryInd== "Y"))}.number default ""
}
----

==== Output
[source,JSON, linenums]
----
{
  "id": "1184001100000000517",
  "markCode": "US",
  "languageCode": "en-US",
  "username": "TheMule",
  "phoneNumber": "230678123"
}
----


[[filter2]]
== filter&#40;Null, &#40;item: Nothing, index: Nothing&#41; &#45;&#62; Boolean&#41;: Null

Helper function that enables `filter` to work with a `null` value.
