= &#45;&#45;
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[minusminus1]]
== &#45;&#45;&#40;Array<S&#62;, Array<Any&#62;&#41;: Array<S&#62;

Removes specified items from an array.


|===
| Name   | Description

| `source` | The source array whose items might be removed (an `Array` type). Can have repeating elements. 
| `toRemove` | The array of items from which to remove from the source array. Need not have repeating elements. 
|===

Note: The result of the `--` operator is the same as applying the `-` operators repeatedy to each element of the `toRemove` array. 

=== Example

This example removes some items from a source array.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "a" : [0, 1, 1, 2] -- [1,2] }
----

==== Output

[source,JSON,linenums]
----
{
  "a": [0]
}
----

Note: The result is the same as 
==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "a" : [0, 1, 1, 2] - 1 - 2 }
----

==== Output

[source,JSON,linenums]
----
{
  "a": [0]
}
----
[[minusminus2]]
== &#45;&#45;&#40;{ &#40;K&#41;?: V }, Object&#41;: { &#40;K&#41;?: V }

Removes key-value pairs from a source object (the first parameter) if the same key/value appears in the second parameter's object. 


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object whose key/values might be removed (of type `Object`).
| `toRemove` | The key/value pairs to remove from the source object (of type `Object`). The key/values in this second object to need not repeat; every matching key/value is removed from the source object. 
|===

Note: For a key/value to be removed from the source object, both the key and value must be identical, not just the key. 



[[minusminus2]]
== &#45;&#45;&#40;{ &#40;K&#41;?: V }, Object&#41;: { &#40;K&#41;?: V }
=== Example

This example removes a key-value pair from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "hello" : "world",
   "name" : "DW",
   "hello" : "world",
   "hello" : "there"
} -- { "hello" : "world"}
----

==== Output

[source,JSON,linenums]
----
{
   "name": "DW",
   "hello" : "there"
}
----


[[minusminus3]]
== &#45;&#45;&#40;Object, Array<String&#62;&#41;

Removes all key/values from the source object that match a key in the second parameter's array. 


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `toRemove` | Keys for the key-value pairs to remove from the source object.
|===

=== Example

This example removes two key-value pairs from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "yes" : "no",
   "yes" : "OK",
   "good" : "bad",
   "old" : "new"
} -- ["yes", "old"]
----

==== Output

[source,JSON,linenums]
----
{
   "good": "bad"
}
----


[[minusminus4]]
== &#45;&#45;&#40;Object, Array<Key&#62;&#41;

Removes specified key-value pairs from an object if the key is in the second parameter array.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `keys` | An array of keys to specify the key-value pairs to remove from the source object.
|===

=== Example

This example specifies the key to remove from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "hello" : "world",
   "name" : "DW"
 } -- ["hello" as Key]
----

==== Output

[source,JSON,linenums]
----
{
   "name": "DW"
}
----

