= reduce
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[[reduce1]]
== reduce(Array<T>, (item: T, accumulator: T) -> T): T | Null

Applies the reduction function for each element in the input array.


Note that if the array is empty and no default value is set on the
accumulator, a null value is returned.

== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `item` | Item in the given list. It provides the value to reduce. Can also be referenced as `&#36;`.
| `acc` | An accumulator (also referenced as `&#36;&#36;`) to apply to items in the input array. It starts with the first value of the array by default.
|===

== Example

This example returns the sum of the values in the input arrays.

=== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
 {
    "sum" : [0, 1, 2, 3, 4, 5] reduce ($$ + $),
    "sum" : [0, 1, 2, 3, 4, 5] reduce ((val, acc) -> acc + val)
 }
----

=== Output

[source,JSON,linenums]
----
{
  "sum": 15,
  "sum": 15
}
----

== Example

This example uses the accumulator to concatenate elements in the input
arrays and return the results in a string.

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
   "concat" : ["a", "b", "c", "d"] reduce ($$ ++ $),
   "concat" : ["a", "b", "c", "d"] reduce ((val, acc) -> acc ++ val)
}
----

=== Output

[source,JSON,linenums]
----
{
  "concat": "abcd",
  "concat": "abcd"
}
----

== Example

This example sets the first elements of the arrays to `"z"` and `3`.

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
   "concat" : ["a", "b", "c", "d"] reduce ((item, acc = "z") -> acc ++ item),
   "sum": [0, 1, 2, 3, 4, 5] reduce ((val, acc = 3) -> acc + val)
}
----

=== Output

[source,JSON,linenums]
----
{
  "concat": "zabcd"
  "sum": 18
}
----

== Example

This example shows a variety of uses of `reduce`, including its application to
arrays of boolean values and objects.

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
var in0 =
{
  "a": [0, 1, 2, 3, 4, 5],
  "b": ["a", "b", "c", "d", "e"],
  "c": [{ "letter": "a" }, { "letter": "b" }, { "letter": "c" }],
  "d": [true, false, false, true, true]
}
---
{
  "a" : [0, 1, 2, 3, 4, 5] reduce $$,
  "b": ["a", "b", "c", "d", "e"] reduce $$,
  "c": [{ "letter": "a" }, { "letter": "b" }, { "letter": "c" }] reduce ((val, acc = "z") -> acc ++ val.letter),
  "d": [{ letter: "a" }, { letter: "b" }, { letter: "c" }] reduce $$,
  "e": [true, false, false, true, true] reduce ($$ and $),
  "f": [true, false, false, true, true] reduce ((val, acc) -> acc and val),
  "g": [true, false, false, true, true] reduce ((val, acc = false) -> acc and val),
  "h": [true, false, false, true, true] reduce $$,
  "i": in0.a reduce ($$ + $),
  "j": in0.a reduce ((val, acc) -> acc + val),
  "k": in0.a reduce ((val, acc = 3) -> acc + val),
  "l": in0.a reduce $$,
  "m": in0.b reduce ($$ ++ $),
  "n": in0.b reduce ((val, acc) -> acc ++ val),
  "o": in0.b reduce ((val, acc = "z") -> acc ++ val),
  "p": in0.b reduce $$,
  "q": in0.c reduce ((val, acc = "z") -> acc ++ val.letter),
  "r": in0.c reduce $$,
  "s": in0.d reduce ($$ and $),
  "t": in0.d reduce ((val, acc) -> acc and val),
  "u": in0.d reduce ((val, acc = false) -> acc and val),
  "v": in0.d reduce $$,
  "w": ([0, 1, 2, 3, 4] reduce ((val, acc = {}) -> acc ++ { a: val })) pluck $,
  "x": [] reduce $$,
  "y": [] reduce ((val,acc = 0) -> acc + val)
}
----

=== Output

[source,JSON,linenums]
----
"a": 0,
"b": "a",
"c": "zabc",
"d": { "letter": "a" },
"e": false,
"f": false,
"g": false,
"h": true,
"i": 15,
"j": 15,
"k": 18,
"l": 0,
"m": "abcde",
"n": "abcde",
"o": "zabcde",
"p": "a",
"q": "zabc",
"r": { "letter": "a" },
"s": false,
"t": false,
"u": false,
"v": true,
"w": [ 0,1,2,3,4 ],
"x": null,
"y": 0
}
----


[[reduce2]]
== reduce(Array<T>, (item: T, accumulator: A) -> A): A
