= orderBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[orderby1]]
== orderBy(O, (value: V, key: K) -> R): O

Reorders the content of an object using a value returned by a function as the criteria.


Note that you can reference the index with `&#36;&#36;` and the value with `&#36;`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `object` | The object to reorder.
| `criteria` | The result of the function is used as the criteria to reorder the object.
|===

=== Example

This example alphabetically orders the values of each object in the array.
Note that `orderBy($.letter)` produces the same result as orderBy($[0]).

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
orderByLetter: [{ letter: "d" }, { letter: "e" }, { letter: "c" }, { letter: "a" }, { letter: "b" }] orderBy($.letter)
----

==== Output

[source,JSON,linenums]
----
{
  "orderByLetter": [
    {
      "letter": "a"
    },
    {
      "letter": "b"
    },
    {
      "letter": "c"
    },
    {
      "letter": "d"
    },
    {
      "letter": "e"
    }
  ]
}
----

=== Example

To invert the order of the resulting array from ascending to descending, simply use `-`, for example:

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
orderDescending: ([3,8,1] orderBy -$)
----

==== Output

[source,JSON,linenums]
----
{ "orderDescending": [8,3,1] }
----


[[orderby2]]
== orderBy(Array<T>, (item: T, index: Number) -> R): Array<T>

Sorts an array using the specified criteria.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `array` | The list (an array) to sort.
| `criteria` | The result of the function will be used as the criteria to sort the list. It should return a simple value (String, Number, etc)
|===

=== Example

This example sorts an array of numbers based on the numeric values.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[3,2,3] orderBy $
----

==== Output

[source,JSON,linenums]
----
[
  2,
  3,
  3
]
----

=== Example

This example sorts an array of people based on their age.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[{name: "Santiago", age: 42},{name: "Leandro", age: 29}, {name: "Mariano", age: 35}] orderBy (person) -> person.age
----

==== Output

[source,JSON,linenums]
----
[
  {
    name: "Leandro",
    age: 29
  },
  {
    name: "Mariano",
    age: 35
  },
  {
    name: "Santiago",
    age: 42
  }
]
----


[[orderby3]]
== orderBy(Null, (item: Nothing, index: Nothing) -> Null): Null

Helper function that allows *orderBy* to work with null values.
