= match
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[match1]]
== match(String, Regex): Array<String>

Uses an regular expression to match string and then separate it into capture
groups. Returns the results in a a list (an array).


It can be applied to the result of any evaluated expression and can return
any evaluated expression. See
https://docs.mulesoft.com/mule-runtime/4.1/dataweave-pattern-matching[Pattern Matching in DataWeave].

== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A string (`String` type).
| `matcher` | A regular expression for matching characters in the `text`.
|===

== Example

In this example, the regular expression describes an email address. It
contains two capture groups: what come before and after the `@`. The
result is an array of three elements: the first is the whole email address,
the second matches one of the capture groups, the third matches the other one.

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "hello" : "anniepoint@mulesoft.com" match(/([a-z]*)@([a-z]*).com/) }
----

=== Output

[source,JSON,linenums]
----
{
  "hello": [
    "anniepoint@mulesoft.com",
    "anniepoint",
    "mulesoft"
  ]
}
----
