= map
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

//* <<map1>>
//* <<map2>>


[[map1]]
== map(Array<T>, (item: T, index: Number) -> R): Array<R>

Iterates over each item in an array and returns the array of items that
results from applying a transformation function to the elements.

The function (a lambda) is invoked with the `value` and the `index` parameters.
In the following example, custom names are defined for these parameters. Then
both are used to construct the returned value. In this case, value is defined
as `firstName`, and its index is defined as `position`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
users: ['john', 'peter', 'matt'] map ((firstName, position) -> position ++ ':' ++ upper(firstName))
----

.Output
[source,json,linenums]
----
{
  'users': [
    '0:JOHN',
    '1:PETER',
    '2:MATT'
  ]
}
----

If the parameters to `map` are not named, the index is defined by default as
`&#36;&#36;`, and the value is `&#36;`. The next example produces the same output as the
script above. Note that the selector for the key in the next example must be
surrounded by parentheses (for example, `(&#36;&#36;)`).

.Transform
----
%dw 2.0
output application/json
---
users: ['john', 'peter', 'matt'] map (($$) ++ ':' ++ upper($))
----

This next transformation script produces an array of objects from an input
array.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
payload.users map { ($$) : upper($) }
----

.Input
----
{ 'users' : ['fer', 'steven', 'lorraine', 'george'] }
----

.Output
[source,json,linenums]
----
[
  {
    '0': 'FER'
  },
  {
    '1': 'STEVEN'
  },
  {
    '2': 'LORRAINE'
  },
  {
    '3': 'GEORGE'
  }
]
----



[[map2]]
== map(Null, (Nothing, Nothing) -> Boolean): Null

Helper function that allows `map` to work with null values.