= sizeOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[sizeof1]]
== sizeOf&#40;array: Array<Any&#62;&#41;: Number

Returns the number of elements in an array. It returns `0` if the array
is empty.


This version of `sizeOf` takes an array or an array of arrays as input.
Other versions act on arrays of objects, strings, or binary values.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `array` | The input array. The elements in the array can be any supported type.
|===

=== Example

This example counts the number of elements in the input array. It returns `3`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf([ "a", "b", "c"])
----

==== Output

[source,JSON,linenums]
----
3
----

=== Example

This example returns a count of elements in the input array.

==== Source
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  "arraySizes": {
     size3: sizeOf([1,2,3]),
     size2: sizeOf([[1,2,3],[4]]),
     size0: sizeOf([])
   }
}
----

==== Output
[source,JSON,linenums]
----
{
   "arraySizes": {
     "size3": 3,
     "size2": 2,
     "size0": 0
   }
}
----


[[sizeof2]]
== sizeOf&#40;object: Object&#41;: Number

Returns the number of key-value pairs in an object.


This function accepts an array of objects. Returns `0` if the input object is
empty.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `object` | The input object that contains one or more key-value pairs.
|===

=== Example

This example counts the key-value pairs in the input object, so it returns `2`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf({a: 1, b: 2})
----

==== Output

[source,JSON,linenums]
----
2
----

=== Example

This example counts the key-value pairs in an object.

==== Source
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
   objectSizes : {
     sizeIs2: sizeOf({a:1,b:2}),
     sizeIs0: sizeOf({})
   }
}
----

==== Output
[source,JSON,linenums]
----
{
  "objectSize": {
    "sizeIs2": 2,
    "sizeIs0": 0
  }
}
----


[[sizeof3]]
== sizeOf&#40;binary: Binary&#41;: Number

Returns the number of elements in an array of binary values.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `binary` | The input array of binary values.
|===

=== Example

This example returns the size of an array of binary values.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf(["\u0000" as Binary, "\u0001" as Binary, "\u0002" as Binary])
----

==== Output

[source,JSON,linenums]
----
3
----


[[sizeof4]]
== sizeOf&#40;text: String&#41;: Number

Returns the number of characters (including white space) in an string.


Returns `0` if the string is empty.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The input text.
|===

=== Example

This example returns the number of characters in the input string `"abc"`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sizeOf("abc")
----

==== Output

[source,JSON,linenums]
----
3
----

=== Example

This example returns the number of characters in the input strings. Notice it
counts blank spaces in the string `"my string"` and that
`sizeOf("123" as Number)` returns `1` because `123` is coerced into a number,
so it is not a string.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  sizeOfSting2 : sizeOf("my string"),
  sizeOfEmptyString: sizeOf(""),
  sizeOfNumber : sizeOf("123" as Number)
}
----

==== Output

[source,JSON,linenums]
----
{
  "sizeOfSting2": 9,
  "sizeOfEmptyString": 0,
  "sizeOfNumber": 1
}
----


[[sizeof5]]
== sizeOf&#40;n: Null&#41;: Null

Helper function that enables `sizeOf` to work with a `null` value.

