= log
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[log1]]
== log&#40;String, T&#41;: T

Without changing the value of the input, `log` returns the input as a system
log.

This function can be used to debug DataWeave scripts until a proper
debugger is incorporated. The Logger component outputs the results
through `DefaultLoggingService` through the Logger component

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `prefix` | A string that typically describes the log.
| `value` | The value to log.
|===

=== Example

This example logs the specified message. The `DefaultLoggingService` for the
Logger component returns the message
`WARNING - "Houston, we have a problem."` In
the console, while the component's `LoggerMessageProcessor` simply returns
`"Houston, we have a problem."`, without the `WARNING` prefix.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
"WARNING" log("Houston, we have a problem.")
----

==== Output

[source,XML,linenums]
----
WARNING - "Houston, we have a problem."
----

