= find
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[find1]]
== find(Array<T>, Any): Array<Number>

Returns the indices of an input array if a specified `elementToFind` is present.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `elements` | An array (`Array` type).
| `elementToFind` | Value to find in the source array.
|===

=== Example

This example finds the index of an element in a string array.

==== Source

[source,DataWeave,lineums]
----
%dw 2.0
output application/json
---
["Bond", "James", "Bond"] find "Bond"
----

==== Output

[source,JSON,linenums]
----
[0,2]
----


[[find2]]
== find(String, Regex): Array<Array<Number>>

Returns the indices in the text that match the specified regex (followed by the capture groups).


The first element in each resulting sub-array is the index in the text that
matched the regex, and the next ones are the capture groups in the regex
(if present).

Note: To retrieve parts of the text that match a regex use the scan function.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A string (`String` type).
| `matcher` | A regular expression for matching characters in the `text`.
|===

=== Example

This example finds the beginning and ending indices of words that contain `ea`

==== Source

[source,DataWeave,lineums]
----
%dw 2.0
output application/json
---
"I heart DataWeave" find /\w*ea\w*(\b)/
----

==== Output

[source,JSON,linenums]
----
[
   [2,7], [8,17]
]
----


[[find3]]
== find(String, String): Array<Number>

Lists indices where the specified characters of a string are present.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A source string.
| `textToFind` | The string to find in the source string.
|===

=== Example

This example lists the indices of "a" found in "aabccdbce".

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"aabccdbce" find "a"
----

==== Output

[source,JSON,linenums]
----
[0,1]
----
