= contains
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[contains1]]
== contains&#40;Array<T&#62;, Any&#41;: Boolean

Returns `true` if a list (array) contains a given value, `false` if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The input list (an `Array`).
| `elements` | An element to find in the list. Can be any supported data type.
|===

=== Example

This example indicates whether the input list contains '"3"'.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
ContainsRequestedItem: payload.root.*order.*items contains "3"
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <order>
      <items>155</items>
    </order>
    <order>
      <items>30</items>
    </order>
    <order>
      <items>15</items>
    </order>
    <order>
      <items>5</items>
    </order>
    <order>
      <items>4</items>
      <items>7</items>
    </order>
    <order>
      <items>1</items>
      <items>3</items>
    </order>
    <order>
        null
    </order>
</root>
----

==== Output

[source,JSON,linenums]
----
{
  "ContainsRequestedItem": true
}
----


[[contains2]]
== contains&#40;String, String&#41;: Boolean

Indicates whether a string contains a given substring. Returns `true`
or `false`.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | An input string (a `String`).
| `toSearch` | The substring (a `String`) to find in the input string.
|===

=== Example

This example finds the substring `"me"` in `"some string"`, so it returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "ContainsString" : payload.root.mystring contains "me" }
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <mystring>some string</mystring>
</root>
----

==== Output

[source,JSON,linenums]
----
{ "ContainsString": true }
----


[[contains3]]
== contains&#40;String, Regex&#41;: Boolean

Returns `true` if a string contains a match to a regular expression, `false`
if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | An input string (`String` type).
| `matcher` | A regular expression for matching characters in the input `text`.
|===

=== Example

This example finds a match to `/s[t|p]rin/` within `"A very long string"`,
so it returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
ContainsString: payload.root.mystring contains /s[t|p]rin/
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <mystring>A very long string</mystring>
</root>
----

==== Output

[source,JSON,linenums]
----
{
  "ContainsString": true
}
----

