= keysOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[keysof1]]
== keysOf<T <: Object&#62;&#40;obj: T&#41;: ?

Returns an array of keys from key-value pairs within the input object.


The returned keys belong to the Key type. To return each key as a string, you can use `namesOf`, instead.

_Introduced in DataWeave 2.3.0. Supported by Mule 4.3 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `object` | The object to evaluate.
|===

=== Example

This example returns the keys from the key-value pairs within the input object.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "keysOf" : keysOf({ "a" : true, "b" : 1}) }
----

==== Output

[source,JSON,linenums]
----
{ "keysOf" : ["a","b"] }
----

=== Example

This example illustrates a difference between `keysOf` and `namesOf`.
Notice that `keysOf` retains the attributes (`name` and `lastName`)
and namespaces (`xmlns`) from the XML input, while `namesOf` returns
`null` for them because it does not retain them.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
var myVar = read('<users xmlns="http://test.com">
                     <user name="Mariano" lastName="Achaval"/>
                     <user name="Stacey" lastName="Duke"/>
                  </users>', 'application/xml')
output application/json
---
{ keysOfExample: flatten([keysOf(myVar.users) map $.#,
                          keysOf(myVar.users) map $.@])
}
++
{ namesOfExample: flatten([namesOf(myVar.users) map $.#,
                    namesOf(myVar.users) map $.@])
}
----

==== Output

[source,JSON,linenums]
----
{
  "keysOfExample": [
    "http://test.com",
    "http://test.com",
    {
      "name": "Mariano",
      "lastName": "Achaval"
    },
    {
      "name": "Stacey",
      "lastName": "Duke"
    }
  ],
  "namesOfExample": [
    null,
    null,
    null,
    null
  ]
}
----


[[keysof2]]
== keysOf&#40;obj: Null&#41;: Null

Helper function that enables `keysOf` to work with a `null` value.

