= splitBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

//* <<splitby1>>
//* <<splitby2>>


[[splitby1]]
== splitBy(String, Regex): Array<String>

Splits a string into an array of separate elements. The function takes a
regular expression to identify some portion of that string, and if it finds
a match, uses the match as separator. `splitBy` performs the opposite
operation of `joinBy`.

Using the regular expression `\^&#36;.|?*+()-`, the following example finds the
the hyphen (`-`) in the input string (`a-b-c`), so it uses the hyphen as
a separator.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
split: "a-b-c" splitBy(/\^$.|?*+()-/)
----

.Output
[source,json,linenums]
----
{
  "split": ["a","b","c"]
}
----


[[splitby2]]
== splitBy(String, String): Array<String>

Splits a string into an array of separate elements. The function takes a
another string to look for some portion of the input string, and if it finds
a match, uses the match as separator. `splitBy` performs the opposite
operation of `joinBy`.

The following example uses the hyphen (`-`) as the separator, but the
separator could be any other character in the input, such as `splitBy("b")`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
split: "a-b-c" splitBy("-")
----

.Output
[source,json,linenums]
----
{
  "split": ["a", "b", "c"]
}
----