= isEmpty
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[isempty1]]
== isEmpty&#40;Array<Any&#62;&#41;: Boolean

Returns `true` if the given list (array) is empty, `false` if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `elements` | The list (an array) to evaluate.
|===

=== Example

This example indicates whether the input array is empty.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "empty" : isEmpty([]),
  "nonEmpty" : isEmpty([1])
}
----

==== Output

[source,JSON,linenums]
----
{
   "empty": true,
   "nonEmpty": false
}
----


[[isempty2]]
== isEmpty&#40;String&#41;: Boolean

Returns `true` if the given string is empty, `false` if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | A string to evaluate.
|===

=== Example

This example indicates whether the input strings are empty.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "empty" : isEmpty(""),
  "nonEmpty" : isEmpty("DataWeave")
}
----

==== Output

[source,JSON,linenums]
----
  {
    "empty": true,
    "nonEmpty": false
  }
----


[[isempty3]]
== isEmpty&#40;Null&#41;: Boolean

Returns `true` if the input is `null`.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | `Null` is the value in this case.
|===

=== Example

This example indicates whether the input is `null`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "null" : isEmpty(null)
}
----

==== Output

[source,JSON,linenums]
----
{
  "null": true
}
----


[[isempty4]]
== isEmpty&#40;Object&#41;: Boolean

Returns `true` if the given object is empty, `false` if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | The object to evaluate.
|===

=== Example

This example indicates whether the input object is empty.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "empty" : isEmpty({}),
  "nonEmpty" : isEmpty({name: "DataWeave"})
}
----

==== Output

[source,JSON,linenums]
----
  {
    "empty": true,
    "nonEmpty": false
  }
----

