= toDateTime
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[todatetime1]]
== toDateTime&#40;number: Number, unit: MillisOrSecs &#124; Null = null&#41;: DateTime

Transform the given number into a DateTime using the given unit :"milliseconds" or "seconds"

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| number | The number of millis or secs
| unit | The unit if null "seconds" is the default
|===

=== Example

This example shows how the `toDateTime` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/dw

import toDateTime from dw::util::Coercions
---
{
    fromEpoch: toDateTime(1443743879),
    fromMillis: toDateTime(1443743879000, "milliseconds"),
}

----

==== Output

[source,DataWeave,linenums]
----
 {
     fromEpoch: |2015-10-01T23:57:59Z|,
     fromMillis: |2015-10-01T23:57:59Z|
 }
----


[[todatetime2]]
== toDateTime&#40;str: String, format: String &#124; Null = null, locale: String &#124; Null = null&#41;: DateTime

Transforms a String into a DateTime using the given format

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| str | The string to transform
| format | The format to be used
| locale | The locale of the format
|===

=== Example

This example shows how the `toDateTime` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toDateTime from dw::util::Coercions
output application/dw
---
{
   a: toDateTime("2015-10-01T23:57:59Z"),
   b: toDateTime("2003-10-01 23:57:59Z","yyyy-MM-dd HH:mm:ssz"),
}
----

==== Output

[source,DataWeave,linenums]
----
{
   a: |2015-10-01T23:57:59Z|,
   b: |2003-10-01T23:57:59Z| as DateTime {format: "yyyy-MM-dd HH:mm:ssz"},
 }
----

