= splitBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[splitby1]]
== splitBy&#40;text: String, regex: Regex&#41;: Array<String&#62;

Splits a string into a string array based on a value that matches part of that
string. It filters out the matching part from the returned array.


This version of `splitBy` accepts a Java regular expression (regex) to
match the input string. The regex can match any character in the input
string. Note that `splitBy` performs the opposite operation of `joinBy`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The input string to split.
| `regex` | A Java regular expression used to split the string. If it does not match some part of the string, the function will return the original, unsplit string in the array.
|===

=== Example

This example uses a Java regular expression to split an address block by the
periods and forward slash in it. Notice that the regular expression goes
between forward slashes.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"192.88.99.0/24" splitBy(/[.\/]/)
----

==== Output

[source,JSON,linenums]
----
["192", "88", "99", "0", "24"]
----

=== Example

This example uses several regular expressions to split input strings. The
first uses `\/^*.b./\` to split the string by `-b-`. The second uses `/\s/`
to split by a space. The third example returns the original input string in
an array (`[ "no match"]`) because the regex `/^s/` (for matching the first
character if it is `s`) does not match the first character in the input
string (`"no match"`). The fourth, which uses `/^n../`, matches the first
characters in `"no match"`, so it returns `[ "", "match"]`. The last removes
all numbers and capital letters from a string, leaving each of the lower case
letters in the array. Notice that the separator is omitted from the output.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "splitters" : {
   "split1" : "a-b-c" splitBy(/^*.b./),
   "split2" : "hello world" splitBy(/\s/),
   "split3" : "no match" splitBy(/^s/),
   "split4" : "no match" splitBy(/^n../),
   "split5" : "a1b2c3d4A1B2C3D" splitBy(/^*[0-9A-Z]/)
  }
}
----

==== Output

[source,JSON,linenums]
----
{
  splitters: {
    split1: [ "a", "c" ],
    split2: [ "hello", "world" ],
    split3: [ "no match" ],
    split4: [ "", "match" ],
    split5: [ "a", "b", "c", "d" ]
  }
}
----


[[splitby2]]
== splitBy&#40;text: String, separator: String&#41;: Array<String&#62;

Splits a string into a string array based on a separating string that matches
part of the input string. It also filters out the matching string from the
returned array.


The separator can match any character in the input. Note that `splitBy` performs
the opposite operation of `joinBy`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to split.
| `separator` | A string used to separate the input string. If it does not match some part of the string, the function will return the original, unsplit string in the array.
|===

=== Example

This example splits a string containing an IP address by its periods.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"192.88.99.0" splitBy(".")
----

==== Output

[source,JSON,linenums]
----
["192", "88", "99", "0"]
----

=== Example

The first example (`splitter1`) uses a hyphen (`-`) in `"a-b-c"` to split the
string. The second uses an empty string (`""`) to split each character
(including the blank space) in the string. The third example splits based
on a comma (`,`) in the input string. The last example does not split the
input because the function is case sensitive, so the upper case `NO` does not
match the lower case `no` in the input string.  Notice that the separator is
omitted from the output.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "splitters" : {
    "split1" : "a-b-c" splitBy("-"),
    "split2" : "hello world" splitBy(""),
    "split3" : "first,middle,last" splitBy(","),
    "split4" : "no split" splitBy("NO")
   }
}
----

==== Output

[source,JSON,linenums]
----
{
  splitters: {
    split1: [ "a","b","c" ],
    split2: [ "h","e","l","l","o","","w","o","r","l","d" ],
    split3: [ "first","middle","last"],
    split4: [ "no split"]
  }
}
----


[[splitby3]]
== splitBy&#40;text: Null, separator: Any&#41;

Helper function that enables `splitBy` to work with a `null` value.

