= toNumber
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[tonumber1]]
== toNumber&#40;dateTime: DateTime, unit: MillisOrSecs &#124; Null = null&#41;: Number

Transforms a DateTime into a the Number of seconds or milliseconds depending in the specified unit.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The datetime to be used
| unit | The unit ("milliseconds" | "seconds") if null "seconds" will be used
|===

=== Example

This example shows how the `toNumber` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toNumber from dw::util::Coercions
output application/json
---
{
    epoch: toNumber(|2015-10-01T23:57:59Z|),
    millis: toNumber(|2015-10-01T23:57:59Z|, "milliseconds"),
}

----

==== Output

[source,DataWeave,linenums]
----
 {
    epoch: 1443743879,
    millis: 1443743879000
 }
----


[[tonumber2]]
== toNumber&#40;period: Period, unit: PeriodUnits &#124; Null = null&#41;: Number

Transforms the given Period into a Number using the specified unit : "hours",  "minutes" , "seconds" , "milliseconds" or "nanos"

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| period | The period to be converted
| unit | The unit to be used
|===

=== Example

This example shows how the `toNumber` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toNumber from dw::util::Coercions
output application/json
---
{
    toSeconds: toNumber(|PT1H10M|, "seconds")
}

----

==== Output

[source,Json,linenums]
----
 {
  "toSeconds": 4200
 }
----


[[tonumber3]]
== toNumber&#40;value: String &#124; Key, format: String &#124; Null = null, locale: String &#124; Null = null&#41;: Number

Transforms the specified String into a Number.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| value |
| format |
| locale |
|===

=== Example

This example shows how the `toNumber` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toNumber from dw::util::Coercions
output application/json
---
 {
     "default": toNumber("1.0"),
     withFormat: toNumber("0.005",".00"),
     withLocale: toNumber("0,035","#.##","ES"),
 }

----

==== Output

[source,Json,linenums]
----
{
   "default": 1.0,
   "withFormat": 0.005,
   "withLocale": 0.035
}
----

