= readUrl
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[readurl1]]
== readUrl&#40;String, String, Object&#41;

Similar to the `read` function. However, `readURL` accepts a URL, including
a classpath-based URL.


The classpath-based URL uses the `classpath:`` protocol prefix, for example,
`classpath://myfolder/myFile.txt` where `myFolder` is located under
`src/main/resources` in a Mule project. Otherwise, `readURL` accepts
the same arguments as `read`.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `url` | The URL string to read. It also accepts a classpath-based URL.
| `contentType` | A supported format (or mime type). Default: `application/dw`.
| `readerProperties` | Optional: Sets reader configuration properties. For other formats and reader configuration properties, see https://docs.mulesoft.com/mule-runtime/4.1/dataweave-formats[Formats Supported by DataWeave].
|===

=== Example

This example reads a JSON object from a URL. (For readability, the output
values shown below are shortened with `...`.)

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
readUrl("https://jsonplaceholder.typicode.com/posts/1", "application/json")
----

==== Output

[source,JSON,linenums]
----
{ "userId": 1, "id": 1, "title": "sunt aut ...", "body": "quia et ..." }
----

=== Example

This example reads a JSON object from a `myJsonSnippet.json` file located in
the `src/main/resources` directory in Studio. (Sample JSON content for that
file is shown in the Input section below.) After reading the file contents,
the script transforms selected fields from JSON to CSV. Reading files
in this way can be useful when trying out a DataWeave script on sample data,
especially when the source data is large and your script is complex.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
var myJsonSnippet = readUrl("classpath://myJsonSnippet.json", "application/json")
fun reduceMapFor(data) = data reduce (($$ splitBy ":") ++ "," ++ ($ splitBy ":"))
output application/csv
---
(myJsonSnippet.results map(item) -> item.profile)
----

==== Input

[source,JSON,linenums]
----
{
  "results": [
    {
      "profile": {
        "firstName": "john",
        "lastName": "doe",
        "email": "johndoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "digital-strategy:Digital Strategy",
              "innovation:Innovation"
            ],
            "contenttypes": []
          }
        ]
      }
    },
    {
      "profile": {
      "firstName": "jane",
        "lastName": "doe",
        "email": "janedoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "tax-reform:Tax Reform",
              "retail-health:Retail Health"
            ],
            "contenttypes": [
              "News",
              "Analysis",
              "Case studies",
              "Press releases"
            ]
          }
        ]
      }
    }
  ]
}
----

==== Output

[source,CSV,linenums]
----
firstName,lastName,email
john,doe,johndoe@demo.com
jane,doe,janedoe@demo.com
----

