= lastIndexOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[lastindexof1]]
== lastIndexOf&#40;array: Array, value: Any&#41;: Number

Returns the index of the _last_ occurrence of the specified element in this Array, or -1 if this list does not contain the element.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| array | The array of elements where to search
| value | The value to search
|===

=== Example

This example shows how the `indexOf` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: ["a","b","c","d"] lastIndexOf "c",
  notPresent: ["x","w","x"] lastIndexOf "c",
  presentMoreThanOnce: ["a","b","c","c"] lastIndexOf "c",
}
----

==== Output

[source,Json,linenums]
----
{
   "present": 2,
   "notPresent": -1,
   "presentMoreThanOnce": 4
 }
----


[[lastindexof2]]
== lastIndexOf&#40;array: String, value: String&#41;: Number

Returns the index of the *last* occurrence of the specified String in this String.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| theString | The String where to search.
| search | The String to search.
|===

=== Example

This example shows how the `indexOf` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: "abcd" lastIndexOf "c",
  notPresent: "xyz" lastIndexOf "c",
  presentMoreThanOnce: "abcdc" lastIndexOf "c",
}

----

==== Output

[source,Json,linenums]
----
{
  "present": 2,
  "notPresent": -1,
  "presentMoreThanOnce": 4
}
----


[[lastindexof3]]
== lastIndexOf&#40;array: Null, value: Any&#41;: Number

Helper function that makes it *Null* friendly.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

