= isLeapYear
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[isleapyear1]]
== isLeapYear&#40;dateTime: DateTime&#41;: Boolean

Returns `true` if it receives a date for a leap year, `false` if not.


This version of `leapYear` acts on a `DateTime` type. Other versions act on
the other date and time formats that DataWeave supports.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` | The `DateTime` value to evaluate.
|===

=== Example

This example indicates whether the input is a leap year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[ isLeapYear(|2016-10-01T23:57:59|), isLeapYear(|2017-10-01T23:57:59|) ]
----

==== Output

[source,JSON,linenums]
----
[ true, false ]
----


[[isleapyear2]]
== isLeapYear&#40;date: Date&#41;: Boolean

Returns `true` if the input `Date` is a leap year, 'false' if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `date` | The `Date` value to evaluate.
|===

=== Example

This example indicates whether the input is a leap year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[ isLeapYear(|2016-10-01|), isLeapYear(|2017-10-01|) ]
----

==== Output

[source,JSON,linenums]
----
[ true, false ]
----


[[isleapyear3]]
== isLeapYear&#40;datetime: LocalDateTime&#41;: Boolean

Returns `true` if the input local date-time is a leap year, 'false' if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `datetime` | A `LocalDateTime` value to evaluate.
|===

=== Example

This example indicates whether the input is a leap year. It uses a `map`
function to iterate through the array of its `LocalDateTime` values,
applies the `isLeapYear`  to those values, returning the results in an array.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[ |2016-10-01T23:57:59-03:00|, |2016-10-01T23:57:59Z| ] map isLeapYear($)
----

==== Output

[source,JSON,linenums]
----
[ true, true ]
----

