= groupBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[groupby1]]
== groupBy(Array<T>, (item: T, index: Number) -> R): { &#40;R&#41;: Array<T> }

Classifies the elements of a list (array) using the specified `criteria` function.

This function returns an object containing the grouping criteria as keys.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The list (`Array` type) to classify in groups.
| `criteria` | Function that receives the `item` and `index` of the element to group and should return the criteria to group by.
|===

=== Example

This example groups the elements of an array based on the language field.
Notice that it uses the `item.language` selector to specify the criteria.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
payload groupBy (item) -> item.language
----

==== Input

[source,JSON,linenums]
----
[
    {
      "name": "Foo",
      "language": "Java"
    },
    {
      "name": "Bar",
      "language": "Scala"
    },
    {
      "name": "FooBar",
      "language": "Java"
    }
]
----

==== Output

[source,JSON,linenums]
----
{
  "Scala": [
    {
      "name": "Bar",
      "language": "Scala"
    }
  ],
  "Java": [
    {
      "name": "Foo",
      "language": "Java"
    },
    {
      "name": "FooBar",
      "language": "Java"
    }
  ]
}
----


[[groupby2]]
== groupBy({ (K)?: V }, (value: V, key: K) -> R): { &#40;R&#41;: Array<T> }

Groups elements of an object based on an input key.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `object` | The object containing the elements to group.
| `criteria` | The `key` and/or `value` of the object to use for grouping.
|===


=== Example

The example groups an object based on its value (`$$`).

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "a" : "b"} groupBy $
----

==== Output

[source,JSON,linenums]
----
{
  "b": {
    "a": "b"
  }
}
----


[[groupby3]]
== groupBy(Null, (Nothing, Nothing) -> Any): Null

Helper function that allows *groupBy* to work with null values.
