= replace
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


[[replace1]]
== replace(String, Regex): ((Array<String>, Number) -> String) -> String

Replaces the part of a string that matches a regular expression and requires
the use of `with` to specify the replacement.

== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A string (`String` type).
| `matcher` | A regular expression for matching characters in the `text`.
|===

== Example

This example replaces the numbers at the end of a string with different
characters. Note that you can also use this notation
`replace(text,matcher) with string` (for example,
`replace("admin123", /(\d+)/) with("ID")`).

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "replace" : "admin123" replace /(\d+)/ with "ID" }
----

=== Output

[source,JSON,linenums]
----
{
  "replace": "adminID"
}
----


[[replace2]]
== replace(String, String): ((Array<String>, Number) -> String) -> String

Replaces part of a string with another string.


== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | A string (`String` type).
| `matcher` | A string (`String` type) for matching characters in the `text`.
|===

== Example

This example replaces the numbers at the end of a string with different
characters.

=== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "replace": "admin123" replace "123" with "ID" }
----

=== Output

[source,JSON,linenums]
----
{
  "replace": "adminID"
}
----
