= &#45;&#45;
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[minusminus1]]
== &#45;&#45;&#40;Array<S&#62;, Array<Any&#62;&#41;: Array<S&#62;

Removes specified items from a list (an array).


|===
| Name   | Description

| `source` | The list (an `Array` type).
| `toRemove` | Items to remove from the list.
|===

=== Example

This example removes a items from a list.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "a" : [0, 1, 1, 2] -- [1,2] }
----

==== Output

[source,JSON,linenums]
----
{
  "a": [0]
}
----


[[minusminus2]]
== &#45;&#45;&#40;{ &#40;K&#41;?: V }, Object&#41;: { &#40;K&#41;?: V }

Removes specified key-value pairs from an object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The object.
| `toRemove` | Objects to remove from the source object.
|===

=== Example

This example removes a key-value pair from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "hello" : "world",
   "name" : "DW"
} -- { "hello" : "world"}
----

==== Output

[source,JSON,linenums]
----
{
   "name": "DW"
}
----


[[minusminus3]]
== &#45;&#45;&#40;Object, Array<String&#62;&#41;

Removes specified key-value pairs from an object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `toRemove` | Keys for the key-value pairs to remove from the source object.
|===

=== Example

This example removes two key-value pairs from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "yes" : "no",
   "good" : "bad",
   "old" : "new"
} -- ["yes", "old"]
----

==== Output

[source,JSON,linenums]
----
{
   "good": "bad"
}
----


[[minusminus4]]
== &#45;&#45;&#40;Object, Array<Key&#62;&#41;

Removes specified key-value pairs from an object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `keys` | A keys for the key-value pairs to remove from the source object.
|===

=== Example

This example specifies the key-value pair to remove from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
   "hello" : "world",
   "name" : "DW"
 } -- ["hello" as Key]
----

==== Output

[source,JSON,linenums]
----
{
   "name": "DW"
}
----

