= toString
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[tostring1]]
== toString&#40;number: Number, format: String &#124; Null = null, locale: String &#124; Null = null, roundMode: RoundingMode &#124; Null = null&#41;: String

Formats a Number and return a String with the result.
A Pattern can be used in order to specify how the number needs to be formatted.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| number | The number to be formatted
| format | The format to be used
| locale | The locale
| roundMode | "UP" or "DOWN" or "CEILING" or "FLOOR" or "HALF_UP" or "HALF_DOWN" or "HALF_EVEN"
|===

=== Example

This example shows how the `toString` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toString from dw::util::Coercions
output application/json
---
 {
    a: toString(1.0),
    b: toString(0.005,".00"),
    c: toString(0.035,"#.##","ES"),
    d: toString(0.005,"#.##","ES","HALF_EVEN"),
    e: toString(0.035,"#.00",null,"HALF_EVEN"),
 }
----

==== Output

[source,Json,linenums]
----
{
  "a": "1",
  "b": ".01",
  "c": "0,04",
  "d": "0",
  "e": ".04"
}
----


[[tostring2]]
== toString&#40;date: Date &#124; DateTime &#124; LocalDateTime &#124; LocalTime &#124; Time, format: String &#124; Null = null, locale: String &#124; Null = null&#41;: String

Formats a Date DateTime Time into a String.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| date   | The date to be formatted
| format | The format to be used to format the date. If null no format will be used
| locale | The locale to be used. If null no locale will be used
|===

=== Example

This example shows how the `toString` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toString from dw::util::Coercions
output application/json
---
{
   a: toString(|2015-10-01T23:57:59|),
   b: toString(|2003-10-01T23:57:59|, "yyyy-MM-dd HH:mm:ss a"),
   c: toString(|2003-10-01|, "yyyy/MM/dd"),
   d: toString(|23:57:59|, "HH-mm-ss"),
   e: toString(|2003-10-01T23:57:59|, "yyyy-MM-dd HH:mm:ss a", "ES"),
}
----

==== Output

[source,Json,linenums]
----
{
  "a": "2015-10-01T23:57:59",
  "b": "2003-10-01 23:57:59 PM",
  "c": "2003/10/01",
  "d": "23-57-59",
  "e": "2003-10-01 23:57:59 PM"
}
----


[[tostring3]]
== toString&#40;binary: Binary, encoding: String&#41;: String

Transforms a Binary data into a String using the given encoding

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| binary | The binary data
| encoding | The encoding to be used
|===

=== Example

This example shows how the `toString` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
var binaryData= "DW Test" as Binary {encoding: "UTF-32"}
---
{
  a: toString(binaryData, "UTF-32"),
}
----

==== Output

[source,Json,linenums]
----
{
  "a": "DW Test"
}
----


[[tostring4]]
== toString&#40;data: TimeZone &#124; Uri &#124; Boolean &#124; Period &#124; Regex &#124; Key&#41;: String

Transform the value (TimeZone | Uri | Boolean| Period| Regex| Key) into the String representation

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| data | The data to be transformed
|===

=== Example

This example shows how the `toString` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
 a: toString(|Z|),
 b: toString(true),
 c: toString(|P1D|),
 d: toString(/a-Z/),
}
----

==== Output

[source,Json,linenums]
----
{
  "a": "Z",
  "b": "true",
  "c": "P1D",
  "d": "a-Z"
}
----


[[tostring5]]
== toString&#40;arr: Array<String&#62;&#41;: String

Transform an array of characters into a String, by joining them.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| arr | The array to transform
|===

=== Example

This example shows how `toString` behaves under different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import toString from dw::util::Coercions
output application/json
---
{
 a: toString([]),
 b: toString(["h", "o", "l", "a"]),
}
----

==== Output

[source,Json,linenums]
----
{
  "a": "",
  "b": "hola",
}
----

