= lastIndexOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[lastindexof1]]
== lastIndexOf&#40;array: Array, value: Any&#41;: Number

Returns the index of the _last_ occurrence of the specified element in a given
array or `-1` if the array does not contain the element.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `array` | The array of elements to search.
| `value` | The value to search.
|===

=== Example

This example shows how `indexOf` behaves given different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: ["a","b","c","d"] lastIndexOf "c",
  notPresent: ["x","w","x"] lastIndexOf "c",
  presentMoreThanOnce: ["a","b","c","c"] lastIndexOf "c",
}
----

==== Output

[source,Json,linenums]
----
{
  "present": 2,
  "notPresent": -1,
  "presentMoreThanOnce": 3
}
----


[[lastindexof2]]
== lastIndexOf&#40;array: String, value: String&#41;: Number

Takes a string as input and returns the index of the _last_ occurrence of
a given search string within the input. The function returns `-1` if the
search string is not present in the input.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `string` | The string to search.
| `value` | A string value to search for within the input string.
|===

=== Example

This example shows how the `indexOf` behaves given different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  present: "abcd" lastIndexOf "c",
  notPresent: "xyz" lastIndexOf "c",
  presentMoreThanOnce: "abcdc" lastIndexOf "c",
}
----

==== Output

[source,Json,linenums]
----
{
  "present": 2,
  "notPresent": -1,
  "presentMoreThanOnce": 4
}
----


[[lastindexof3]]
== lastIndexOf&#40;array: Null, value: Any&#41;: Number

Helper function that enables `lastIndexOf` to work with a `null` value.

