= sizeOf
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[sizeof1]]
== sizeOf&#40;Array<Any&#62;&#41;: Number

Returns the number of elements in an array.


Returns `0` if the array is empty.

=== Example

This example returns a count of elements in the input array.

==== Source
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  "arraySize": sizeOf([1,2,3])
}
----

==== Output
[source,JSON,linenums]
----
{
  "arraySize": 3
}
----


[[sizeof2]]
== sizeOf&#40;Object&#41;: Number

Returns the number of key-value pairs in an input object.


Returns `0` if the object is empty.

=== Example

This example counts the key-value pairs in an input object.

==== Source
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  objectSize: sizeOf({a:1,b:2})
}
----

==== Output
[source,JSON,linenums]
----
{
  "objectSize": 2
}
----


[[sizeof3]]
== sizeOf&#40;Binary&#41;: Number

Returns the byte length of a binary.


=== Example

This example returns the size of a binary value that is passed through a
variable. The binary is returned by a function in `core::Binaries`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
var var1 = fromBase64(000000)
output application/json
---

{ "size" : sizeOf(var1) }
----

==== Output

[source,JSON,linenums]
----
{
  "size": 4
}
----


[[sizeof4]]
== sizeOf&#40;String&#41;: Number

Returns the number of characters (including white space) in an string.


Returns `0` if the string is empty.

=== Example

This example returns the number of characters in the input strings.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  "sizeOfString1" : sizeOf("MuleSoft"),
  "sizeOfSting2" : sizeOf("my string")
}
----

==== Output

[source,JSON,linenums]
----
{
  "sizeOfString1": 8,
  "sizeOfSting2": 9
}
----

