= isLeapYear
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[isleapyear1]]
== isLeapYear&#40;DateTime&#41;: Boolean

Returns `true` if it receives a `DateTime` for a leap year, `false` if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` | The date-time (`DateTime` type) to evaluate.
|===

=== Example

This example indicates whether the input is a leap year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "leapYear" : isLeapYear(|2016-10-01T23:57:59Z|),
  "leapYear" : isLeapYear(|2016-10-01T23:57:59-03:00|),
  "leapYear": isLeapYear(|2017-10-01T23:57:59Z|),
  "leapYear": isLeapYear(|2017-10-01T23:57:59-03:00|)
}
----

==== Output

[source,JSON,linenums]
----
  {
    "leapYear": true,
    "leapYear": true,
    "leapYear": false,
    "leapYear": false
  }
----


[[isleapyear2]]
== isLeapYear&#40;Date&#41;: Boolean

Returns `true` if the input `Date` is a leap year, 'false' if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `date` | The date (`Date` type) to evaluate.
|===

=== Example

This example indicates whether the input is a leap year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "leapYear" : isLeapYear(|2016-10-01|),
  "leapYear": isLeapYear(|2017-10-01|)
}
----

==== Output

[source,JSON,linenums]
----
  {
    "leapYear": true,
    "leapYear": false
  }
----


[[isleapyear3]]
== isLeapYear&#40;LocalDateTime&#41;: Boolean

Returns `true` if the input local date-time is a leap year, 'false' if not.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `datetime` | A local date-time (`LocalDateTime` type) to evaluate.
|===

=== Example

This example indicates whether the input is a leap year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "leapYear" : isLeapYear(|2016-10-01T23:57:59|),
  "leapYear": isLeapYear(|2017-10-01T23:57:59|)
}
----

==== Output

[source,JSON,linenums]
----
  {
    "leapYear": true,
    "leapYear": false
  }
----

