= unzip
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[unzip1]]
== unzip<T&#62;&#40;items: Array<Array<T&#62;&#62;&#41;: Array<Array<T&#62;&#62;

Performs the opposite of `zip`. It takes an array of arrays as input.


The function groups the values of the input sub-arrays by matching indices,
and it outputs new sub-arrays with the values of those matching indices. No
sub-arrays are produced for unmatching indices. For example, if one input
sub-array contains four elements (indices 0-3) and another only contains
three (indices 0-2), the function will not produce a sub-array for the
value at index 3.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The input array of arrays.
|===

=== Example

This example unzips an array of arrays. It outputs the first index of each
sub-array into one array `[ 0, 1, 2, 3 ]`, and the second index of each into
another `[ "a", "b", "c", "d" ]`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
unzip([ [0,"a"], [1,"b"], [2,"c"],[ 3,"d"] ])
----

==== Output

[source,JSON,linenums]
----
[ [ 0, 1, 2, 3 ], [ "a", "b", "c", "d" ] ]
----

=== Example

This example unzips an array of arrays. Notice that the number of elements in
the input arrays is not all the same. The function creates only as many full
sub-arrays as it can, in this case, just one.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
unzip([ [0,"a"], [1,"a","foo"], [2], [3,"a"] ])
----

==== Output

[source,JSON,linenums]
----
[0,1,2,3]
----

