= log
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[log1]]
== log&#40;String, T&#41;: T

Without changing the value of the input, `log` returns the input as a system
log.


Use this function to debug DataWeave scripts until a proper
debugger is incorporated. The Logger component outputs the results
through `DefaultLoggingService` in the console.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `prefix` | A string that typically describes the log.
| `value` | The value to log.
|===

=== Example

The following example logs the specified message. In the console, the Logger component's `DefaultLoggingService` returns the message `WARNING - "Houston, we have a problem."` MuleSoft adds the dash `-` between the prefix and value. +
While the Logger component's `LoggerMessageProcessor` simply returns the value `"Houston, we have a problem."`, without the `WARNING` prefix.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
"WARNING" log("Houston, we have a problem.")
----

==== Output

[source,XML,linenums]
----
WARNING - "Houston, we have a problem."
----
