= filterObject
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[filterobject1]]
== filterObject<K, V&#62;&#40;@StreamCapable value: { &#40;K&#41;?: V }, criteria: &#40;value: V, key: K, index: Number&#41; &#45;&#62; Boolean&#41;: { &#40;K&#41;?: V }

Iterates a list of key-value pairs in an object and applies an expression that
returns only matching objects, filtering out the rest from the output.


The expression must return `true` or `false`. If the expression returns `true`
for a key, value, or index of an object, the object gets captured in the
output. If it returns `false` for any of them, the object gets filtered out
of the output. If there are no matches, the output array will be empty.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | The source object to evaluate.
| `criteria` | Boolean expression that selects a `value`, `key`, or `index` of the object.
|===

=== Example

This example outputs an object if its value equals `"apple"`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{"a" : "apple", "b" : "banana"} filterObject ((value) -> value == "apple")
----

==== Output

[source,JSON,linenums]
----
{ "a": "apple" }
----

=== Example

This example only outputs an object if the key starts with "letter". The
DataWeave `startsWith` function returns `true` or `false`. Note that you can
use the anonymous parameter for the key to write the expression
`((value, key) -> key startsWith "letter")`: (&#36;&#36; startsWith "letter")`

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{"letter1": "a", "letter2": "b", "id": 1} filterObject ((value, key) -> key startsWith "letter")
----

==== Output

[source,JSON,linenums]
----
{ "letter1": "a", "letter2": "b" }
----

=== Example

This example only outputs an object if the index of the object in the array
is less than 1, which is always true of the first object. Note that you can
use the anonymous parameter for the index to write the expression
`((value, key, index) -> index < 1)`: `(&#36;&#36;&#36; < 1)`

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "1": "a", "2": "b", "3": "c"} filterObject ((value, key, index) -> index < 1)
----

==== Output

[source,json,linenums]
----
{ "1": "a" }
----


[[filterobject2]]
== filterObject&#40;value: Null, criteria: &#40;value: Nothing, key: Nothing, index: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `filterObject` to work with a `null` value.

