= &#45;&#45;
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

//* <<minusminus1>>
//* <<minusminus2>>
//* <<minusminus3>>
//* <<minusminus4>>


[[minusminus1]]
== --(Array<S>, Array<Any>): Array<S>

Returns a new array that removes every occurrence of elements listed in the
right-hand side (`rhs`) array from the left-hand side (`lhs`) array. The result
is that same as iteratively taking `lhs - elementN`, for each `elementN` in `rhs`.

When an element in the `lhs` array matches one of the values in the `rhs` array,
it is removed. If multiple elements in the `lhs` array match a value, all matching
values are removed from the
`lhs`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
a: [0, 1, 1, 2] -- [1,2]
----

.Output
[source,json,linenums]
----
{
  "a": [0],
}
----


[[minusminus2]]
== --({ (K)?: V }, Object): { (K)?: V }

Removes all the entries from the source that are present on the `toRemove`
parameter.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
   hello: 'world',
   name: "DW"
 } -- {hello: 'world'}
----

.Output
[source,json,linenums]
----
{
   "name": "DW"
}
----


[[minusminus3]]
== --(Object, Array<String>)

Removes the properties from the source that are present the given list of keys.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
   hello: 'world',
   name: "DW"
 } -- ['hello']
----

.Output
[source,json,linenums]
----
{
   "name": "DW"
}
----


[[minusminus4]]
== --(Object, Array<Key>)

Removes the properties from the source that are present the given list of keys.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
   hello: 'world',
   name: "DW"
 } -- ['hello' as Key]
----

.Output
[source,json,linenums]
----
{
   "name": "DW"
}
----