= &#45;&#45;
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[minusminus1]]
== &#45;&#45;<S&#62;&#40;source: Array<S&#62;, toRemove: Array<Any&#62;&#41;: Array<S&#62;

Removes specified values from an input value.


This version of `--` removes all instances of the specified items from an array. Other
versions act on objects, strings, and the various date and time formats that
are supported by DataWeave.

[source,JSON,linenums]
|===
| Name   | Description
| `source` | The array containing items to remove.
| `toRemove` | Items to remove from the source array.
|===

=== Example

This example removes specified items from an array. Specifically, it removes
all instances of the items listed in the array on the right side of `--` from
the array on the left side of the function, leaving `[0]` as the result.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ "a" : [0, 1, 1, 2] -- [1,2] }
----

==== Output

[source,JSON,linenums]
----
{ "a": [0] }
----


[[minusminus2]]
== &#45;&#45;<K, V&#62;&#40;source: { &#40;K&#41;?: V }, toRemove: Object&#41;: { &#40;K&#41;?: V }

Removes specified key-value pairs from an object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `toRemove` | Object that contains the key-value pairs to remove from the source object.
|===

=== Example

This example removes a key-value pair from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{ "hello" : "world", "name" : "DW" } -- { "hello" : "world"}
----

==== Output

[source,JSON,linenums]
----
{ "name": "DW" }
----


[[minusminus3]]
== &#45;&#45;&#40;source: Object, keys: Array<String&#62;&#41;

Removes all key-value pairs from the source object that match the specified search key.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `toRemove` | An array of keys to specify the key-value pairs to remove from the source object.
|===

=== Example

This example removes two key-value pairs from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{ "yes" : "no", "good" : "bad", "old" : "new" } -- ["yes", "old"]
----

==== Output

[source,JSON,linenums]
----
{ "good": "bad" }
----


[[minusminus4]]
== &#45;&#45;&#40;source: Object, keys: Array<Key&#62;&#41;

Removes specified key-value pairs from an object.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `source` | The source object (an `Object` type).
| `keys` | A keys for the key-value pairs to remove from the source object.
|===

=== Example

This example specifies the key-value pair to remove from the source object.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{ "hello" : "world", "name" : "DW" } -- ["hello" as Key]
----

==== Output

[source,JSON,linenums]
----
{ "name": "DW" }
----


[[minusminus5]]
== &#45;&#45;&#40;source: Null, keys: Any&#41;

Helper function that enables `--` to work with a `null` value.

