= scan
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[scan1]]
== scan&#40;String, Regex&#41;: Array<Array<String&#62;&#62;

Returns a list (array) with all of the matches found within the given string.


Each match is returned as an array that contains the complete match followed by any
capture groups in your regular expression (if present).


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The text to scan (`String` type).
| `regex` | A regular expression that describes the pattern to look for in the text.
|===

=== Example

In the example, the `regex` describes an email address. It contains two
capture groups, the characters before and after the `@`. It produces an
an array matching the two email addresses in the input string. Each match
is an array of three elements: The first is the entire email address, and the
second and third are matches to the `regex` capture groups.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"hello" : "anypt@mulesoft.com,max@mulesoft.com" scan /([a-z]*)@([a-z]*).com/
----

==== Output

[source,JSON,linenums]
----
{
  "hello": [
    [
      "anypt@mulesoft.com",
      "anypt",
      "mulesoft"
    ],
    [
      "max@mulesoft.com",
      "max",
      "mulesoft"
    ]
  ]
}
----

