= contains
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[contains1]]
== contains<T&#62;&#40;@StreamCapable items: Array<T&#62;, element: Any&#41;: Boolean

Returns `true` if an input contains a given value, `false` if not.


This version of `contains` accepts an array as input. Other versions
accept a string and can use another string or regular expression to
determine whether there is a match.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `items` | The input array.
| `elements` | Element to find in the array. Can be any supported data type.
|===

=== Example

This example finds that `2` is in the input array, so it returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
[ 1, 2, 3, 4 ] contains(2)
----

==== Output

[source,JSON,linenums]
----
true
----

=== Example

This example indicates whether the input array contains '"3"'.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
ContainsRequestedItem: payload.root.*order.*items contains "3"
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <order>
      <items>155</items>
    </order>
    <order>
      <items>30</items>
    </order>
    <order>
      <items>15</items>
    </order>
    <order>
      <items>5</items>
    </order>
    <order>
      <items>4</items>
      <items>7</items>
    </order>
    <order>
      <items>1</items>
      <items>3</items>
    </order>
    <order>
        null
    </order>
</root>
----

==== Output

[source,JSON,linenums]
----
{ "ContainsRequestedItem": true }
----


[[contains2]]
== contains&#40;text: String, toSearch: String&#41;: Boolean

Indicates whether a string contains a given substring. Returns `true`
or `false`.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | An input string (a `String`).
| `toSearch` | The substring (a `String`) to find in the input string.
|===

=== Example

This example finds "mule" in the input string "mulesoft", so it returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
"mulesoft" contains("mule")
----

==== Output

[source,JSON,linenums]
----
true
----

=== Example

This example finds that the substring `"me"` is in `"some string"`, so it
returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{ ContainsString : payload.root.mystring contains("me") }
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root><mystring>some string</mystring></root>
----

==== Output

[source,JSON,linenums]
----
{ "ContainsString": true }
----


[[contains3]]
== contains&#40;text: String, matcher: Regex&#41;: Boolean

Returns `true` if a string contains a match to a regular expression, `false`
if not.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | An input string.
| `matcher` | A Java regular expression for matching characters in the input `text`.
|===

=== Example

This example checks for any of the letters `e` through `g` in the input
`mulesoft`, so it returns `true`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
contains("mulesoft", /[e-g]/)
----

==== Output

[source,JSON,linenums]
----
true
----

=== Example

This example finds a match to `/s[t|p]rin/` within `"A very long string"`,
so it returns `true`. The `[t|p]` in the regex means `t` or `p`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
ContainsString: payload.root.mystring contains /s[t|p]rin/
----

==== Input

[source,XML,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root><mystring>A very long string</mystring></root>
----

==== Output

[source,JSON,linenums]
----
{ "ContainsString": true }
----


[[contains4]]
== contains&#40;text: Null, matcher: Any&#41;: false

Helper function that enables `contains` to work with a `null` value.

