= atBeginningOfHour
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofhour1]]
== atBeginningOfHour&#40;dateTime: DateTime&#41;: DateTime

Returns a  new `DateTime` value that changes the `Time` value in the input to the
beginning of the specified _hour_.


The minutes and seconds in the input change to `00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` |  The `DateTime` value to reference.
|===

=== Example

This example changes the `Time` value within the `DateTime` input to the
beginning of the specified _hour_.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
 {
    "atBeginningOfHourDateTime": atBeginningOfHour(|2020-10-06T18:23:20.351-03:00|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHourDateTime": "2020-10-06T18:00:00-03:00"
 }
----


[[atbeginningofhour2]]
== atBeginningOfHour&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a  new `LocalDateTime` value that changes the `Time` value in the input to the
beginning of the specified _hour_.


The minutes and seconds in the input change to `00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `localDateTime` | The `LocalDateTime` value to reference.
|===

=== Example

This example changes the `Time` value within the `LocalDateTime` input to the
beginning of the specified hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
 {
    "atBeginningOfHourLocalDateTime": atBeginningOfHour(|2020-10-06T18:23:20.351|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHourLocalDateTime": "2020-10-06T18:00:00"
 }
----


[[atbeginningofhour3]]
== atBeginningOfHour&#40;localTime: LocalTime&#41;: LocalTime

Returns a  new `LocalTime` value that changes its value in the input to the
beginning of the specified _hour_.


The minutes and seconds in the input change to `00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `localTime` | The `LocalTime` value to reference.
|===

=== Example

This example changes the `LocalTime` value to the
beginning of the specified hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
 {
    "atBeginningOfHourLocalTime": atBeginningOfHour(|18:23:20.351|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHourLocalTime": "18:00:00"
 }
----


[[atbeginningofhour4]]
== atBeginningOfHour&#40;time: Time&#41;: Time

Returns a new `Time` value that changes the input value to the
beginning of the specified _hour_.

The minutes and seconds in the input change to `00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `time` | The `Time` value to reference.
|===

=== Example

This example changes the `Time` value to the beginning of the specified hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
 {
    "atBeginningOfHourTime": atBeginningOfHour(|18:23:20.351-03:00|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHourTime":  "18:00:00-03:00"
 }
----

