= localTime
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[localtime1]]
== localTime&#40;parts: LocalTimeFactory&#41;: LocalTime

Creates a `LocalTime` value from values specified for `hour`, `minutes`, and
`seconds` fields.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `parts` | `Number` values for `hour`, `minutes`, and
            `seconds` fields. Valid values are 0 through 23 for the
            `hour`, 0 through 59 for `minutes`, and 0 through 60 (not inclusive; the field accepts 59.99, for example) for `seconds` fields.
            You can specify the name-value pairs in any order,
            but the output is ordered as a default `LocalTime` value,
            such as `10:10:10`. The input fields are parts of
            a `LocalDateTimeFactory` type.
|===

=== Example

This example shows how to create a value of type `LocalTime`.

==== Source

---
 %dw 2.0
 import * from dw::core::Dates
 output application/json
 ---
 {
   newLocalTime: localTime({ hour: 12, minutes: 30, seconds: 40})
 }
----

==== Output

[source,Json,linenums]
----
 {
    "newLocalTime": "12:30:40"
 }
----

