= atBeginningOfMonth
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofmonth1]]
== atBeginningOfMonth&#40;dateTime: DateTime&#41;: DateTime

Returns a new `DateTime` value that changes the `Day` value from the
input to the first day of the specified _month_. It also sets the `Time` value to `00:00:00`.


The day and time in the input changes to `01T00:00:00`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` | The `DateTime` value to reference.
|===

=== Example

This example changes the `Day` value within the `DateTime` input to the
first day of the specified month and sets the `Time` value to `00:00:00`.

==== Source


[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  "atBeginningOfMonthDateTime": atBeginningOfMonth(|2020-10-06T18:23:20.351-03:00|)
}
----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonthDateTime": "2020-10-01T00:00:00-03:00"
}
----


[[atbeginningofmonth2]]
== atBeginningOfMonth&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new `LocalDateTime` value that changes the `Day` and `LocalTime`
values from the input to the beginning of the specified _month_.


The day and time in the input changes to `01T00:00:00`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `localDateTime` | The `LocalDateTime` value to reference.
|===

=== Example

This example changes the `Day` and `LocalTime` values within the `LocalDateTime`
input to the beginning of the specified month.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
 "atBeginningOfMonthLocalDateTime": atBeginningOfMonth(|2020-10-06T18:23:20.351|)
}
----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonthLocalDateTime": "2020-10-01T00:00:00"
}
----


[[atbeginningofmonth3]]
== atBeginningOfMonth&#40;date: Date&#41;: Date

Returns a new `Date` value that changes the `Day` value from the
input to the first day of the specified _month_.


The day in the input changes to `01`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `date` | The `Date` value to reference.
|===

=== Example

This example changes the `Day` value within the `Date`
input to the first day of the specified month.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  atBeginningOfMonthDate: atBeginningOfMonth(|2020-10-06|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonthDate": "2020-10-01"
}
----

