= atBeginningOfYear
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofyear1]]
== atBeginningOfYear&#40;dateTime: DateTime&#41;: DateTime

Takes a `DateTime` value as input and returns a `DateTime` value for
the first day of the _year_ specified in the input. It also sets the `Time` value to `00:00:00`.


The month, day, and time in the input changes to `01-01T00:00:00`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` | The `DateTime` value to reference.
|===

=== Example

This example transforms the `DateTime` input (`|2020-10-06T18:23:20.351-03:00|`)
to the date of the first day of the `Year` value (`2020`) in the input.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  atBeginningOfYearDateTime: atBeginningOfYear(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYearDateTime": "2020-01-01T00:00:00.000-03:00"
}
----


[[atbeginningofyear2]]
== atBeginningOfYear&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Takes a `LocalDateTime` value as input and returns a `LocalDateTime` value for
the first day of the _year_ specified in the input. It also sets the `Time` value to `00:00:00`.


The month, day, and time in the input changes to `01-01T00:00:00`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `localDateTime` | The `LocalDateTime` value to reference.
|===

=== Example

This example transforms the `LocalDateTime` input (`|2020-10-06T18:23:20.351|`)
to the date of the first day of the `Year` value (`2020`) in the input.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  atBeginningOfYearLocalDateTime: atBeginningOfYear(|2020-10-06T18:23:20.351|)
}
----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYearLocalDateTime": "2020-01-01T00:00:00"
}
----


[[atbeginningofyear3]]
== atBeginningOfYear&#40;date: Date&#41;: Date

Takes a `Date` value as input and returns a `Date` value for
the first day of the _year_ specified in the input.


The month and day in the input changes to `01-01`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `date` | The `Date` value to reference.
|===

=== Example

This example transforms `Date` input (`|2020-10-06|`) to the date of the
first day of the `Year` value (`2020`) in the input.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  atBeginningOfYearDate: atBeginningOfYear(|2020-10-06|)
}
----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYearDate": "2020-01-01"
}
----

