= atBeginningOfHour
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofhour1]]
== atBeginningOfHour&#40;dateTime: DateTime&#41;: DateTime

Returns a new DateTime with the Time changed to the start of the current hour

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The DateTime used as reference
|===

=== Example

This shows how it changes the specified Time to the the start of the given hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
 {
    "atBeginningOfHour": atBeginningOfHour(|2020-10-06T18:23:20.351-03:00|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHour": "2020-10-06T18:00:00-03:00"
 }
----


[[atbeginningofhour2]]
== atBeginningOfHour&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new LocalDateTime changed to the beginning of the given hour

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| localDateTime | The LocalDateTime used as reference
|===

=== Example

This shows how it changes the specified Time to the the start of the given hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
 {
    "atBeginningOfHour": atBeginningOfHour(|2020-10-06T18:23:20.351|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHour": "2020-10-06T18:00:00"
 }
----


[[atbeginningofhour3]]
== atBeginningOfHour&#40;localTime: LocalTime&#41;: LocalTime

Returns a new LocalTime changed to the start of the current hour

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime |
|===

=== Example

This shows how it changes the specified LocalTime to the the start of the given hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
 {
    "atBeginningOfHour": atBeginningOfHour(|18:23:20.351|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHour": "18:00:00"
 }
----


[[atbeginningofhour4]]
== atBeginningOfHour&#40;time: Time&#41;: Time

Returns a new Time changed to the beginning of the given hour.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| time | The time to be used as reference
|===

=== Example

This shows how it changes the specified Time to the the start of the given hour.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
 {
    "atBeginningOfHour": atBeginningOfHour(|18:23:20.351-03:00|)
 }
----

==== Output

[source,Json,linenums]
----
 {
  "atBeginningOfHour":  "18:00:00-03:00"
 }
----

