= atBeginningOfDay
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofday1]]
== atBeginningOfDay&#40;dateTime: DateTime&#41;: DateTime

Returns a new DateTime but at the beginning of the day of the given DateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The dateTime to be used as reference
|===

=== Example

This example shows how it transforms the DateTime `2020-10-06T18:23:20.351-03:00` to the same date but at the start of the given day.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "atBeginningOfDayDateTime": atBeginningOfDay(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfDayDateTime": "2020-10-06T00:00:00-03:00"
}
----


[[atbeginningofday2]]
== atBeginningOfDay&#40;dateTime: LocalDateTime&#41;: LocalDateTime

Returns a new LocalDateTime but at the beginning of the day of the given LocalDateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The dateTime to be used as reference
|===

=== Example

This example shows how it transforms the LocalDateTime `2020-10-06T18:23:20.351-03:00` to the same date but at the start of the given day.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  "atBeginningOfDayLocalDateTime": atBeginningOfDay(|2020-10-06T18:23:20.351|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfDayLocalDateTime": "2020-10-06T00:00:00"
}
----

