= atBeginningOfMonth
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofmonth1]]
== atBeginningOfMonth&#40;dateTime: DateTime&#41;: DateTime

Returns a new DateTime but at the beginning of the Month of the given DateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The dateTime to be used as reference
|===

=== Example

This example shows how it transforms the DateTime `2020-10-06T18:23:20.351-03:00` to the same date but at the start of the given Month.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfMonth(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-01T00:00:00-03:00"
}
----


[[atbeginningofmonth2]]
== atBeginningOfMonth&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new LocalDateTime but at the beginning of the Month of the given LocalDateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The localDateTime to be used as reference
|===

=== Example

This example shows how it transforms the LocalDateTime `2020-10-06T18:23:20.351` to the same date but at the start of the given Month.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
 "atBeginningOfMonth": atBeginningOfMonth(|2020-10-06T18:23:20.351|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-01T00:00:00"
}
----


[[atbeginningofmonth3]]
== atBeginningOfMonth&#40;date: Date&#41;: Date

Returns a new Date but at the beginning of the Month of the given Date

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The date to be used as reference
|===

=== Example

This example shows how it transforms the Date |2020-10-06| to the same date but at the start of the given Month.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfMonthDate: atBeginningOfMonth(|2020-10-06|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-01"
}
----

