= atBeginningOfDay
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofday1]]
== atBeginningOfDay&#40;dateTime: DateTime&#41;: DateTime

Returns a  new `DateTime` value that changes the `Time` value in the input to the
beginning of the specified _day_.


The hours, minutes, and seconds in the input change to `00:00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `dateTime` | The `DateTime` value to reference.
|===

=== Example

This example changes the `Time` value within the `DateTime` input to the
beginning of the specified day.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  "atBeginningOfDayDateTime": atBeginningOfDay(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfDayDateTime": "2020-10-06T00:00:00-03:00"
}
----


[[atbeginningofday2]]
== atBeginningOfDay&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new `LocalDateTime` value that changes the `Time` value within the
input to the start of the specified _day_.


The hours, minutes, and seconds in the input change to `00:00:00`.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `localDateTime` | The `LocalDateTime` value to reference.
|===

=== Example

This example changes the `Time` value within the `LocalDateTime` input to the
beginning of the specified day.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::core::Dates
output application/json
---
{
  "atBeginningOfDayLocalDateTime": atBeginningOfDay(|2020-10-06T18:23:20.351|)
}
----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfDayLocalDateTime": "2020-10-06T00:00:00"
}
----

