= atBeginningOfWeek
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofweek1]]
== atBeginningOfWeek&#40;dateTime: DateTime&#41;: DateTime

Returns a new DateTime but at the beginning of the Week of the given DateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The dateTime to be used as reference
|===

=== Example

This example shows how it transforms the DateTime |2020-10-06T18:23:20.351-03:00| to the same date but at the start of the given Week.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfWeekDateTime: atBeginningOfWeek(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-04T00:00:00-03:00"
}
----


[[atbeginningofweek2]]
== atBeginningOfWeek&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new LocalDateTime but at the beginning of the Week of the given LocalDateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| localDateTime | The localDateTime to be used as reference
|===

=== Example

This example shows how it transforms the LocalDateTime |2020-10-06T18:23:20.351| to the same date but at the start of the given Week.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfMonth: atBeginningOfWeek(|2020-10-06T18:23:20.351|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-04T00:00:00"
}
----


[[atbeginningofweek3]]
== atBeginningOfWeek&#40;date: Date&#41;: Date

Returns a new Date but at the beginning of the Week of the given Date

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| date | The date to be used as reference
|===

=== Example

This example shows how it transforms the Date |2020-10-06| to the same date but at the start of the given Week.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfMonth: atBeginningOfWeek(|2020-10-06|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfMonth": "2020-10-04"
}
----

