= atBeginningOfYear
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[atbeginningofyear1]]
== atBeginningOfYear&#40;dateTime: DateTime&#41;: DateTime

Returns a new DateTime but at the beginning of the Year of the given DateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| dateTime | The dateTime to be used as reference
|===

=== Example

This example shows how it transforms the DateTime |2020-10-06T18:23:20.351-03:00| to the same date but at the start of the given Year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfYear: atBeginningOfYear(|2020-10-06T18:23:20.351-03:00|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYear": "2020-01-01T00:00:00.000-03:00"
}
----


[[atbeginningofyear2]]
== atBeginningOfYear&#40;localDateTime: LocalDateTime&#41;: LocalDateTime

Returns a new LocalDateTime but at the beginning of the Year of the given LocalDateTime

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| localDateTime | The localDateTime to be used as reference
|===

=== Example

This example shows how it transforms the LocalDateTime |2020-10-06T18:23:20.351| to the same date but at the start of the given Year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfYear: atBeginningOfYear(|2020-10-06T18:23:20.351|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYear": "2020-01-01T00:00:00.000"
}
----


[[atbeginningofyear3]]
== atBeginningOfYear&#40;date: Date&#41;: Date

Returns a new Date but at the beginning of the Year of the given Date

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4.0 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| date | The date to be used as reference
|===

=== Example

This example shows how it transforms the Date |2020-10-06| to the same date but at the start of the given Year.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
{
  atBeginningOfYear: atBeginningOfYear(|2020-10-06|)
}

----

==== Output

[source,Json,linenums]
----
{
  "atBeginningOfYear": "2020-01-01"
}
----

