= Formatting Symbols
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


include::partial$eol-warning.adoc[]

DataWeave supports symbols that enable you to format string representations of numbers, dates, and times.

[[format_number]]
== Number Symbols

When you coerce a `Number` value into a `String` value, you can format the value using literal characters and the following placeholders:

* `&#35;`
* `0`

For _decimals_ (for example, 0.234), you can use either of the placeholders (but not both). As the example shows, you can use formatting placeholders to truncate decimal values.

For _whole_ numbers less than 10, a single `&#35;` or `0` placeholder is optional. Additional `0` values are treated as literal values, but additional `&#35;` values produce an error.

You can add other characters to the formatting symbols, but it is necessary to escape <<special_characters, special characters>>, such as a dollar sign (`\$`).
In addition, <<disallowed_characters, disallowed>>. characters, such as a comma (`,`), produce an error and cannot be escaped.

.Source
[source,weave,linenums]
----
%dw 2.0
output application/json
---
[
    2.132 as String { format : ".##"},
    2.132 as String { format : ".00"},
    2.132 as String { format : ".#"},
    2.132 as String { format : ".0"},
    2.132 as String { format : "\$10.000"},
    2.132 as String { format : "\$1#.###"},
    2.132 as String { format : "\$10.###"},
    2.132 as String { format : "\$100.## dollars"},
    2.132 as String { format : "\$100.## 'my money'"}
]
----

.Output
[source,JSON,linenums]
----
[
  "2.13",
  "2.13",
  "2.1",
  "2.1",
  "$12.132",
  "$12.132",
  "$12.132",
  "$102.13 dollars"
]
----

[[special_characters]]
Escaping special characters with a backslash:

* Dollar sign (`$`), for example, `\$`.
* Double quotes (`" "`) that are surrounded by double quotes, for example, `{ format : ".## \"my escaped quotes\""}`. An unclosed double quote produces an error even if escaped.
* Single quotes (`' '`) that are surrounded by single quotes, for example, `{ format : '.## \'my escaped quotes\''}`. An unclosed single quote produces an error even if escaped.
+
In some formats, like JSON and XML, single quotes _do not appear in the output_ even if you escape them, but you can see the expected format if you output to `application/dw`.

[[disallowed_characters]]
The following characters produce an error when _inside_ a formatting string
if you do not surround them with inner quotation marks:

* An additional decimal (`.`) if you do not embed it within inner quotation marks
* A comma (`,`) if you do not embed it within inner quotation marks
* A backslash when not followed by another character (`\`)
* Unclosed single or double quotes

[[format_date_time]]
== Date and Time Symbols

DataWeave supports the use of formatting symbols, such as the `u` (for the year), `M`, and `d` combined in the date format `uuuu-MM-dd`. The characters are based on the Java 8 `java.time.format` package.

For examples that use these characters, see xref:dataweave-cookbook-format-dates.adoc[Format Dates and Times].

[%header,cols="1,2,2"]
|===
| Symbol | Meaning | Examples
| `G` | Era	| "AD"
| `GGGG` | Era	| "Anno Domini"
| `u`	| Year | "2021"
| `uu`	| Year | "21"
| `y`	| Year of an era	| "2021" (`u` is recommended over `y`)
| `yy` | Year of an era	| "21" (`uu` is recommended over `yy`)
| `D` or `DDD`	| Day of a year	| "189"
| `M` or `MM` | Month of a year	| "11"
| `MMM`| Month of a year	| "Nov"
| `MMMM` | Month of a year	| "November"
| `MMMMM`| Month of a year	| "N"
| `d` or `dd`	| Day of a month| "10"
| `Q`, `QQQQQ` or `q` | Quarter of a year	| "2"
| `QQ` or `qq` | Quarter of a year	| "02"
| `QQQ` | Quarter of a year	| "Q2"
| `QQQQ` | Quarter of a year	| "2nd quarter"
| `Y`, `YYY`, `YYYY` | _Week-based_ year	| "2021"
| `Y`, `YYY`, `YYYY` | _Week-based_ year	| "21"
| `w`	or `ww`| Week of a _week-based_ year | "27"
| `W`	| Week of the month	| "4"
| `E`, `EE`, OR `EEEE`	| Day of a week	| "Sunday"
| `EEE`	| Day of a week	| "Sun"
| `EEEEE`	| Day of a week	| "S" for Saturday or Sunday
| `e` or `c`	| Localized day of a week	| "7"
| `ee`	| Localized day of a week	| "07"
| `ee`	| Localized day of a week	| "07"
| `eee` or `ccc`	| Localized day of a week	| "Sat"
| `eeee` or `cccc`	| Localized day of a week	| "Saturday"
| `eeeee`	| Localized day of a week	| "S" for Saturday or Sunday
| `ccccc`	| Localized day of a week	| "6" for sixth day of the week
| `F`	| Day of week as a number | "3"
| `a`	| a.m. or p.m. | "PM" or "AM"
| `h`	| Clock hour (1-12) | "12"
| `K`	| Clock hour of a.m. or p.m. (0-11) | "7"
| `KK`	| Clock hour of a.m. or p.m. (0-11) | "07"
| `k`	or `kk`| Clock hour (1-24) of a.m. or p.m. | "19", "24"
| `H` or `HH`	| Clock hour of a day (0-23) | "19"
| `m`	| Minutes of a hour | "30"
| `s`	| Seconds of a hour | "59", "0"
| `S`	| Fraction of a second | "978"
| `A`	| Milliseconds of a day | "71101245"
| `n`	| Nanoseconds of a second | "216000000"
| `N`	| Nanoseconds of a day | "71155943000000"
| `VV`	| Timezone ID | "America/Los_Angeles", "GMT"
| `z`	| Timezone name | "PDT", "GMT"
| `zzzz`	| Timezone name | "Pacific Daylight Time", "Greenwich Mean Time"
| `O` or `OOOO`	| Localized timezone offset | "GMT", "GMT-07:00"
| `X` or `XX`	| Timezone offset	| "-07", "Z"
| `XXX`	| Timezone offset	| "-07:00", "Z"
| `XXXX` or `XXXXX`	| Timezone offset	| "-0700", "Z"
| `x`	| Timezone offset	| "+00", "-07"
| `xx` or `xxxx` | Timezone offset	| "+0000", "-0700"
| `xxx` or `xxxxx` | Timezone offset	| "+00:00", "-07:00"
| `Z`, `ZZ`, or `ZZZ`	| Timezone offset	| "-0700", "+0000"
| `ZZZZ`	| Timezone offset	| "GMT-07:00", "GMT"
| `ZZZZZ`	| Timezone offset	| "-07:00", "Z"
|===

== See Also

* xref:dataweave-types-coercion.adoc#type-coercion-table[Type Coercion Table]
