= DataWeave Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

DataWeave 2.0 functions are packaged in modules.
//DW 1.0 OPERATORS IN MULE 3.9 DOCS
include::partial$dataweave1-links.adoc[tag=dataweave1Operators]

Functions in the Core (`dw::Core`) module are imported automatically into your DataWeave scripts. To use other modules, you need to import the module or functions you want to use by adding the import directive to the head of your DataWeave script, for example:

* `import dw::core::Strings`
* `import camelize, capitalize from dw::core::Strings`
* `import * from dw::core::Strings`

The way you import a module impacts the way you need to call its functions from a DataWeave script. If the directive does not list specific functions to import or use `* from` to import all functions from a function module, you need to specify the module when you call the function from your script. For example, this import directive does not identify any functions to import from the String module, so it calls the `pluralize` function like this: `Strings::pluralize("box")`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
import dw::core::Strings
output application/json
---
{ 'plural': Strings::pluralize("box") }
----

The next example identifies a specific function to import from the String module, so it can call the method like this: `pluralize("box")`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
import pluralize from dw::core::Strings
output application/json
---
{ 'plural': pluralize("box") }
----

The next example imports all functions from the String module, so it can call the method like this: `pluralize("box")`.

.Transform
[source,dataweave,linenums]
----
%dw 2.0
import * from dw::core::Strings
output application/json
---
{ 'plural': pluralize("box") }
----

[[dw_modules]]
== DataWeave Modules

* xref:dw-arrays.adoc[Arrays (dw::core::Arrays)]

* xref:dw-binaries.adoc[Binaries (dw::core::Binaries)]

* xref:dw-core.adoc[Core (dw::Core)]

* xref:dw-crypto.adoc[Encryption (dw::Crypto)]

* xref:dw-diff.adoc[Diff (dw::util::Diff)]

* xref:dw-objects.adoc[Objects (dw::core::Objects)]

* xref:dw-runtime.adoc[Runtime (dw::Runtime)]

* xref:dw-strings.adoc[Strings (dw::core::Strings)]

* xref:dw-system.adoc[System (dw::System)]

* xref:dw-url.adoc[URL (dw::core::URL)]

== Function Signatures

Each DataWeave function in the reference is identified by its function signature, such as xref:dw-core-functions-contains.adoc#contains2[contains(String, String): Boolean] for the `contains` function. This function has two parameters, each of which accepts a value of the String type. The function returns as Boolean value. The parameters in the function correspond, _in order_, to the xref:dw-core-functions-contains.html#parameters-2[named parameters], `text` for the first parameter and `toSearch` for the second.

Basic syntax of a two-parameter function:

`function(parameterType,parameterType): returnType`

Many functions are overloaded to handle different data types. There is a unique function signature for each variant of the function. For example, xref:dw-core-functions-isempty.adoc[isEmpty] is overloaded to support an input value of an Array, String, Object, or Null type.

Function signatures can contain type parameters, which are similar to generics in some programming languages. For example, the `Array<T>` in `contains(Array<T>, Any): Boolean` indicates that the array can contain elements of any type (`T`) that DataWeave supports.

Some parameters within function signatures are lambdas that take one or more parameters of the form `variable:Type` with a transformation expression (`-> expression`). For example, the lambda `(item: T, index: Number) -> R)` is a parameter of the `map` function (`map(Array<T>, (item: T, index: Number) -> R): Array<R>`. The lambda accepts a value of type `T` and a value of type Number, which serve as parameters to the expression `R`. For a complete example, see xref:dw-core-functions-map.adoc[map].

For more information on the data types, see xref:dataweave-type-system.adoc[Type System].


[[see_also]]
== See Also

xref:dataweave.adoc[About DataWeave]

xref:dataweave-quickstart.adoc[DataWeave Quickstart]
