= mergeWith
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[mergewith1]]
== mergeWith<T <: Object, V <: Object&#62;&#40;source: T, target: V&#41;: ?

Appends any key-value pairs from a source object to a target object.


If source and target objects have the same key, the function appends
that source object to the target and removes that target object from the output.

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `source` | The object to append to the `target`.
| `target` | The object to which the `source` object is appended.
|===

=== Example

This example appends the source objects to the target. Notice that
`"a" : true,` is removed from the output, and `"a" : false` is appended
to the target.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import mergeWith from dw::core::Objects
output application/json
---
{ "mergeWith" : { "a" : true, "b" : 1} mergeWith { "a" : false, "c" : "Test"} }
----

==== Output

[source,JSON,linenums]
----
"mergeWith": {
    "b": 1,
    "a": false,
    "c": "Test"
}
----


[[mergewith2]]
== mergeWith<T <: Object&#62;&#40;a: Null, b: T&#41;: T

Helper function that enables `mergeWith` to work with a `null` value.


[[mergewith3]]
== mergeWith<T <: Object&#62;&#40;a: T, b: Null&#41;: T

Helper function that enables `mergeWith` to work with a `null` value.

