= DataWeave Operators
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

DataWeave 2.0 supports several mathematical, equality, relational, logical,
prepend, and append operators.

== Mathematical Operators

DataWeave 2.0 supports the most common mathematical operators:

[%header,cols="1,2"]
|===
| Operator | Description
| `+` | For addition
| `-` | For subtraction.
| `*` | For multiplication.
| `/`  | For division.
|===

These examples use mathematical operators:

.Source
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{ "mathOperators" : [
    { "2 + 2" : (2 + 2) },
    { "2 - 2" : (2 - 2) },
    { "2 * 2" : (2 * 2) },
    { "2 / 2" : (2 / 2) }
  ]
}
----

.Output
[source,json,linenums]
----
{
  "mathOperators": [
    { "2 + 2": 4 },
    { "2 - 2": 0 },
    { "2 * 2": 4 },
    { "2 / 2": 1.0 }
  ]
}
----

Note that several DataWeave functions operate on numbers, for example: xref:dw-core-functions-sum.adoc[sum], xref:dw-core-functions-mod.adoc[mod] (for modulo), and xref:dw-core-functions-abs.adoc[avg] (for average).

== Equality and Relational Operators

DataWeave 2.0 supports the following equality and relational operators:

[%header,cols="1,2"]
|===
| Operator | Description
| `<` | For less than.
| `>` | For greater than.
| `&lt;=` | For less than or equal to.
| `>=` | For greater than or equal to.
| `==` | For equal to.
| `~=` | Equality operator that tries to coerce one value to the type of the other when the types are different.
|===

Note that you can negate these operators by using the <<logical_operators, logical operator>>, `not`.

These examples use relational operators:

.Source
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{ "relational" : [
    { "1 < 1" : (1 < 1) },
    { "1 > 2" : (1 > 2) },
    { "1 <= 1" : (1 <= 1) },
    { "1 >= 1" : (1 >= 1) }
  ]
}
----

.Output
[source,json,linenums]
----
"relational": [
    { "(1 < 1)": false },
    { "(1 > 2)": false },
    { "(1 <= 1)": true },
    { "(1 >= 1)": true }
  ]
}
----

These examples use equality operators:

.Source
[source,dataweave,linenums]
----
%dw 2.0
output application/dw
---
{ "equality" :
  [
    (1 == 1),
    (1 == 2),
    ("true" == true),
    ("true" ~= true),
    (['true'] ~= [true]),
    ('1' ~= 1)
  ]
}
----

.Output
[source,text,linenums]
----
{
  equality: [ true, false, false, true, true, true ]
}
----

[[logical_operators]]
== Logical Operators

The following logical operators are supported.

[%header,cols="1,2"]
|===
| Operator | Description
| `not` | Negates the result of the input. See also, `!`.
| `!` | Negates the result of the input. See also, `not`. _Introduced in DataWeave 2.2.0. Supported by Mule 4.2 and later._
| `and` | Returns `true` if the result of all inputs is true, `false` if not.
| `or` | Returns `true` if the result of any input is true, `false` if not.
|===

NOTE: Though the semantics of `not` and `!` are the same, their precedence
differs. `not true or true` is executed as `not (true or true)`,
so it returns `false`, whereas `!true or true` returns `true` because
the `!` only applies to the first `true`. `!(true or true)` returns
`true`.

These examples show uses of these operators:

.Source
[source,dataweave,linenums]
----
%dw 2.0
output application/json
var myArray = [1,2,3,4,5]
var myMap = myArray map not (($ mod 2) == 0)
---
{
  "not" : [
    "notTrue" : not true,
    "notFalse" : not false,
    "myMapWithNot" : myMap
  ],
  "and" : [
    "andTrueFalse" : true and false,
    "andIsTrue" : (1 + 1 == 2) and (2 + 2 == 4),
    "andIsFalse" : (1 + 1 == 2) and (2 + 2 == 2)
  ],
  "or" : [
    "orTrueFalse" : true or false,
    "orIsTrue" : (1 + 1 == 2) or (2 + 2 == 2),
    "orIsFalse" : (1 + 1 == 1) or (2 + 2 == 2)
  ],
  "!-vs-not" : [
	  "example-!" : (! true or true),
	  "example-not" : (not true or true)
  ]
}
----

Note that `myMap` iterates through the items in a list (`myArray`) and
determines whether the modulo (`mod`) expression _does not_ evaluate to `0` when
applied to each given item.

.Output
[source,json,linenums]
----
{
  "not": [
    { "notTrue": false },
    { "notFalse": true },
    { "myMapWithNot": [ true, false, true, false, true ] }
  ],
  "and": [
    { "andTrueFalse": false },
    { "andIsTrue": true },
    { "andIsFalse": false }
  ],
  "or": [
    { "orTrueFalse": true },
    { "orIsTrue": true },
    { "orIsFalse": false }
  ],
  "!-vs-not": [
    { "example-!": true },
    { "example-not": false }
  ]
}
----

Note that `not` works in expressions such as `not (true)`, but `not(true)`
(without the space) does not work.


You can use logical operators together. The next example uses `or not` as defined in the `orNot` expression, uses `and not` in `andNot`, and uses `not` and `and not` in `notWithAndNot`.

.Example: Using Logical Operators Together
[source,dataweave,linenums]
----
%dw 2.0
output application/json
var orNot = if (1 + 1 == 4 or not 1 == 2) {"answer": "foo"}
             else {"answer": "nope"}
var andNot = if (1 + 1 == 2 and not 1 == 2) {"answer": "bar"}
             else {"answer": "nope"}
var notWithAndNot = if (not (1 + 1 == 2 and not 1 == 1)) {"answer": "foobar"}
              else {"answer": "nope"}
---
{ "answers" :
  [
    orNot,
    andNot,
    notWithAndNot
  ]
}
----

.Output
[source,json,linenums]
----
{
  "answers": [
    { "answer": "foo" },
    { "answer": "bar" },
    { "answer": "foobar" }
  ]
}
----

== Prepend, Append, and Remove Operators for Arrays

DataWeave 2.0 supports operators for appending and prepending items within
an array.

[%header,cols="1,2"]
|===
| Operator | Description
| `>>` | Prepends data on the left-hand side of the operator to items in the
         array on the right-hand side. For example, `1 >> [2]` results in `[ 1, 2 ]`,
         prepending `1` to `2` in the array.
| `<<` | Appends data on the right-hand side of the operator to items in the
         array on the left-hand side. For example, `[1] << 2` results in `[ 1, 2 ]`,
         appending `2` to `1` in the array.
| `+` | Appends data on the right-hand side of the operator to items in the
        array on the left-hand side. For example, `[1] + 2` results in `[ 1, 2 ]`,
        appending `2` to `1` in the array. The array is always on the left-hand side
        of the operator.
| `-` | Removes a specified element of any supported type from an array.
|===

These examples show uses of these operators:

.Example: Using Prepend and Append Operators
[source,dataweave,linenums]
----
%dw 2.0
output application/json
---
{
  "prepend-append" : [
  	 // Array on right side when prepending.
     { "prepend" : 1 >> [2] },
     { "prepend-number" : 1 >> [1] },
     { "prepend-string" : "a" >> [1] },
     { "prepend-object" : { "a" : "b"} >> [1] },
     { "prepend-array" : [1] >> [2, 3] },
     { "prepend-binary" : (1 as Binary) >> [1] },
     { "prepend-date-time" : |23:57:59Z| >> [ |2017-10-01| ] },
  	 // Array is on left side when appending.
     { "append-number" : [1] << 2 },
     { "append-string" : [1] << "a" },
     { "append-object" : [1] << { "a" : "b"} },
     { "append-array" : [1,2] << [1, 2, 3] },
     { "append-binary" : [1] << (1 as Binary) },
     { "append-date-time" : [ |2017-10-01| ] << |23:57:59Z| },
     { "append-object-to-array" : [1,2] << {"a" : "b"} },
     { "append-array-to-array1" : ["a","b"] << ["c","d"] },
     { "append-array-to-array2" : [["a","b"],["c","d"]] << ["e","f"] },
     // + always appends within the array
     { "append-with-+" : [1] + 2 },
     { "append-with-+" : [2] + 1 },
     { "removeNumberFromArray" : ( [1,2,3] - 2 ) },
     { "removeObjectFromArray" : ( [ {a : "b"}, {c : "d"} , { e : "f"} ] - { c : "d"} ) }
  ]
}
----

.Output
[source,json,linenums]
----
{
  "prepend-append": [
    { "prepend": [ 1, 2 ] },
    { "prepend-number": [ 1, 1 ] },
    { "prepend-string": [ "a", 1 ] },
    { "prepend-array": [ [ 1 ], 2, 3 ] },
    { "prepend-object": [ { "a": "b" }, 1 ] },
    { "prepend-binary": [ "\u0001", 1 ] },
    { "prepend-date-time": [ "23:57:59Z", "2017-10-01" ] },
    { "append-number": [ 1, 2 ] },
    { "append-string": [ 1, "a" ] },
    { "append-object": [ 1, { "a": "b" } ] },
    { "append-array": [ 1, 2, [ 1, 2, 3 ] ] },
    { "append-binary": [ 1, "\u0001" ] },
    { "append-date-time": [ "2017-10-01", "23:57:59Z" ] },
    { "append-object-to-array": [ 1, 2, { "a": "b" } ] },
    { "append-array-to-array1": [ "a", "b", ["c","d"] ] },
    { "append-array-to-array2": [ ["a","b"], ["c","d"], ["e","f"] ] },
    { "append-with-+": [ 1, 2] },
    { "append-with-+": [ 2, 1] },
    { "removeNumberFromArray": [ 1, 3 ] },
    { "removeObjectFromArray": [ { "a": "b" }, { "e": "f" } ] }
  ]
}
----
