= someEntry
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[someentry1]]
== someEntry&#40;obj: Object, condition: &#40;value: Any, key: Key&#41; &#45;&#62; Boolean&#41;: Boolean

Returns `true` if at least one entry in the object matches the specified condition.


The function stops iterating after the first element that matches the condition is found.

_Introduced in DataWeave 2.3.0. Supported by Mule 4.3 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `obj` | The object to evaluate.
| `condition` | The condition to use when evaluating elements in the object.
|===

=== Example

This example shows how the `someEntry` behaves with different inputs.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import someEntry from dw::core::Objects
output application/json
---
{
    a: {} someEntry (value, key) -> value is String,
    b: {a: "", b: "123"} someEntry (value, key) -> value is String,
    c: {a: "", b: 123} someEntry (value, key) -> value is String,
    d: {a: "", b: 123} someEntry (value, key) -> key as String == "a",
    e: {a: ""} someEntry (value, key) -> key as String == "b",
    f: null someEntry (value, key) -> key as String == "a"
}

----

==== Output

[source,Json,linenums]
----
{
  "a": false,
  "b": true,
  "c": true,
  "d": true,
  "e": false,
  "f": false
}
----


[[someentry2]]
== someEntry&#40;obj: Null, condition: &#40;value: Nothing, key: Nothing&#41; &#45;&#62; Boolean&#41;: Boolean

Helper function that enables `someEntry` to work with a `null` value.


_Introduced in DataWeave 2.3.0. Supported by Mule 4.3 and later._

