= Runtime Types (dw::Runtime)

|===
| Type | Definition | Description

| DataFormatDescriptor
| `type DataFormatDescriptor = { name: String, binary: Boolean, defaultEncoding?: String, extensions: Array<String&#62;, defaultMimeType: String, acceptedMimeTypes: Array<String&#62;, readerProperties: Array<DataFormatProperty&#62;, writerProperties: Array<DataFormatProperty&#62; }`
| *EXPERIMENTAL*

Describes a DataFormat providing all the metadata information.


| DataFormatProperty
| `type DataFormatProperty = { name: String, optional: Boolean, defaultValue?: Any, description: String, possibleValues: Array<Any&#62; }`
| 


| EvalSuccess
| `type EvalSuccess = { success: true, value: Any, logs: Array<LogEntry&#62; }`
| *EXPERIMENTAL*

When the *eval* function executes with no problem


| ExecutionFailure
| `type ExecutionFailure = { success: false, message: String, kind: String, stack?: Array<String&#62;, location: Location, logs: Array<LogEntry&#62; }`
| *EXPERIMENTAL*

When the *run* or *eval* function failed.


| Location
| `type Location = { start?: Position, end?: Position, content: String }`
| 


| LogEntry
| `type LogEntry = { level: LogLevel, timestamp: String, message: String }`
| 


| LogLevel
| `type LogLevel = "INFO" &#124; "ERROR" &#124; "WARN"`
| 


| LoggerService
| `type LoggerService = { /**
* This function is going to be called when the execution starts.
* The result is going to be sent in every log so for example if some logging header needs to be sent it could be done at initialize and then recover in each log.
**/
initialize?: &#40;&#41; &#45;&#62; Object, /**
* This log method is going to be called on every log message
**/
log: &#40;level: LogLevel, msg: String, context: Object&#41; &#45;&#62; Any, /**
* When the execution finished it is going to be called. Good time to flush any buffer or to gracefully logout.
**/
shutdown?: &#40;&#41; &#45;&#62; Boolean }`
| *EXPERIMENTAL*

This service handles all the logging.


| MimeType
| `type MimeType = String`
| A MimeType represented in a String


| Position
| `type Position = { index: Number, line: Number, column: Number }`
| 


| ReaderInput
| `type ReaderInput = { /**
* The actual input
**/
value: Binary, /**
* The encoding to be used
**/
encoding?: String, /**
* The reader properties to be used to parse this input
**/
properties?: Dictionary<SimpleType&#62;, /**
* The mimeType of this input.
**/
mimeType: MimeType }`
| *EXPERIMENTAL*

An Reader Input. This is input is going to be used as the source content of the reader created by the specified *mimeType*


| RunSuccess
| `type RunSuccess = { success: true, value: Binary, mimeType: MimeType, encoding?: String, logs: Array<LogEntry&#62; }`
| *EXPERIMENTAL*

When the *run* function executes with no problem


| RuntimeExecutionConfiguration
| `type RuntimeExecutionConfiguration = { /**
* The max time this script should take.
**/
timeOut?: Number, /**
* The default output mimeType if it is not specified in the script
**/
outputMimeType?: MimeType, /**
* The writer properties to be used when the specified the *outputMimeType* property.
**/
writerProperties?: Dictionary<SimpleType&#62;, /**
* When an the execution fails what it should happen. When *Handle* &#40;default value&#41; is specify the execution will return *ExecutionFailure* if *Fail* is specify
* then the *Exception* is going to be propagated.
**/
onException?: "HANDLE" &#124; "FAIL", /**
* The *SecurityManager* to use in this execution. This security manager is going to be composed with the *current* SecurityManager.
**/
securityManager?: SecurityManager, /**
* The *LoggerService* to be used in this execution.
**/
loggerService?: LoggerService, /**
* The Max stack size
**/
maxStackSize?: Number }`
| *EXPERIMENTAL*

Configures the runtime execution with some advance parameters.


| SecurityManager
| `type SecurityManager = &#40;grant: String, args: Array<Any&#62;&#41; &#45;&#62; Boolean`
| *EXPERIMENTAL*

This function is going to be called every time some privilege needs to be granted to the current execution.
The *grant* is the name of the Privilege i.e: *Resource*
The *args* represents the list of parameters the function that is requesting the Privilege is being called.


| TryResult
| `type TryResult = { success: Boolean, result?: T, error?: { kind: String, message: String, stack?: Array<String&#62;, /**
* Since 4.4.0. It is only available when stack is not present. It will contain the native java stacktrace.
**/
stackTrace?: String, location?: String } }`
| Object with a result or error message. If `success` is `false`, it contains
the `error`. If `true`, it provides the `result`.

|===