= substringEvery
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[substringevery1]]
== substringEvery&#40;text: String, amount: Number&#41;: Array<String&#62;

Splits a string into an array of substrings equal to a specified length.


The last substring can be shorter than that length. If the length
is greater than or equal to the length of the string to split, the
function returns the entire string.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to split.
| `amount` | The desired length of each substring.
|===

=== Example

This example shows how `substringEvery` behaves when splitting an
input string. The last returned substring is shorter than the others.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import substringEvery from dw::core::Strings
output application/json
---
substringEvery("substringEvery", 3)
----

==== Output

[source,Json,linenums]
----
["sub", "str", "ing", "Eve", "ry"]
----


[[substringevery2]]
== substringEvery&#40;text: Null, amount: Any&#41;: Null

Helper function that enables `substringEvery` to work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

