= withMaxSize
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[withmaxsize1]]
== withMaxSize&#40;text: String, maxLength: Number&#41;: String

Checks that the string length is no larger than the specified `maxLength`.
If the string's length is larger than the `maxLength`, the function cuts
characters from left to right, until the string length meets the length limit.


_Introduced in DataWeave 2.3.0. Supported by Mule 4.3 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name | Description
| `text` | The input string.
| `maxLength` | The maximum length of the string.
|===

=== Example

This example shows how `withMaxSize` behaves with different inputs and sizes.
Note that if `withMaxSize` is 0, the function returns an empty string. If
the input is `null`, the output is always `null`.

==== Source

[source,DataWeave, linenums]
----
%dw 2.0
import withMaxSize from dw::core::Strings
output application/json
---
{
   a: "123" withMaxSize 10,
   b: "123" withMaxSize 3,
   c: "123" withMaxSize 2,
   d: "" withMaxSize 0,
   e: null withMaxSize 23,
}
----

==== Output

[source,JSON,linenums]
----
{
  "a": "123",
  "b": "123",
  "c": "12",
  "d": "",
  "e": null
}
----


[[withmaxsize2]]
== withMaxSize&#40;text: Null, maxLength: Number&#41;: Null

Helper function that enables `withMaxSize` to work with a `null` value.

