= countMatches
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[countmatches1]]
== countMatches&#40;text: String, pattern: String&#41;: Number

Count the number of times `pattern` appears in `text`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The text to look in.
| `pattern` | The pattern to look for.
|===

=== Example

This example shows how the `countMatches` can be used to count for a string.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import countMatches from dw::core::Strings
output application/json
---
"hello worlo!" countMatches "lo"

----

==== Output

[source,Json,linenums]
----
2
----


[[countmatches2]]
== countMatches&#40;text: String, pattern: Regex&#41;: Number

Count the number of times `pattern` matches in `text`.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The text to look in
| `pattern` | The regex to match with
|===

=== Example

This example shows how the `countMatches` can be used to count for vowels.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import countMatches from dw::core::Strings
output application/json
---
"hello worlo!" countMatches /[aeiou]/

----

==== Output

[source,Json,linenums]
----
4
----


[[countmatches3]]
== countMatches&#40;text: Null, pattern: Any&#41;: Null

Helper function to make `countMatches` work with `null`

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

