= substringBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[substringby1]]
== substringBy&#40;text: String, predicate: &#40;character: String, index: Number&#41; &#45;&#62; Boolean&#41;: Array<String&#62;

Splits a string at each character where the `predicate` expression
returns `true`.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to split. The string is treated as an array of characters.
| `predicate` | Expression that tests each character and returns a
                Boolean value. The expression can iterate over each
                character and index of the string.
|===

=== Example

This example splits a string where any of the specified characters
(`"~"`, `"="`, or `"_"`) are present.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import substringBy from dw::core::Strings
output application/json
---
"hello~world=here_data-weave" substringBy $ == "~" or $ == "=" or $ == "_"
----

==== Output

[source,Json,linenums]
----
["hello", "world", "here", "data-weave"]
----


[[substringby2]]
== substringBy&#40;text: Null, predicate: &#40;character: Nothing, index: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function that enables `substringBy` to work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

