= first
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[first1]]
== first&#40;text: String, amount: Number&#41;: String

Returns characters from the beginning of a string to the
specified number of characters in the string, for example,
the first two characters of a string.


If the number is equal to or greater than the number of characters
in the string, the function returns the entire string.

_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to process.
| `amount` | The number of characters to return. Negative
             numbers and `0` return an empty string. Decimals
             are rounded down to the nearest whole number.
|===

=== Example

This example returns the first five characters from a string.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import first from dw::core::Strings
output application/json
---
"hello world!" first 5
----

==== Output

[source,Json,linenums]
----
"hello"
----


[[first2]]
== first&#40;text: Null, amount: Any&#41;: Null

Helper function that enables `first` to work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

