= countMatches
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[countmatches1]]
== countMatches&#40;text: String, pattern: String&#41;: Number

Counts the number of matches in a string.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to search for matches.
| `pattern` | A substring to find in the text.
|===

=== Example

This example counts matches in a string.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import countMatches from dw::core::Strings
output application/json
---
"hello worlo!" countMatches "lo"
----

==== Output

[source,Json,linenums]
----
2
----


[[countmatches2]]
== countMatches&#40;text: String, pattern: Regex&#41;: Number

Counts the number of times a regular expression matches text in a string.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to search for matches.
| `pattern` | The regex pattern to use in the search.
|===

=== Example

This example counts the vowels in a string.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import countMatches from dw::core::Strings
output application/json
---
"hello, ciao!" countMatches /[aeiou]/
----

==== Output

[source,Json,linenums]
----
5
----


[[countmatches3]]
== countMatches&#40;text: Null, pattern: Any&#41;: Null

Helper function that enables `countMatches` to work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

