= countCharactersBy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[countcharactersby1]]
== countCharactersBy&#40;text: String, predicate: &#40;character: String&#41; &#45;&#62; Boolean&#41;: Number

Counts the number of times an expression that iterates through
each character in a string returns `true`.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `text` | The string to which the `predicate` applies.
| `predicate` | Expression to apply to each character in the
                `text` string. The expression must return a
                Boolean value.
|===

=== Example

This example counts the digits in a string.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import countCharactersBy from dw::core::Strings
output application/json
---
"42 = 11 * 2 + 20" countCharactersBy isNumeric($)
----

==== Output

[source,Json,linenums]
----
7
----


[[countcharactersby2]]
== countCharactersBy&#40;text: Null, predicate: &#40;character: Nothing&#41; &#45;&#62; Any&#41;: Null

Helper function to make `countCharactersBy` work with a `null` value.


_Introduced in DataWeave 2.4.0. Supported by Mule 4.4 and later._

