= URL Types (dw::core::URL)

|===
| Type | Definition | Description

| URI
| `type URI = { isValid: Boolean, host?: String, authority?: String, fragment?: String, path?: String, port?: Number, query?: String, scheme?: String, user?: String, isAbsolute?: Boolean, isOpaque?: Boolean }`
a| Describes the URI type, which consists of the following fields:

* `isValid`: Boolean that indicates whether the URI is valid.
* `host`: String representing the host name (for example,
  `+my.company.com+` from `+http://my.company.com:8080/hello+`)
* `authority`: String representing the authority, which includes the host
   and port (for example, `+my.company.com:8080+` from
  `+http://my.company.com:8080/hello+`).
* `fragment`: String representing the subordinate resource after the `#` in
              the URI (for example, `footer` in the URI
              `+"https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#footer"+`).
* `path`: String representing a path following the host or authority (for example,
          for example, `/hello` in `+http://my.company.com:8080/hello+`) .
* `port`: Number representing an explicit port in the URI (for example, `8080`
          in +http://my.company.com:8080/hello+`). If no port is specified
          (for example, `+http://my.company.com/hello+`), the value is `null`.
* `query`: String identifying a query (for example, `field=value` in
           '+http://my.company.com:1234/hello/?field=value+').
* `scheme`: String identifying the URI scheme, such as `https` or `http`,
            which appears before a colon (`:`).
* `user`: String representing user information in a URI (for example, the
          `myname` in `+http://myname@www.mycompany.com+`).
* `isAbsolute`: `true` if the URI contains a scheme, `false` if the URI is
                relative (for example, `/path/to/somewhere`).
* `isOpaque`: `true` if the scheme of the URI begins with a slash (`/`).
               `+mailto:somebody@somewhere.com+` returns `false`.

|===
