= Values (dw::util::Values)

This utility module simplifies changes to values.


The module is included with Mule runtime. To use it, you must import it into
your DataWeave code, for example, by adding the line
`import * from dw::util::Values` to the header of your script.

_Introduced in DataWeave 2.2.2. Supported by Mule 4.2.2 and later._

== Functions

[%header, cols="1,3"]
|===
| Name  | Description
| xref:dw-values-functions-attr.adoc[attr] | This function creates a `PathElement` to use for selecting an XML
attribute and populates the type's `selector` field with the given string.
| xref:dw-values-functions-field.adoc[field] | This function creates a `PathElement` data type to use for selecting an
_object field_ and populates the type's `selector` field with the given
string.
| xref:dw-values-functions-index.adoc[index] | This function creates a `PathElement` data type to use for selecting an
_array element_ and populates the type's `selector` field with the specified
index.
| xref:dw-values-functions-mask.adoc[mask] | Helper function that enables `mask` to work with a `null` value.
| xref:dw-values-functions-update.adoc[update] | This `update` function updates a field in an object with the specified
string value.
|===

== Types
* xref:dw-values-types.adoc[Values Types]


