= update
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[update1]]
== update&#40;objectValue: Object, fieldName: String&#41;: UpdaterValueProvider<Object&#62;

This `update` function updates a field in an object with the specified
string value.


The function returns a new object with the specified field and value.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `objectValue` | The object to update.
| `fieldName` | A string that provides the name of the field.
|===

=== Example

This example updates the `name` field in the object `{name: "Mariano"}` with
the specified value.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
{name: "Mariano"} update "name" with "Data Weave"
----

==== Output

[source,Json,linenums]
----
{
  "name": "Data Weave"
}
----


[[update2]]
== update&#40;objectValue: Object, fieldName: PathElement&#41;: UpdaterValueProvider<Object&#62;

This `update` function updates an object field with the specified
 `PathElement` value.


The function returns a new object with the specified field and value.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `objectValue` | The object to update.
| `fieldName` | A `PathElement` that specifies the field name.
|===

=== Example

This example updates the value of a `name` field in the object
`{name: "Mariano"}`. It uses `field("name")` to return the `PathElement`
that it passes to `update`. It uses `with "Data Weave"` to specify the value
(`Data Weave`) of `name`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
{name: "Mariano"} update field("name") with "Data Weave"
----

==== Output

[source,Json,linenums]
----
{
  "name": "Data Weave"
}
----


[[update3]]
== update&#40;arrayValue: Array, indexToUpdate: Number&#41;: UpdaterValueProvider<Array&#62;

Updates an array index with the specified value.

This `update` function returns a new array that changes the value of
the specified index.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| objectValue | The array to update.
| indexToUpdate | The index of the array to update. The index must be a number.
|===

=== Example

This example replaces the value `2` (the index is `1`) with `5` in the
the input array `[1,2,3]`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
[1,2,3] update 1 with 5

----

==== Output

[source,Json,linenums]
----

[
   1,
   5,
   3
 ]
----


[[update4]]
== update&#40;arrayValue: Array, indexToUpdate: String&#41;: UpdaterValueProvider<Array&#62;

This `update` function updates all objects within the specified array with
the given string value.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `objectValue` | The array of objects to update.
| `indexToUpdate` | A string providing the name of the field to update.
|===

=== Example

This example updates value of the `role` fields in the array of objects.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
[{role: "a", name: "spiderman"}, {role: "b", name: "batman"}] update "role" with "Super Hero"
----

==== Output

[source,Json,linenums]
----

[{
   "role": "Super Hero",
   "name": "spiderman"
 },
 {
   "role": "Super Hero",
   "name": "batman"
}]
----


[[update5]]
== update&#40;arrayValue: Array, indexToUpdate: PathElement&#41;: UpdaterValueProvider<Array&#62;

This `update` function updates the specified index of an array with the
given `PathElement` value.

The function returns a new array that contains given value at
the specified index.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `objectValue` | The array to update.
| `indexToUpdate` | The index of the array to update. The index must be specified as a `PathElement`.
|===

=== Example

This example updates the value of an element in the input array. Notice
that it uses `index(1)` to return the index as a `PathElement`, which
it passes to `update`. It replaces the value `2` at that index with `5`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
[1,2,3] update index(1) with 5

----

==== Output

[source,Json,linenums]
----

[
   1,
   5,
   3
 ]
----


[[update6]]
== update&#40;value: Array &#124; Object &#124; Null, path: Array<String &#124; Number &#124; PathElement&#62;&#41;: UpdaterValueProvider<Array &#124; Object &#124; Null&#62;

Updates the value at the specified path with the given value.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `objectValue` | The value to update. Accepts an array, object, or null value.
| `path` | The path to update. The path must be an array of strings, numbers, or `PathElement`s.
|===

=== Example

This example updates the name of the user.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
import * from dw::util::Values
output application/json
---
{user: {name: "Mariano"}} update ["user", field("name")] with "Data Weave"

----

==== Output

[source,Json,linenums]
----

{
   "user": {
     "name": "Data Weave"
   }
 }
----


[[update7]]
== update&#40;value: Null, toUpdate: Number &#124; String &#124; PathElement&#41;: UpdaterValueProvider<Null&#62;

Helper function that enables `update` to work with a `null` value.

