= mask
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]



[[mask1]]
== mask&#40;value: Null, fieldName: String &#124; Number &#124; PathElement&#41;: &#40;newValueProvider: &#40;oldValue: Any, path: Path&#41; &#45;&#62; Any&#41; &#45;&#62; Null

Helper function that enables `mask` to work with a `null` value.


[[mask2]]
== mask&#40;value: Any, selector: PathElement&#41;: &#40;newValueProvider: &#40;oldValue: Any, path: Path&#41; &#45;&#62; Any&#41; &#45;&#62; Any

This `mask` function replaces all _simple_ elements that match the specified
criteria.


Simple elements do not have child elements and cannot be objects or arrays.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | A value to use for masking. The value can be any DataWeave type.
| `selector` | The `PathElement` selector.
|===

=== Example

This example shows how to mask the value of a `password` field in
an array of objects. It uses `field("password")` to return the `PathElement`
that it passes to `mask`. It uses `with "*****"` to specify the value
(`*****`) to use for masking.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
import * from dw::util::Values
---
[{name: "Peter Parker", password: "spiderman"}, {name: "Bruce Wayne", password: "batman"}] mask field("password") with "*****"
----

==== Output

[source,Json,linenums]
----
[
   {
     "name": "Peter Parker",
     "password": "*****"
   },
   {
     "name": "Bruce Wayne",
     "password": "*****"
   }
 ]
----


[[mask3]]
== mask&#40;value: Any, fieldName: String&#41;: &#40;newValueProvider: &#40;oldValue: Any, path: Path&#41; &#45;&#62; Any&#41; &#45;&#62; Any

This `mask` function selects a field by its name.


=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | The value to use for masking. The value can be any DataWeave type.
| `fieldName` | A string that specifies the name of the field to mask.
|===

=== Example

This example shows how to perform masking using the name of a field in the
input. It modifies the values of all fields with that value.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
import * from dw::util::Values
---
[{name: "Peter Parker", password: "spiderman"}, {name: "Bruce Wayne", password: "batman"}] mask "password" with "*****"
----

==== Output

[source,Json,linenums]
----
[
   {
     "name": "Peter Parker",
     "password": "*****"
   },
   {
     "name": "Bruce Wayne",
     "password": "*****"
   }
 ]
----


[[mask4]]
== mask&#40;value: Any, i: Number&#41;: &#40;newValueProvider: &#40;oldValue: Any, path: Path&#41; &#45;&#62; Any&#41; &#45;&#62; Any

This `mask` function selects an element from array by its index.

=== Parameters

[%header, cols="1,3"]
|===
| Name   | Description
| `value` | The value to mask. The value can be any DataWeave type.
| `index` | The index to mask. The index must be a number.
|===

=== Example

This example shows how `mask` acts on all elements in the nested arrays.
It changes the value of each element at index `1` to `false`.

==== Source

[source,DataWeave,linenums]
----
%dw 2.0
output application/json
import * from dw::util::Values
---
[[123, true], [456, true]] mask 1 with false

----

==== Output

[source,Json,linenums]
----
[
   [
     123,
     false
   ],
   [
     456,
     false
   ]
 ]
----

