= Encryption Strategies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Security Manager can be configured with one or more encryption strategies that can then be used by encryption transformers, security filters, or secure transports such as xref:ssl-and-tls-transports-reference.adoc[SSL] or xref:http-transport-reference.adoc[HTTPS]. These encryption strategies can greatly simplify configuration for secure messaging as they can be shared across components.

Following is an example of a password-based encryption strategy (PBE) that provides password-based encryption using JCE. Users must specify a password and optionally a salt and iteration count as well. The default algorithm is PBEWithMD5AndDES, but users can specify any valid algorithm supported by JCE.

[source,xml,linenums]
----
<security-manager>
    <password-encryption-strategy name="PBE" password="mule"/>
</security-manager>
----

This strategy can then be referenced by other components in the system such as filters or transformers.

[source,xml,linenums]
----
<decrypt-transformer name="EncryptedToByteArray" strategy-ref="PBE"/>

<service name="Svc1">
    <inbound>
        <inbound-endpoint address="vm://test">
            <encryption-security-filter strategy-ref="PBE"/>
        </inbound-endpoint>
    </inbound>
    ...cut...

<service name="Svc2">
    ...cut...
    <outbound>
        <pass-through-router>
            <outbound-endpoint address="vm://output" transformer-refs="EncryptedToByteArray"/>
        </pass-through-router>
    </outbound>
----