= Exception Filter
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: error handling, exceptions, exception catching, exceptions, filter

Purpose: +
Filters messages according to the type of an exception.

Minimum Configuration: +
The class that indicates the type of the exception.

Discussion: +
An Exception Filter matches the type of an exception you configure in the *Expected Type* field in the *Global Element* properties in Studio, or in the `expectedType` property in the Configuration XML.
For example, for a runtime exception type, you set *Expected Type* to `java.lang.RuntimeException`. You can enter the class name or browse to it.

The Exception Filter expects an exception from the previous module in the flow; this means that you need to add it within a Catch Exception Strategy processor. The exception will be passed to the next processor in the flow only if it matches the Exception Filter's configured `expectedType`.

Use the Exception Filter to decide if your Catch Exception Strategy needs to handle an exception or not, based on the type of the exception. When the Exception Filter receives an exception that does not match its configured `expectedType`, it returns a `null` value, and the processing of that message stops.

