= Expression Component Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: expression component, native code, legacy code, java, javascript, python, groovy, ruby, custom code

This component evaluates an xref:mule-expression-language-mel.adoc[expression]. It accepts either a user-defined expression or a reference to a file.

*Minimum requirement:* The expression or file to evaluate.

== Configuration

Unlike the xref:expression-transformer-reference.adoc[Expression Transformer], the expression component does not replace the message payload with the results of expression evaluation. See the *Implementing Business Logic* subsection in xref:mule-expression-language-mel.adoc[Mule Expression Language MEL] for an example illustrating the use of an expression component.

* *Display name*: Type a useful name for the transformer to display in your flow (optional)
* *Expression:* The expression to evaluate
* *File:* Absolute path of the file containing the expression to evaluate. Click the ellipsis (**...**) button next to the *File* field to select the file with a browser