= Extending
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule ESB provides a great deal of default functionality that you can use in your implementation. If you need different functionality, you can extend Mule as described on this page.

== Creating Extensions

You can create five basic types of extensions to Mule: projects, modules, transports, examples, and enterprise patterns.

* A *project* is a stand-alone Mule application.

* A *module* is a package of related functionality in Mule, such as the XML module, which provides XML-based utilities like filters and routers. For a list of the available modules you can use, see xref:3.7@modules-reference.adoc[Modules Reference].

* A *xref:3.7@connecting-using-transports.adoc[transport]* is a type of module that carries messages between Mule flows via a specific protocol. For a list of the available transports you can use, see xref:3.6@transports-reference.adoc[Transports Reference].

* An *example* is a sample application that you create to help users get up and running more quickly.

* A *catalog* is a Mule-created Maven archetype created to help Mule users create custom configuration patterns.

Mule provides Maven archetypes that create the templates for each of these types of functionality in seconds, including the configuration files, unit tests, and packages.

An archetype acts as a wizard, prompting you to provide input, and then creates template configuration, source, and unit test files. Furthermore, if you run an archetype on an existing project or module you created, Maven will update it for you.

When working with transports, note that you can xref:3.7@configuring-a-transport.adoc[configure an existing transport], or you can xref:3.6@creating-transports.adoc[create a new one]. The recommended approach is to try to use and configure an existing transport first.

* xref:3.7@extending-components.adoc[Extending Components]
* xref:3.7@custom-message-processors.adoc[Custom Message Processors]
* xref:3.6@creating-example-archetypes.adoc[Creating Example Archetypes]
* xref:3.6@creating-a-custom-xml-namespace.adoc[Creating a Custom XML Namespace]
* xref:3.6@creating-module-archetypes.adoc[Creating Module Archetypes]
* xref:creating-catalog-archetypes.adoc[Creating Catalog Archetypes]
* xref:3.6@creating-project-archetypes.adoc[Creating Project Archetypes]
* xref:3.6@creating-transports.adoc[Creating Transports]
* xref:3.6@creating-custom-routers.adoc[Creating Custom Routers]

== Developing Your Extension

After using the Maven archetype to get started, the recommended practice is to use an integrated development environment (IDE) such as Eclipse or IntelliJ to develop your Mule project, transport, module, or example. The Mule IDE allows you to quickly get up and running developing with Mule in Eclipse. For more information, see Using IDEs.

== Promoting Your Extension

After you have created a new extension, you can submit it as a project on GitHub. This allows you to share it with the Mule community so you can get feedback on the quality and design of the module before putting it into production.

== Internationalizing Mule

If you will use Mule in countries where English is not spoken, you can extend Mule by internationalizing the strings in the messages and exceptions. Additionally, there are guidelines you should take into consideration to make sure your code handles different locales. For more information, see xref:internationalizing-strings.adoc[Internationalizing Strings].

== Creating Configuration Patterns

The creation of custom configuration patterns can allow you to reach new levels of productivity with Mule. Follow this tutorial for xref:creating-catalog-archetypes.adoc[starting to create your own patterns now].