= Feature Flagging Mechanism
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule runtime engine incorporates a feature flagging mechanism that allows Mule applications to change the behavior of the Mule instance depending on the required minimum Mule version. This feature ensures backwards compatibility because it allows Mule applications to continue working on later Mule runtime versions, while new Mule applications can benefit from the latest bug fixes implemented in the Mule instance.

The feature flagging mechanism is automatic. For each Mule application deployed to a Mule instance, Mule decides which features are enabled or disabled based on the application’s minimum Mule version configured in the application descriptor file (`mule-artifact.json`) of the Mule app.

By default, Mule runtime engine disables any new features or bug fixes that are not backwards compatible with Mule applications running in earlier Mule versiones. However, it is possible to enable these features manually for each Mule application or for all apps running in the same Mule instance.

== Configure Feature Flags

You can configure feature flags for a certain Mule application or for the Mule instance:

=== Configure Feature Flags in a Mule Application

To configure feature flags for a Mule application, change the `minMuleVersion` value in the `mule-artifact.json` file of your app. This configuration instructs the Mule instance to run this application implementing all features and bug fixes that were released to Mule 4.3.0, and disable features and bug fixes that are active by default in later Mule versions.
//Think of adapting this to versionless. 

This configuration is compatible with any deployment target because the configuration exists at the Mule application level.

For example, you can run a Mule app in Mule 4.3.0 instructing the Mule instance to apply only the features that do not change core functionality up to Mule 4.1.0:

.Example `mule-artifact.json` file
----
{
  "minMuleVersion": "4.1.0"
}
----

=== Configure Feature Flags in a Mule Runtime Instance

An alternative way to configure feature flags is by using system properties. In this case, you can enable or disable each one of the available feature flags. However, configuring feature flags through system properties applies the changes at the Mule instance level, so all applications deployed to this Mule instance behave according to the configured feature flags.

This configuration is compatible with on-premise deployments only, because you cannot configure system properties in other deployment targets.

For example, you can configure a Mule 4.3.0 instance to enable and disable specific features for all applications running on this instance:

.Example `wrapper.conf` file
----
…
wrapper.java.additional.999=-DHONOUR_RESERVED_PROPERTIES_PROPERTY=true
wrapper.java.additional.1000=-DBATCH_FIXED_AGGREGATOR_TRANSACTION_RECORD_BUFFER_PROPERTY=false
----



== Feature Flags Reference

The following table shows the available feature flags, a description of their functionality, and the earlier minor version releases that implemented the feature:

[%header%autowidth.stretch,cols="a,a,a"]
|===
|Feature Flag | Description | Minor Version Release
|`HONOUR_RESERVED_PROPERTIES_PROPERTY`
|If set to `true`,  reserved properties such as ‘app.name’ are protected and cannot be overridden by global properties.
|
* 4.4.0
+
* 4.3.1
|`HANDLE_SPLITTER_EXCEPTION_PROPERTY`
|If set to true, DataWeave handles Splitter component exceptions and prevents serialization issues.
|
* 4.4.0
+
* 4.3.1
+
* 4.2.3
|`BATCH_FIXED_AGGREGATOR_TRANSACTION_RECORD_BUFFER_PROPERTY`
|If set to true, batch jobs including a fixed size aggregator commit records only after all records in a block are processed.
|
* 4.4.0
+
* 4.3.1
+
* 4.2.3
|`COMPUTE_CONNECTION_ERRORS_IN_STATS_PROPERTY`
|If set to true, connection errors are computed to trigger alerts.
|
* 4.4.0
+
* 4.3.1
|`TO_STRING_TRANSFORMER_TRANSFORM_ITERATOR_ELEMENTS_PROPERTY`
|If set to true, when managed iterators are transformed into strings, the strings show the representation of the elements instead of generic value: `+org.mule.runtime.core.internal.streaming.object. ManagedCursorIteratorProvider$ManagedCursorIterator@######+`.
| * 4.4.0
|===

== See Also

xref:mule-app-properties-system.adoc[Configure System Properties]
