= Feature Flagging Mechanism
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule runtime engine incorporates a feature flagging mechanism that allows Mule applications to change the behavior of the Mule instance depending on the required minimum Mule version. This feature ensures backward compatibility because it allows Mule applications to continue working on later Mule runtime versions, while new Mule applications can benefit from the latest bug fixes implemented in the Mule instance.

The feature flagging mechanism is automatic. For each Mule application deployed to a Mule instance, Mule decides which features are enabled or disabled based on the application’s minimum Mule version configured in the application descriptor file (`mule-artifact.json`) of the Mule app.

By default, Mule runtime engine disables any new features or bug fixes that are not backward compatible with Mule applications running in earlier Mule versions. However, it is possible to manage the feature flags configured for each Mule application or all apps running in the same Mule instance.

== Configure Feature Flags for a Mule Application

To configure feature flags for a Mule application, change the `minMuleVersion` value in the `mule-artifact.json` file of your app. This configuration instructs the Mule instance to run this application implementing all features and bug fixes that were released to that particular version and disabling features and bug fixes that are active by default in later Mule versions.
//Think of adapting this to versionless.

For example, you can run a Mule app in Mule 4.4.0 instructing the Mule instance to apply only the features that do not change core functionality up to Mule 4.1.0:

.Example `mule-artifact.json` file
----
{
  "minMuleVersion": "4.1.0"
}
----

== Configure Feature Flags for the Mule Instance

An alternative way to configure feature flags is by using system properties. In this case, you can enable or disable each one of the available feature flags. However, configuring feature flags through system properties applies the changes at the Mule instance level, so all applications deployed to this Mule instance behave according to the configured feature flags.

Note that this configuration is compatible with on-premise deployments only because you cannot configure system properties in other deployment targets.

For example, you can configure a Mule 4.3.0 instance to enable and disable specific features for all applications running on this instance:

.Example `wrapper.conf` file
----
…
wrapper.java.additional.999=-DHONOUR_RESERVED_PROPERTIES_PROPERTY=true
wrapper.java.additional.1000=-DCOMPUTE_CONNECTION_ERRORS_IN_STATS_PROPERTY=false
----

== Feature Flags Reference

//Confirm this statement which is not clear yet.
The following table shows the available feature flags, a description of their functionality, the Mule version in which the flag became available, the earlier minor version releases that enable the flag by default, and the issue ID where the change was implemented:

[%header%autowidth.stretch,cols="a,a,a"]
|===
|Feature Flag | Description | Issue ID
<.^|`HONOUR_RESERVED_PROPERTIES_PROPERTY`
|When enabled, reserved properties such as `app.name` can't be overridden by global properties (overrides are ignored).

*Available Since*

* 4.4.0
* 4.3.0-202102

*Enabled by Default Since*

* 4.4.0
* 4.3.1
<.^| `MULE-17659`
<.^|`HANDLE_SPLITTER_EXCEPTION_PROPERTY`
|When enabled, DataWeave handles splitter exceptions and prevents Scala serialization issues.

*Available Since*

* 4.4.0

*Enabled by Default Since*

* 4.4.0
<.^|`DW-383`
!===
<.^|`BATCH_FIXED_AGGREGATOR_TRANSACTION_RECORD_BUFFER_PROPERTY`
|When enabled, batch aggregators with fixed size aggregators commit only when a full block is processed. See EE-7443 for more information.

*Available Since*

* 4.4.0
* 4.3.0-202103
* 4.2.2-202103

*Enabled by Default Since*

* Not enabled by default in any Mule version
<.^| `MULE-19218`
<.^|`COMPUTE_CONNECTION_ERRORS_IN_STATS_PROPERTY`
|When enabled, Connection errors are computed as part of alerts triggering.

*Available Since*

* 4.4.0
* 4.3.0-202103

*Enabled by Default Since*

* 4.4.0
* 4.3.1
<.^| `MULE-19020`
<.^|`TO_STRING_TRANSFORMER_TRANSFORM_ITERATOR_ELEMENTS_PROPERTY`
|When enabled, managed cursor iterators transformed to Strings show the representation of the elements instead of generic value `org.mule.runtime.core.internal.streaming.object.-ManagedCursorIteratorProvider$ManagedCursorIterator@######`.

*Available Since*

* 4.4.0

*Enabled by Default Since*

* 4.4.0
<.^| `MULE-19323`
<.^|`ENABLE_POLICY_ISOLATION_PROPERTY`
|When enabled, Mule manages extensions imported by a policy in complete isolation from the extensions imported by the Mule application. Also, validations prevent the usage of explicit configurations that the application declared as part of the policy initialization.

*Available Since*

* 4.4.0
* 4.3.0-202107

*Enabled by Default Since*

* 4.4.0
<.^| `MULE-19226`
<.^|`ENTITY_RESOLVER_FAIL_ON_FIRST_ERROR_PROPERTY`
|When enabled, the Mule XML DSL parser fails when deploying an application that declares a schema that cannot be located. Otherwise, the parser fails if the application also makes use of the namespace that such schema is bound to.

*Available Since*

* 4.4.0

*Enabled by Default Since*

* 4.4.0
<.^| `EE-7827`
<.^|`ENABLE_PROFILING_SERVICE_PROPERTY`
|When enabled, Mule runtime profiling capabilities become available.

*Available Since*

* 4.4.0

*Enabled by Default Since*

//Is this correct? or typo? or intended for a next release?
//* 4.5.0
* Not enabled by default in any Mule version
<.^| `MULE-19588`
<.^|`SET_VARIABLE_WITH_NULL_VALUE_PROPERTY`
|When enabled, the Set Variable component creates a variable even if its value is null.

*Available Since*

* 4.4.0

*Enabled by Default Since*

* 4.4.0
<.^|`MULE-19443`
|===

== See Also

xref:mule-app-properties-system.adoc[Configure System Properties]
