= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, jdk, installation

If you plan to install Mule and run it on premises, review these minimum hardware and software requirements before you install.

== Minimum Hardware Requirements

* 2 GHz CPU or 1 virtual CPU in virtualized environments
* 1 GB of RAM. Add RAM to match your latency requirements, or to support large simultaneous messages or a large number of simultaneous messages if your applications process them.
* 4 GB of storage

== Supported Software and Systems

Verify that you use a supported version of Java and a supported operating system before you install Mule.

Mule Runtime runs as a standalone server; therefore an application server is not required. However, if you use an application server or need to access a data store, verify that you use a supported application server or database.

[%header,cols="15a,85a"]
|===
|Software |Version
| JDK | JDK 1.8.0 (JDK 1.8.0_161 recommended), OpenJDK 8 (JDK 1.8.0_162 recommended), IBM JDK 1.8
| OS | MacOS 10.11.x, HP-UX 11i V3, AIX 7.2, Windows 2016 Server (recommended), Windows 2012 R2 Server, Windows 10 (recommended), Windows 8.1, Solaris 11.3, RHEL 7, Ubuntu Server 16.04, or any other Linux distribution that runs a supported JDK and Linux kernel 3.13
| Application Servers | Tomcat 7, Tomcat 8, Weblogic 12c, Wildfly 8, Wildfly 9, Websphere 8, Jetty 8, Jetty 9
| Databases | Oracle 11g, Oracle 12c, MySQL 5.5+, IBM DB2 10, PostgreSQL 9, Derby 10, Microsoft SQL Server 2014
|===

If you use the Microsoft Dynamics GP connector, install Java Cryptography Extension (JCE) 8 after installing JRE or JDK.

The unified Mule Runtime 4.1.5 and API Gateway is compatible with APIkit 1.1.8.

This version of Mule Runtime is bundled with the Runtime Manager Agent plugin version 2.1.9.

Anypoint Connector DevKit 3.9.5 is compatible with Mule Runtime versions 4.1 and later. DevKit version numbering does not correspond to Mule versions. For example, DevKit 3.9 is compatible with Mule versions 3.5-4.1. For the latest fixes and improvements, use the current version of Mule Runtime with its corresponding DevKit as listed in release notes.

== See Also

* xref:release-notes::index.adoc[Release Notes]
* xref:1.5@private-cloud::system-requirements.adoc[About Minimum System Requirements for Anypoint Private Cloud]
* http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8]
