= Mule Runtime Requirements for Hardware and Software
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, jdk, installation

== Minimum Hardware Requirements

Mule Runtime (Mule) requires the following minimum hardware resources:

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM
* 4GB of storage

Adjust RAM to match your latency requirements and the size and number of simultaneous messages that applications process.

== Minimum Software Requirements

Mule requires the following minimum software resources:

* One of the following supported Java versions:
+
** Oracle JDK 1.8.0 (JDK 1.8.0_161 recommended). 
+
[NOTE]
If you run a Standalone instance of Mule and Anypoint Studio freezes during start up, check to see if the JDK where Studio is installed is 1.8 Update 152 (1.8.0_152). If it is, downgrade to 1.8.0_151 to correct the problem.
+
** IBM JDK 1.8
** OpenJDK 8 (JDK 1.8.0_162 recommended)
+
* An operating system that supports one of the following Java versions:
+
** MacOS 10.11.4
** HP-UX 11i V3
** AIX 7.2
** Windows 2016, Windows 2012 R2 Server, or Windows 8.1
** Solaris 11.3
** RHEL 7
** Ubuntu Server 15.04 or 16.04, or any other Linux distribution that runs a supported JDK and Linux kernel 3.13
* An application server is not required because Mule runs as a standalone server. However, Mule can run under one of these supported application servers:
+
** Tomcat 7 and 8
** WebLogic 12c
** WebSphere 8
** WildFly 8 or 9
** Jetty 8 or 9
* If you use the Microsoft Dynamics GP connector, install Java Cryptography Extension (JCE) 8 after installing JRE or JDK.
* If you need to access a data store, a database is required. Mule can access any of the following supported databases:
+
** Mule Oracle 11g
** Oracle 12c
** MySQL 5.5+
** IBM DB2 10
** PostgreSQL 9
** Derby 10
** Microsoft SQL Server 2014

== See Also

To see the latest hardware and software versions tested for use with Mule or any product, see xref:release-notes::index.adoc[Release Notes] for that product.

