= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, os, jdk, installation, jre

This page lists the hardware, operating systems, Java, and other requirements to run MuleSoft products.

[TIP]
For Hardware and Software requirements of Anypoint Studio, MuleSoft's IDE for building integration applications, see xref:5@studio::hardware-and-software-requirements.adoc[Studio Hardware and Software Requirements].

== Mule Runtime

=== Mule Hardware Requirements

This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM
* 4GB of storage

=== Mule Software Requirements

Because the only mandatory requirement for Mule is Java, Mule should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JREs.

NOTE: After installing a JRE or JDK, install the http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[Java Cryptography Extension (JCE) 7] unlimited strength jurisdiction policy files.

[%header,cols="30a,70a"]
|===
|Software |Requirement
|*Java Runtime Environments*
a|

* Oracle http://www.oracle.com/technetwork/java/javase/overview/index.html[JRE 1.8]
* Oracle http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0] (recommended: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0_79/80])
* IBM JVM version 1.7
* Open JDK 8

|*Operating Systems*
a|Mule validates against the following operating systems:

* MacOS 10.10.0 +
* HP-UX 11i V3
* AIX 7.1
* Windows 2012 R2 Server
* Windows 8.1
* Solaris 11.2
* RHEL 7.0
* Ubuntu Server 14.04
* Ubuntu Server 15.04
* Amazon Linux
|*Application Servers*
a|Mule validates against the following application servers:

* Apache Tomcat 7
* Apache Tomcat 8
* Oracle WebLogic 12c
* JBoss Enterprise 6.1
* JBoss Community 8
* IBM Websphere 8
* Eclipse Jetty 8
* Eclipse Jetty 9
|*Database Servers*
a|The following databases are compatible with Mule:

* Oracle Database 11g
* MySQL 5.5
* IBM DB2 10.1
* PostgreSQL 9
* Derby 10
* Microsoft SQL Server 2014

|===


== API Gateway Runtime

=== API Gateway Runtime Hardware Requirements

This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).

* 2GHz, dual-core CPU, or 2 virtual CPUs in virtualized environments
* 2GB of RAM
* 4GB of storage

=== API Gateway Runtime Software Requirements

Because the only mandatory requirement for the API Gateway Runtime is Java, the API Gateway should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JRE.

NOTE: After installing a JRE or JDK, install the http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[Java Cryptography Extension (JCE) 7] unlimited strength jurisdiction policy files.

[%header,cols="30a,70a"]
|===
|Software |Requirement
|*Java Runtime Environments*
a|* API Gateway Runtime 1.3.n and older: Oracle http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7]
* API Gateway Runtime 2.0.n and newer:
** Oracle http://www.oracle.com/technetwork/java/javase/overview/index.html[JRE 1.8]
** JRE 1.7.0 (recommended: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0_79/80])
** IBM version 1.7
|*Operating Systems*
a|API Gateway Runtime validates against the following operating systems.

API Gateway Runtime 2.0.n and newer:

* Mac OS 10.10.0
* HP-UX 11i V3
* AIX 7.1
* Windows 2012 R2 Server
* Windows 8.1
* Solaris 11.2
* RHEL 7
* Ubuntu Server 14.0.4
* Amazon Linux

API Gateway Runtime 1.3.n and older:

The operating systems MuleSoft used to validate the current release are:

* Windows (32- and 64-bit) 2003, 2008, Windows 7, Windows 2012
* Mac OS 10.7, 10.8
* Linux RHEL (64-bit) 5.3, 6.1
* Ubuntu Server 12.04 (64-bit) footnote:[If you use SSL, MuleSoft recommends installing Ubuntu Server 12.14 (64-bit) and newer instead of 12.04.]
* Solaris OS 10
* HP-UX 11i V3
* AIX V7.1
|===

== Anypoint Platform

[%header%autowidth.spread]
|===
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or newer - *Note:* The Edge browser is not supported
* Minimum screen resolution of 1024x768
|===

== Anypoint Exchange

[%header%autowidth.spread]
|===
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or newer - *Note:* The Edge browser is not supported
* Minimum screen resolution of 1024x768
|===

== CloudHub

[%header%autowidth.spread]
|===
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 11 or newer - *Note:* The Edge browser is not supported
* Minimum screen resolution of 1024x768
|===

== DevKit Versions

Any version of Anypoint DevKit from 3.5 and newer is compatible with
all Mule versions 3.5 and newer. Anypoint DevKit version numbering
does not correspond to Mule versions. For example, DevKit 3.8 is
compatible with Mule versions 3.5, 3.6, 3.7, and 3.8.

We recommend using the latest version of Mule with DevKit to get the
latest fixes and improvements.

== Mule Management Console (MMC)

NOTE: After installing a JRE or JDK, install the http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[Java Cryptography Extension (JCE) 7] unlimited strength jurisdiction policy files.

[%header%autowidth.spread]
|===
2+|*Hardware Requirements:* footnote:[We strongly recommend running MMC on a separate server from the hardware that runs Mule Runtime.]
|
a|* 2GHz CPU
* 4 GB of RAM
* 10 GB of storage
2+|*Software Requirements:*
|*Java Runtime Environments*
a|* Mule 3.7: Oracle http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[Java 1.7] and Oracle http://www.oracle.com/technetwork/java/javase/overview/index.html[Java 1.8]

* Mule 3.6: Oracle http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[Java 1.7]
|*Web Application Servers*
a|* JBoss 6 or 6.1
* Apache Tomcat 6.x or 7.x
* WebSphere Application Server 7.0 and 8.0
* Oracle WebLogic 12.1
* Oracle 12c (in MMC 3.7.3 and newer)
|*Operating Systems*
|MMC runs the operating systems supported by the above web application servers.
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or newer
* Minimum screen resolution of 1024x768
|===

=== Compatible MMC Databases for Persisting Data

* link:/mule-management-console/v/3.7/persisting-mmc-data-to-oracle[Oracle]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-postgresql[Postgres]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-mysql[MySQL]
* link:/mule-management-console/v/3.7/persisting-mmc-data-to-ms-sql-server[MS SQL Server]

=== Run MMC as a Web Application

Mule Management Console should be run as a web application deployed on a web container such as JBoss or Tomcat, and NOT as a Mule application. We recommend configuring the web application server's memory areas with the following minimum sizes:

*  Heap: 2GB (3GB recommended)
*  Permanent Generation: 512MB


== See Also

* Learn how to xref:downloading-and-starting-mule-esb.adoc[download, install, and launch] Mule.
* Learn more about installing an xref:installing-an-enterprise-license.adoc[Enterprise license].
* xref:general:getting-started:index.adoc[Get started] with Anypoint Studio.
* https://www.mulesoft.com/platform/studio[Download Anypoint Studio]