= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This page lists the hardware, operating systems, JREs, and other requirements to run Mule, Mule Management Console, and Mule Studio.

== Mule

[%header%autowidth.spread]
|===
2+|*Hardware Requirements**
|
a|* 2GHz, dual-core CPU, or 2 virtual CPUs in virtualized environments
* 2GB of RAM
* 4GB of storage
2+|*Software Requirements*
|*Java Runtime Environments*
a|* Oracle Java 1.6 +
* Oracle Java 1.7 +
* IBM Java 1.6
|*Operating Systems*
a|**Mule runs on any operating system supported by the above JREs.** To ensure this, every Mule release is validated against specific versions of the most widely used operating systems. +
 +
The operating systems MuleSoft used to validate the current release are: +
 +
* Windows (32- and 64-bit) 2003, 2008, XP, Windows 7, and Windows 2012 +
* Mac OS 10.6 +
* Linux RHEL (64-bit) 5.3, 6.1 +
* Ubuntu Server 12.04 (64-bit) +
* Solaris OS 10 +
* SunOS 5.11 v11.0 (Sparc Sun-Fire-T1000) +
* HP-UX 11i V3 +
* AIX V7.1 +
 +
Because the only mandatory requirement for Mule is Java, Mule should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JREs.
|===

*This hardware requirements list is a recommendation and a starting point. Different applications will have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications will process (which will in turn determine the amount of RAM Mule will need).

== Mule Management Console

[%header%autowidth.spread]
|===
2+|*Hardware Requirements**
|
a|* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1 GB of RAM
* 4 GB of storage
2+|*Software Requirements*
|*Java Runtime Environments*
a|* Oracle Java 1.6
* Oracle Java 1.7
* IBM Java 1.6
|*Web Application Servers*
a|* JBoss 6 or 6.1
* Tomcat 6.x or 7.x
* WebSphere Application Server 7.0 and 8.0
|*Operating Systems*
|Mule Management Console will run on any operating system supported by one of the above web application servers.
|*Browsers*
a|* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 9 or later
|===

* We strongly recommend running Mule Management Console on a separate server from the hardware that runs Mule ESB.

[cols="1*"]
|===
|*Compatible Databases for Persisting Data*
a|
* Oracle
* Postgres
* Microsoft SQL Server (_*Mule 3.4.1/3.4.2 only*_ with a patch for business events)
* Apache Derby/H2
* MySQL
|===

Mule Management Console should be run as a web application deployed on a web container such as JBoss or Tomcat, and NOT as a Mule application. We recommend configuring the web application server's memory areas with the following minimum sizes:

*  Heap: 2GB (3GB recommended)
*  Permanent Generation: 512MB

== Mule Studio

[%header%autowidth.spread]
|===
2+|*Hardware Requirements*
|
a|* 3GB of RAM
* 2GHz CPU
* 4GB free hard drive space
2+|*Software Requirements*
|*Java Runtime Environments*
a|* Oracle Java 1.6
* Oracle Java 1.7
* IBM Java 1.6
|*Operating Systems*
a|* Windows (32- or 64-bit)
* Mac OS (32- or 64-bit)
* Linux (32- or 64-bit)
|===

== Mule Studio as Eclipse Plug-In

[%header%autowidth.spread]
|===
2+|*Hardware Requirements*
|
a|* 3GB of RAM
* 2GHz CPU
* 4GB free hard drive space
2+|*Software Requirements*
|*Eclipse*
a|* Eclipse 3.8 for Java Developers or Java EE Developers
* Spring Tool Suite (STS) versions that run on top of Eclipse 3.8
|*Java Runtime Environments*
a|* Oracle Java 1.6
* Oracle Java 1.7
* IBM Java 1.6
|*Operating Systems*
a|* Windows (32- or 64-bit)
* Mac OS (32- or 64-bit)
* Linux (32- or 64-bit)
|===

Get more information about installing xref:studio-in-eclipse.adoc[Studio as an Eclipse plug-in].