= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, jdk, installation, jre

If you plan to install Mule and run it on premises, review these minimum hardware and software requirements before you install.

== Minimum Hardware Requirements

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM. Add RAM to match your latency requirements, or to support large simultaneous messages or a large number of simultaneous messages if your applications process them.
* 4GB of storage


== Supported Software and Systems

Verify that you use a supported version of Java and a supported operating system before you install Mule.

Mule Runtime runs as a standalone server; therefore an application server is not required. However, if you use an application server or need to access a data store, verify that you use a supported application server or database.

[%header,cols="20a,75a"]
|===
|Software |Version
|JDK | JDK 1.8.0 (1.8.0_202 recommended), IBM JDK 1.8, OpenJDK 8 (latest update recommended)
|OS |MacOS 10.11.4, HP-UX 11i V3, AIX 7.2, Windows 2012 R2 Server, Windows 8.1, Solaris 11.3, RHEL 7, Ubuntu Server 15.04 and 16.04
|Application servers |Tomcat 7 and 8, WebLogic 12c, WebSphere 8, WildFly 8 and 9, Jetty 8 and 9
|Databases |Oracle 11g, Oracle 12c, MySQL 5.5+, IBM DB2 10, PostgreSQL 9, Derby 10, Microsoft SQL Server 2014
|Browsers for working on Anypoint Platform | Firefox or Chrome (latest), Internet Explorer 10 or later; minimum screen resolution of 1024x768
|===

The unified Mule Runtime 3.9 is compatible with APIkit 3.9.0 and Anypoint Studio 6.4.0

Mule Runtime 3.9 is bundled with the Runtime Manager Agent plugin version 1.9.0.

For Microsoft Dynamics GP connector install Java Cryptography Extension (JCE) 8 after installing JRE or JDK.

== Anypoint Connector DevKit Requirements

Anypoint Connector DevKit 3.5 and later is compatible with Mule versions 3.5 and later. DevKit version numbering does not correspond to Mule versions. For example, DevKit 3.9 is compatible with Mule versions 3.5-3.8. For the latest fixes and improvements, use the current version of Mule with its corresponding DevKit as listed in release notes.

== See also

* xref:1.5@private-cloud::system-requirements.adoc[About Minimum System Requirements for Anypoint Private Cloud]
* xref:release-notes::connector-devkit/anypoint-connector-devkit-release-notes.adoc[Anypoint Connector DevKit Release Notes]
