= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, jdk, installation

If you plan to install Mule and run it on premises, review these minimum hardware and software requirements before you install.

== Minimum Hardware Requirements

* 2 GHz CPU or 1 virtual CPU in virtualized environments.
* 1 GB of RAM.
* 4 GB of storage.

Adjust RAM to match your latency requirements and the size and number of simultaneous messages that applications process.

== Required Software

Verify that you use a supported version of Java before you install Mule.

[%header,cols="15a,85a"]
|===
|Software |Version
| JDK | JDK 1.8.0 (1.8.0_202 recommended)
|===

== Supported Software

Mule runs on any operating systems that runs a supported Java Runtime Environment (JRE). The Mule runtime engine passed functional testing against the following software and operating systems:

|===
|Software |Version
| OS | MacOS 10.14, HP-UX 11i V3, AIX 7.2, Windows 2019 Server, Windows 10, Solaris 11.3, RHEL 7, Ubuntu Server 18.04
| JDK | JDK 1.8.0, JDK 11
|===

[NOTE]
Mule might work with other software and operating systems, but those have not been tested. MuleSoft recommends that you run Mule on tested software and operating systems versions.

This version of Mule Runtime is bundled with the Runtime Manager agent plugin version 2.1.9.


== See Also

* xref:1.5@private-cloud::system-requirements.adoc[About Minimum System Requirements for Anypoint Private Cloud]
//* http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8]
