= Application Hot Deployment
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: runtime, deploy, hot deployment, application, applications

You can now modify your configuration files and custom classes and have them reloaded without having to restart Mule.

== Outline of a Deployment

Here is a quick summary for deploying an app 'foo':

* Create a directory under `$MULE_HOME/apps/foo`
* Place your packaged application (e.g. `foo.jar`) at `$MULE_HOME/apps`
* Compress to a jar custom classes (if any), and put them under `$MULE_HOME/apps/foo/META-INF/mule-src/foo/src/main/java/`
* Start your app with `mule -M-Dmule.deploy.applications=foo` (see xref:application-deployment[Application Deployment] section for more information).

As a bonus, application's configuration files are monitored, so if there are any class changes you want to pick up or simply modify any config, save or touch any of the mule configuration files and Mule will hot-reload the application.

== How Hot Deployment works

Mule checks every three seconds for updated configuration files under the `$MULE_HOME/apps` directory, and when it finds one, it reloads the configuration file and the JARs in that applications lib directory. To reload an application, you can: 
* Touch the anchor file of that application
* Touch or update any of the Mule Configuration Files declared in the xref:intro-packaging#app_descriptor[`mule-artifact.json`] file. 

Therefore, if you want to change one of your custom classes, you modify it, copy the updated class to the java directory, and then touch the anchor file.

