= Converting Maven into Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You may wish to leverage Studio's graphical user interface by importing a http://maven.apache.org/[Maven] project into Studio.

*Important*: if you use the Maven *studio:studio* goal, you cannot use the *m2ecplipse* plugin, because it will override the studio:studio goal. Mule Studio has built in capabilities for importing and exporting between Maven and Studio using the studio:studio goal, which covers most use cases.

== Importing a Maven Project into Studio

To use Studio's built-in functionality to import a Maven project, you must have a clean Maven project with no Eclipse-specific files.

. In Studio, go to *File > Import...*
. Select *Maven-based Mule Project* from `*pom.xml*`, then click *Next*.
. Navigate to the location of the pom.xml file you wish to import. Mule will automatically populate a Project Name, but you can adjust it.
. Be sure to select the runtime you wish to use. Check the box to *Copy project into workspace* if you want to create a copy of your project that resides in your workspace.
. Click *Finish*.

Mule Studio runs the studio:studio goal to import the project into Studio.

== Troubleshooting

=== M2_REPO Classpath Variable Errors

If after you open your Maven project in Studio and encounter error messages (as illustrated below), you may need to set the **M2_REPO** classpath variable or, if it has already been set, re-point it to the correct repository.


. In Studio, right-click your project's name in the *Package Explorer*, then select *Properties*.
. In the *Properties* pane, click *Java Build Path* in the menu on the left, then click the *Libraries* tab.
. Click *Add Variable...*.
. In the *New Variable Classpath Entry* panel, click the *Configure Variables...* button.
. Select the `M2_REPO` item from the list of classpath variables, then click *Edit...*.
+
[NOTE]
If `M2_REPO` does not appear as an item in the list of classpath variables, click *New...* to create this classpath variable.
+
. Change the contents of the *Path* field to specify the location of your Maven (`.m2`) repository.
+
. Click *OK* in each of the open panels to save your changes.
. Click the *Problems* tab in the console to confirm that the errors are no longer listed, which means they have been resolved.

=== Missing Required Repositories

If you encounter errors like this,

`Failed to execute goal on project schema-extractor-plugin: Could not resolve dependencies for project org.mule.tooling:schema-extractor-plugin:maven-plugin:1.0-SNAPSHOT...`

Mule is indicating that some dependencies or artifacts cannot be resolved. Ensure that the required plugin repositories are included in your pom file.

[source,xml,linenums]
----
<pluginRepositories>
        <pluginRepository>
            <id>mulesoft-release</id>
            <name>mulesoft release repository</name>
            <layout>default</layout>
            <url>http://repository.mulesoft.org/releases/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
  </pluginRepositories>
----

== See Also

* xref:exporting-studio-to-maven.adoc["mavenize" an existing Mule project]