= Mule Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, getting started, transform, message, payload

Mule runtime engine (Mule) is a lightweight integration engine that runs Mule
applications and supports domains and policies. Mule applications, domains,
and policies share an XML DSL (domain-specific language).

== Mule Applications

Mule applications connect systems, services, APIs, and devices using API-led
connectivity instead of point-to-point integrations. Mule applications provide
functionality for message routing, data mapping, orchestration, reliability,
security, and scalability.

Anypoint Studio and Flow Designer support Mule application development.

== Domains

Domains enable you to share global configurations that Mule applications need to
reuse, such as default error handlers, shared properties, scheduler pools, and
component configurations.

Anypoint Studio supports Mule domain development.

== Policies

Policies on HTTP-based APIs can enforce security, regulate traffic through
Mule applications, and adapt APIs to your business needs.

Mule Runtime includes an embedded API Gateway, which enables you to apply
security policies to an API, enrich incoming or outgoing messages, and add
capabilities to an API without having to write any code. See
xref:api-manager::api-gateway-capabilities-mule4.adoc[API Gateway Capabilities]
for information on the Mule runtime engine in the API Manager documentation.

API Manager supports configuration for automated policies. Custom policy
development and configuration are also supported.

[[Maven]]
== Maven Support

Maven is a project management utility that Mule implements to enhance project
development. Mule provides built-in Maven functionality. For the Mule Runtime engine,
you can integrate the packaging, testing, and deployment of your Mule applications,
domains, and custom policies with your Maven lifecycle using the Mule Maven plugin.

For details, see xref:using-maven-with-mule.adoc[Maven Support in Mule].

[[install_deploy_manage]]
== Mule Installation, Deployment, Management

For a Mule app to run, it must be deployed into an environment where the Mule
runtime engine is installed.

Mule is packaged within the xref:studio::index.adoc[Studio] IDE and with
xref:design-center::index.adoc[Design Center] on Anypoint Platform so
that you can run a Mule app as you design it.

For production and pre-production deployments of Mule apps, you can use
xref:runtime-manager::index.adoc[Runtime Manager] to deploy Mule apps
to runtimes within CloudHub and other supported platform as a service (PaaS)
solutions.

* xref:runtime-manager::cloudhub.adoc[CloudHub] is a fully managed, Cloud-based
integration platform as a service (iPaaS) for Anypoint Platform that enables you
to run your Mule apps without requiring you to provide Mule runtimes or the
infrastructure on which your apps run. You use Runtime Manager to deploy Mule
apps to CloudHub, select the Mule runtime version, set the number of vCores
needed to run the app, and so on.
* Hybrid deployment models manage Mule apps and runtimes from the Cloud while
running them in a datacenter that is managed by your company:
** For remote Mule runtimes (also called standalone or "naked" Mules), you
start Mule runtimes from your datacenter, but you can deploy and manage
Mule apps from the Cloud, though Runtime Manager. In this deployment model, you
provide the infrastructure and Mule runtime (see
xref:mule-standalone.adoc[Mule Installation]).
** For a hybrid PaaS deployment, you set up and run the PaaS on your company's
datacenter and use Runtime Manager to manage Mule apps within the PaaS. In this
case, you provision the infrastructure in which the apps run. To guarantee the
high availability of Mule apps, you use Runtime Manager to handle Mule runtimes.
xref:anypoint-platform-pcf::index.adoc[Anypoint Platform for PCF] is an
example of a hybrid PaaS solution. MuleSoft also provides the built-in PaaS
solution, xref:runtime-fabric::index.adoc[Runtime Fabric], which runs Mule
runtime engines in a "containerized" environment.

In addition to using Runtime Manager, you can perform deployments and manage
Mule apps with
xref:runtime-manager::anypoint-platform-cli-commands.adoc[Anypoint CLI 3.x],
which includes commands for deployments and a number of Anypoint Platform use
cases.

== Non-blocking Execution Engine

The Mule execution engine is based on a non-blocking runtime. This is a
task-oriented execution model that allows you to take advantage of non-blocking
IO calls and to make tuning configurations in a simple way.

In Mule applications, a flow always functions synchronously. If you need to achieve
asynchronous patterns, such as Fire-and-Forget, you can use the
xref:async-scope-reference.adoc[Async (`<async>`)] component.

Mule Event processors indicate to the runtime whether they are CPU intensive,
CPU light, or IO intensive operations. These workload types help the runtime tune
for different workloads, removing the need for you to manage thread pools manually
to achieve optimum performance. Instead, the runtime introspects the available
resources (such as memory and CPU cores) in the system to tune thread pools
automatically.

For more detailed documentation on the execution engine, threading model, and
tuning options, see xref:execution-engine.adoc[Execution Engine].

== See Also

* xref:mule-app-dev.adoc[Mule Application Development]
* xref:studio::domain-support-concept.adoc[Domains]
* xref:api-manager::policies-landing-page.adoc[Policies]
* xref:about-mule-configuration.adoc[Mule Configuration XML]
* xref:runtime-manager::deployment-strategies.adoc[Deployment Strategies]
