= About Mule Runtime 4.x
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, getting started, transform, message, payload

// This guide offers information about how to use Mule Runtime, commonly called Mule, or Mule ESB to integrate systems, orchestrate web services and configure the runtime environment.

Mule is a lightweight integration engine that runs Mule apps. Rather than creating multiple point-to-point integrations between systems, services, APIs, and devices, you use Mule to create apps that manage message routing, data mapping, orchestration, reliability, security, and scalability between nodes.

The runtime defines the rules for how event data is handled in an application.  Mule apps receive events, then process and route them to other endpoints.

Developing with Mule You Can...

* Deploy or integrate apps or systems on premise or in the Cloud.
* Employ out-of-the-box connectors to create SaaS integration apps.
* Build and expose APIs.
* Consume APIs.
* Create Web services that orchestrate calls to other services.
* Create interfaces to expose apps for mobile consumption.
* Integrate B2B with solutions that are secure, efficient, and quick to build and deploy.
* Shift apps to the Cloud.
* Connect B2B e-commerce activities.

== About the Non-blocking Execution Engine

The Mule execution engine is based on a non-blocking runtime. This is a task-oriented execution model that allows you to take advantage of non-blocking IO calls and to avoid performance problems.

Flows always function synchronously. If you need to achieve asynchronous patterns, such as Fire-and-Forget, you can use the Async (`<async>`) component.

Each Mule event processor can inform the runtime if it is CPU intensive, CPU light, or an IO intensive operation. This helps the runtime self-tune for different workloads dynamically, removing the need for you to manage thread pools manually to achieve optimum performance.

== About Thread Pool Executor (Schedulers) Configuration

You can configure schedulers (thread pool executors) through the well-commented `schedulers.conf` file in the standalone Mule EE installation.

// TODO: NOT SURE IF THIS WILL BE READY FOR RC: It is also possible to configure the same attributes in the Mule EE XSD file.


// == Mule Reference Material
//
// Learn more about Mule features and configuring applications that run on Mule.
//
// * link:reference[Reference]
// * link:publishing-and-consuming-apis-with-mule[Publishing and Consuming APIs with Mule]
// * xref:business-events.adoc[Business Events]
// * link:using-maven-with-mule[Using Maven with Mule]
// * link:improving-performance-with-the-kryo-serializer[Improving Performance with the Kryo Serializer]
// * xref:error-handling.adoc[About Error Handling]
// * link:batch-processing[Batch Processing]
// * xref:transaction-management.adoc[Transaction Management]
// * link:adding-and-removing-user-libraries[Adding and Removing User Libraries]
// * xref:shared-resources.adoc[Shared Resources]
// * link:mule-versus-web-application-server[Mule versus Web Application Server]

== See Also

* xref:mule-application-about.adoc[About the Mule Application]
//COMBAK: Enable download link when standalone beta is available
//* link:downloading-and-starting-mule-esb[Download and Start Mule Runtime]
