= Installing Mule ESB 3 and the Mule IDE
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you are installing Mule Enterprise, read the next section. If you are installing the community or snapshot release, skip ahead to that section.

== Installing Mule Enterprise

[TIP]
These instructions are for Mule Enterprise only. For the community or snapshot releases, skip to the next section.

This section describes installation of Mule Enterprise. Follow the instructions for the version of the file you downloaded.

=== Installing the TAR.GZ

. If you downloaded the TAR.GZ version of Mule Enterprise, simply decompress the files into a directory. You must use a decompression utility like WinZip, not just the built-in Windows extractor.

[IMPORTANT]
Do not install Mule in a directory path that contains spaces!

. Do one of the following:
* If you will use the Mule IDE, see Installing Mule IDE.
* If you will use Maven, skip ahead to set up your Maven repository.
* Otherwise, skip ahead to the section on Running Mule.

=== Set Up the Maven Repository

You are now ready to set up your Maven repository as follows:

. Open a command prompt and navigate to the Mule `bin` directory.
. Type `populate_m2_repo.cmd` followed by the location of the Maven repository directory (the same directory you specified in the `settings.xml` file when you installed Maven).

For example:

----
cd c:\mule\binpopulate_m2_repo.cmd c:\.m2\repository
----

This step is required to populate the Maven repository with the local Mule Enterprise JAR files from the distribution. Note that when you add Mule Enterprise-only features to your code, you must add the correct [dependencies] to your POM before building your project with Maven.

You have completed the Mule installation and setup. You can now go to the xref:mule-studio.adoc[Mule Studio] for information on getting started, or skip to xref:running-mule-esb-3.adoc[Running Mule ESB 3] if you will not use the Mule IDE.

== Installing the Mule Community or Snapshot Release

This section describes installation of the community or snapshot release on Windows or Linux/UNIX.

. If you have a previous release already installed, you should delete the directory where it is installed before installing the later release.
. Download Mule.
. Click the link next to the release you want to download. Use the `.zip` links for installing on Windows and the `.tar.gz` links for installing on Linux/UNIX. The latest releases are at the top of the page.
. On Linux/UNIX, if you must download it through a terminal instead of a browser, or if you must download to a remote computer without X-Windows, use `wget`. For example, to download the Mule 2.0.1 snapshot using `wget`, enter the following command on one line:

[source,text,linenums]
----
wget http://snapshots.dist.codehaus.org/mule/org/mule/distributions/mule-full/2.0.1-SNAPSHOT/mule-full-2.0.1-SNAPSHOT.tar.gz
----

. After the distribution is downloaded, extract the files from it into your installation directory. For example, on Linux/UNIX, you would switch to your installation directory, and then enter the following command:

[source,text,linenums]
----
tar -xvzf mule-full-2.0.1-SNAPSHOT.tar.gz
----
+
[IMPORTANT]
Do not install Mule in a directory path that contains spaces!

== Installing Multiple Instances

To install multiple instances of Mule on the same machine, simply unpack the distribution archive as described above to a different location.

Mule 3 does no longer support sharing a Mule installation directory between multiple instances.

== Installing the Mule IDE

If you need to reinstall Mule Studio, contact MuleSoft Support. Unzip the software distribution and execute the application file.