= Installing and Endorsing the JDK
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before installing Mule ESB, ensure that the host machine has one of the following Java Development Kit versions installed on it:

* Standard Edition 1.6.0_26 (also known as JDK SE 6 Update 26) or more recent (including SE 7)
* Enterprise Edition 1.6u3 (JDK EE 6 Update 3) or more recent (including EE 7)

You can download the JDK from http://www.oracle.com/technetwork/java/javase/downloads/index.html[here].

[CAUTION]
Be sure to set the JAVA_HOME environment variable on your system to point at the directory where you have installed your JDK, as in `C:\Java`

== Endorsement

[CAUTION]
====
*If* you choose *not* to use one of the JDK options listed above for *any* version of Mule ESB, you *must* "endorse" that JDK with a proper implementation of JAXP (Java API for XML Processing).

To do this, download Apache http://xerces.apache.org/xerces2-j[Xerces] and http://xml.apache.org/xalan-j[Xalan] and drop the .jar files into the `jre/lib/endorsed` directory of your JVM (Java Virtual Machine). If that directory does not yet exist, create it.
====