= Introduction to Mule 4: Configuring Mule Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Mule 3, Spring property placeholders are often used to configure apps dynamically for the environment in which they are deployed. Mule 4 contains a built-in mechanism for this that allows you to set default values and avoid the need to learn Spring. +

Mule 3 supports `.properties` configuration files, while Mule 4 supports both `.yaml` and `.properties`  configuration files. The recommended approach is to use `.yaml` configuration files, because it allows the addition of type validations and autocompletion.

Example of a `.yaml` configuration file:
[source,yaml]
----
http:
  path: service
  port: "10000"
----

You can add the YAML file to your Mule app through the Configuration Properties Global Element. The XML configuration looks like this:
[source,xml,linenums]
----
<configuration-properties file="myConfiguration.yaml" />
----

In Mule 3, when you create a new application via Anypoint Studio, it automatically adds a default `mule-app.properties` file that you can use to add your properties for the application. However, in Mule 4 this file is no longer automatically created. +
If you choose to create a custom `.properties` file, you also need to configure it in your Mule app via the Configuration Properties Global Element. The XML configuration looks like this:

[source,xml,linenums]
----
<configuration-properties file="myConfiguration.properties"/>
----

MuleSoft highly recommends that you do not package the configuration files for all the environments inside your app. Instead, you should use a `.yaml` file to provide defaults, then use Runtime Manager to override each of these properties at deployment time.


== See Also

xref:configuring-properties.adoc[Configure Properties]
