= Jetty Transport
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, esb, studio, jetty, SSL

The Jetty transport provides support for exposing applications over HTTP by embedding a light-weight Jetty server. The xref:jetty-ssl-transport.adoc[Jetty SSL Transport] works the same way but over SSL. You can only define inbound endpoints with this transport.

The Javadoc for this transport can be found below:

https://www.mulesoft.org/docs/site/3.8.0/apidocs/org/mule/transport/servlet/jetty/JettyHttpConnector.html[Jetty Transport Javadoc]

The connector allows Mule to expose Mule Services over HTTP using a Jetty HTTP server. A single Jetty server is created for each connector instance. One connector can serve many endpoints. Users should rarely need to have more than one Jetty connector. The Jetty connector can be configured using a Jetty XML config file, but the default configuration is sufficient for most scenarios.

== Attributes of the Connector

These attributes are for the optional global connector, jetty:connector.

[%header,cols="30a,70a"]
|===
|Name |Description
|name |The name of the connector in a flow.

*Type*: string +
*Required*: yes +
*Default*: Jetty
|configFile |The location of the Jetty config file to configure this connector with.

*Type*: string +
*Required*: no +
*Default*: none
|Acceptors |The number of acceptor threads.

*Type*: integer +
*Required*: no +
*Default*: 1
|resourceBase |Specifies a local path from which files are served. The local path gets mapped directly to the path on the `serverUrl`.

*Type*: string +
*Required*: no +
*Default*: none
|useContinuations |Whether to use continuations to free up connections in high load situations.

*Type*: boolean +
*Required*: no +
*Default*: none
|doc:name |A descriptive name for the connector. Not required in Mule Standalone configuration.

*Type*: string +
*Required*: Only for Studio configurations +
*Default*: Jetty
|===

== Child Elements of the Connector

[%header,cols="30a,20a,50a"]
|===
|Name |Cardinality |Description
|webapps |0..1 |Allows configuring of a directory which contains WAR files to be served out by Jetty.
|===

== Endpoints

Jetty endpoints are configured the same way as xref:file-transport-reference.adoc[FTP endpoints]. Note that the Jetty transport can only be used for inbound endpoints.

For example:

[source,xml,linenums]
----
include::{examplesdir}/jetty-transport-reference.xml[]
----