= Logging and Debugging
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

MuleSoft provides a variety of logging and debugging options for Mule apps.

Application logs and a runtime log help you monitor and troubleshoot your apps and the Mule server. For details, see xref:logging-in-mule.adoc[Configuring Logging].

The Logger component can help you monitor or even debug your Mule app by logging important information such as error messages, status notifications, payloads, and so on. You can add a Logger anywhere in a flow, and you can configure it to log a string that you specify, the output of a DataWeave expression you write, or any combination of strings and expressions. For details, see xref:logger-component-reference.adoc[Logger Component] in the Core component documentation.

To control the display of Mule stack traces, you can use command-line arguments or set properties in Anypoint Studio. For details, see xref:configuring-mule-stacktraces.adoc[Configuring Mule Stack Traces].

To troubleshoot a Mule app in Anypoint Studio, you can use the Studio Visual Debugger, which lets you set breakpoints to stop execution and check events. If you are creating your Mule app outside of Studio, you can either use MUnit to test your app, or you can activate remote debugging. For details, see xref:debugging-outside-studio.adoc[Debugging Outside Studio].
