= Maven Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, maven, version control, dependencies, libraries

This page summarizes reference information that helps work with Maven and Mule. Refer to xref:using-maven-with-mule.adoc[Using Maven with Mule] for an introduction and overview.

== Deploying Mule Artifacts to a Central Maven Repository

Using a central repository can save users' time when building applications. To deploy to a central repository, you need to deploy the Mule `POM` files and `JAR` artifacts to the desired repository.

The deploy plugin is primarily used during the deploy phase, to add your artifacts to a remote repository for sharing with other developers and projects.

=== Deploying pom.xml

To deploy the `pom.xml` to a remote repository, use the following command:

[source,text,linenums]
----
mvn deploy:deploy-file
-DgroupId=${project.groupId}
-DartifactId=${project.artifactId}
-Dversion=${version}
-Dpackaging=pom
-Dfile=${localPom.canonicalPath}
-Durl=http://<your_repository_ip>/nexus/content/repositories/releases
-DrepositoryId=releases
----

For the `-Durl` parameter, replace `your_repository_ip` with the correct IP address. Also, the `-DrepositoryId` needs to match with the credentials defined on the `settings.xml` file.

=== Deploying the JARs

To deploy a jar file to a remote repository, use the following command:

[source,text,linenums]
----
mvn deploy:deploy-file
-DgroupId=${pomProps.groupId}
-DartifactId=${pomProps.artifactId}
-Dversion=${pomProps.version}
-Dpackaging=jar
-Dfile=${f.canonicalPath}
-DpomFile=${localPom.canonicalPath}
-Durl=http://${your_repository_ip}/nexus/content/repositories/releases
-DrepositoryId=releases
----

For the `-Durl` parameter, replace `your_repository_ip` with the correct IP address. Also, the `-DrepositoryId` needs to match with the credentials defined on the `settings.xml` file.

If you wish to both install the JARs locally and deploy them remotely, you can keep both locations in the argument definition.

== pom.xml File

[source,xml]
----
<project root>/pom.xml
----

Project Object Model file that defines settings for a Maven project describing an application. It includes all settings necessary to build the application such as build plugin configurations. Note that the `pom.xml` exists on a per-project basis and is distributed along with a project.

== settings.xml File

[source,xml,linenums]
----
<system-wide Maven directory>/settings.xml
<user home directory>/.m2/settings.xml
----

Contains global settings for your Maven installation. Unlike a project's `pom.xml`, it defines system-wide settings and is not distributed with a project, since it can contain confidential information such as authentication credentials.

The `settings.xml` file may reside in two locations: in a system-wide settings folder, and in a user-specific settings folder. In the first case, it is a _global_ settings file which defines the settings for all Maven installations on the system, regardless of user. For example:

----
/etc/maven2/settings.xml
----

In the second, per-user case, the file is a _user_ settings file only relevant for a specific user's Maven installation. In this case, the default location is the `.m2` directory in the user's home directory:

----
/home/joe/.m2/settings.xml
----

On a system with both global and user `settings.xml` files, the settings from both files become merged. In case of duplicate settings, the user's settings take precedence over the global settings.

== Useful Commands

=== Locate the Maven binary and other files (Unix)

----
whereis mvn
----

=== Locate Maven files such as global configuration files (Unix)

----
locate maven
----

=== Obtain Maven version

----
mvn --version
----

This also provides other information such as the Java home directory, locale and processor architecture.

=== Obtain a List of Maven Commands and Options

----
mvn -h
----

=== Check the Manual Page for Maven (Unix)

----
man mvn
----

=== Create a Project

----
mvn archetype:generate -DgroupId=com.company.app -DartifactId=myapp -DarchetypeArtifactId=myarchetypeid -DinteractiveMode=false
----

=== Build a Project

----
mvn package
----

=== Clean a project

----
mvn clean
----

=== Generate a Site

----
mvn site
----

=== Obtain a List of Jars Included in Your Artifact

----
mvn dependency:build-classpath
----

=== Obtain the Dependency Tree for Your Artifact

----
mvn dependency:tree
----
