= Maven Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: studio, maven, esb, version control, dependencies, libraries

This page summarizes reference information that is helpful for working with Maven and Mule. Refer to xref:using-maven-with-mule.adoc[Using Maven with Mule] for an introduction and overview.

== Populating the Maven Repositories From the Command Line

[TIP]
You don't usually need to do this, as it occurs automatically when creating a Maven Mule project. In case something doesn't work as expected, you have the option of doing it manually.

To include Mule libraries as dependencies of your project, you must populate your Maven repository with these. To do this manually, you can run the `populate_m2_repo` script in `$MULE_HOME/bin` from the command line.

On Unix:

[source,text,linenums]
----
$MULE_HOME/bin/populate_m2_repo
----

On Windows:

[source,text,linenums]
----
%MULE_HOME%\bin\populate_m2_repo.cmd
----

These scripts call `$MULE_HOME/bin/populate_m2_repo.groovy` which you can modify.

== Deploying Mule Artifacts to a Central Maven Repository

Using a central repository can save users' time when building applications. To deploy to a central repository, you need to deploy the Mule POM files and JAR artifacts to the desired repository.

=== Deploying `pom.xml`

In your Mule installation, locate the file `<MULE_HOME>/bin/populate_m2_repo.groovy` and open it for editing. Locate the following line:

[source,text,linenums]
----
mvn(["install:install-file",
 "-DgroupId=${project.groupId}", "-DartifactId=${project.artifactId}",
"-Dversion=${version}", "-Dpackaging=pom",
"-Dfile=${localPom.canonicalPath}"])
----

Modifiy the line as shown.

[source,text,linenums]
----
mvn(["deploy:deploy-file",
 "-DgroupId=${project.groupId}", "-DartifactId=${project.artifactId}",
"-Dversion=${version}", "-Dpackaging=pom",
"-Dfile=${localPom.canonicalPath}","-Durl=http://<your_repository_ip>/nexus/content/repositories/releases", "-DrepositoryId=releases"])
----

For the `-Durl` parameter, replace `your_repository_ip` with the correct IP address.

=== Deploying the JARs

In the  `<MULE_HOME>/bin/populate_m2_repo.groovy` file, locate the second `// Install pom via maven` comment. Immediately below this line is the argument definition, which reads as shown below.

[source,text,linenums]
----
def args = ["install:install-file", "-DgroupId=${pomProps.groupId}", "-DartifactId=${pomProps.artifactId}", "-Dversion=${pomProps.version}", "-Dpackaging=jar", "-Dfile=${f.canonicalPath}", "-DpomFile=${localPom.canonicalPath}"]
----

Modify this line as shown.

[source,text,linenums]
----
def args = ["deploy:deploy-file",
 "-DgroupId=${pomProps.groupId}", "-DartifactId=${pomProps.artifactId}",
 "-Dversion=${pomProps.version}", "-Dpackaging=jar",
"-Dfile=${f.canonicalPath}", "-DpomFile=${localPom.canonicalPath}",
"-Durl=http://${your_repository_ip}/nexus/content/repositories/releases", "-DrepositoryId=releases"]
----

For the `-Durl` parameter, replace `your_repository_ip` with the correct IP address.

If you wish to both install the JARs locally and deploy them remotely, you can keep both locations in the argument definition.

== Referencing MuleSoft's Enterprise Repositories

See xref:configuring-maven-to-work-with-mule-esb.adoc[Configuring Maven to Work with Mule ESB].

== Checking JARs Included in a Project

Maven can automatically include dependencies into your project. It is possible that, when attempting to test the project outside of Maven, you may find that you need to explicitly define these dependencies for the project to work. For example, if you create a project with Studio and Maven and build it using another tool such as Apache Ant, you need to ensure that all dependencies required for the project are included in your Ant config.

To obtain a list of dependencies included in your project, run the following command:

[source,text,linenums]
----
mvn dependency:build-classpath
----

== Files

=== pom.xml

[source,xml,linenums]
----
<project root>/pom.xml
----

Project Object Model file that defines settings for a Maven project describing an application. It includes all settings necessary to build the application such as build plugin configurations. Note that the `pom.xml` exists on a per-project basis and is distributed along with a project.

See the https://maven.apache.org/pom.html[POM Reference] at the Apache Maven online documentation for details.

=== settings.xml

[source,xml,linenums]
----
<system-wide Maven directory>/settings.xml
<user home directory>/.m2/settings.xml
----

Contains global settings for your Maven installation. Unlike a project's `pom.xml`, it defines system-wide settings and is not distributed with a project, since it can contain confidential information such as authentication credentials.

The `settings.xml` file may reside in two locations: in a system-wide settings folder, and in a user-specific settings folder. In the first case, it is a _global_ settings file which defines the settings for all Maven installations on the system, regardless of user. For example:

[source,text,linenums]
----
/etc/maven2/settings.xml
----

In the second, per-user case, the file is a _user_ settings file only relevant for a specific user's Maven installation. In this case, the default location is the `.m2` directory in the user's home directory:

[source,text,linenums]
----
/home/joe/.m2/settings.xml
----

On a system with both global and user `settings.xml` files, the settings from both files become merged. In case of duplicate settings, the user's settings take precedence over the global settings.

For a complete reference for this file, see https://maven.apache.org/settings.html[Settings Reference] on the Apache Maven online documentation.

== Useful Commands

=== Locate the Maven binary and other files (Unix)

[source,text,linenums]
----
whereis mvn
----

=== Locate Maven files such as global configuration files (Unix)

[source,text,linenums]
----
locate maven
----

=== Obtain Maven version

[source,text,linenums]
----
mvn --version
----

This also provides other information such as the Java home directory, locale and processor architecture.

=== Obtain a List of Maven Commands and Options

[source,text,linenums]
----
mvn -h
----

=== Check the manual page for Maven (Unix)

[source,text,linenums]
----
man mvn
----

=== Create a project

[source,text,linenums]
----
mvn archetype:generate -DgroupId=com.company.app -DartifactId=myapp -DarchetypeArtifactId=myarchetypeid -DinteractiveMode=false
----

=== Build a project

[source,text,linenums]
----
mvn package
----

=== Clean a project

[source,text,linenums]
----
mvn clean
----

=== Generate a Site

[source,text,linenums]
----
mvn site
----

=== Obtain a list of jars included in your artifact

[source,text,linenums]
----
mvn dependency:build-classpath
----

=== Obtain the dependency tree for your artifact

[source,text,linenums]
----
mvn dependency:tree
----

== External Resources

* https://maven.apache.org/index.html[Apache Maven home page]
* https://maven.apache.org/guides/getting-started/index.html[Maven Getting Started Guide]
* http://code.google.com/p/m4enterprise/wiki/MavenCommandReference[Maven commands reference]
* https://maven.apache.org/pom.html[POM reference]
* https://maven.apache.org/settings.html[Settings reference]
