= Message Property Filter
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Matches properties on a message.

Minimum Configuration: The Pattern that the filter should match on.

Use a Message Property Filter to route messages using logic based on the values of one or more message properties. Using this filter you can access the message meta-data (that is, the message properties) including transport-specific and user-defined properties. These message properties represent all the meta information about the message that is available from the underlying transport. For example, if you receive a message via a HTTP endpoint, you can use this filter to check HTTP header values.

The Pattern is expressed as a key/value pair, where the key is the name of the property. For example, to test the `http.method` is GET, you could write `http.method=GET`.

By default, the Case Sensitive box is checked, indicating that the comparison is case sensitive. Uncheck this box if you want the comparison to be case insensitive.

You can also limit the filter to the scope of the message. Scope can be inbound, invocation, outbound, session, or application. The default scope is outbound. For more information, see xref:message-property-scopes.adoc[Message Property Scopes].

For more information on using a Message Property Filter, see xref:using-filters.adoc[Using Filters].

== Mule Reference

For more information about Message Property Filter, see the xref:filters-configuration-reference.adoc[Filters Configuration Reference].