= Message Processors
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, esb, message processors, elements, component

After Mule receives a message from a Message Source, it uses one or more message processors to process the message through a flow.

These can transform, filter, enrich, and otherwise process the message as it transitions through your flow.

Message Processors can be categorized by function as follows:

* *Connectors* send and receive data, and plug into external data sources via standard protocols or third-party APIs.
* *Components* are flexible tools which perform business logic implemented in Java, Javascript, Groovy, Python, or Ruby.
* *Filters* only allow certain messages to continue to be processed in a flow based on certain criteria.
* *Routers* control message flow to route, resequence, or split and aggregate messages in a flow.
* *Scopes* wrap snippets of code to define fine-grained behavior within a flow.
* *Transformers* convert message payload type and data format to facilitate communication between systems.
* *Exception Strategies* handle any errors that occur during message processing.
* *Business Events* capture data related to key performance indicators.

*Note:* Only use message processors after a Router.

== See Also

* xref:components.adoc[Components]
* xref:filters.adoc[Filters]
* xref:routers.adoc[Routers]
* xref:scopes.adoc[Scopes]
* xref:transformers.adoc[Transformers]
* xref:business-events.adoc[Business Events]