= Migrating Connectors and Modules to Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This section covers the migration of connector-specific features and lists connectors that are deprecated or removed from Mule 4.

////
(*NOTE: We can break the files out on a per connector basis if necessary*)

* From Mariano G: Multipart and attachment handling in email, WSC and Http (Contact: Ana Felisatti, Juani
 ** From Ana: HTTP should map directly to the docs on DW's support for multipart. Already created that ticket.
* <<connector_1>>: Description of migrated featured here.
* <<connector_2>>: Description of migrated featured here.
////

== Deprecated or Removed Connectors

The following table shows deprecated/removed Mule 3.x modules and how to replace them in Mule 4.0.

[%header,cols="30,70"]
|===
Mule 3.x Module| Mule 4.0 Replacement
|Ajax	| Use APIkit + standard REST.
|Atom	| Replaced with HTTP + DataWeave
|Axis	| Use WS Consumer / APIkit for SOAP
|Drools|Removed.
|BPM|MuleSoft now provides connectivity to Pega or Appian for BPM.
|EJB|Removed.
|Guice|Removed.
|jBPM|MuleSoft now provides connectivity to Pega or Appian for BPM.
|Jetty	| Use new HTTP module.
|OGNL	| Replaced DataWeave expression language, or MEL in compatibility module.
|Patterns|Removed. Use flows instead.
|Quartz	| Use new Scheduler component.
|RSS	| Use HTTP + DataWeave
|SXC	| Use DataWeave.
|Tomcat 	| New embedded mode in development.
|Servlet	| New embedded mode in development.
|Stdio|Removed.
|UDP	| Use Sockets connector.
|XMPP|Removed.
|===

////
[[connector_1]]
== Connector_1

Intro re features covered:

 ** Feature_1
 ** Feature_2

=== Feature_1

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

=== Feature_2

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

[[connector_2]]
== Connector_2

Follows the same pattern.

////

== See Also

xref:migration-patterns.adoc[Migration Patterns]
