= Prepare to Migrate to Mule 4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// Contacts/SMEs: Esteban Wasinger, Ana Felisatti, Mariano Gonzalez

Mule 4 introduces many changes, so plan accordingly before attempting to migrate from Mule 3.

[[when_to_start]]
== When to Start Using Mule 4

MuleSoft recommends that you develop all *new* projects on Mule 4, provided that:

* You and your team have updated your skills for Mule 4 through the documentation or formal training.
* You have the <<prepare_dev_environ, proper deployment environment>>.
* You do not require all applications to be on a single version of Mule (see below).

For projects that are already in development or deployed on Mule 3 (whether a prospect or customer), MuleSoft recommends that you wait to migrate these applications until the Mule Migration Assistant (MMA) is available.

Migrate your applications if any one of the following conditions is met:

* The 3.x version you are using reaches end of life.
* You want to make significant updates to the existing applications.
* You want to take advantage of key Mule 4 capabilities.
* You decide to upgrade all their apps to Mule 4 because you require all apps to be on one version (some on-prem customers).

[[prepare_dev_environ]]
== Setting up Your Local Development Environment

First, you will need to download Studio 7 and install it. If you're deploying locally, you will also need to download the Mule 4 standalone runtime.
// TODO link to pages

[[prepare_to_deploy]]
== Getting Ready to Deploy
Next, you need to make sure your deployment environment is ready. Depending on which environment you have, different steps may be required.

[%header,cols="1,3"]
|===
|Deployment Mechanism | Instructions

|CloudHub
|CloudHub is Mule 4 ready.

|Hybrid Deployment
|You must install the standalone version of Mule 4 your servers.

|Anypoint Platform Private Cloud Edition (PCE)
| PCE supports Mule runtime, version 4.

|Anypoint Platform for Pivotal Cloud Foundry (PCF)
| PCF does not support Mule runtime, version 4.
|===

[[write_code]]
== Writing the Code

That's it! You're ready to start building and deploying Mule 4 applications.

You should review these topics to get an overview of the migration process and understand changes introduced in Mule 4:

xref:intro-overview.adoc[Introduction to Mule 4]
