= Migrating the Choice Router
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

// sme: DF, author: sduke?

The Choice router didn't change much from Mule runtime engine (Mule) 3 to Mule 4:

* DataWeave is now the expression language, so `<when>` attributes use it instead of MEL.
* The `<otherwise>` block is now optional.

== Expression Language for the When Block

Change `<when>` expressions from MEL to DataWeave. As an added benefit, you can leverage DataWeave's ability to interpret any format to avoid unnecesary convertions.

For example, suppose a flow in which a JSON document representing a user is posted through HTTP and you want to check if the person is below a specified age limit (underage).

.Mule 3 Example: MEL
[source,xml,linenums]
----
<flow name="checkAge">
  <http:listener path="person" method="POST" config-ref="http" />
  <json:json-to-object-transformer />
  <choice>
    <when expression="#[payload.age > 21]">
      <logger message="adult" />
    </when>
    <otherwise>
      <logger message="underage" />
    </otherwise>
  </choice>
</flow>
----

With Mule 4, you don't need to worry about JSON or Java formats.

.Mule 4 Example: DataWeave 2
[source,xml,linenums]
----
<flow name="checkAge">
  <http:listener path="person" method="POST" config-ref="http" />
  <choice>
    <when expression="#[payload.age > 21]">
      <logger message="adult" />
    </when>
    <otherwise>
      <logger message="underage" />
    </otherwise>
  </choice>
</flow>
----

== Optional Otherwise

In Mule 3, the `<otherwise>` block was required. Many times, when fallback logic wasn't necessary, the `<otherwise>` block contained an insignificant logger. In Mule 4, the `<otherwise>` block is optional and you don't need to specify it if it's not necessary.

== See Also

xref:intro-error-handlers.adoc[Introduction to Mule 4: Error Handlers]

xref:migration-mel.adoc[Migrating from MEL to DataWeave]

xref:migration-dataweave.adoc[Migrating from DataWeave 1.0 to 2.x]