= Migration to Mule 4
ifndef::env-site,env-github[]
include::_attributes[]
endif::[]

Mule 4 introduces a number of improvements over Mule 3, including:

* Easier and faster app development
* Seamless access and data mapping 
* Simplified connectivity
* Auto-tuned and highly performant runtime 
* Seamless upgrades of runtime and connector versions
* Up to 50% fewer steps and concepts to learn than Mule 3

For your Mule 3 apps to take advantage of these and other benefits, you can migrate your apps to Mule 4 through one of the following processes:

* A fully manual migration of connectors, modules, transports, expressions, and API gateways to their Mule 4 counterparts.
* A partially automated migration by using the Mule Migration Assistant (MMA), which
is available as an open source project on https://github.com/mulesoft/mule-migration-assistant[GitHub].

MuleSoft suggests that you try MMA to determine whether you prefer it to a fully manual migration. 

== Understand the Migration Process

Before beginning the migration process, review documentation on how to
prepare for the migration and understand the basic steps of the migration.

* xref:migration-prep.doc[Preparing for a Migration to Mule 4]: Both migration scenarios require the same preparation.
* MMA migration process +
//TODO (WAIT TO PUBLISH): https://github.com/mulesoft/mule-migration-assistant/......TODO......./migration-process (on GitHub)
* xref:migration-process.adoc[Manual Migration Process]
//TODO: CONFIRM TITLE "Manual Migration Process"

A benefit of using MMA is that it automates part of the migration of Mule 3 apps to Mule 4. Though the MMA does not migrate the app entirely, it provides significant help with the following tasks:

* Migrating the project structure.
* Automatically creating descriptor files, such as `pom.xml` or `mule-artifact.json`.
* Automatically performing many adaptations of the app’s code.
* Providing guidance on how to manually migrate components and patterns that cannot be migrated automatically.

MMA helps with such tasks, but it does not deliver a fully functional app. Some additional steps are required. Those steps include testing and can also include:

* Manual migration of unsupported components.
* Manual migration of complex MEL expressions to DataWeave that cannot be automatically converted by MMA.
* Manual migration of complex DataWeave transformations that cannot be automatically converted by MMA.
* Prior migration of the DataMapper with the DataWeave Migration tool, before running the MMA.

It is also important to note that the MMA does not support incremental migrations.

////
== See Also

* xref:migration-tutorial.adoc[Mule Migration Tool Tutorial]
* xref:migration-report.adoc[Mule Migration Report]
* xref:migration-tool-post-mig.adoc[Post-Migration Tasks]
////
