= Migrating Transports
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The transports in Mule 3 have been replaced by connectors that follow an operation model in Mule 4. Most transports are
replaceable by a connector in Mule 4.

This page addresses items of migration that are common to all transports. For transport-specific migration
documentation, refer to xref:migration-connectors.adoc[Migrating Connectors and Modules to Mule 4] and its child pages.

[[address]]
== Endpoint Addresses

In Mule 3, an endpoint could be configured with the attributes that are specific to the transport (for instance, `host`, `port` and `path` for http) or with the generic `address` attribute.

In the case where the generic `address` attribute was used, it was possible to reference a property, for instance:

[source,xml,linenums]
----
<http:inbound-endpoint address="${External.URL}"/>
----

where the properties configuration is something like:

[source,text,linenums]
----
External.URL=http://0.0.0.0:8080/rootPath
----

In Mule 4, the connectors define the connection attributes separately, so any full address property has to be split into its components.

[source,xml,linenums]
----
<http:listener-config name="listenerConfig">
    <http:listener-connection host="${External.URL.host}" port="${External.URL.port}"/>
</http:listener-config>

<flow>
    <http:listener config-ref="listenerConfig" path="${External.URL.path}"/>
    
    ...
</flow>
----

and the properties configuration becomes:

[source,text,linenums]
----
External.URL.host=0.0.0.0
External.URL.port=8080
External.URL.path=/rootPath
----

Check the documentation for a specific connector for details on what properties it requires. 

[[service_overrides]]
== Service Overrides

In Mule 3, the behavior of a transport could be customized via a `service-overrides` inside the connector, which
references Java classes with custom code to provide the new functionality.

.Mule 3 Example: Connector with `service-overrides`
[source,xml,linenums]
----
<imap:connector name="imapConnector" moveToFolder="processed" deleteReadMessages="false" checkFrequency="200">
    <service-overrides messageReceiver="org.mule.transport.email.functional.RetrieveMessageReceiverPollCounter"/>
</imap:connector>
----

In Mule 4, this kind of customization through custom Java code is not supported. There are three possible approaches
that can be taken to migrate such scenario, depending on what the custom code is actually doing:

* Replace it with some other feature of Mule or another component (i.e.: xref:dataweave.adoc[Data Weave] transformation, xref:connectors::java/java-module.adoc[Java Module]
or xref:connectors::scripting/scripting-module.adoc[Scripting Module]) that provides a similar functionality.
* Create a new connector based on the replacement of the modified transport with the custom code added. This will
require working with the SDK that was used to implemented the new connector for Mule 4. Refer to xref:1.1@mule-sdk::index.adoc[Mule SDK]. Open Source connectors may be used as dependencies in order to have a starting point.
* Similar to the previous approach, you may fork the connector and add the custom code there. Sending a Pull Request with that change is welcome, also.
* You can request a feature to be added to a connector that does what your custom code did in `service-overrides`. Visit https://support.mulesoft.com/s/ideas[MuleSoft Support Ideas] to submit your requirement.

== See Also

xref:migration-connectors.adoc[Migrating Connectors and Modules to Mule 4]

xref:intro-java-integration[Java Integration]

xref:1.1@mule-sdk::index.adoc[Mule SDK]