= Migration to Mule 4
ifndef::env-site,env-github[]
include::_attributes[]
endif::[]

//TODO: FOR GA, REMOVE *Beta* FROM GA VERSION
*Beta Release: Mule Migration tool and Compatibility Module*

This section provides guidance on migrating a Mule 3 app to Mule 4.

The migration process is a multi-part procedure, where you:

. Perform any pre-migration steps, such as migrating from the DataMapper to DataWeave.
. Run the migrator on a Mule 3 project.
. Import the migrator output into a supported version of Studio 7.
. Review the Migration report.
. Perform a manual migration on what the tool does not migrate.
. Remove uses of Compatibility module components.
. Run any migrated MUnit tests.

These steps are detailed in xref:migration-tool-procedure[Perform a Migration to Mule 4]. However, before proceeding with a migration, it is important to review the rest of this topic, which describes the <<migration_tool>>, the <<compatibility_module>>, and <<whats_migrated>>.

[[migration_tool]]
== Mule Migration Tool

The Mule Migration tool (migrator) automates the migration of Mule 3
apps to Mule 4. Though it does not migrate the app entirely,
the tool provides significant help with these tasks:

* Migrating the project structure.
* Automatically creating descriptor files, such as `pom.xml` or `mule-artifact.json`.
* Automatically performing a great number of adaptations in the app's
code.
* Providing guidance on how to manually migrate components and patterns that
cannot be migrated automatically.

The migrator helps with such heavy lifting, but it is not to be expected to
deliver a fully functional app. Some additional steps are required.
Those steps include testing and can also include:

* Manual migration of unsupported components.
* Manual migration of complex MEL expressions to DataWeave.
* Manual migration of complex DataWeave transformations.
* Prior migration of the DataMapper with the _DataWeave_ Migration tool,
_before_ running the Mule Migration tool.

It is important to note that the Mule Migration tool does not support
incremental migrations.

[[compatibility_module]]
== Compatibility Module

Some components or patterns cannot be migrated automatically by transforming
the app's XML. For such cases, the migrator adds the Compatibility
module to your project. The Compatibility module is a set of components that
either adapts Mule 3 components into the Mule 4 architecture, or in some cases,
enables some Mule 3 components to work in Mule 4.

*Important:* MuleSoft recommends that you migrate to a point where the
Compatibility module can be dropped from your app and that you simply use the
module as a bridge until the manual steps of the migration are complete.

The Compatibility module does not cover every migration gap. Instead, it
complements the Mule Migration tool:

 * By providing MEL support for the cases where a MEL expression could not be
 migrated to DataWeave automatically.
 * By adapting the Mule 3 Message model to Mule 4.

You or your team will need to handle other migration gaps that are covered in the xref:migration-report.adoc[Mule Migration report].

//TODO: QUESTION: API for the tool? Tool consists of an execution engine,
//a proprietary API to allow extensions of it, and a reporting framework.


[[whats_migrated]]
== What Is Migrated?

* <<supported_migrations>>
* <<unsupported_migrations>>
* <<unsupported_connectors>>
* <<supported_future>>

[[supported_migrations]]
=== Supported Migrations

//TODO: FOR GA, REMOVE NOTE AND REVISE CONTENT, AS NEEDED
*Note on the Beta release*: This list applies to the Beta and will expand over
time.

The Mule Migration tool supports the following migrations:

* Mule apps and domains only (no policies are supported)
* MEL to DataWeave expressions (simple cases only)
* DataWeave component to `ee:transform` (DataWeave 1.0 to DataWeave 2.0)
* Connectors: HTTP, Database, Web Service Consumer, ObjectStore
* Modules: Validations, Scripting (DSL only, no migration of the script itself)
* Transports: HTTP, JMS, File, VM
* Components: Cache, Batch, For Each, Choice, Scatter-Gather, Poll
* Error Handling, Transactional scope
* Properties and secure properties
* Spring Beans definitions
* xref:migration-tool-procedure#munit[MUnit tests]
* ApiKit

Note that the <<compatibility_module, Compatibility module>> supports some
additional items from Mule 3.x until you can migrate them:

* `set-property`
* `remove-property`
* `copy-properties`
* `set-session-variable`
* `remove-session-variable`

[[unsupported_migrations]]
=== Unsupported Migrations

//TODO: FOR GA, REMOVE NOTE AND REVISE CONTENT, AS NEEDED
*Note on the Beta release*: This list applies to the Beta and will change over
time.

The Mule Migration tool does not support the following migrations:

* Custom Java code, either used directly or through any of the following:
** `<custom-transformer>`
** `<custom-message-processor>`
** `<component>`
** `<pooled-component>`
** `<invoke>`
** Anything that implements the `org.mule.api.lifecycle.Callable` interface
** etc.
* DataMapper: Use the DataWeave Migration tool. See
xref:migration-tool-procedure#datamapper[Migrating from the DataMapper to DataWeave].

See also:

* xref:migration-tool-procedure#devkit[Migrating Custom DevKit Connectors]
* <<unsupported_connectors>>

[[unsupported_connectors]]
=== Unsupported Connectors

Connectors that are used in an app but not yet supported by the Mule Migration
tool generate this ERROR in the Migration report:

`The migration of some-connector is not supported`

Such connectors require manual migration.

To manually migrate them, see xref:migration-tool-procedure#unsupported_projects[Migrating Unsupported Connectors].

[[supported_future]]
=== Supported in the Future

*Note on the Beta Release:* This list might change over time.

For future releases, we will also support these:

* Documentation on how to migrate DataMapper transformations
* `<until-successful>`
* `<first-successful>`
* `<async>`
* Security Module
* Watermark
* Email transport
* Tracking component
* Gzip transformers
* Basic structure for policies
* FTP and SFTP transports
* XML and JSON module
* Splitter and aggregator pattern

== See Also

xref:migration-report.adoc[Mule Migration Report]

xref:migration-tool-post-mig.adoc[Post-Migration Tasks]
