= Migrating the Security Filters
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Mule runtime engine (Mule) 3, the Security Filters are part of the Mule Module Security. In Mule 4, security filters are in the xref:connectors::validation/validation-connector.adoc[Mule Validation Module].

== IP filters

In Mule 3 you can filter by IP, IP range, or IP range pulus CIDR:
* `<filters:filter-by-ip>`
* `<filters:filter-by-ip-range>`
* `<filters:filter-by-ip-range-cidr>`

=== Filtering By One IP in Mule 3

.Example: Filtering by one IP in Mule 3
[source,xml,linenums]
----
<filters:filter-by-ip regex="127.0.0.1"/>
----

This will filter those IPs that matches the regex. In mule4:

.Example: Filtering by One IP in Mule 4
[source,xml,linenums]
----
<validation:is-blacklisted-ip blacklist="iplist" ip="#[vars.ip]">
<validation:ip-filter-list>
	<validation:ips>
		<validation:ip value="127.0.0.1"/>
	</validation:ips>
</validation:ip-filter-list>
----

Where is necessary to set that `ip` variable (or whichever variable suits).

=== Filtering by a Range of IPs

In mule 3, we had two ways of defining subnet mask to filter with:

.Example: Filtering by IP range in Mule 3
[source,xml,linenums]
----
<filters:filter-by-ip-range net="127.0.0.1" mask="255.255.255.0"/>
<!-- or -->
<filters:filter-by-ip-range-cidr cidr="127.0.0.1/24"/>
----

Both are replaced by:

.Example: Filtering by IP range in Mule 4
[source,xml,linenums]
----
<validation:is-blacklisted-ip blacklist="iplist" ip="#[vars.ip]">
<validation:ip-filter-list>
	<validation:ips>
		<validation:ip value="127.0.0.1/24"/>
	</validation:ips>
</validation:ip-filter-list>
----

Set the `ip` variable.

Mule 4 also offers whitelist validation, which only allows IPs from an IP filter list.

== Time Expiration Filters

In Mule 3 you can filter the message if it older than a specifed time from a starting date. For example:

.Example: Filtering by elapsed time in Mule 3
[source,xml,linenums]
----
<filters:filter-expired dateTime="#[vars.startingTime]" expiresIn="1000"/>
----

In Mule 4, this validation is in the validations module:

.Example: Filtering by elapsed time in Mule 4
[source,xml,linenums]
----
<validation:is-not-elapsed time="1" timeUnit="SECONDS" since="#[vars.startingTime]"/>
----

Mule 4 also offers a time-elapsed validation, which validates whether the time elapsed has exceded a specified amount of time.

== See Also
xref:connectors::validation/validation-documentation.adoc[Validation Connector Technical Reference]