= Migrating the Poll Component
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In Mule 3, the `<poll>` element was used to trigger a certain flow at a fixed frequency of time. This element was also a scope which required one (and only one) message processor to live inside of it. The output of that processor would be the message that the flow receives.

.Mule 3 Example: Poll
[source,xml,linenums]
----
<flow name="poll>
    <poll frequency="1000">
        <db:select config-ref="MySQL_Configuration">
            <db:parameterized-query>SELECT * FROM PERSON></db:parameterized-query>
        <db:select>
    </poll>

    <flow-ref name="doProcess" />
</flow>
----

In Mule 4, the `<poll>` element was replaced with the `<scheduler>` element. Main differences are:

* It just triggers the flow. It's no longer a scope
* It supports both fixed frequency and cron expressions

.Mule 4 Example: Scheduler
[source,xml,linenums]
----
<flow name="poll>
    <scheduler>
        <scheduling-strategy>
            <fixed-frequency frequency="1000"/>
        </scheduling-strategy>
    </scheduler>

    <db:select config-ref="MySQL_Configuration">
        <db:sql>SELECT * FROM PERSON></db:sql>
    <db:select>

    <flow-ref name="doProcess" />
</flow>
----

For more information on the `<scheduler>` element, please read the xref:scheduler-concept.adoc[Scheduler documentation].

== Migrating a Watermark

The `<poll>` element also supported a `<watermark>` element which was used to aid and scheduled synchronizations. That element doesn't exist anymore. Instead, please read
the xref:migration-patterns-watermark.adoc[Migrating Watermarks] page.

[[qz]]
== Quartz transport

In Mule 3, a `quartz` transport existed that had been deprecated in favor of the `poll`, so most of its uses may also be replaced by the `scheduler` in Mule 4.

Some features of the `quartz` transport do not exist in Mule 4 though, and a different approach must be taken to migrate those use cases.

[[qz_repeat_count]]
=== `repeatCount`

This is not supported in Mule 4 by the `scheduler`.

If this is really needed by fetching, comparing and storing a counter in an xref:connectors::object-store/object-store-connector.adoc[Object Store].

[[qz_outbound_endpoint]]
=== `quartz:outbound-endpoint`

This is not supported in Mule 4.

An alternative approach is to write the events to a queue (JMS or VM, for instance) and have another flow with with a scheduler that consumes all the messages from the queue and processes them.

[[qz_job_endpoint]]
=== Unsupported `job-endpoint`

The transport used in a `job-endpoint`, when migrated to a Mule 4, may be migrated to a connector that has a polling source (such as File). In that case, the scheduler configuration may be put directly into the polling source. 

.Mule 3 Example: Polling source
[source,xml,linenums]
----
<flow name="poll>
    <quartz:inbound-endpoint name="quartzInboundEndpoint"
        cronExpression="0/3 * * * * ?" jobName="cronJob">
        <quartz:endpoint-polling-job>
            <quartz:job-endpoint address="sftp://.../~/data" />
        </quartz:endpoint-polling-job>
    </quartz:inbound-endpoint>

    <flow-ref name="doProcess" />
</flow>
----

.Mule 4 Example: Polling source
[source,xml,linenums]
----
<flow name="poll>
    <sftp:listener config-ref="inboundEndpointConfig" directory="data">
        <scheduling-strategy>
            <cron expression="0/3 * * * * ?"/>
        </scheduling-strategy>
    </sftp:listener>

    <flow-ref name="doProcess" />
</flow>
----

== See Also

* xref:scheduler-concept.adoc[Scheduler documentation]