= About Deploying a Mule Application (Mule Maven Plugin)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Mule Maven Plugin allows you to automate the deployment of your Mule application to your Mule servers. +

By default, this plugin allows you to deploy using four different deployment strategies:

* CloudHub deployment. +
Automate the deployment of your Mule application to CloudHub.
* ARM deployment. +
Deploy your Mule application to your Mule server, or server clusters using the ARM API.
* Mule Agent deployment. +
Deploy your Mule Application using the Mule Agent. +
This deployment strategy only works if all your Mule Runtime instances live under the same address space.
* Standalone runtimes deployment. +
Deploy to a runtime running on your own machine.

When deploying an application using the Mule Maven Plugin you need to specify a valid deployment configuration in your pom file. +
You can set up deployment configuration using their dedicated deployment references.



== See Also

* xref:ch-deploy-mule-application-mmp-task.adoc[To Deploy a Mule Application to CloudHub (Mule Maven Plugin)]
* xref:stnd-deploy-mule-application-mmp-task.adoc[To Deploy a Mule Application to a Standalone Mule Runtime (Mule Maven Plugin)]
* xref:arm-deploy-mule-application-mmp-task.adoc[To Deploy a Mule Application Using ARM API (Mule Maven Plugin)]
* xref:agent-deploy-mule-application-mmp-task.adoc[To Deploy a Mule Application Using the Mule Agent (Mule Maven Plugin)]