= Mule Maven Plugin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Mule Maven plugin enables you to integrate the packaging and deployment of your Mule applications with your Maven lifecycle. +
See xref:package-a-mule-application.adoc[Package a Mule Application] for packaging instructions.

The Mule Maven plugin is compatible with Mule runtime engine (Enterprise Edition) and with Mule Kernel (Community Edition).

Using the Mule Maven plugin, you can automate your Mule application deployment to CloudHub, to Anypoint Runtime Fabric, or on-premises, using any of the following deployment strategies:

* CloudHub deployment +
Deploys your Mule application to CloudHub. +
See xref:deploy-to-cloudhub.adoc[Deploy Applications to CloudHub] for instructions.
* Runtime Fabric deployment +
Deploys your Mule application to Anypoint Runtime Fabric. +
See xref:deploy-to-rtf.adoc[Deploy Applications to Anypoint Runtime Fabric] for instructions.
* Runtime Manager REST API deployment +
Deploys your Mule application to your server, or server clusters using the Runtime Manager REST API. +
See xref:deploy-on-premises.adoc#mmp-deploy-arm[Deploy a Mule Application Using the Runtime Manager REST API] for instructions.
* Runtime Manager agent deployment +
Deploy your Mule application using the Runtime Manager agent. +
This deployment strategy works only if all your Mule instances reside in one address space. +
See xref:deploy-on-premises.adoc#mmp-deploy-agent[Deploy a Mule Application Using the Runtime Manager Agent] for instructions.
* Standalone runtime deployment +
Deploy your Mule application to a Mule instance running on your machine. +
See xref:deploy-on-premises.adoc#mmp-deploy-standalone[Deploy a Mule Application to a Standalone Mule Runtime Engine] for instructions.

== Compatibility

* Mule 4.x
* Anypoint Studio 7.x

== Mule Maven Plugin Goals

The Mule Maven plugin has three goals:

* `package` +
Generates the jar file for your project.
* `deploy` +
Automatically uploads and starts your application in any of the application deployment targets (CloudHub, Runtime Fabric, or On-Premises).
* `mule:undeploy` +
Automatically removes your application from any of the application deployment targets (CloudHub, Runtime Fabric, or On-Premises).

Each goal accepts parameters that are unique to the desired plugin behavior.
To provide a parameter from the command line, prepend `-D` to the parameter name.

[[package-goal]]
=== Package Goal

The `package` goal generates the application JAR file. This goal binds by default to the Maven lifecycle phase: `package`.

Optional Parameters
[%header%autowidth.spread,cols="a,a,a"]
|===
|Name | Type | Description
|`onlyMuleSources` | boolean | Generates the application JAR file containing only the source code. This property is just for sharing purposes.
|`attachMuleSources` | boolean | Attaches the source code inside the generated JAR file.
|`lightweightPackage` | boolean | Doesn't generate the repository with all the application dependencies inside the JAR file. This property is just for sharing purposes.
|===

For example, to execute the `package` goal and set the `attachMuleSources` parameter, you run the following command:
[source,console,linenums]
----
mvn package -DattachMuleSources
----

=== Deploy Goal

This goal uploads and deploys the application JAR file to any of the application deployment targets. The deploy goal binds by default to the Maven lifecycle phase: `deploy`.

Optional Parameters
[%header%autowidth.spread,cols="a,a,a"]
|===
|Name | Type | Description
|`artifact` | String | Path to the application JAR file to be deployed. By default is set to the application `target` folder.
|`muleDeploy` | boolean | Instructs the plugin to deploy using the deployment strategy defined in the plugin configuration. If the `muleDeploy` parameter is not set, the plugin uploads the artifacts to the repository defined in the `distributionManagement` section of the application's `pom.xml` file.
|===

For example, to execute the `deploy` goal and set the `muleDeploy` parameter, you run the following command:
[source,console,linenums]
----
mvn deploy -DmuleDeploy
----

=== Undeploy Goal

This goal removes an application from any of the application deployment targets. It uses the information from the plugin configuration to remove the application from the defined deployment target.

To execute the `undeploy` goal, run the following command:
[source,console,linenums]
----
mvn mule:undeploy
----

The undeploy goal also deletes the app in Mule Maven plugin 3.3.0 and later versions.

[[add-mmp]]
== Add the Mule Maven Plugin to a Mule Project

Before you can perform any operations, you must add the Mule Maven plugin to your project.

include::4.2@partial$mmp-concept.adoc[tag=addMuleMavenPluginToAProject]

== Skip Plugin Execution

You can skip the plugin execution by setting the `skip` parameter to true inside your deployment configuration:

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
  <configuration>
    <standaloneDeployment>
      <muleHome>${mule.home.test}</muleHome>
      <skip>true</skip>
    </standaloneDeployment>
  </configuration>
</plugin>
----

== Skip Deployment Verification

You can skip the status verification of your deployed app by setting the `skipDeploymentVerification` parameter to true inside of any of the platform deployments (Cloudhub, Runtime Manager, and Runtime Fabric):

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
  <configuration>
    <runtimeFabricDeployment>
      ...
      <skipDeploymentVerification>true</skipDeploymentVerification>
      ...
    </runtimeFabricDeployment>
  </configuration>
</plugin>
----

If the `skipDeploymentVerification` parameter is not present, the default value is false. +
This feature is available in plugin version 3.2.5 and later.

== See Also

* xref:about-classloading-isolation.adoc[Classloading Isolation]
* xref:how-to-export-resources.adoc[Export Resources]
* xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven]
* xref:runtime-fabric::deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric]
* xref:runtime-manager::runtime-manager-api.adoc[Runtime Manager REST API]
* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
