= Mule Maven Plugin
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Mule Maven Plugin allows you to integrate the packaging, testing, and deployment of your Mule applications with your Maven lifecycle. +
This plugin allows you to deploy your Mule application to different deployment targets such as standalone runtimes, clustered instances, and CloudHub.

The Mule Maven Plugin supports both Community and Enterprise editions.

== Compatibility

* Mule 4.x
* Anypoint Studio 7.x

== Goals Overview

The Mule Maven Plugin has three goals:

* `xref:mmp-concept.adoc#package-goal[package]`
+
Generates the jar file for your project.
* `xref:mmp-concept.adoc#deploy-goal[deploy]`
+
Automatically uploads and starts your application in any of the application deployment targets (CloudHub, Runtime Fabric, or On-Premises).
* `xref:mmp-concept.adoc#undeploy-goal[mule:undeploy]`
+
Automatically removes your application from any of the application deployment targets (CloudHub, Runtime Fabric, or On-Premises).

== Add the Mule Maven Plugin to a Mule Project

To add the Mule Maven Plugin, you need to add its maven dependency to the project:

[source,xml,linenums]
----
<plugin>
  <groupId>org.mule.tools.maven</groupId>
  <artifactId>mule-maven-plugin</artifactId>
  <version>3.3.2</version>
  <extensions>true</extensions>
</plugin>
----

From this repository:

[source,xml,linenums]
----
<pluginRepositories>
    <pluginRepository>
        <id>mule-public</id>
        <url>https://repository.mulesoft.org/nexus/content/repositories/releases</url>
    </pluginRepository>
</pluginRepositories>
----

This enables the Mule Maven Plugin in your project.

[IMPORTANT]
Enable extensions. If `<extensions>true</extensions>` is not present, the plugin does not work.

== Mule Application Packaging

The Mule Maven Plugin can package your Mule application into a deployable JAR file that you can later deploy to a running Mule Runtime. +
The package contains the application and all its dependencies whether those be JAR files required by the application or by its plugins.

Every Mule application has two descriptors. These descriptors tell the plugin how to handle your Mule application's dependencies.

* A `mule-artifact.json` file. +
This file describes how your application is composed. +

* A `pom.xml` file. +
This file describes all the dependencies required by the package to work properly.

=== Package a Mule Application

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. From the command line in your project's folder, run the package goal:
+
[source,console,linenums]
----
$ mvn clean package
----

The plugin packages your application and creates the deployable JAR file into the target directory within your project's folder. +

=== Create an Application Package to Import into Anypoint Studio

To generate a JAR file that can be imported into Anypoint Studio, you need to package your application using the `-DattachMuleSources` parameter to include source files and metadata that Studio requires to re-import the deployable file as an open Mule project into your workspace.

From the command line in your project's folder, run:
[source,console,linenums]
----
$ mvn clean package -DattachMuleSources
----

The `-DattachMuleSources` parameter tells the plugin to add a `mule-src` folder inside the `META-INF` directory with an exact copy of your application structure at design time. This option also packages project modules and dependencies required to create a functioning Mule deployable archive file that can be deployed into a Mule runtime engine.

=== Create a Lightweight Package

You can skip bundling the actual modules and external dependencies required to run the Mule application in a Mule runtime engine, and create a lightweight package with only the source files and metadata required to import the JAR package back into Anypoint Studio.

From the command line in your project's folder, run:
[source,console,linenums]
----
$ mvn clean package -DlightweightPackage
----

When you specify this parameter, the plugin creates a lightweight JAR file that does not include any dependencies declared in the Mule application's `pom.xml` file. This JAR file cannot be deployed to a Mule runtime engine, it only offers a way to archive just the Mule application's source files. The result of this Maven parameter is the same as unchecking *Include project modules and dependencies* when exporting the Mule application from Anypoint Studio.

=== Specify Multiple Parameters

You can also combine the parameters together to create a lightweight Mule application package that also includes the source files and metadata to import the package back into Anypoint Studio.

From the command line in your project's folder, run:
[source,console,linenums]
----
$ mvn clean package -DattachMuleSources -DlightweightPackage
----
== Mule Application Structure Reference

At design time, your Mule application must have at least these three basic components:

[%header%autowidth.spread,cols=",,"]
|===
| Component | Type | Description
| `src`
| Folder
| The source directory for your application's productive source code and tests. +
See a reference for this folder below.

| `pom.xml`
| Descriptor
| The POM file of your Mule application. +
This file describes all of your application's required dependencies.


| `mule-artifact.json`
| Descriptor
| The mule-artifact file of your Mule application. +
This file describes how your Mule application is composed.

|===

These three components are mandatory. If one is missing, the plugin won't package your project into a deployable JAR file. +
Additionally, the plugin does not consider any other directory or file in the root folder of your Mule application when packaging.


== Source Directory Reference

The `src` directory has two main folders: `main` and `test`. +
The plugin does not consider any other directory inside `src` when packaging the application.

=== src/main

src/main is the root folder for all the productive source code of the application.

[%header%autowidth.spread,cols=",,"]
|===
|Folder  | Folder Type | Description

| `src/main/mule`
| source
| The root folder of the Mule configuration files. +
It can contain nested folders, in the way of Java packages.

This folder is mandatory.

| `src/main/resources`
| resource
| It contains the application resources, such as XML, JSON, and properties files. +
Jar files located here are loaded by the application classloader but as plain file resources.
|===

The plugin sends all files inside src/main/mule and src/main/resources to the root directory of your binary package. +
Nested folders within src/main/mule are preserved as directories within the root directory of the binary package.

=== src/test

src/test is the root folder for all the test source code of the application.

[%header%autowidth.spread,cols=",,"]
|===
|Folder | Folder Type | Description

| `src/test/java`
| source
| It’s the root folder of the test classes used to validate the custom Java code of the app. +
It follows the conventions of any normal Java application.

| `src/test/munit`
| source
| It contains the MUnit source code. +
It can contain nested folders in the way of packages.

| `src/test/resources`
| resource
| It contains resources, such as XML, JSON,  and properties files. +
This folder also contains files describing metadata being referenced in the `mule-config.xml`.

|===

== Mule Application Deployment

The Mule Maven Plugin allows you to automate the deployment of your Mule application to any of the application deployment targets (CloudHub, Runtime Fabric, or On-Premises). +

By default, this plugin allows you to deploy using five different deployment strategies:

* CloudHub deployment. +
Automate the deployment of your Mule Application to CloudHub.
* Runtime Fabric deployment. +
Deploy your Mule Application to Runtime Fabric.
* Runtime Manager REST API deployment. +
Deploy your Mule Application to your server, or server clusters using the Runtime Manager REST API.
* Mule Agent deployment. +
Deploy your Mule Application using the Mule Agent. +
This deployment strategy only works if all your Mule instances live under the same address space.
* Standalone runtime deployment. +
Deploy to a Mule instance running on your machine.

When deploying an application using the Mule Maven Plugin you need to specify a valid deployment configuration in your `pom.xml` file. +
You can set up a deployment configuration using their dedicated deployment references.

== Deploy a Mule Application to CloudHub

=== Prerequisites

* The host and port number of your HTTP Listener flow sources are properly configured. +
+
If you are using the HTTP Listener as sources for your flow, you need to set its host to *0.0.0.0* and its port to *${http.port}*.
+
CloudHub then dynamically allocates a port at deployment time.
+
* All your external classes and resources are properly declared in the `mule-artifact.json` file of your Mule application.
+
Due to Mule 4.x classloading isolation mechanism, all external classes and resources must be explicitly declared in the "exportedPackages" and "exportedResources" fields on the `mule-artifact.json` file before packaging and deploying the app.
+
See xref:how-to-export-resources.adoc[Export Resources] to learn more about working with external resources in your Mule application.

=== Deploying to CloudHub

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your CloudHub deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <cloudHubDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${app.runtime}</muleVersion>
            <username>${username}</username>
            <password>${password}</password>
            <applicationName>${cloudhub.application.name}</applicationName>
            <environment>${environment}</environment>
            <properties>
                <key>value</key>
            </properties>
        </cloudHubDeployment>
    </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your CloudHub information.
. From the command line in your project's folder, package the app and run the deploy goal:
+
[source,console,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

=== Redeploying to CloudHub

To redeploy the app, run the same command as you did to deploy. +
CloudHub rewrites the app you had deployed.

=== Undeploying from CloudHub

To undeploy an app, run the following command:

[source,console,linenums]
----
$ mvn mule:undeploy
----

The undeploy command also deletes the app in Mule Maven Plugin 3.3.0 and later versions.

=== CloudHub Deployment Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`cloudHubDeployment` | Top-Level Element.
| `uri` | Your Anypoint Platform URI. +
If not set, by default this value is set to +https://anypoint.mulesoft.com+.
| `muleVersion` | The Mule runtime version that will run in your CloudHub instance. +
You need to ensure that this value is equal to or higher than the minimum required runtime version of your application.
| `username` | Your CloudHub username.
| `password` | Your CloudHub password.
| `applicationName` | The name of your application in CloudHub. +
This name is part of the domain of your deployed app. For example, naming your application application-1 makes your app's public domain +application-1.cloudhub.io+.
| `artifact` | Absolute file location of the JAR to be deployed. +
If not set, by default it is the location of the JAR generated at the package phase
| `environment` | The CloudHub environment to which you want to deploy.
// tag::propertiesParameterDescription[]
| `properties` | Top-Level element. +
If you need to set properties for the Mule application you are deploying, you can use the `<properties>` top-level element:
[source,xml,linenums]
----
<properties>
  <key>value</key>
</properties>
----

For example:
[source,xml,linenums]
----
<properties>
  <http.port>8081</http.port>
</properties>
----
// end::propertiesParameterDescription[]
| `workers` | The number of workers. +
By default, it is set to 1.
| `workerType` | Size of each worker. +

Accepted values are:

MICRO (0.1 vCores) +
SMALL (0.2 vCores) +
MEDIUM (1 vCore ) +
LARGE (2 vCores) +
XLARGE (4 vCores) +
XXLARGE (8 vCores) +
4XLARGE (16 vCores)

The default value is MICRO.
| `region` | Region of worker clouds.

Accepted values are:

* us-east-1      -  US East (N. Virginia)
* us-west-2      -  US West (Oregon)
* eu-west-1      -  EU (Ireland)
* ap-southeast-2 -  Asia Pacific (Sydney)
* ap-southeast-1 -  Asia Pacific (Singapore)
* us-west-1      -  US West (N. California)
* eu-central-1   -  EU (Frankfurt)
* ap-northeast-1 -  Asia Pacific (Tokyo)
* eu-west-2      -  EU (London)
* ca-central-1   -  Canada (Central)
* sa-east-1      -  South America (São Paulo)
* us-east-2      -  US East (Ohio)

The default value is  us-east-1.
// tag::businessGroupParameterDescription[]
| `businessGroup` | The Business group path of the deployment. +
For example:
[source,xml,linenums]
----
<businessGroup>MasterOrg/SubOrg</businessGroup>
----
// end::businessGroupParameterDescription[]
// tag::businessGroupIdParameterDescription[]
| `businessGroupId` | The Business group id of the deployment. +
This parameter is available in plugin version 3.2.7 and later.
// end::businessGroupIdParameterDescription[]
// tag::deploymentTimeoutParameterDescription[]
| `deploymentTimeout` | The allowed elapsed time, in milliseconds, between the start of the deployment process and the confirmation that the artifact has been deployed.

The default value is `1000000`.
// end::deploymentTimeoutParameterDescription[]
// tag::serverParameterDescription[]
| `server` | Maven server with Anypoint Platform credentials. This is only needed if you want to use your credentials stored in your Maven `settings.xml` file. This is not the Mule server name.
// end::serverParameterDescription[]
// tag::skipParameterDescription[]
|`skip` | Boolean value. When set to true, skips the plugin deployment goal. Its default value is false.
// end::skipParameterDescription[]
|===

== Deploy a Mule Application to Runtime Fabric

=== Prerequisites

* Before deploying an application to Runtime Fabric, check the number of resources required. See xref:runtime-fabric::deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric] for more information.
* The application must be published in Exchange. +
** To do this from Studio, see xref:studio::export-to-exchange-task.adoc[Publishing a Project to Exchange]. +
** To do this using Maven, see xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].

[NOTE]
Studio allows you to select only two project types when uploading an application to Exchange: `example` and `template`. To specify a different project type, publish your application using Maven.

[[deploying-to-rtf]]
=== Deploying to Runtime Fabric

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your Runtime Fabric deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <runtimeFabricDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${app.runtime}</muleVersion>
            <username>${username}</username>
            <password>${password}</password>
            <applicationName>${runtime.fabric.application.name}</applicationName>
            <environment>${environment}</environment>
            <provider>${provider}</provider>
            <properties>
                <key>value</key>
            </properties>
            <deploymentSettings>
                <publicUrl>${app.url}</publicUrl>
                <cpuReserved>500m</cpuReserved>
                <memoryReserved>800Mi</memoryReserved>
            </deploymentSettings>
        </runtimeFabricDeployment>
    </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your Runtime Fabric information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,bash,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

=== Redeploying to Runtime Fabric

To redeploy the application, run the same command as you did to deploy. +
Runtime Fabric rewrites the application you had deployed.

=== Runtime Fabric Deployment Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`runtimeFabricDeployment` | Top-Level Element.
| `uri` | Your Anypoint Platform URI. +
If not set, by default this value is set to +https://anypoint.mulesoft.com+.
| `muleVersion` | The Mule runtime version that will run in your Runtime Fabric instance. +
You need to ensure that this value is equal to or higher than the minimum required runtime version of your application.
| `username` | Your Anypoint Platform username.
| `password` | Your Anypoint Platform password.
| `applicationName` | The name of your application deployed in Exchange. +
This name is part of the domain of your deployed app.
| `target` | The Runtime Fabric target name where to deploy the app.
| `provider` | Provider type. Set to MC ("MC" specifies Runtime Fabric).
| `environment` | The Anypoint Platform environment to which you want to deploy.
| `clusteringEnabled` | Enable Mule clustering across each replica of the application. It requires to have at least two replicas. +
By default, is set to false. +
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=serverParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=propertiesParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=skipParameterDescription]
| `deploymentSettings` | See the xref:mmp-concept.adoc#deploymentsettings-reference[deploymentSettings Reference] table below for a complete list of parameters that can be configured inside this element.
|===

=== deploymentSettings Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
| `replicationFactor` | The number of instances for your application. +
By default, it is set to 1. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <replicationFactor>2</replicationFactor>
</deploymentSettings>
----
| `lastMileSecurity` | Enable Last-Mile security to forward HTTPS connections to be decrypted by this application. +
This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources. +
By default, is set to false. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <lastMileSecurity>true</lastMileSecurity>
</deploymentSettings>
----
| `memoryReserved` | Amount of memory to be allocated for each replica of the application. If not present, the default value is 700MB. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <memoryReserved>100Mi</memoryReserved>
</deploymentSettings>
----
This will set 100MB of memory to each replica.
| `memoryMax` | Amount of max memory to be allocated for each replica of the application. If a memoryReserved configuration is present, ensure that this value is equal or higher. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <memoryMax>200Mi</memoryMax>
</deploymentSettings>
----
This will set 200MB of memory max to each replica.
| `cpuReserved` | Amount of cores to be allocated for each replica of the application. If not present, the default value is 0.5 vCores. +
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <cpuReserved>500m</cpuReserved>
</deploymentSettings>
----
This will set 0.5 vCores for each replica.
| `cpuMax` | Amount of max cores to be allocated for each replica of the application. If a cpuReserved configuration is present, ensure that this value is equal or higher.
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <cpuMax>1000m</cpuMax>
</deploymentSettings>
----
This will set a max of 1 vCores to each replica.
| `publicUrl` | Url of the deployed application.
For example:
[source,xml,linenums]
----
<deploymentSettings>
    <publicUrl>myapp.anypoint.com</publicUrl>
</deploymentSettings>
----
|===

== Deploy a Mule Application to a Standalone Mule Runtime

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your CloudHub deployment as shown below:
+
[source,xml,linenums]
----
<plugin>

  <configuration>
    <standaloneDeployment>
      <muleHome>${mule.home.test}</muleHome>
      <muleVersion>${app.runtime}</muleVersion>
    </standaloneDeployment>
  </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your local Mule runtime information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,console,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

=== Standalone Deployment Reference

[%header,cols="30,70"]
|===
|Parameter | Description
|`standaloneDeployment` | Top-Level Element.
| `muleVersion` | The Mule runtime version running in your local machine instance. +
If this value does not match the runtime version running in your deployment target, the plugin raises an exception.

The Mule Maven Plugin does not download a Mule runtime if these values don't match.
| `muleHome` | The location of the Mule Runtime instance in your local machine.
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=skipParameterDescription]

|===

== Deploy a Mule Application Using the Runtime Manager REST API

=== Prerequisites

* You need a server, server group or cluster created in Runtime Manager. +
** To create a server, see xref:runtime-manager::servers-create.adoc#creating-a-server[Creating a Server]. +
** To create a server group, see xref:runtime-manager::server-group-create[Creating a Server Group]. +
** To create a cluster, see xref:runtime-manager::cluster-create#creating-a-cluster[Creating a Cluster]. +

=== Deploying Using the Runtime Manager REST API

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your Runtime Manager deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
      <armDeployment>
        <muleVersion>${app.runtime}</muleVersion>
        <uri>https://anypoint.mulesoft.com</uri>
        <target>${target}</target>
        <targetType>${target.type}</targetType>
        <username>${username}</username>
        <password>${password}</password>
        <environment>${environment}</environment>
        <properties>
          <key>value</key>
        </properties>
      </armDeployment>
    </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your Runtime Manager information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,console,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

=== Runtime Manager REST API Deployment Reference

[%header%autowidth.spread,cols="a,a"]
|===
|Parameter | Description
|`armDeployment` | Top-Level Element.
| `muleVersion` | The runtime version required for your application to run in your deployment target. +
If this value does not match the runtime version running in your deployment target, the plugin raises an exception.

The Mule Maven Plugin does not download a Mule runtime if these values don't match.
| `uri` | The server URI where your Mule runtime instances are installed. +
If not set, by default this value is set to +https://anypoint.mulesoft.com+.
| `target` | The server name for the server where your Mule runtime instances are installed.
| `targetType` | The type of target to which you are deploying.

Valid values are:

* server
* serverGroup
* cluster

| `username` | Your username for the server where your Mule runtime instances are installed.
| `password` | Your password for the server where your Mule runtime instances are installed.
| `environment` | The environment name for the server where your Mule runtime instances are installed.
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=serverParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=propertiesParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=skipParameterDescription]
|===

== Deploy a Mule Application Using the Mule Agent

. Make sure you added the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your Mule Agent deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
  <configuration>
    <agentDeployment>
      <uri>http://localhost:9999/</uri>
    </agentDeployment>
  </configuration>

</plugin>
----
+
The example is using placeholder values. Configure the URI value with your remote server information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,console,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

=== Mule Agent Deployment Reference

[%header,cols="30,70"]
|===
|Parameter | Description
|`agentDeployment` | Top-Level Element.
| `muleVersion` | The runtime version required for your application to run in your deployment target. +
If this value does not match the runtime version running in your deployment target, the plugin raises an exception.

The Mule Maven Plugin does not download a Mule runtime if these values don't match.
| `uri` | The server URI where your Mule runtime instances are installed.
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime:ROOT:page$mmp-concept.adoc[tag=skipParameterDescription]
|===

== Deploy a Domain

The Mule Maven Plugin supports deploying domains to standalone Mule instances and also when using the Mule agent.

To deploy a domain, use the same configuration and deployment steps you use when deploying an application. For example, to deploy a domain to a Standalone instance:

. Add the Mule Maven Plugin to your `pom.xml` file.
. Inside the plugin element, add a configuration for your standalone deployment. For example:
+
[source,xml,linenums]
----
<plugin>

  <configuration>
    <standaloneDeployment>
      <muleHome>${mule.home.test}</muleHome>
      <muleVersion>${app.runtime}</muleVersion>
    </standaloneDeployment>
  </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your local Mule runtime engine information.
. From the command line in your project's folder, package the domain and run the deploy goal:
+
[source,console,linenums]
----
$ mvn clean package deploy -DmuleDeploy
----

== Encrypting credentials

Encrypted credentials are available in all platform deployments: CloudHub, Runtime Fabric, and Runtime Manager.
To use encrypted credentials when deploying, you need to set up your Maven master encrypted password and your `settings-security.xml` file.

. Create a master password for your Maven configuration.
+
----
$ mvn --encrypt-master-password <yourMasterPassword>
----
+
Maven returns your master password encrypted:
+
----
{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}
----
+
. Create a `settings-security.xml` file in your ~/.m2 repository and add your encrypted master password.
+
[source,xml,linenums]
----
<settingsSecurity>
  <master>{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}</master>
</settingsSecurity>
----
+
. Encrypt your Anypoint platform password:
+
----
$ mvn --encrypt-password <yourAnypointPlatformPassword>
----
+
Maven returns your Anypoint platform password encrypted:
+
----
{HTWFGH5BG9QmvJ1B=}
----
. Add your encrypted Anypoint Platform password to your `settings.xml` file in the <server> section:
+
[source,xml,linenums]
----
<settings>
 ...
  <servers>
   ...
    <server>
      <id>my.anypoint.credentials</id>
      <username>my.anypoint.username</username>
      <password>{HTWFGH5BG9QmvJ1B=}</password>
    </server>
   ...
  </servers>
 ...
</settings>
----
. In your configuration deployment, reference the credentials injecting the server id configured in your `settings.xml` file.
Below is an example of a CloudHub Deployment using encrypted credentials:

[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <cloudHubDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${app.runtime}</muleVersion>
            <server>my.anypoint.credentials</server>
            <applicationName>${cloudhub.application.name}</applicationName>
            <environment>${environment}</environment>
            <properties>
                <key>value</key>
            </properties>
        </cloudHubDeployment>
    </configuration>

</plugin>
----

NOTE: Make sure that username and password are not set in the deployment configuration, as they have precedence over the defined server id.

== Mule Maven Plugin Goals description

=== Package Goal

Generates the application JAR file.
Bind's by default to the http://maven.apache.org/ref/3.6.1/maven-core/lifecycles.html[lifecycle phase]: package

Optional parameters:

[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Type | Description
|`onlyMuleSources` | boolean | Generates the application JAR file containing only the source code. This property is just for sharing purposes.
|`attachMuleSources` | boolean | Attaches the source code inside the generated JAR file.
|`lightweightPackage` | boolean | Doesn't generate the repository with all the application dependencies inside the JAR file. This property is just for sharing purpose.
|===

=== Deploy Goal

Uploads and deploys the application JAR file to any of the application deployment targets.
Bind's by default to the http://maven.apache.org/ref/3.6.1/maven-core/lifecycles.html[lifecycle phase]: deploy

Optional parameters:

[%header%autowidth.spread,cols="a,a,a"]
|===
|Parameter | Type | Description
|`artifact` | String | Path to the application JAR file to be deployed. By default is set to the application `target` folder.
|`muleDeploy` | boolean | If it is set to `true`, the plugin performs a deploy using the deployment strategy defined in the plugin configuration. +
If it is set to `false`, it uploads the artifacts to the repository defined in the `distributionManagement` section on the application's `pom.xml` file.
|===

=== Undeploy Goal

Removes an application from any of the application deployment targets.
Uses the information from the plugin configuration to remove the application from the defined deployment targets.

== Skipping Plugin Execution

You can skip the plugin execution by setting the `skip` parameter to true inside your deployment configuration:

[source,xml,linenums]
----
<plugin>
  ...
  <configuration>
    <standaloneDeployment>
      <muleHome>${mule.home.test}</muleHome>
      <skip>true</skip>
    </standaloneDeployment>
  </configuration>
</plugin>
----

== Skipping Deployment Verification

You can skip the status verification of your deployed app by setting the `skipDeploymentVerification` parameter to true inside of any of the platform deployments (Cloudhub, Runtime Manager, and Runtime Fabric):

[source,xml,linenums]
----
<plugin>
  <groupId>org.mule.tools.maven</groupId>
  <artifactId>mule-maven-plugin</artifactId>
  <version>${mule.maven.plugin.version}</version>
  <extensions>true</extensions>
  <configuration>
    <runtimeFabricDeployment>
      ...
      <skipDeploymentVerification>true</skipDeploymentVerification>
      ...
    </runtimeFabricDeployment>
  </configuration>
</plugin>
----

If the `skipDeploymentVerification` parameter is not present, the default value is false. +
This feature is available in plugin version 3.2.5 and later.

== Excluding Files from the Application Package

When you package an application, you can exclude certain files or directories. Create a `_muleExclude` file at the project root directory and edit its content to set the exclusion rules.

Each line in a `_muleExclude` file specifies a rule that follows the https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob[glob pattern].

For example, consider the following `_muleExclude` file which contains two exclusion rules:
----
fileToBeExcluded.json
**/src/main/resources/local_directory
----

* The first line indicates that all files named `fileToBeExcluded.json`, inside any directory, are excluded from the application package. +
* The second line indicates that only the directory named `local_directory` located under `src/main/resources` is excluded from the package. +
If `**/src/main/resources/local_directory` is replaced with `local_directory` then all directories named `local_directory`, inside the project, are excluded from the application package.

== Anypoint Runtime Manager On-Premises TLS Errors

When trying to connect to an instance of Runtime Manager that's on an  xref:1.5@private-cloud::index.adoc[Anypoint Platform Private Cloud Edition] installation, the plugin validates certificates for that server. If you haven't installed the server certificates in your truststore, an SSL error occurs. To avoid this problem, you can run the plugin in an insecure mode, which skips the security validations. You can use the *armInsecure* tag or the *arm.insecure* system property.

[WARNING]
Enabling an insecure connection is a dangerous practice. Don't use this unless you know what you are doing and your On-Premises installation is isolated in a local network.

See the configuration example below:

[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
      <armDeployment>
          <target>${target}</target>
          <targetType>${target.type}</targetType>
          <username>${username}</username>
          <password>${password}</password>
          <environment>${environment}</environment>
          <armInsecure>true</armInsecure>
      </armDeployment>
    </configuration>
</plugin>
----

== See Also

* xref:mule-app-properties-to-configure.adoc[Configure Property Placeholders for Mule Apps]
* xref:about-classloading-isolation.adoc[Classloading Isolation]
* xref:how-to-export-resources.adoc[Export Resources]
* xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven]
* xref:runtime-fabric::deploy-resource-allocation.adoc[Resource Allocation on Anypoint Runtime Fabric]
* xref:runtime-manager::runtime-manager-api.adoc[Runtime Manager REST API]
