= Modularizing Your Configuration Files for Team Development
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, team, shared projects

Though it may seem convenient to keep all your Mule configuration in one place,
the reality is that a gigantic XML file quickly becomes unmanageable. This is why
 it is recommended to split monolithic configurations into several files and leverage
  Mule's capacity to load multiple configuration files at application start-up time.
 Moreover, splitting configurations into multiple fragments encourages re-use across teams.

Mule offers two options for loading several configuration files:

* side-by-side: provide a list of independent configuration files to load, +
* imported: have one configuration file import several others, which in-turn can
import other files.

In practice, it is common to use both approaches simultaneously.

Don't forget that all the configuration files end up loaded in the same context;
therefore you should be careful and use unique names for all your configuration
elements. Mule will refuse to load an application whose configuration files contain
 name conflicts.

How can you determine what constitutes good separation lines between configuration
 fragments? Here are a few rules of thumb:

* Business domains usually form a natural border that can be used to separated
configuration elements +
 * Keeping together elements that have similar reasons for change reduces the risk
  of impacting unrelated aspects of your application +
 * Technical aspects, like administrative components, security or external system
 configurations, define good lines of demarcation +
 * Extracting a side-by-side connector configuration facilitates functional testing.
 Note that it is not intended to take care of environment specific connector
 configuration, which is dealt with properties files +
 * And, last but not least, re-use across teams and projects

[NOTE]
By default, all present XML configuration files are considered configurations
when an application is packaged and loaded in the syde-by-side fashion.

== Imported configuration files

Mule has a special configuration component for importing configuration files into
each other called `import`. This component take a `file` parameter which should
contain the reference to the desired configuration file.

Here is a main configuration file, which takes care of importing three other
configuration elements:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.mulesoft.org/schema/mule/core"
      xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">

    <import file="global-configurations.xml"/>
    <import file="admin-config.xml"/>
    <import file="audit-flows.xml"/>

</mule>

----

[NOTE]
The import mechanism needs the XML files to be in the classpath.

== See also

* xref:intro-packaging.adoc[Packaging Applications]
