= Mule Secure Token Service OAuth 2.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: security, oauth, authentication, oauth provider, token, private key, secret key, access key

The Mule Runtime is capable of working with the OAuth 2.0 protocol. Depending of the role that it will take and the objective needed by the user, different configurations are needed.

== Client Authentication Required by a Server

Configure authentication in your client Mule app when sending requests to a service that requires authentication, such as the Github OAuth2 server, with the xref:connectors::oauth/oauth-documentation[OAuth Module].

== Mule Runtime as Authorization and or Resource Server

You can create a Mule application that grants and validates tokens needed to access a protected resource with the xref:connectors::oauth/oauth2-provider-documentation-reference[Mule OAuth2 Provider Connector].

When you want to protect your API or app from receiving requests from unauthorized access, use an API Manager policy, such as the OAuth 2.0 Access Token Enforcement Using External Provider policy. To expose a Web service protected by OAuth 2.0 security, see xref:api-manager::mule-oauth-provider-landing-page.adoc[API Manager documentation].
