= Mule High Availability
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*(for Mule 3.2.0 and later)*

== Mule High Availability Clustering

Mule HA Clustering allows a set if Mule instances to act as a unified processing system. If one instance fails, the remainder seamlessly continue to process any outstanding events. If that instance is later restarted, it automatically rejoins the cluster. The result is that the applications running in the cluster function continuously, with the starting or stopping of individual instances within the cluster being completely transparent.

A Mule HA Cluster provides the following advantages:

* Availability
So long as one instance in the cluster is running, the cluster's application continue to process messages.

* Reliability
If an instance fails while processing a message, that message will be reprocessed by another instance, provided that either:
** The message was read within a transaction, or
** For a non-transactional transport (like File or HTTP), the message is processed using a xref:reliability-patterns.adoc[reliability pattern].

* Scalability
Additional processing power can be achieved by adding instances to the cluster.

* Manageability
The cluster is managed as a single unit by the Mule Enterprise Management Console, making it possible to deploy, undeploy, or update applications across the entire cluster with a single command. In addition, the Console can perform other management operations like starting or stopping an endpoint or flow on every cluster node at once.