= Mule Upgrade Tool

*Latest version: 1.0.0*

include::release-notes::partial$mule-upgrade-tool/mule-upgrade-tool.adoc[tag=intro]

The Mule upgrade tool runs in any environment that is capable of running a standalone Mule instance. This tool can update only standalone Mule instances that are running any Mule 4 version.
//You can upgrade local Mule instances to the latest available version or to a particular Mule distribution that you have previously downloaded and unpacked.
You can also use the Mule upgrade tool to update Mule instances located in different folders.

As part of the upgrade process, the Mule upgrade tool also updates the Runtime Manager agent version if it is installed in your current Mule instance.

== Before You Begin

Before starting your upgrade, ensure that you have:

* A currently operational Mule 4 instance, in _stopped_ status to prepare for the upgrade
* The Mule upgrade tool inside your current Mule instance's `$MULE_HOME/tools` directory
+
If the Mule upgrade tool is not bundled with your current Mule distribution, download the tool from the https://help.mulesoft.com/s/[Support Portal^] and copy it into the `$MULE_HOME/tools` directory of your current Mule instance.
//* The new Mule runtime engine distribution you want to upgrade to
* The latest Mule runtime engine distribution, downloaded and unpacked in your system
+
You can download Mule distributions from the https://help.mulesoft.com/s/[Support Portal^].
* At least 2 GB of available disk space on the file system and access privileges to install the new Mule distribution
//Confirm if the tool is downloaded from the Support portal or help center, and update the link.

//This feature is not yet available
////
== Upgrade Mule to the Latest Version

To upgrade your Mule instance to the latest version:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade` command:
+
```
$MULE_HOME/tools/upgrade-tool upgrade
```
////

== Upgrade Mule

To upgrade your Mule instance to the latest version:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade -n` command, specifying the directory of the latest Mule distribution as an argument:
+
```
$MULE_HOME/tools/upgrade-tool upgrade -n ./<newMuleDistributionPath>

```

=== Solving Conflicts with Mule Configuration Files

During the upgrade process, the Mule upgrade tool checks if there are differences between the configuration files of the current and the new Mule distributions. If there are differences, the tool logs an error message for each configuration file with conflicts, creates the `upgrade-tool/mule-configs-files/conf` folder, and includes all the configuration files from the current distribution in this location adding the suffix `_TO_FIX` to the files with conflicts.

To fix the conflicts and continue with the upgrade process, place the configuration files with the final content to use during the upgrade inside the `upgrade-tool/mule-configs-files/conf` folder.

You can compare the differences in the original config files with conflicts of the current and new distribution by exploring the `upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_OLD_DISTRO` and `upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_NEW_DISTRO` folders.

== Roll Back an Upgrade

The Mule upgrade tool generates a backup of your existing Mule instance before starting the upgrade process. The backup is stored in the `$MULE_HOME/backup` folder in case you want to use the tool to restore your upgraded Mule instance to its previous state.

To perform a rollback:

. Navigate to the Mule upgrade tool directory.
. Run the `rollback` command:
```
$MULE_HOME/tools/upgrade-tool rollback
```

== Mule Upgrade Tool Commands and Options

The following table lists and describes the commands and options you can use when running the Mule upgrade tool:

[%header%autowidth.spread,cols=".^a,.^a"]
|===
|Command | Description
| `upgrade`
| Upgrades the local Mule instance to the latest available version. +
The following are the supported options for this command:

[%header%autowidth.spread,cols=".^a,.^a"]
!===
  ! Options ! Description
  ! `-n <newMuleDistributionPath>`
  ! Upgrades the local Mule instance to the distribution that is downloaded and unpacked in your file system. Parameter `<newMuleDistribution>` specifies the path to the new Mule distribution, for example:
  +
  `$ ./upgrade-tool upgrade -n /<newMuleDistributionPath>`
  ! `-o <localMuleInstancePath>`
  ! Upgrades the local Mule instance located in path `<localMuleInstancePath>`. This option enables you to upgrade a different Mule instance than the one located in the same `$MULE_HOME` path as the upgrade tool, for example:
  +
  `$ ./upgrade-tool upgrade -o /<localMuleInstancePath>`
  ! `-d` ! Simulates the upgrade process without performing any permanent changes to the current Mule instance.
  ! `-f` ! Performs the upgrade without requesting user confirmation for destructive operations like overwriting a backup or removing applied patches.
!===
| `rollback`
| Restores the Mule instance to its previous state. This command works only after performing a successful upgrade with the tool. +
The following are the supported options for this command:

[%header%autowidth.spread,cols=".^a,.^a"]
!===
  ! Options ! Description
  ! `-o <localMuleInstancePath>`
  ! Restores the local Mule instance located in path `<localMuleInstancePath>`. This option enables you to restore a different Mule instance than the one located in the same `$MULE_HOME` path as the upgrade tool, for example:
  +
  `$ ./upgrade-tool rollback -o /<localMuleInstancePath>`
  ! `-d` ! Simulates the rollback process without performing any permanent changes to the current Mule instance.
  ! `-f` ! Restores the Mule instance without requesting user confirmation.
!===
| `status`
| Provides information about the current Mule instance, including:

* The Mule runtime engine version
* A message confirming that the current Mule instance meets conditions to upgrade or roll back
* Any existing backup and its location
* The integrity of the backup, if it exists

|===

== See Also

* xref:release-notes::mule-runtime/upgrade-update-mule.adoc[Mule Upgrades and Patch Updates]
