= Configure Property Placeholders
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Instead of using static values for connections and other configurations in your Mule application, you can create a `.yaml` or a `.properties` file to contain your properties and then reference the properties from your application.
Configuring a properties file improves the organization and maintainability of your applications.

In a `.yaml` file, the properties take this form:
[source, yaml]
----
http:
  path: "/service"
  port: "10000"
  host: "my-api.cloudhub.io"
----

In a `.properties` file, the properties take this form:
----
http.path=/service
http.port=10000
http.host=my-api.cloudhub.io
----

You must store the file in the project directory for your Mule app:

* `/src/main/resources`

You can add the YAML file to your Mule app through the Global Element called Configuration Properties. The XML for it looks like this:

`<configuration-properties file="myConfiguration.yaml" doc:name="Configuration properties" doc:id="872422be-3571-4a52-a383-a2b0e16859d7" />`

Once the attributes are configured, you can reference them using a syntax like this: `${http.path}` and `${http.port}`.

For example, your HTTP Listener might pass the port like this:
`<http:listener-connection host="0.0.0.0" port="${http.port}" />`

//Note that Spring configurations cannot use these properties. They must use a `.properties` file.

== See Also

* xref:configuring-properties.adoc[Configure Properties]
