= Hello Mule Tutorial
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To demonstrate a simple HTTP request-response flow, this example responds
with the message "Hello Mule" to requests submitted from a Web browser.
The example demonstrates how a Mule application interacts with a user over an
HTTP request.

You set up and run this application as a project in Anypoint Studio. In a more
complex application, it is possible to do much more than this simple example
shows. For example, you can connect to external servers (such as SAP,
Salesforce, a database, or an FTP server), import and implement API
specifications directly within a Mule project, set up security, and process and
transform the data in programmatic ways. It is beyond the scope of this
example to explore such tasks.

== Prerequisites

xref:7.3@studio::to-download-and-install-studio.adoc[Studio 7] is required.

Once Studio is installed, you can set up and run the example. The example
assumes that you have basic familiarity with the Studio UI, including
the Mule Palette and the Studio canvas, where you drag and drop Mule components
and connector operations into a Mule flow. If you do not, review these topics
in the Studio overview, xref:7.3@docs-studio::index.adoc[Anypoint Studio].

== How the Example Works

The Hello Mule example consists of one simple Mule flow. This flow accepts an
HTTP request, sets a static payload on the message, and then returns a response
to you.

The request-response inbound HTTP endpoint receives requests the end user submits to the Web service. Because the message-exchange pattern is request-response, this HTTP endpoint is responsible for both receiving and returning messages. The descriptive notes included in the configuration of the endpoint can help you understand the actions the endpoint performs.

As its name suggests, the Set Payload component sets a value in the message payload. In this example, the value utilizes a Mule expression to set a static string on the payload. Like the HTTP endpoint, the configuration contains descriptive notes to help you understand what the component does.


== Set Up the Example

Follow these steps to create example in your own instance of Studio. Note that
you can create template applications in Studio and tweak the configurations
of the use case-based templates to create your own customized applications in
Mule.

. Create a project in Studio named "HelloMule" by selecting
*File* > *New* > *Mule Project*, providing the *Project Name*, and clicking
*Finish*.
+
Notice that the project name does not contain any blank spaces.
+
. In the project's *Mule Palette* tab, click *HTTP*, and drag the *Listener*
operation into the the *Source* section of the *hellomuleFlow*.
. In the Studio canvas, click the *Listener* to open its configuration UI in
its *Listener* tab.
+
. In the listener's *Connector configuration* field, click the *+*, use
*Test connection* to check that the default configuration works, and then click
*Add* to add the configuration to the project.
+
If the connection fails, try using a port number that is not in use, such as
`8082` or `8083`, retest the connection, and then add the configuration.
+
. In the listener's *Path* field, type the path `/hellomule`.
+
The example will use this path from a browser to trigger the listener.
+
. From the Studio canvas, click the Set Payload component to open its
configuration UI in its *Set Payload* tab.
. In the component's *Value* field, type the string `Hello Mule!`.
. From the Studio canvas, click the Logger component to open its configuration
UI in its *Logger* tab.
. In the logger's *Message* field, click the *fx* button, and add the following
expression for printing the request path to the Studio console.
+
`attributes.requestPath`
+
. Save the project by selecting *File* -> *Save* from Studio.
. Proceed to <<run_example>>.

== Run and Execute the Hello Mule Example

After setting up Hello Mule in Studio, you can run and test it.

. Run your *hellomule* app by right-clicking within the Studio canvas and
selecting *Run project hellomule*.
+
This action open the Studio console, where the logs print important information
about the two-stage build and deployment process.
+
If you receive a failure (`FAILED`) in the console that includes a message like
this one, try setting a new HTTP port in your HTTP listener configuration:
`Could not create server: A server in port(8081) already exists for host(0.0.0.0) or one overlapping it (0.0.0.0).`
Then save your project and rerun the your project. Note that you can also try
changing the host to `localhost` if the failure persists.
+
. Once your application is running, open a browser window, and provide load
the URL to the listener, for example, +`http://0.0.0.0:8081/hellomule`+.
+
You must use the same host and port that is configured in the HTTP listener.
+
. Check for the following message in the browser: `Hello Mule!`
. In the Studio, notice that the message in the console includes the
request path (`/hellomule`) in the first `INFO` line, which ends
`org.mule.runtime.core.internal.processor.LoggerMessageProcessor: /hellomule`.


== Configuration XML for the Hello Mule Example

The following XML provides the flow and HTTP listener configuration for the
example. To reserve space, the example omits the `doc:id` attributes, which
are not required.

.Configuration XML from Studio:

[source,XML,linenums]
----
<http:listener-config name="HTTP_Listener_config"
                      doc:name="HTTP Listener config" >
  <http:listener-connection host="0.0.0.0" port="8081" />
</http:listener-config>
<flow name="hello-muleFlow" >
  <http:listener doc:name="Listener"
                 config-ref="HTTP_Listener_config"
                 path="/hellomule"/>
  <set-payload value="Hello Mule!"
               doc:name="Set Payload"
               mimeType="text/plain"/>
  <logger level="INFO"
          doc:name="Logger"
          message="#[attributes.requestPath]"/>
</flow>
----

== See Also

* xref:mule-app-tutorial.adoc[Mule App Development Tutorial]
* xref:dataweave-quickstart.adoc[DataWeave Quickstart]
