= Mule Upgrade Tool

*Latest version: 1.0.0*

include::release-notes::partial$mule-upgrade-tool/mule-upgrade-tool.adoc[tag=intro]

== Compatibility

* The Mule upgrade tool runs in any environment that is capable of running a standalone Mule instance.
* You can update only standalone Mule instances with this tool.
* The upgrade tool is compatible with Mule 4 versions only.

== Before You Begin

Before getting started, ensure you have:

* A Mule 4 instance currently configured and working in your local environment.
* The Mule runtime engine version you want to upgrade to.
+
You can download Mule from the https://help.mulesoft.com/s/[Support Portal^].
* At least 2 GiB of available disk space on the file system and access privileges to install the new Mule distribution.
* The Mule instance to update in stopped status.
//Confirm if the tool is downloaded from the Support portal or help center, and update the link.
* The Mule upgrade tool inside your current Mule instance's `$MULE_HOME/tools` directory.
+
If the Mule upgrade tool is not bundled with your current Mule distribution, download the tool from the https://help.mulesoft.com/s/[Support Portal^] and copy it into the `$MULE_HOME/tools` directory of your current Mule instance.

== Upgrade a Mule Instance

You can upgrade local Mule instances to
//the latest available version or to
a particular Mule distribution that you have previously downloaded and unpacked. You can also use the Mule upgrade tool to update Mule instances located in different folders.

=== Considerations

When the tool upgrades your Mule instance, it also downloads the Runtime Manager agent that is bundled with the new Mule version. If the Runtime Manager agent was installed in your previous Mule instance, the tool also updates the agent to the new version that comes bundled with the new Mule version.

//This feature is not yet available
////
=== Upgrade Mule to the Latest Version

To upgrade your Mule instance to the latest version:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade` command:
+
```
$MULE_HOME/tools/upgrade-tool upgrade
```
////

=== Upgrade Mule to a Specific Distribution

To upgrade your Mule instance to a specific Mule distribution:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade -n` command, specifying the directory of the new Mule distribution as an argument:
+
```
$MULE_HOME/tools/upgrade-tool upgrade -n ./<mule-home-of-the-later-version>

```

== Backup and Rollback

The Mule upgrade tool generates a backup of the current Mule instance before starting the upgrade process. The backup is stored in the `$MULE_HOME/.backup` folder. This backup allows the upgrade tool to restore a Mule instance to its previous state before performing the upgrade.

=== Rollback an Upgrade

To perform a rollback to the previous state before an upgrade:

. Navigate to the Mule upgrade tool directory.
. Run the `rollback` command:
```
$MULE_HOME/tools/upgrade-tool rollback
```

== Mule Upgrade Tool Commands and Options

The following reference table shows a list of possible commands and options you can use when running the Mule upgrade tool:

[%header%autowidth.spread,cols=".^a,.^a"]
|===
|Command | Description
| `upgrade`
| Upgrades the local Mule instance to the latest available version. +
The following are the supported options for this command:

[%header%autowidth.spread,cols=".^a,.^a"]
!===
  ! Options ! Description
  ! `-n <newMuleDistributionPath>`
  ! Upgrades the local Mule instance to a specific distribution that is downloaded and unpacked in your file system. Parameter `<newMuleDistribution>` specifies the path to the new Mule distribution.
  +
  For example:
  +
  `$ ./upgrade-tool upgrade -n ./mule-home-of-the-later-version`
  ! `-o <localMuleInstancePath>`
  ! Upgrades the local Mule instance located in path `<localMuleInstancePath>`. This option enables you to upgrade a different Mule instance than the one located in the same `$MULE_HOME` path as the upgrade tool.
  +
  For example:
  +
  `$ ./upgrade-tool upgrade -o ./mule-home-of-the-instace-to-upgrade`
!===
| `rollback`
| Restores the Mule instance to its previous state. This command works only after performing a successful upgrade with the tool.
| `status`
| Provides information about the current Mule instance, including:

* The Mule runtime engine version
* A message confirming if the current Mule instance mets conditions to upgrade or rollback
* Any existing backup and its location
* Integrity of the backup, if it exists

|===

== See Also

* xref:release-notes::mule-runtime/upgrade-update-mule.adoc[Mule Upgrades and Patch Updates]
