= Mule MQ Integration
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Introduction

[Mule MQ] is an enterprise-class Java Message Service (JMS) implementation with official support from MuleSoft.

For more information, refer to the [Mule MQ Documentation].

== Usage

To use Mule MQ with the xref:jms-transport-reference.adoc[JMS Transport Reference] you need to:

. Copy the Mule MQ client JAR `nJMSClient.jar` from the Mule MQ `lib` folder to the `<MULE_HOME>/lib/user` folder.
. Configure the JMS connector.

Use the `<jms:mulemq-connector>` tag to configure the Mule MQ connector in your Mule configuration file. Since the `<jms:mulemq-connector>` tag extends `<jms:connector>`, all the attributes that one can set on the JMS connector can also be set on the Mule MQ connector. The following attributes are required:

[source,xml,linenums]
----
<jms:mulemq-connector name="jmsConnector"                            brokerURL="nsp://localhost:9000"                            specification="1.1"...                            />
----

[WARNING]
If you want to use XA transactions, use the `<jms:mulemq-xa-connector>` instead of the standard `<jms:mulemq-connector>`. The `mulemq-xa-connector` has the same extra attributes as the default connector.

== Connecting using JNDI

. First configure JNDI managed object using the Mule MQ [JNDI admin]

. Then connect using the managed connection factory:

[source,text,linenums]
----
    <jms:connector name="muleMQJmsConnector"        jndiInitialFactory="com.pcbsys.nirvana.nSpace.NirvanaContextFactory"        jndiProviderUrl="nsp://172.16.10.148:9000"        connectionFactoryJndiName="ConnectionFactory"         specification="1.1" ...                            />
----

== Configuration Reference

xslt: Read http://svn.codehaus.org/mule/branches/mule-3.1.x/transports/jms/src/main/resources/META-INF/mule-jms.xsd error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/transports/jms/src/main/resources/META-INF/mule-jms.xsd

xslt: Read http://svn.codehaus.org/mule/branches/mule-3.1.x/transports/jms/src/main/resources/META-INF/mule-jms.xsd error because of: java.io.IOException: Server returned HTTP response code: 401 for URL: http://svn.codehaus.org/mule/branches/mule-3.1.x/transports/jms/src/main/resources/META-INF/mule-jms.xsd