= Mule Object Stores
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

An *object store* is a facility for storing objects in Mule. Mule uses object stores whenever it needs data to persist for later retrieval. Internally, Mule uses object stores in various filters, routers, and other message processors that need store their state between messages. In most cases, Mule creates and manages object stores automatically, so no user configuration is necessary.


== Configuration

In most cases, Mule creates and manages object stores for you, so no configuration is necessary. However, you may explicitly configure an object store in the following cases:

. when configuring an idempotent message filter or until successful scope
. when configuring a custom component that must use an object store to persist information
. when storing or retrieving information from a Mule flow through the http://mulesoft.github.io/objectstore-connector/[Object Store connector].

Mule provides two types of object stores for non-clustered servers:

* **in-memory store** – Mule persists data by default.

* *persistent store* – Mule persists data when an object store is explicitly configured to be persistent. Mule creates a default persistent store in the file system.

[NOTE]
====
*A note about clustering*

When Mule servers are clustered, all object stores are replaced with clustered object stores. Clustered object stores use the shared memory grid created by the clustering code to persist information.
====

== Example

The following example demonstrates how to configure object stores in the following three situations:

. idempotent filter with an in-memory object store
. idempotent filter with a persistent object store
. until successful scope with an in-memory object store

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:http="http://www.mulesoft.org/schema/mule/http" xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans" version="EE-3.4.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">


# Global object store definition for a Listable Object Store, used in Flow 3 below.

    <spring:beans>
        <spring:bean id="myListableObjectStore" class="org.mule.util.store.SimpleMemoryObjectStore"/>
    </spring:beans>


# Idempotent Filter with In Memory Object Store

    <flow name="Flow1_idempotentWithInMemoryStore" doc:name="Flow1_idempotentWithInMemoryStore">
        <http:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8081" path="idempotentInMemory" />
        <idempotent-message-filter idExpression="#[message.payload]" throwOnUnaccepted="true" storePrefix="Idempotent_Message" doc:name="Idempotent Message">
            <in-memory-store name="myInMemoryObjectStore" entryTTL="120" expirationInterval="3600" maxEntries="60000" />
        </idempotent-message-filter>
        <set-payload value="YAY!" doc:name="Set Payload" />
        <catch-exception-strategy doc:name="Catch Exception Strategy">
            <set-payload value="NAY!" doc:name="Set Payload" />
        </catch-exception-strategy>
    </flow>


# Idempotent Filter with Persistent File Store

    <flow name="Flow2_idempotentWithTextFileStore" doc:name="Flow2_idempotentWithTextFileStore">
        <http:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8081" path="idempotentTextFile" doc:name="HTTP" />
        <idempotent-message-filter idExpression="#[message.payload]" throwOnUnaccepted="true" storePrefix="Idempotent_Message" doc:name="Idempotent Message">
            <simple-text-file-store
                name="mySimpleTextFileStore"
                directory="#[server.tmpDir + '/objectstore']"
                entryTTL="120"
                expirationInterval="3600"
                maxEntries="60000" />
        </idempotent-message-filter>
        <set-payload value="YAY!" doc:name="Set Payload" />
        <catch-exception-strategy doc:name="Catch Exception Strategy">
            <set-payload value="NAY!" doc:name="Set Payload" />
        </catch-exception-strategy>
    </flow>


# Until Successful Scope with In Memory Object Store

    <flow name="Flow3_UntilSuccessfulWithListableObjectStore" doc:name="UntilSuccessfulWithListableObjectStore">
        <http:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8081" path="hey" doc:name="HTTP" />
        <until-successful objectStore-ref="myListableObjectStore" maxRetries="15" secondsBetweenRetries="1" doc:name="Until Successful">
            <processor-chain doc:name="Processor Chain">
                <message-filter throwOnUnaccepted="true">
                    <expression-filter expression="return Math.random() &lt; 0.1" doc:name="Expression" />
                </message-filter>
                <logger message="This will eventually happen." doc:name="Logger" />
            </processor-chain>
        </until-successful>
        <set-payload value="Completed" doc:name="Set Payload" />
    </flow>

</mule>
----

== See Also

* Find out more about the http://mulesoft.github.io/mule-module-objectstore/mule/objectstore-config.html[Object Store module], available as a Mule extension.
* Learn about the https://docs.mulesoft.com/runtime-manager/managing-application-data-with-object-stores[CloudHub implementation of object stores].