= Run Mule Runtime Engine On-Premises
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, studio, enterprise, ee, premium features, paid features, purchase, license, licensed

When you deploy applications on-premises, you have complete control over the Mule instance which enables you to take advantage of certain characteristics of the xref:mule-deployment-model.adoc[On-Premises Deployment Model]

If you want to host Mule runtime engine in your own environment, first xref:hardware-and-software-requirements.adoc[verify that you meet all hardware and software requirements], and then xref:runtime-installation-task.adoc[download and install Mule].

You don't need to install Mule in the following scenarios:

* When you use Anypoint Studio (which contains Mule) for development and testing
* When you deploy applications to CloudHub or Anypoint Runtime Fabric.

After your installation of Mule is complete, xref:installing-an-enterprise-license.adoc[install an enterprise license] to enable all capabilities of Mule runtime engine.

Learn how to xref:starting-and-stopping-mule-esb.adoc[start and stop Mule runtime engine] to deploy Mule applications.

Follow the steps in xref:hardening-your-mule-installation.adoc[Hardening your Mule Installation] when you are ready to promote your Mule applications to production.

If you want to manage your on-premises Mule instance using Runtime Manager, xref:runtime-manager::servers-create.adoc[register it using the Runtime Manager agent].

Learn how to xref:choosing-the-right-clustering-topology.adoc[choose cluster runtime instances] to enhance availability, fault tolerance, and performance characteristics.
