= To Create Placeholders for Spring Configurations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Spring module in a Mule app can use any sort of Spring configurations. You can define the Spring property placeholders in a `.properties` file (for example, `spring-properties.properties`) that are fully interoperable with the Spring module.

The properties in the file takes this form:
----
springPropertyA=springPropertyAValue
springPropertyB=springPropertyBValue
----

// The prefix (`${`) and suffix (`}`) is fixed in Spring.

In Anypoint Studio, you must store the file in the project directory for your Mule app:

* `/src/main/resources`

You can add the `.properties` file to your Mule app through the Global Element called Configuration Properties. The XML for this element looks like this:

`<configuration-properties file="spring-properties.properties" doc:name="Spring Property Placeholders" doc:id="07ee5c11-bc54-4d55-91b8-ce02f743cb7a" />`

Note that you cannot use a YAML file to create Spring property placeholders, as you can for non-Spring modules.

== See Also

* xref:configuring-properties.adoc[About Property Placeholders]

* xref:mule-app-properties-to-configure.adoc[To Create Property Placeholders for Mule Apps]

////
???
----
<?xml version=“1.0” encoding=“UTF-8"?>
<beans xmlns=“http://www.springframework.org/schema/beans”
       xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance”
       xsi:schemaLocation=”
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd”>

  <bean class=“org.springframework.beans.factory.config.PropertyPlaceholderConfigurer”>
        <property name=“location”>
            <value>spring-properties.properties</value>
        </property>
  </bean>
</beans>
----
////