= Store Application Data Using Object Stores
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: esb, deploy, configuration, cluster, ha, high availability, downtime

An object store is a facility for storing objects in or across Mule applications. Mule runtime engine uses object stores to persist data for eventual retrieval. Internally, Mule uses object stores in various filters, routers, and other message processors that need to store states between messages.

If you deploy your application to CloudHub, you can use ObjectStore V2.
See xref:object-store::index.adoc[Object Store V2] for additional information.

== Use Cases

You can configure a custom object store to use in the following scenarios:

* When configuring an Idempotent Message validator, to store the unique IDs in the specified object store.
* When configuring a Redelivery policy in a listener (HTTP, File, JMS, VM, Socket), to store the redelivery count in the specified object store.
* When configuring a Cache Scope that uses a custom caching strategy, to store the cached data in the specified object store.
* When a custom component uses an object store to persist information.
* When storing or retrieving information from a Mule flow, by using the object store connector.

== Configuration

By default, each Mule application has an object store that is persistent and is always available to the app. You can also create custom object stores, which can be persistent or in-memory.

You can configure a custom object store for a specific component that supports its usage, or configure the object store as a global element, to be accessible for any component in your app.

=== Create a Global Object Store

To Create a global object store that can be referenced by other components in your application, include the following code as a top-level element in your application XML:

[source,xml,linenums]
----
<os:object-store name="myObjectStore"
   entryTtl="1"
   entryTtlUnit="HOURS"
   maxEntries="100"
   persistent="true"
   expirationInterval="30"
   expirationIntervalUnit="MINUTES" />
----

Configure each attribute with the desired value. See xref:object-store-connector::object-store-connector-reference.adoc#objectStore[Object Store Reference] for a definition of each XML attribute.

You can find additional configuration examples in xref:object-store-connector::object-store-to-define-a-new-os.adoc[Examples: Define Object Stores]


== Create an Object Store for a Specific Component

You can configure an Object Store that is accessed only by the container component by including the object store configuration inside the component element, for example:

[source,xml,linenums]
----
<idempotent-message-validator doc:name="Idempotent Message Validator" >
  <os:private-object-store
    maxEntries="20"
    entryTtl="20"
    entryTtlUnit="MILLISECONDS"
    expirationInterval="20"
    expirationIntervalUnit="MILLISECONDS"
    config-ref="ObjectStore_Config" />
</idempotent-message-validator>
----

== Manage Data using the Object Store Connector

The Object Store connector enables you to perform different operations to interact with the object stores in your Mule application. Example operations include Store, Retrieve and Remove.

See the xref:object-store-connector::index.adoc[Object Store Connector] documentation for details about available operations and configuration examples.
