= Mule Upgrade Tool

*Latest version: 1.0.0*

include::release-notes::partial$mule-upgrade-tool/mule-upgrade-tool.adoc[tag=intro]

The Mule upgrade tool runs in any environment that is capable of running a standalone Mule instance. This tool can update only standalone Mule instances that are running any Mule 4 version.
//You can upgrade local Mule instances to the latest available version or to a particular Mule distribution that you have previously downloaded and unpacked.
You can also use the Mule upgrade tool to update Mule instances located in different folders.

As part of the upgrade process, the Mule upgrade tool also updates the Runtime Manager agent version if it is installed in your current Mule instance.

The Mule upgrade tool does not support upgrading clustered Mule instances. For clustered environments, upgrade each of the nodes manually by following the instructions in xref:release-notes::mule-runtime/updating-mule-4-versions.adoc#mulerunvers[Upgrading an On-Premises Mule Instance Managed Through Runtime Manager]

== Before You Begin

Before starting your upgrade, ensure that you have:

* A currently operational Mule 4 instance, in _stopped_ status to prepare for the upgrade
* The Mule upgrade tool inside your current Mule instance's `$MULE_HOME/tools` directory
+
If the Mule upgrade tool is not bundled with your current Mule distribution, download the tool from the https://help.mulesoft.com/s/[Help Center^] and copy it into the `$MULE_HOME/tools` directory of your current Mule instance.
* The latest Mule runtime engine distribution, downloaded and unpacked in your system
+
The Mule upgrade tool does not support upgrading to patch distributions, identified by including the word `patch` in the file name. Ensure you download a full Mule distribution, identified by including the word `distribution` in the file name, for example: `mule-ee-distribution-standalone-4.4.0-20220221.zip`.
+
You can download Mule distributions from the https://help.mulesoft.com/s/[Help Center^].
* At least 2 GB of available disk space on the file system and access privileges to install the new Mule distribution
* (For Windows environments) The execution policy for Powershell scripts set to *Unrestricted*

//This feature is not yet available
////
== Upgrade Mule to the Latest Version

To upgrade your Mule instance to the latest version:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade` command:
+
```
$MULE_HOME/tools/upgrade-tool upgrade
```
////

== Upgrade Mule

To upgrade your Mule instance to the latest version:

. Navigate to the Mule upgrade tool directory.
. Run the `upgrade -n` command specifying as an argument the directory where the latest Mule distribution is downloaded and unpacked:
+
```
$MULE_HOME/tools/upgrade-tool upgrade -n ./<newMuleDistributionPath>

```

=== Solving Conflicts with Mule Configuration Files

Before performing the upgrade, the tool compares configuration files from the current Mule distribution with the ones from the new distribution to detect whether there are changes between them and therefore to prevent changes to be lost.

If changes are detected in the NEW distribution, the following actions will be performed by the tool:

* The upgrade command execution will fail showing an error message
* Config files with conflicts will be logged into the log output
* The config files inside the `${MULE_HOME}/conf` directory will be copied to `${MULE_HOME}/upgrade-tool/mule-config-files/conf` adding to the config files with conflicts the suffix `_TO_REVIEW`
* As a reference to identify what are the changes in the config files of the NEW distribution without the needing to consider the user changes in the `${MULE_HOME}/conf` config files, the original content of the configuration files of the OLD and NEW distributions will be available at the following paths:
  * `${MULE_HOME}/upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_OLD_DISTRO/`
  * `${MULE_HOME}/upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_NEW_DISTRO/`

At this point, human intervention is needed to resolve the conflicts, follow these suggested steps to resolve them:

* Assuming that the file `wrapper.conf` is in conflict, there will be a file named `${MULE_HOME}/upgrade-tool/mule-configs-files/conf/wrapper_TO_REVIEW.conf`
* To identify what were the changes added in the new distro compare with [diff tools](https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools) the `${MULE_HOME}/upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_OLD_DISTRO/wrapper.conf` against `${MULE_HOME}/upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_NEW_DISTRO/wrapper.conf`
* Once these changes were reviewed take one of the following approaches:
  * Adopt new changes: Use [diff tools](https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools) to compare and merge the content of the file `${MULE_HOME}/upgrade-tool/mule-configs-files/conf/wrapper_TO_REVIEW.conf` with the new added changes of the `${MULE_HOME}/upgrade-tool/mule-configs-files/ORIGINAL_CONFIG_FILES_NEW_DISTRO/wrapper.conf`. Once the merge is finished rename `${MULE_HOME}/upgrade-tool/mule-configs-files/conf/wrapper_TO_REVIEW.conf` removing the `_TO_REVIEW` suffix.
  * Discard new changes: Rename `${MULE_HOME}/upgrade-tool/mule-configs-files/conf/wrapper_TO_REVIEW.conf` removing the `_TO_REVIEW` suffix. Bear in mind that this approach could lead to the usage of deprecated settings in the updated Mule distribution
* Follow the same previous steps till all the config files with the `_TO_REVIEW` suffix are resolved.
* Finally, retry the upgrade command 
* When the upgrade finish successfully the `${MULE_HOME}/upgrade-tool/mule-config-files` folder will be deleted to have a clean environment for new Mule Distribution upgrades. 
                 
In case a Mule Distribution upgrade that have config files conflicts is needed to be done without user interaction, follow these suggested steps:

* In an environment were user interaction can be done and the same distributions versions are available: 
  * Review and resolve all the conflicts as explained in the previous section
* In the new environment where shouldn't be user interaction:
  * Before running the upgrade command copy the files from `${MULE_HOME_WITH_USER_INTERACTION}/upgrade-tool/mule-configs-files/conf/` to `${MULE_HOME_WITHOUT_USER_INTERACTION}/upgrade-tool/mule-configs-files/conf/`
  * Run the upgrade command
  * The upgrade will finish without user interaction

== Roll Back an Upgrade

The Mule upgrade tool generates a backup of your existing Mule instance before starting the upgrade process. The backup is stored in the `$MULE_HOME/backup` folder in case you want to use the tool to restore your upgraded Mule instance to its previous state.

To perform a rollback:

. Navigate to the Mule upgrade tool directory.
. Run the `rollback` command:
```
$MULE_HOME/tools/upgrade-tool rollback
```

== Mule Upgrade Tool Commands and Options

The following table lists and describes the commands and options you can use when running the Mule upgrade tool:

[%header%autowidth.spread,cols=".^a,.^a"]
|===
|Command | Description
| `upgrade`
| Upgrades the local Mule instance to the latest available version. +
The following are the supported options for this command:

[%header%autowidth.spread,cols=".^a,.^a"]
!===
  ! Options ! Description
  ! `-n <newMuleDistributionPath>`
  ! Upgrades the local Mule instance to the distribution that is downloaded and unpacked in your file system. Parameter `<newMuleDistribution>` specifies the path to the new Mule distribution, for example:
  +
  `$ ./upgrade-tool upgrade -n /<newMuleDistributionPath>`
  ! `-o <localMuleInstancePath>`
  ! Upgrades the local Mule instance located in path `<localMuleInstancePath>`. This option enables you to upgrade a different Mule instance than the one located in the same `$MULE_HOME` path as the upgrade tool, for example:
  +
  `$ ./upgrade-tool upgrade -o /<localMuleInstancePath>`
  ! `-d` ! Simulates the upgrade process without performing any permanent changes to the current Mule instance.
  ! `-f` ! Performs the upgrade without requesting user confirmation for destructive operations like overwriting a backup or removing applied patches.
  ! `-h` ! Displays the help message for this command.
!===
| `rollback`
| Restores the Mule instance to its previous state. This command works only after performing a successful upgrade with the tool. +
The following are the supported options for this command:

[%header%autowidth.spread,cols=".^a,.^a"]
!===
  ! Options ! Description
  ! `-o <localMuleInstancePath>`
  ! Restores the local Mule instance located in path `<localMuleInstancePath>`. This option enables you to restore a different Mule instance than the one located in the same `$MULE_HOME` path as the upgrade tool, for example:
  +
  `$ ./upgrade-tool rollback -o /<localMuleInstancePath>`
  ! `-d` ! Simulates the rollback process without performing any permanent changes to the current Mule instance.
  ! `-f` ! Restores the Mule instance without requesting user confirmation.
  ! `-h` ! Displays the help message for this command.
!===
| `status`
| Provides information about the current Mule instance, including:

* The Mule runtime engine version
* A message confirming that the current Mule instance meets conditions to upgrade or roll back
* Any existing backup and its location
* The integrity of the backup, if it exists

|===

== See Also

* xref:release-notes::mule-runtime/upgrade-update-mule.adoc[Mule Upgrades and Patch Updates]
