= About the Mule Packager Tool
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule uses a packager tool to package your Mule application into a deployable JAR file. +
You can operate this packager using the Mule Maven Plugin.

There are two types of packages that you can create:

* Heavy Package +
Contains the application and all its dependencies whether those be JAR files required by the application or by its plugins.

* Lightweight Package +
The application package declares its dependencies so that the other components obtain the JAR files.

Every Mule application has two descriptors. These descriptors tell the packager tool how to handle your Mule application's dependencies.

* A mule-artifact.json file. +
This file describes how your application is composed. +

* A pom.xml file. +
This file describes all the dependencies required by the package to work properly.


== See Also

* xref:package-task-mmp.adoc[To Package a Mule Application (Mule Maven Plugin)]
* xref:application-structure-reference.adoc[Application Structure Reference]