= @Payload Annotation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: annotations, custom java code

A parameter injection annotation that can be used on component entry points and transformer methods defined using the xref:3.6@transformer-annotation.adoc[@Transformer] annotation, this annotation controls how the current message payload is passed into a method by performing automatic transformation of the message payload to match the annotated parameter type. For example, if you are expecting an XML document, this can be injected into a component entry point and automatically converted into a `org.wc3.dom.Document`.

[source,java,linenums]
----
public class MyComponent {
    public Object process(@Payload Document doc) {
        // do stuff
    }
}
----

== Annotated Component Methods

Note that when using Annotations on component methods, all parameters need to be annotated for the method to be invoked. You will almost always be using the `@Payload` annotation to mark the message payload parameter.