= Properties Configuration Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, esb, properties, configure, external reference, variables, parameters, global properties, global variables, global parameters

This page provides detailed reference information for property elements in Mule.

== Global Property

A global property is a named string. It can be inserted in most attribute values using standard (ant-style) Spring placeholders.

=== Attributes of global-property

[%header%autowidth.spread]
|===
|Name |Description
|`name` |The name of the property. This is used inside Spring placeholders. +
*Type*: `name (no spaces)` +
*Required*: no +
*Default*: none
|`value` |The value of the property. This replaces each occurrence of a Spring placeholder. +
*Type*: `string` +
*Required*: yes +
*Default*: none
|===

No child elements for global-property.

== Property

Sets a Mule property. This is a name/value pair that can be set on components, services, etc., and which provide a generic way of configuring the system. Typically, you shouldn't need to use a generic property like this, since almost all functionality is exposed via dedicated elements. However, it can be useful in configuring obscure or overlooked options and in configuring transports from the generic endpoint elements.

=== Attributes of property

[%header%autowidth.spread]
|===
|Name |Description
|`key` |*Type*: `string` +
*Required*: no +
*Default*: none
|`value` |*Type*: `string` +
*Required*: no +
*Default*: none
|`value-ref` |*Type*: `string` +
*Required*: no +
*Default*: none
|===

No child elements for property.

== Properties

A map of Mule properties.

No attributes or child elements of properties.

== Jndi provider property

Direct setting of a JNDI property.

=== Attributes of jndi-provider-property

[%header%autowidth.spread]
|===
|Name |Description
|`key` |*Type*: `string` +
*Required*: no +
*Default*: none
|`value` |*Type*: `string` +
*Required*: no +
*Default*: none
|`value-ref` |*Type*: `string` +
*Required*: no +
*Default*: none
|===

No child elements for jndi-provider-property.

== JNDI Provider Properties

Direct setting of JNDI properties (allows access to the full Spring map entry).

No attributes or child elements of jndi-provider-properties.