= Raise Error Component
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, esb, studio, raise, error

This Core component generates a Mule Error, as if a failure had occurred, which allows you to customize its description and type.

Note that you only this component to raise core runtime errors, such as `MULE:SECURITY`, `MULE:CONNECTIVITY`, etc, or custom ones.
You cannot raise an error from another connector or module like `FILE:FILE_NOT_FOUND`, `JSON:INVALID_SCHEMA`.

For core runtime errors type, you must use the implicit namespace and identifier, you can only customize its description message. +
For custom error types, you are forced to declare one namespace. The namespace of an error type can help you identify the origin of an error. +
The custom error namespace must not be used elsewhere in your app, meaning that you cannot use `HTTP` as a namespace if you are using HTTP operations for example. Once you declare a custom namespace by using it in a `raise-error`, you can use it in other
`raise-error` components and custom types.

The following example flow produces an `ACCOUNT:INSUFFICIENT_FUNDS` error when a
transfer amount surpasses the available balance, preventing the transfer from
taking place. Additionally, it generates a dynamic description by providing an
expression with failure details.

.Example: XML Configuration of the Flow
[source,xml,linenums]
----
<flow name="raise-error-example-flow">
  <http:request url="https://unsecurebank.com/balance" target="balance"/>
  <choice>
      <when expression="#[payload.amount > vars.balance]">
          <raise-error type="ACCOUNT:INSUFFICIENT_FUNDS" description="#['Cannot transfer $(payload.amount) since only $(vars.balance) are available.']"/>
      </when>
  </choice>
  <http:request url="https://unsecurebank.com/transfer"/>
</flow>
----

This example raises an error with a static description and features a custom type using
the `ORDERS` namespace:

[source,xml,linenums]
----
 <raise-error description="Email is invalid. Cannot complete transaction." type="ORDER:INVALID_DATA"/>
----

== Raise Error Configuration

[%header,cols="1,1,2,2"]
|===
| Field | Value | Description | Example

| Description | String or DataWeave expression | Specifies the error description. |
`description="Invalid email. Cannot complete transaction."`

| Type | String | Specifies the type of the error. |
`type="ORDER:INVALID_DATA"`

|===

== See also
xref:mule-error-concept.adoc[Mule Error]
