= Reconnection Strategies
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint, studio, reconnection strategies, reconnection strategy, retry policies, retry

When an operation in a Mule app fails to connect to an external server, the
default is to produce a connectivity error and stop the application. For example, if an operation in the FTP connector fails to connect to an FTP server, the default is to throw an `FTP:CONNECTIVITY` error. The error name prepends a namespace that is specific to the connector, such as `FTP:CONNECTIVITY`, `HTTP:CONNECTIVITY`, or `DB:CONNECTIVITY` (for the Database connector).

You can modify this behavior by setting a reconnection strategy on the operation:

* None: Default behavior, which returns a connectivity error and forces the deployment to fail if the attempt to connect is unsuccessful.
* Standard (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them before returning a connectivity error. For example, you might set a `count` of `5` reconnection attempts at a `frequency` of every `4000` milliseconds (ms). Defaults to `2` reconnection attempts at a frequency of `2000` ms.
+
.Example with that fails after `5` reconnection attempts are exhausted:
[source,xml,linenums]
----
<ftp:config name="FTP_Config" doc:name="FTP Config" >
  <ftp:connection host="ftp.someftphost.com" port="21" username="myusername" password="mypassword" >
    <reconnection failsDeployment="true" >
      <reconnect count="5"/>
    </reconnection>
  </ftp:connection>
</ftp:config>
<flow name="reconnectionsFlow" >
  <ftp:listener doc:name="On New or Updated File" config-ref="FTP_Config">
    <scheduling-strategy >
      <fixed-frequency />
    </scheduling-strategy>
  </ftp:listener>
</flow>
----
+
* Forever (`reconnect-forever`): Attempts to reconnect at a given interval, for example, every `4000` ms for as long as the app runs. Defaults to every `2000` ms.
+

.Example that does not set a limit on the number of reconnection attempts:
[source,xml,linenums]
----
<ftp:connection host="ftp.someftphost.com" port="21" username="myusername" password="mypassword" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</ftp:connection>
----

== See Also

* xref:about-components.adoc[Core Components]
* xref:connectors::index.adoc[Connectors and Modules]
