= Redelivery Policy
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, flow, redelivery, policy

A redelivery policy is a filter that helps you conserve resources by limiting the number of times the Mule runtime engine (Mule) executes flow messages that cause errors. You can add a redelivery policy to some connectors that act as flow sources, such as the Salesforce, SAP, and VM connectors. To see whether a connector can use a redelivery policy, see the reference document for that connector.

When you add a redelivery policy to a flow's source, Mule evaluates the received data before it executes the flow's components. If the data caused failures a specified number of times, the redelivery policy prevents the flow from processing the received data and raises a REDELIVERY_EXHAUSTED error.

Some connectors have their own logic for handling an error thrown by a redelivery policy. In such cases, check the documentation for the connector to which the source belongs. For example, the HTTP connector might return 429: TOO MANY REQUESTS.

== Redelivery Policy Configuration Parameters

[%header,cols="20a,20a,20a,60a"]
|===
|Field |Type |Default Value |Description
|*Max Redelivery Count* |Number |5 |Maximum number of times that a message can be redelivered and processed unsuccessfully before raising a MULE:REDELIVERY_EXHAUSTED error.
|*Use Secure Hash* |Boolean |True |Indicates whether to use a secure hash algorithm to identify a redelivered message.
|*Message Digest Algorithm* |String |SHA-256 a|Secure hashing algorithm to use for the message. If the payload of the message is a Java object, Mule ignores the *Message Digest Algorithm* value and returns the value that the payload's `hashCode()` returned.
|*ID Expression* |Expression|- | Defines one or more expressions that determine when a message has been redelivered. This property can be set only if the value of *Use Secure Hash* is False.
|*Object Store* |String |Object Store created by Mule's default `ObjectStoreManager`. Nonpersistent, with an `entryTtl` of 300 seconds and an `expirationInterval` of 6 seconds. |Object Store in which
 the redelivery counter for each message is stored. You can configure the Object Store as a reference or an inner element. For information, see the xref:connectors::object-store/object-store-connector.adoc[Object Store connector documentation].
|===

== How the Redelivery Policy Works

Each time the source receives a new message, Mule generates a key from the message by using the configured *Message Digest Algorithm* or by evaluating the ID expression.

* If the processing flow causes an exception, the associated counter is incremented. When the counter reaches a value greater than the configured *maxRedeliveryCount* value, Mule throws a MULE:REDELIVERY_EXHAUSTED error.
* If the processing flow does not cause an exception, its counter is reset.

== Errors

* MULE:REDELIVERY_EXHAUSTED
+
Thrown when the number of executions that raise an error is greater than the configured *maxRedeliveryCount* value.


== Example

In this example, Mule logs an error with a `Redelivery exhausted in http listener` message when the *maxRedeliveryCount* of 2 is exceeded:

[source,xml]
----
<flow name="logOnRedeliveryExhausted">
    <http:listener path="test" config-ref="listenerConfig">
        <redelivery-policy maxRedeliveryCount="2" useSecureHash="true"/>
    </http:listener>
    <flow-ref name="processData"/>
    <error-handler>
        <on-error-continue type="MULE:REDELIVERY_EXHAUSTED">
            <logger message="Redelivery exhausted in http listener" level="ERROR"/>
        </on-error-continue>
    </error-handler>
</flow>
----

== See Also

* xref:flow-component.adoc[Flow and Subflow Components]
* xref:index.adoc#event-sources[Event Sources]
