= Remove Variable Transformer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, studio, mule, variable transformer, variables, set variable, edit variable, remove variable

The Remove Variable component takes a Mule variable name and removes the variable from a Mule event.

[%header,cols="1,1,3a"]
|===
|Field | Description

| Display Name
| `doc:name`
| Customize to display a unique name for this component in Anypoint Studio. Defaults to `Remove Variable`.

| Name
| `variableName`
| Name of the variable to remove.
|===

== Example

The basic example shows how to remove a Mule variable from the flow.

[source,xml]
----
<flow name="remove-variable-ex" >
  <scheduler doc:name="Scheduler" >
    <scheduling-strategy >
      <fixed-frequency frequency="10" timeUnit="SECONDS"/>
    </scheduling-strategy>
  </scheduler>
  <set-variable value='"value of my Mule variable"' doc:name="Set Variable"
                variableName="myMuleVar"/>
  <logger level="INFO" doc:name="Logger"
          message="#[vars.myMuleVar]"
          category="PRINT VALUE OF VARIABLE"/>
  <remove-variable doc:name="Remove Variable"
                   variableName="myMuleVar"/>
  <logger level="INFO" doc:name="Logger"
           category="ATTEMPT TO PRINT VALUE OF REMOVED VARIABLE"
           message="#[vars.myMuleVar]"/>
</flow>
----

The flow uses the following processors:

* The Scheduler component triggers the flow.
* Set Variable creates a Mule variable (`myMuleVar`).
* The first Logger in the flow prints the value of the variable (`"value of my Mule variable"`).
* Remove Variable provides a string with the name of the variable (`variableName="myMuleVar"`) to remove the variable from the Mule event.
* The second Logger prints `null` because the Mule variable no longer exists.

 The following example shows the logs for an execution of this flow:

 [source,logs]
 ----
 INFO  2022-12-11 11:25:34,151 ...event: 95596e60-7989-11ed-9f3f-147ddaaf4f97]
 PRINT VALUE OF VARIABLE: "value of my Mule variable"

 INFO  2022-12-11 11:25:34,151 ...event: 95596e60-7989-11ed-9f3f-147ddaaf4f97]
 ATTEMPT TO PRINT VALUE OF REMOVED VARIABLE: null
 ----

== See Also

* xref:about-mule-variables.adoc[Variables in Mule Events]
* xref:target-variables.adoc[Enrich Data with Target Variables]
