= Download and Install Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before downloading and installing Mule, verify that you have Java SE JDK 1.8 installed, for example:

[source,console,linenums]
----
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
----

== Downloading Mule

. Download the Mule 4 binary file from the following link and unzip it:
+
https://www.mulesoft.com/lp/dl/mule-esb-enterprise[https://www.mulesoft.com/lp/dl/mule-esb-enterprise]
+
. Set an environment variable called `MULE_HOME` for the `mule` directory inside your extracted folder.
+
Example for version 4.1.5 in the `Downloads` directory:
+
* On Windows environments:
+
[source,console]
----
$ env:MULE_HOME=C:\Downloads\mule-enterprise-standalone-4.1.5\
----
+
* On Linux/Unix environments:
+
[source,console]
----
$ export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.1.5/
----

== Running Mule

You can test if Mule runs in your system without errors by running the following commands:

* On Windows environments:
+
[source,powershell]
----
%MULE_HOME%\bin\mule.bat
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule
----

These commands run Mule in foreground mode, and the startup script displays information on the terminal’s standard output. You can’t issue further commands on the terminal as long as Mule is running.

To stop Mule, press `CTRL-C` in the terminal in which the script is running.

== See Also

* xref:7.1@studio::to-download-and-install-studio.adoc[Install Anypoint Studio 7.0]
* xref:mule-runtime-updates.adoc[What's New in Mule 4]
