= Download, Install, Configure, Upgrade Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before downloading and installing Mule, verify that you have a supported JDK installed.
This example uses AdoptOpenJDK 8, which is recommended for Mule 4.4.

[source,console,linenums]
----
$ java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
----

== Download Mule

. Download the Mule 4 binary file from the following link and unzip it:
+
https://www.mulesoft.com/lp/dl/mule-esb-enterprise[https://www.mulesoft.com/lp/dl/mule-esb-enterprise]
+
. Set an environment variable called `MULE_HOME` for the `mule` directory inside your extracted folder.
+
Example for version 4.4.0 in the `Downloads` directory:
+
* On Windows environments:
+
[source,console]
----
$ env:MULE_HOME="C:\Downloads\mule-enterprise-standalone-4.4.0"
----
+
* On Linux/Unix environments:
+
[source,console]
----
$ export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.4.0
----

The procedure for making the `MULE_HOME` setting permanent depends on your operating system.

=== Test Your Mule Instance

After downloading Mule, you can test if it runs in your system without errors by executing the following commands:

* On Windows environments:
+
[source,powershell]
----
%MULE_HOME%\bin\mule.bat
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule
----

These commands run Mule in foreground mode, and the startup script displays information on the terminal’s standard output. You can’t issue further commands on the terminal as long as Mule is running.

To stop Mule, press `CTRL-C` in the terminal in which the script is running.

== Install Mule

You can install Mule as a Windows Service or a Linux/Unix Daemon by executing the corresponding command:

* On Windows environments:
+
[source,powershell]
----
$ $MULE_HOME\bin\mule.bat install
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule install
----

== Configure Properties in the wrapper.conf File

After the installation of Mule as a Windows service, you can override the properties defined in the `wrapper.conf` file by declaring new properties in the `wrapper.additional.conf` file.

The behavior changes depending on the Mule edition you are using:

* Mule Community Edition
+
. After adding a new property, reinstall or restart the Windows Service.
. Add the property and ensure that its index is greater than the greatest index in the `wrapper-additional.conf` file. Otherwise, your property can be overridden.
+
For example, if the `wrapper-additional.conf` has the property:
+
`wrapper.java.additional.n=-Dproperty=value`
+
When `n` is the greatest index, you should add your property in the `wrapper.conf` file incrementing the index:
+
`wrapper.java.additional.n+1=-DyourProperty=valueOfYourProperty`

* Mule Enterprise Edition
+
. By default, you can add  20 extra properties after installing Mule as a Service.
. Configure the number of extra properties you need, using the following command line argument
when you install the service:
+
`-additionalJavaProperties=numberOfExtraProperties`

== Configure CPU Affinity

Many operating systems provide a mechanism to bind a process to one or more central processing units (CPUs), so that the process executes only on the assigned CPUs. You can configure this feature in your environment to run using CPU affinity.

=== Considerations When Using CPU Affinity

* CPUs have groups of cores that share a cache, where thread communication and migration has better performance. Check with your infrastructure team which cores share this cache before setting up this feature to avoid a negative impact to performance.
* Check with your infrastructure team if there is any resource allocation policy that can interfere with your CPU affinity configuration.
* Ensure that the number of cores you configure through CPU affinity is in compliance with the number of cores entitlted by your MuleSoft subscription plan.

== Remove the Mule Service or Daemon

Run the `remove` command to remove the service or daemon from your system.

The following example removes the Mule daemon from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule remove
MULE_HOME is set to /Applications/mule-enterprise-standalone-4.3.0
MULE_BASE is set to /Applications/mule-enterprise-standalone-4.3.0
Detected Mac OSX:
Mule Enterprise Edition is not running.
Removing Mule Enterprise Edition daemon...
----

== Install Anypoint Monitoring

You can xref:monitoring::am-installing.adoc[install Anypoint Monitoring] for cloud-managed supported versions of on-premises runtimes so you can monitor applications running on that server.

== Update, Upgrade, or Migrate Mule Versions

include::4.3@mule-runtime::partial$upgrade-update-migrate-mule.adoc[]

== See Also

* xref:starting-and-stopping-mule-esb.adoc[Starting and Stopping Mule]
* xref:mule-runtime::deploying.adoc[Deploy Mule Applications]
* xref:studio::to-download-and-install-studio.adoc[Install Anypoint Studio 7.0]
* xref:mule-runtime-updates.adoc[What's New in Mule 4]
