= Download and Install Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before downloading and installing Mule, verify that you have a supported JDK installed.
This example uses AdoptOpenJDK 8, which is recommended for Mule 4.2.

[source,console,linenums]
----
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
----

== Downloading Mule

. Download the Mule 4 binary file from the following link and unzip it:
+
https://www.mulesoft.com/lp/dl/mule-esb-enterprise[https://www.mulesoft.com/lp/dl/mule-esb-enterprise]
+
. Set an environment variable called `MULE_HOME` for the `mule` directory inside your extracted folder.
+
Example for version 4.2.0 in the `Downloads` directory:
+
* On Windows environments:
+
[source,console]
----
$ env:MULE_HOME=C:\Downloads\mule-enterprise-standalone-4.2.0
----
+
* On Linux/Unix environments:
+
[source,console]
----
$ export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.2.0
----

== Running Mule

You can test if Mule runs in your system without errors by running the following commands:

* On Windows environments:
+
[source,powershell]
----
%MULE_HOME%\bin\mule.bat
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule
----

These commands run Mule in foreground mode, and the startup script displays information on the terminal’s standard output. You can’t issue further commands on the terminal as long as Mule is running.

To stop Mule, press `CTRL-C` in the terminal in which the script is running.



== See Also

* xref:starting-and-stopping-mule-esb.adoc[Starting and Stopping Mule]
* xref:studio::to-download-and-install-studio.adoc[Install Anypoint Studio 7.0]
* xref:mule-runtime-updates.adoc[What's New in Mule 4]
