= Download and Install Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before downloading and installing Mule, verify that you have Java SE JDK 1.8 installed, for example:

[source,console,linenums]
----
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
----

== Downloading Mule

. Download the Mule 4 binary file from the following link and unzip it:
+
https://www.mulesoft.com/lp/dl/mule-esb-enterprise[https://www.mulesoft.com/lp/dl/mule-esb-enterprise]
+
. Set an environment variable called `MULE_HOME` for the `mule` directory inside your extracted folder.
+
Example for version 4.2.0 in the `Downloads` directory:
+
* On Windows environments:
+
[source,console]
----
$ env:MULE_HOME=C:\Downloads\mule-enterprise-standalone-4.2.0\
----
+
* On Linux/Unix environments:
+
[source,console]
----
$ export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.2.0/
----

== Running Mule

You can test if Mule runs in your system without errors by running the following commands:

* On Windows environments:
+
[source,powershell]
----
$ $MULE_HOME\bin\mule.bat
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule
----

These commands run Mule in foreground mode, and the startup script displays information on the terminal’s standard output. You can’t issue further commands on the terminal as long as Mule is running.

To stop Mule, press `CTRL-C` in the terminal in which the script is running.

== Starting Mule as a Windows Service

To run Mule as a Windows service, you need to install it first by running:

[source,powershell]
----
$ $MULE_HOME\bin\mule.bat install
----

Once installed, you can run Mule as a service:

[source,powershell]
----
$ $MULE_HOME\bin\mule.bat start
----

[NOTE]
====
When Windows restarts, the Mule service stops the same way as using the `mule stop` command.
The only situation where this could be different is if Windows kills the process due to a timeout.
====

=== Adding Properties to wrapper.conf File After Installation

After the installation of Mule as a Windows service, you can override the properties defined in the `wrapper.conf` file by declaring new properties in the `wrapper.additional.conf` file.

The behavior changes depending on the Mule edition you are using:

* Mule Community Edition
+
. After adding a new property, reinstall or restart the Windows Service.
. Add the property and ensure that its index is greater than the greatest index in the `wrapper-additional.conf` file. Otherwise, your property can be overridden.
+
For example, if the `wrapper-additional.conf` has the property:
+
`wrapper.java.additional.n=-Dproperty=value`
+
When `n` is the greatest index, you should add your property in the `wrapper.conf` file incrementing the index:
+
`wrapper.java.additional.n+1=-DyourProperty=valueOfYourProperty`

* Mule Enterprise Edition
+
. By default, you can add  20 extra properties after installing Mule as a Service.
. Configure the number of extra properties you need, using the following command line argument
when you install the service:
+
`-additionalJavaProperties=numberOfExtraProperties`

== Starting Mule as a Linux/Unix Daemon

To run Mule as a Linux-Unix Daemon, you need to install it first by running:

[source,console]
----
$ $MULE_HOME/bin/mule install
----

Once installed, you can run Mule as a daemon:

[source,console]
----
$ $MULE_HOME/bin/mule start
----

[NOTE]
====
You can also start Mule without executing the installation step. This will start the Mule in the background for the current user session.
====

This example starts Mule from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule start
MULE_HOME is set to ~/Downloads/mule-enterprise-standalone-4.2.0
MULE_BASE is set to ~/Downloads/mule-enterprise-standalone-4.2.0
Starting Mule Enterprise Edition...
Waiting for Mule Enterprise Edition.................
running: PID:87318
----

== Deploying Mule Applications

. Start Mule.
. After Mule starts, you can deploy your Mule applications by moving your packaged JAR files to the `apps` directory in `$MULE_HOME`.

== Stopping Mule

Use the `stop` command to stop Mule.

This example stops Mule from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule stop
MULE_HOME is set to /Applications/mule-enterprise-standalone-4.2.0
MULE_BASE is set to /Applications/mule-enterprise-standalone-4.2.0
Stopping Mule Enterprise Edition...
Stopped Mule Enterprise Edition.
----

== Removing the Mule Service or Daemon

Use the `remove` command to remove the service or daemon from your system.

This example removes the Mule daemon from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule remove
MULE_HOME is set to /Applications/mule-enterprise-standalone-4.2.0
MULE_BASE is set to /Applications/mule-enterprise-standalone-4.2.0
Detected Mac OSX:
Mule Enterprise Edition is not running.
Removing Mule Enterprise Edition daemon...
----

== Enable Anypoint Monitoring

Optionally, you can xref:monitoring::am-installing.adoc[install Anypoint Monitoring] for cloud-managed supported versions of on-premises runtimes so you can monitor applications running on that server.

== See Also

* xref:studio::to-download-and-install-studio.adoc[Install Anypoint Studio 7.0]
* xref:mule-runtime-updates.adoc[What's New in Mule 4]
