= Schema Documentation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, schema

Mule 3.0 was released with new Javadoc-style schema documentation, making it easier to familiarize yourself with all the elements and attributes permissible in XML configuration files.

If you are familiar with versions of Mule older than v3.0, you may want to consult this list of xref:notes-on-mule-3.0-schema-changes.adoc[schema changes].

== JavaDoc-Style HTML Output

Framed HTML documentation provides most detailed and easy accessible information about all Mule schema components and interconnections between them.

* http://www.mulesoft.org/docs/site/current3/schemadocs[Schemadocs]
* https://www.mulesoft.org/docs/site/3.8.0/apidocs/[3.8.0 API Docs]
* http://www.mulesoft.org/docs/site/3.8.0/testapidocs/[3.8.0 Test API Docs]

== UML Diagrams

Diagrams of many of the logical structures you will use to write Mule configurations.

== Elements, Attributes, Annotations, and Substitutions

Navigate among exploded views of Mule schemas, viewing all objects - inherited or native - in a single location.