= Schema Documentation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule 3.0 was released with new Javadoc-style schema documentation, making it easier to familiarize yourself with all the elements and attributes permissible in xml configuration files.

If you are familiar with versions of Mule older than v 3.0, you may want to consult this list of link:notes-on-mule-3.0-schema-changes[schema changes].

== JavaDoc-Style HTML Output

Framed HTML documentation provides most detailed and easy accessible information about all Mule schema components and interconnections between them.

* http://www.mulesoft.org/docs/site/current3/schemadocs[Schemadocs]
* https://www.mulesoft.org/docs/site/3.4.0/apidocs/[API Docs]
* http://www.mulesoft.org/docs/site/3.4.0/testapidocs/[Test API Docs]

== UML Diagrams

Diagrams of many of the logical structures you will use to write Mule configurations.

== Elements, Attributes, Annotations, and Substitutions

Navigate among exploded views of Mule schemas, viewing all objects - inherited or native - in a single location.