= Scheduler Endpoint (Trigger)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Scheduler component is an event source that initiates execution of a flow at configured times. You can configure a fixed and repeating frequency (such as every second) or a cron expression. A cron expression can specify one or more specific dates and times, but more commonly, the expression specifies recurring dates, times, or intervals. For example, the cron expression `* * * ? * *` configures a Scheduler to start its flow every second.

Consider the following when you implement a Scheduler in your Mule application:

* Schedulers use the same timezone as the machine on which Mule is running. However, if an application is running in CloudHub, the Scheduler conforms to the UTC timezone, regardless of the geographic region in which the application is running.
* If xref:execution-engine.adoc#backpressure[back pressure] occurs because Mule lacks sufficient resources to process an event in the flow, the application skips the scheduled trigger for the event and throws a MULE:FLOW_BACK_PRESSURE error. This error indicates that the flow cannot accept new events at that time. Anypoint Studio logs this error only once, the first time it occurs.
+
Using `maxConcurrency` on a Flow component can lead to back pressure if the component contains a Scheduler that runs too frequently or if the flow takes too long to execute. To avoid back pressure and improve performance of the application, you can try the default `maxConcurrency` setting or increase the value so that more instances of the flow can run concurrently. To avoid receiving the error message, use the Scheduler's `disallowConcurrentExecution` property (see xref:scheduler-xml-reference.adoc#scheduler-properties[<scheduler> Properties]). 
+
To capture log messages each time the Scheduler attempts to trigger an event, you can enable the xref:logging-in-mule#change-the-log-level[DEBUG] logging level in the Mule application.
//Enhancement request for this: MULE-14930
* In a multi-worker CloudHub deployment or in a customer-hosted cluster of Mule runtime engines, the Scheduler runs and executes the flow on the primary node only. That is, it runs on one specific Mule runtime engine and no others.

== Example Projects

There are several example projects in Anypoint Exchange that you can open in Anypoint Studio to learn more about how to use the Scheduler component:

* _Data Sync Using Watermarking and Batch_
* _Import Contacts into Microsoft Dynamics CRM_
* _Import Leads into Salesforce_
* _Importing a CSV File into mongoDB_
* _Importing an Email Attachment Using the IMAP Connector_
* _Salesforce to MySQL Database Using Batch Processing_
* _Sending a CSV File Through Email Using SMTP_

To download and open an example project while you are in Anypoint Studio, click the Exchange icon in the upper-left corner. Then, in the window that opens, log into Anypoint Exchange and search on the name of the project.

== Fixed Frequency

You can use the following parameters to set a Scheduler to trigger and execute its flow at a regular intervals.

[%header,cols="1,2,1"]
|===
|Attribute |Description |Default
|*Frequency*
|The frequency at which the Scheduler triggers execution of its flow. You select the unit of time in the *Time unit* field. Setting the value to `0` or a negative value causes the default value to be used.
|
1000

| *Start Delay*
| The amount of time to wait before triggering execution of its flow for the first time after the application is started. This value is expressed in the same unit of time as the frequency.
| 0

| *Time Unit*
| The time unit for the values of *Frequency* and *Start Delay*. The possible values are:

MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
| MILLISECONDS
|===

== Cron Expressions

Cron is a widely used standard for describing date-time information and repeating intervals.

The Scheduler keeps track of every second and creates a Mule event when the
Quartz Cron expression matches your time-date setting. You can configure the Scheduler to trigger
just once or at regular intervals.

A date-time expression consists of six required settings and can include the
optional year setting. You specify the settings in the following order:

. Seconds (0-59)
. Minutes (0-59)
. Hours (0-23)
. Day of month (1-31)
. Month (1-12 or JAN-DEC)
. Day of the week (1-7 or SUN-SAT)
. Year (empty or a 4-digit year between 1970-2099, for example, 2019)

The Scheduler supports Quartz Cron expressions. Here are a few examples:

[%header,cols="2*"]
|===
|Expression |Behavior
|`1/2 * * * * ?` |Run every 2 seconds of the day, every day.
|`0 15 10 ? * *` |Run at 10:15 a.m., every day. `0 15 10 * * ? *` and
`0 15 10 * * ?` produce the same effect.
|`0 15 10 * * ? 2019` |Run at 10:15 a.m., every day during the year 2019.
|`0 * 14 * * ?` |Run every minute starting at 2pm and ending at 2:59pm, every day.
|`0 0/5 14 * * ?` |Run every 5 minutes starting at 2pm and ending at 2:55pm, every day
|`1 1 1 1,7 * ?` |Run the first second of the first minute of the first hour, on the first and seventh day, every month.
|===

Note that the Scheduler component also supports Quartz Scheduler special characters:

* `*`: All values.
* `?`: No specific value.
* `-`: Range of values, for example, `1-3`.
* `,`: Additional values, for example, `1,7`.
* `/`: Incremental values, for example, `1/7`.
* `L`: Last day of the week or month, or last specific day of the month
  (such as `6L` for the last Saturday of the month).
* `W`: Weekday, which is valid in the month and day-of-the-week fields.
* `#`: Nth day of the month. For example, `#3` is the third day of the month.

//source info: +http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html+

This example logs the message "hello" every second and allows only one instance of the flow to execute at a time:

[source,XML,linenums]
----
<flow name="cronFlow" maxConcurrency="1" >
  <scheduler doc:name="Scheduler"  >
    <scheduling-strategy >
      <cron expression="* * * * * ?" timeZone="America/Los_Angeles"/>
    </scheduling-strategy>
  </scheduler>
  <logger level="INFO" doc:name="Logger" message='"hello"'/>
</flow>
----

Note that there are a number of free online tools that can help you build Cron
expressions.

=== Time Zones (timeZone)

For Cron configurations, Java `timeZone` values are supported. You should avoid
the Java abbreviations, such as `PST` and `AGT`, and instead use the full-name
Java equivalents, such as `America/Los_Angeles` and
`America/Argentina/Buenos_Aires`.

//source info: +https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html+

== Stop or Start a Scheduler in Debug Mode

In Anypoint Studio, when you run a Mule application using debug mode, an arrow icon appears at the bottom of the Scheduler component. The arrow indicates that you can start or stop the Scheduler from its right-click menu.

By default, the Scheduler runs when in debug mode. If you place a break point on a message processor in the flow, the Scheduler component will start the flow and continue emitting events as scheduled until you stop it. If you set a break point before stopping the Scheduler and the Scheduler emits one or more events, the application queues those events to run through the flow after you finish stepping through the break point.

== See Also

* xref:scheduler-xml-reference.adoc[Scheduler XML Reference]
