= Scheduler Endpoint (Trigger)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Scheduler component allows you to trigger a flow when a time-based condition is met. You can configure it to be triggered at a regular interval or give it a more flexible cron expression. For example, a Scheduler might trigger an event to start a flow every 5 seconds.

Schedulers follow the timezone used by the machine where the Mule runtime is running. If an application is running in CloudHub, the timezone that the Scheduler conforms to corresponds to the region in which the CloudHub worker is running.

//Enhancement request for this: MULE-14930
Note that in a Mule runtime cluster or multi-worker CloudHub deployment, the Scheduler runs (or triggers) only on the primary node (that is, only in one Mule runtime).

There are several example projects in Anypoint Exchange that you can open in Anypoint Studio to learn more about how to use the Scheduler component:

* _Data Sync Using Watermarking and Batch_
* _Import Contacts into Microsoft Dynamics CRM_
* _Import Leads into Salesforce_
* _Importing a CSV File into mongoDB_
* _Importing an Email Attachment Using the IMAP Connector_
* _Salesforce to MySQL Database Using Batch Processing_
* _Sending a CSV File Through Email Using SMTP_

To download and open an example project while you are in Anypoint Studio, click the Exchange icon in the upper-left corner. Then, in the window that opens, log into Anypoint Exchange and search on the name of the project.


== Fixed Frequency

You can use the following parameters to set a Scheduler to trigger a flow at a regular intervals.

[%header,cols="34,33,33"]
|===
|Attribute |Description |Default
|*Frequency*
|The frequency at which the Scheduler triggers the flow. You select the unit of time in the *Time unit* field. Setting the value to `0` or a negative value causes the default value to be used.
|
1000

| *Start Delay*
| The amount of time to wait before triggering the flow for the first time after the application is started. This value is expressed in the same unit of time as the frequency.
| 0

| *Time Unit*
| The time unit for the values of *Frequency* and *Start Delay*. The possible values are:

MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
| MILLISECONDS
|===

== Cron Expressions

Cron is a widely used standard for describing time and date information. It can be used to signal a specific event that occurs just once, or a recurring event that might be yearly, monthly, weekly, daily, hourly, etc.

The condition is evaluated every time the time changes (every second) and produces a trigger when true.

The expression consists of 6 or 7 items, where they represent the following, in order:

* Seconds
* Minutes
* Hours
* Month
* Day of month
* Day of the week
* Year (optional)

Here are a few sample Cron expressions:

[%header,cols="2*"]
|===
|Expression |Behavior
|0 15 10 * * * |Run at 10:15am every day
|0 15 10 * * ? 2005 |Run at 10:15am every day during the year 2005
|0 * 14 * * ? |Run every minute starting at 2pm and ending at 2:59pm, every day
|0 0/5 14 * * ? |Run every 5 minutes starting at 2pm and ending at 2:55pm, every day
|1 1 1 1,7 * ? |Run the first day of January and the first day of June, every year (in the first second of the first minute of the first hour) +
|===

Note that there are a number of free online tools that can help you build cron expressions by filling in a form, without needing to learn the syntax.

When debugging a flow with a Scheduler, the scheduling frequency is ignored. This prevents events from piling up while you are stepping through the flow. +
You can click the green arrow icon at the bottom of the Scheduler component in your canvas to trigger a poll.

== See Also

* xref:scheduler-xml-reference.adoc[Scheduler XML Reference]
