= Set Transaction Id
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: transaction, id, component, mule

The Set Transaction Id component enables you to set an identifier for all tracked events so that meaningful information, such as an order number, is displayed for a transaction when analyzing tracked events at runtime, whether using Anypoint Runtime Manager or CloudHub.

== Set Transaction Id Configuration

[%header,cols="1,4"]
|===
| Field | Description
| Transaction ID (`id`) a| Defines the value of the identifier. It can be an expression or a literal. By default, the component assigns a numeric value.
|===

== Example Transaction Id Configuration

The following example shows a flow that creates a transaction from a VM Listener component and then uses the Set Transaction Id component to define an identifier for the existing transaction.

[source, xml, linenums]
----
<flow name="main-flow">
  <!-- A VM listener that starts a transaction-->
  <vm:listener doc:name="Listener" config-ref="VM_Config" queueName="toTransactionalVM" transactionalAction="ALWAYS_BEGIN"/>
  <!-- The Set Trasaction ID component defines an id for the existing transaction -->
  <tracking:transaction doc:name="Set Transaction Id" id="#[payload.orderId]" />
  <!--
    Additional processing logic of the flow
  -->
</flow>
----

== See Also

xref:transaction-management.adoc[Transaction Management]
