= Setting Up Your Environment (Not Required for Mule IDE Users)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Before you can use Mule, you must create environment variables for Java and optionally Maven, and update your path to include their bin directories. *NOTE*: If you are using the Mule IDE with Eclipse, these steps are not required.

[WARNING]
To run Mule as a Windows service, create system environment variables instead of user environment variables.

. Create an environment variable called `JAVA_HOME` and set it to the directory where the JDK is installed.
. For Maven, create an environment variable called `MAVEN_HOME` and set it to the directory where you unpacked Maven, and then create an environment variable called `MAVEN_OPTS` and set it to `-Xmx512m -XX:MaxPermSize=256`
. Update the `PATH` environment variable so that it includes the path to the JDK and Maven binaries. This step is not required if you will use the Mule IDE.

On Windows, use the System utility in the Control Panel to add the environment variables and edit your path. Alternatively, use the export or set commands at the command prompt as shown below:

*Linux/UNIX*

[source,text,linenums]
----
export JAVA_HOME=/opt/java/jdk
export MAVEN_HOME=/opt/apache/maven-2.0.9
export MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=256m'
export PATH=$PATH:$JAVA_HOME/bin:$MAVEN_HOME/bin
----

*Windows*

[source,text,linenums]
----
set JAVA_HOME=C:\Program Files\Java\jdk
set MAVEN_HOME=C:\Apache\maven-2.0.9
set MAVEN_OPTS=-Xmx512m -XX:MaxPermSize=256m
----