= Single Resource Transactions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, runtime, transaction, local, resource, single

Use a *Single Resource transaction* (also known as a simple transaction or local transaction) to send or receive messages using only one single resource: JMS broker, VM queues, or JDBC connections.

The example below illustrates a flow which includes a single resource transaction applied to source and publish operation 
of the JMS connectors.

[source,xml,linenums]
----
<flow name="asdFlow" doc:id="2a67b1ee-0394-44a8-b6d9-9ce4f94f1ae2" >
	<jms:listener config-ref="JMS_Config" destination="test.in" transactionalAction="ALWAYS_BEGIN"/>
	<!-- Other operations -->
	<jms:publish config-ref="JMS_Config" destination="test.out" transactionalAction="ALWAYS_JOIN"/>
</flow>
----

The configuration above defines a JMS message source that receives on a `test.in` queue and another JMS operation that sends on a `test.out` queue. The `transactionalAction` attribute dictates how Mule initiates a transaction. Within this flow, Mule starts a new transaction for every message it receives (message source), and **always joins** the transaction in progress for every message it sends (publish operation). Mule commits only those messages which successfully pass through the complete flow; if at any point in the flow a message throws an error which is propagate (i.e. is not handled by an `on-error-continue`), Mule rolls back the transaction. Refer to xref:on-error-scope-concept.adoc[On Error Scope]for details on how to handle errors. Both JMS source and publish operation must use the same connection configuration, since this mechanism is intended to manage one resource.

== See Also

* xref:transaction-management.adoc[Transaction Management].