= Split Aggregate Scope
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, studio, mule, split, aggregate, scope

The Split Aggregate scope splits a collection and parallel processes each part of the collection with the components within the scope (subject to any limitation in concurrency that has been configured). The output is a collection with the result of each route. After all messages are processed, the results are aggregated before continuing within the flow in the same order they were in prior to the split.

The Split Aggregate scope can be configured through the following fields:

[%header,cols="1,3"]
|===
|Child element |Description
|Collection (`collection`) | Specifies the expression that defines the collection of parts to be processed in parallel. By default, it uses the incoming payload.
|===

[%header,cols="1,3"]
|===
|Attribute |Description
|Collection Expression (`collection`) | An expression that returns a collection. By default, the payload is taken as the collection to split.
|Timeout (`timeout`) | Specifies the timeout for each parallel route. By default, there is no timeout.
|Max Concurrency (`maxConcurrency`) | Specifies the maximum level of parallelism for the router to use. By default, all routes run in parallel.
|Target Variable (`target`) | Specifies a variable to use for storing the processed payload. By default, the output is saved in the flow's payload.
|Target Value (`targetValue`) | Specifies an expression to evaluate against the operation's output value. The outcome of this expression is stored in the target variable. By default, this is the same as the operation's output value.
|===

This XML example adds to every element in the collection the string `"-result"`:

[source,xml,linenums]
----
<split-aggregate collection="#[['apple', 'banana', 'orange']]">
    <set-payload value="#[payload ++ '-result']"/>
</split-aggregate>

----

Every route starts with the same initial variable values. Modification to a variable within a specific route does not affect other routes. So if a variable is added or modified in one route, then, after aggregation, the value is defined by that route. If a variable is added or modified by more than one route, the value is added to a list of all the values defined for that variable within all the routes, for example:

[source,xml,linenums]
----
<set-variable variableName="var1" value="var1"/>
<set-variable variableName="var2" value="var2"/>
<split-aggregate #[['apple', 'banana', 'orange']]>
    <choice>
        <when expression="#[payload == 'apple']">
            <set-variable variableName="var2" value="newValue"/>
            <set-variable variableName="var3" value="appleVal"/>
        </when>
        <when expression="#[payload == 'banana']">
            <set-variable variableName="var3" value="bananaVal"/>
        </when>
        <otherwise>
            <set-variable variableName="var3" value="otherVal"/>
            <set-variable variableName="var4" value="val4"/>
        </otherwise>
    </choice>
</split-aggregate>
----

After aggregation, the variables are:

`{var1: "var1", var2: "newValue", var3: ["appleVal, bananaVal, otherVal"], var4: "val4"}`

== Error Handling

Every route is processed in parallel. So, when an error is thrown in one route, Split Aggregate continues to process each route and then invokes the xref:intro-error-handlers.adoc[Error Handler] with the aggregation of the results and errors of all the routes, for example:

[source,xml,linenums]
----
<split-aggregate collection="#['banana', 'apple']">
    <choice>
        <when expression="#[payload == 'banana']">
            <!-- Processor that throws error -->
        </when>
        <otherwise>
            <set-payload value="#[payload ++ '-result']"/>
        </otherwise>
    </choice>
</split-aggregate>
<error-handler>
    <on-error-continue type="COMPOSITE_ROUTING">
        <!-- This will have the error thrown by the above processor -->
        <logger message="#[error.errorMessage.payload.failures['0']"/>
        <!-- This will be a null value -->
        <logger message="#[error.errorMessage.payload.failures['1']"/>
        <!-- This will be a null value -->
        <logger message="#[error.errorMessage.payload.results['0']"/>
        <!-- This will have the result of this (correctly executed) route -->
        <logger message="#[error.errorMessage.payload.results['1']"/>
    </on-error-continue>
</error-handler>
----

=== Throws

* `MULE:COMPOSITE_ROUTING`

include::partial$splitagg_vs_foreach.adoc[]

See also xref:for-each-scope-concept.adoc[For Each Scope].
