= Starting and Stopping Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, esb, deploy, launch, run, terminate

[NOTE]
====
This section deals with starting and stoping Mule and deploying applications. To take full advantage of managing and monitoring features, you can deploy to the same Mule via the Runtime Manager.
====

Mule uses the Java Service Wrapper to control the Java Virtual Machine (JVM) from your native OS. The wrapper provides many options and features, including the ability to run Mule as a Unix daemon or install or remove Mule as a Windows Service. The wrapper can handle system signals and start parameters, and overall provides much better interaction between the JVM and the underlying OS.

== Startup and Shutdown Script

The wrapper is called by a script in `$MULE_HOME/bin`.

The table below lists all the parameters that the script accepts.

[%header,cols="30a,70a"]
|===
|Parameter |Description
| `start` |Starts Mule in the terminal background.
| `stop` |Stops Mule. Inbound endpoints process in-flight messages before Mule shuts down. However, after the timeout period, inflight messages that haven't completed are abandoned and Mule shuts down.
| `restart` |Restarts Mule.
| `status` | *(Linux/Unix only.)* Displays the status of the Mule server (`running` or `not running`) and the process PID if running.
| `dump` | *(Linux/Unix only.)* Dumps the Mule wrapper's core to `$MULE_HOME/log/mule_ee.log`.
| `console` |Start Mule in the terminal foreground (console mode). Same as running `mule` with no parameters.
| `install` | *(Windows only.)* Install Mule as a Windows service.
| `remove` | *(Windows only.)* Remove Mule from your Windows services.
|===

== Running Mule

Start Mule from a command line by changing the directory to where you unzipped the Mule software distribution and then changing to the bin directory. Run the following commands:

* On Windows environments:
+
[source,powershell]
----
$ $MULE_HOME\bin\mule.bat
----

* On Linux/Unix environments:
+
[source,console]
----
$ $MULE_HOME/bin/mule
----

These commands run Mule in foreground mode, and the startup script displays information on the terminal’s standard output. You can’t issue further commands on the terminal as long as Mule is running.

To stop Mule, press `CTRL-C` in the terminal in which the script is running.

== Starting Mule as a Windows Service

To run Mule as a Windows service, you need to install it first by running:

[source,powershell]
----
$ $MULE_HOME\bin\mule.bat install
----

Once installed, you can run Mule as a service:

[source,powershell]
----
$ $MULE_HOME\bin\mule.bat start
----

[NOTE]
====
When Windows restarts, the Mule service stops the same way as using the `mule stop` command.
The only situation where this could be different is if Windows kills the process due to a timeout.
====

=== Adding Properties to wrapper.conf File After Installation

After the installation of Mule as a Windows service, you can override the properties defined in the `wrapper.conf` file by declaring new properties in the `wrapper.additional.conf` file.

The behavior changes depending on the Mule edition you are using:

* Mule Community Edition
+
. After adding a new property, reinstall or restart the Windows Service.
. Add the property and ensure that its index is greater than the greatest index in the `wrapper-additional.conf` file. Otherwise, your property can be overridden.
+
For example, if the `wrapper-additional.conf` has the property:
+
`wrapper.java.additional.n=-Dproperty=value`
+
When `n` is the greatest index, you should add your property in the `wrapper.conf` file incrementing the index:
+
`wrapper.java.additional.n+1=-DyourProperty=valueOfYourProperty`

* Mule Enterprise Edition
+
. By default, you can add  20 extra properties after installing Mule as a Windows service.
. Configure the number of extra properties you need, using the following command line argument
when you install the service:
+
`-additionalJavaProperties=numberOfExtraProperties`

== Starting Mule as a Linux/Unix Daemon

To run Mule as a Linux/Unix Daemon, you need to install it first by running:

[source,console]
----
$ $MULE_HOME/bin/mule install
----

Once installed, you can run Mule as a daemon:

[source,console]
----
$ $MULE_HOME/bin/mule start
----

[NOTE]
====
You can also start Mule without executing the installation step. This starts Mule in the background for the current user session.
====

This example starts Mule from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule start
MULE_HOME is set to ~/Downloads/mule-enterprise-standalone-4.1.5
MULE_BASE is set to ~/Downloads/mule-enterprise-standalone-4.1.5
Starting Mule Enterprise Edition...
Waiting for Mule Enterprise Edition.................
running: PID:87318
----

== Starting Mule from a Script
To start Mule from a script or from your IDE without using the Java Service Wrapper, you can use the `org.mule.MuleServer` class. This class accepts a couple of parameters.

----
org.mule.MuleServer -config mule-config.xml
----

or

----
org.mule.MuleServer -builder <fully qualified classname> -config appContext.xml
----

* *-config* specifies one or more configuration files to use. If this argument is omitted, it will look for and use `mule-config.xml` if it exists.

* *-builder* is a fully qualified classname of the configuration builder to use. If this is not set, the default `org.mule.config.builders.AutoConfigurationBuilder` is used, which will try to auto-detect configuration files based on available builders. In the most common scenario, this will resolve to `org.mule.config.spring.SpringXmlConfigurationBuilder`.

The easiest way to set the classpath is to include all JARs in the `./lib/mule` and `./lib/opt` directories of the distribution. You can look at the dependency report for the server and each of the modules to see exactly which JARs are required for a particular module.


== Deploying Mule Applications

. Start Mule.
. After Mule starts, you can deploy your Mule applications by moving your packaged JAR files to the `apps` directory in `$MULE_HOME`.

== Stopping Mule

Use the `stop` command to stop Mule.

This example stops Mule from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule stop
MULE_HOME is set to /Applications/mule-enterprise-standalone-4.1.5
MULE_BASE is set to /Applications/mule-enterprise-standalone-4.1.5
Stopping Mule Enterprise Edition...
Stopped Mule Enterprise Edition.
----

== Removing the Mule Service or Daemon

Use the `remove` command to remove the service or daemon from your system.

This example removes the Mule daemon from a Unix console:

[source,console,linenums]
----
$ $MULE_HOME/bin/mule remove
MULE_HOME is set to /Applications/mule-enterprise-standalone-4.1.5
MULE_BASE is set to /Applications/mule-enterprise-standalone-4.1.5
Detected Mac OSX:
Mule Enterprise Edition is not running.
Removing Mule Enterprise Edition daemon...
----

== Enable Anypoint Monitoring

Optionally, you can install Anypoint Monitoring for cloud-managed supported versions of on-premises runtimes so you can monitor applications running on that server.


== See Also
* xref:starting-and-stopping-mule-esb.adoc[Starting and Stopping Mule]
* xref:monitoring::am-installing.adoc[Anypoint Monitoring]
* xref:runtime-manager::index.adoc[Runtime Manager]
* xref:runtime-manager::deployment-strategies.adoc[Deployment Strategies]
* xref:passing-additional-arguments-to-the-jvm-to-control-mule.adoc[Passing Additional Arguments to the JVM to Control Mule]
