= Streaming Strategy Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can use the default streaming strategy settings or configure then for your
needs. See xref:streaming-about.adoc[Streaming in Mule Apps] for more details
on these strategies.

== Repeatable In-Memory Stream Reference

[%header,cols="20,10,10,10,40"]
|===
|Parameter Name | Is required? | Expressions | Default Value | Description
| `initialBufferSize`
| No
| No
| 256
| Amount of memory allocated to consume the stream and provide random
access to it. If the stream contains more data than fits into this buffer,
the memory expands according to the `bufferSizeIncrement` attribute, with an
upper limit of `maxInMemorySize`.

| `bufferSizeIncrement`
| No
| No
| 256
| Amount to expand the buffer size if the size of the stream exceeds the initial
buffer size. Setting a value of zero or lower indicates that the buffer does
not expand and that a STREAM_MAXIMUM_SIZE_EXCEEDED error is raised when the
buffer is full.

| `maxInMemorySize`
| No
| No
| 1024
| Maximum amount of memory to use. If the size of the stream exceeds the maximimu,
a STREAM_MAXIMUM_SIZE_EXCEEDED error is raised. A value lower or equal to zero means no limit. Defaults to 1024

| `bufferUnit`
| NO
| NO
| KB
| The unit in which all these attributes are expressed. Possible values: BYTE, KB, MB, GB.
|===


=== File-Stored Input Stream

File storage is only available in Mule Enterprise Edition (Mule EE).

[%header,cols="20,10,10,10,40"]
|===
|Parameter Name | Is required? | Expressions | Default Value | Description
| `inMemorySize`
| No
| No
| 512
| Defines the maximum memory size that the stream should use to keep data in memory.
If more than that the configured amount is consumed, the strategy starts to
buffer the content on disk.

| `bufferUnit`
| No
| No
| KB
| The unit in which all these attributes are expressed. Possible values: BYTE, KB, MB, GB.
|===

== See Also

* xref:streaming-about.adoc[Streaming in Mule Apps]
