= Studio in Eclipse
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As an Eclipse-based IDE, Mule Studio has adopted many of the functionalities Eclipse has to offer. However, you don't need to download a new IDE in order to take advantages of all that Studio provides. If you are already an Eclipse user, you can simply download and install **Studio as an Eclipse plug-in**.

[NOTE]
The *Mule Studio Eclipse plugin* is accessible in the Java, Java EE, and STS distributions that use Eclipse 3.8.

. In Eclipse, under the *Help* menu, select *Install New Software...*
. In the first panel of the *Install* wizard, enter the following URL in the *Work With* field, then click *Next*.
+
`MuleStudio Update Site - http://studio.mulesoft.org/3.4/plugin`
. Review the install details, then click *Next*.
. Accept the terms and conditions of the license agreement, then click *Finish*.
. Eclipse installs *Mule Studio*, then demands a restart of the application.
. After Eclipse has restarted, use the Window menu to select *Open Perspective* > *Mule Studio*.  Alternatively, open the *Mule Visual Debugger* perspective to us Studio to debug your application.

== Go Further

* Access a list of all the xref:studio-update-sites.adoc[update sites] available for your version of Mule Studio.