= Team Development with Mule
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Most topics in the Mule documentation set address creating and managing a single project with a single configuration file on your local workstation. When working on a team, a Mule project increases in size and number of developers. It also must run in multiple environments, such as test and production.

The following approaches to modularizing Mule configurations and applications facilitate splitting work across teams by enabling reuse. You can use these approaches whether the teams work on the same overarching project or on different projects.

// * xref:modularizing-your-configuration-files-for-team-development.adoc[Modularizing Your Configuration Files for Team Development]
// * xref:using-side-by-side-configuration-files.adoc[Using Side-by-Side Configuration Files]
// * xref:using-modules-in-your-application.adoc[Using Modules In Your Application]
// * xref:sharing-custom-code.adoc[Sharing Custom Code]
// * xref:sharing-custom-configuration-fragments.adoc[Sharing Custom Configuration Fragments]
// * xref:sharing-applications.adoc[Sharing Applications]
* xref:sustainable-software-development-practices-with-mule.adoc[Sustainable Software Development Practices with Mule]
