= Transaction Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: transaction, management, demarcation, jms, jdbc, vm, database, resource, xa, tx

Transactions are operations in a Mule app for which the result cannot remain indeterminate. When a series of steps in a flow must succeed or fail as one unit, Mule uses a transaction to demarcate that a unit. For example, you might use a transaction to encapsulate several steps in a flow that result in committing information to a database. In this type of scenario, the commit (or transaction) is either entirely complete and succeeds, or is incomplete and fails. Even if partially complete, the commit fails. When a transaction fails, Mule rolls back the operations within the transaction so that no one part results in partial completion.

The Try scope provides a way to configure a transaction from its General tab. The XML for this configuration looks like this:

.XML Example: Transaction Configuration in the Try Scope

In this example, the Try scope demarcates a transaction that includes a database operation and a VM operation. Either both will be applied, or none will be applied if an error is raised within the Try scope.

[source,xml,linenums]
----
include::{examplesdir}/transaction-management_1.xml[]
----

It's also possible to start a transaction from a message source. In that case, the entire flow is a transaction. This is useful when working with messaging connectors to prevent the consumption of the message if a problem occurs when processing it so you can later retry (because of the rollback).

.XML Example: Transaction Configuration in the Message Source

[source,xml,linenums]
----
include::{examplesdir}/transaction-management_2.xml[]
----

In Studio, operations in these connectors provide an Advanced tab for setting up transactions:

* JMS:
 ** Listener supports Local and XA transaction types. When set, the entire flow is treated as a transaction.
 ** Consume and Publish operations support transactions.
* VM:
 ** Listener supports Local and XA transaction types. When set, the entire flow is treated as a transaction.
 ** Consume and Publish operations support transactions.
* Database:
 ** All database operations support transactions.

Note that a Mule flow can begin with a non-transactional connector (such as HTTP) that requires a transaction within the flow. For example, a Mule flow might accept information from an external Web service, then transform the data before charging a credit card and saving invoice information to a database. In such a situation, you might use the Try scope to set up a transaction by wrapping the credit card charge and database commit operations within a transaction to ensure either complete success or complete failure and rollback.

== Transactional Actions

A Transactional Action (`transactionalAction`)

* ALWAYS_BEGIN: Always start a new transaction when receiving a message. An exception will be thrown if a transaction already exists. Listeners that support transactions have this option.

* ALWAYS_JOIN: Always expect a transaction to be in progress when a message is received. If there is no transaction, an exception is thrown. Operations that support transactions have this option.

* BEGIN_OR_JOIN: If a transaction is already in progress when a message is received, join the transaction if possible. Otherwise, start a new transaction. Scopes that support transactions provide this setting.

* JOIN_IF_POSSIBLE: Join the current transaction if one is available. Otherwise, no transaction is created. Operations that support transactions provide this setting.

* INDIFFERENT: Do not treat actions as a transaction. Scopes that support transactions provide this setting.

* NONE: Never participate in a transaction. Listeners that support transactions provide this setting.

* NOT_SUPPORTED: Execute outside any existent transaction. Operations that support transactions provide this setting. Scopes that support transactions provide this setting.

== Transaction Types

Mule supports Single Resource (Local, the default) and Extended Architecture (`XA`) transaction types (`transactionType`). The following table describes characteristics of each type.

* Single Resource Transactions (Local)
 ** Receives or sends messages to only one resource.
 ** Performs better than XA.

* XA Transactions
 ** Receives or sends messages to more than one resource.
 ** Involves using a two-phase commit algorithm.
 ** Connectors must be XA-enabled.
 ** Slower but more reliable than Local.


[[tx_scopes_routers]]
== Scopes and Routers' behaviour with Transactions

When running in a transactional scope, the entire process must run in the same Thread. This may change the way a Scope executes, or the transaction is handled. These are the Scopes you must consider when running in a transactional scope: 

* xref:async-scope-reference.adoc[Async Scope]: When running within a transaction, the async scope will still run in another thread (remaining asynchronous). However, this means that the entire execution of the processors within this scope are out of the transactional scope. Therefore, any error produced inside an Async Scope does not result in a rollback.
* xref:scatter-gather-reference.adoc[Scatter Gather]: When running within a transaction, Scatter Gather does not execute parallely. This means that the second route will execute after the first one is processed, the third after the second one, etc. This does not affect the way this component handles errors.
* xref:until-successful-scope.adoc[Until Sucessful]: In non-transactional scenario, when performing a retry of the processors within the scope the retry is delayed an amount of time configured in the `until-successful` component. Meanwhile, the thread that used to run this processors can be used to execute another task. The retry can be performed in the same thread or another one of the same thread pool. When running within a transaction, the thread is blocked to enforce the retry to be performed in the same thread. So, the Until Successful is not non blocking in a transactional use case. 
* xref:parallel-foreach-scope.adoc[Parallel Foreach]: When running within a transaction, Parallel Foreach Scope does not execute parallely. This means it will execute as the Foreach Scope: the second element of the collection will be processed after the first one has finished. This does not affect the way this scope handles errors. 
* xref:batch-processing-concept.adoc[Batch]: Since batch is designed to work on parallel as Async Scope, and every record is treated transactionally (with internal Batch Transactions), the batch execution will not be part of the transaction. 
* xref:flowref-about.adoc[Flow Ref]: If the flow (or subflow) being executed is running within a transaction, the execution of the flow (or subflow) referenced by the `flow-ref` will continue with the same transaction. If the flow referenced has a Message Source, which begins a transaction (e.g. a JMS `jms:listener` source with `transactionalAction="ALWAYS_BEGIN"`), such `transactionalAction` is ignore as the `flow-ref` component executes the referenced flow components skipping the message source. 
* Any other router or scope (e.g. Foreach) will continue with transaction and its behaviour will not be modified. 

