= Tuning Recommendations
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule 4 runtime engine provides self-tuning execution, which adjusts itself for optimal performance according to the underlying operating conditions of the environment where you deploy Mule runtime engine (Mule). +
Self-tuning allows you to focus on the specifics of your application rather than Mule internals, which eases the optimization process. Besides, Mule 4 out of the box configuration is already tuned for optimal performance for most common use cases, and changing any parameter is advised against unless you fully understand the implications of doing so.

There are tuning recommendations that you can apply at the application level and benefit regardless of your use case:

== Repeatable vs Non-repeatable Streaming
Understand which streaming strategy applies on your use case to get the best performance of your flows: +

* A repeatable stream (read payload more than once)
* A non-repeatable stream (read payload only once)

See xref:tuning-repeatable-nonrepeatable.adoc[Repeatable vs Non-repeatable Streaming] for details.

== Back-pressure and Max Concurrency
Understand the back-pressure messages that Mule logs when it can not handle and event and learn how to use the `maxConcurrency` parameter to set the maximum number of concurrent messages that a flow can process at any given time.

See xref:tuning-backpressure-maxconcurrency.adoc[Back-Pressure and MaxConcurrency] for details.

== Backend Servers Response Time
Understand if the backend servers average latency and throughput are limiting the scalability or performance of your application.

See xref:tuning-backend-server.adoc[Backend Server Response Time] for details.

== Caching
Identifying key aspects of your data leads to a better solution approach. Mule offers some customizable mechanisms, such as Cache Scope and HTTP Caching API Gateway policy, to enable cache according to your needs. Understand when to use cache and which cache-strategy to follow.

See xref:tuning-caching.adoc[Caching] for details.

== Pooling Profiles
Pooled components configure their component pool which contains multiple instances of the component to handle simultaneous incoming requests. Understand how to add add `pooling-profile` to connectors when performance tests show it necessary.

See xref:tuning-pooling-profiles.adoc[Pooling Profiles] for details.

== Domains
By having a centralized-point for all the shared resources, domains help the class-loading process. Domains are also a performance choice when deploying multiple services on the same on-premises Mule runtime engine.

See xref:tuning-domains.adoc[Domains] for details.

== Logging
Understand why asynchronous logging has better performance  achieved than in synchronous logging strategy.

See xref:tuning-logging.adoc[Logging] for details.

== Batch Processing
Mule possesses the ability to process messages in batches. Batch processing requires having enough available memory to process the threads in parallel, which means moving the records from persistent storage into RAM in a fixed size block. Understand how to configure the batch block size property for your application.

See xref:tuning-batch-processing.adoc[Batch Processing] for details.

== Application Design Best Practices
These practices can help you on the application design phase to get a better performance for your Mule apps.

See xref:tuning-app-design.adoc[Application Design] for details.

== See Also
* xref:tuning-guide.adoc[Performance Tuning Guide]
