= Caching
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When it comes to performance, identifying key aspects of your data always leads to a better solution approach. Among those key aspects are the ones that define when to use cache and which cache strategy to follow.

* Is the data frequently called with often repeated results?
* Can you afford eventual consistency between the data source and the cache information? At least for a while until cache refreshes.

Mule runtime engine (Mule) offers customizable mechanisms, such as Cache Scope and HTTP Caching API Gateway policy, to enable cache according to your needs. +
Both strategies help applications which constantly request the same data to experience a noticeable performance improvement by reducing the processing load, especially network interactions with a remote host.

For Cache Scope, the default configuration is in-memory caching which is not recommended for production because it might use up all your memory resources, so an object-store caching with well-defined storage and expiry policies is most recommended.

== See Also

* xref:cache-scope.adoc[Cache Scope]
* xref:api-manager::http-caching-policy.adoc[HTTP Caching]
