= How Caching Use Helps to Improve Processing Performance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Identifying key aspects of your data such as when to use cache and which cache strategy to follow, helps you to improve processing performance:

* Is the data frequently called with often repeated results?
* Can you afford eventual consistency between the data source and the cache information? At least for a while until cache refreshes.

Mule runtime engine (Mule) offers customizable strategies, such as Cache scope and HTTP Caching API Gateway policy, to enable cache according to your needs. +
Both strategies help applications that constantly request the same data by reducing the processing load, especially network interactions with a remote host.

For Cache scope, in a production environment, the default in-memory caching configuration might use up all your memory resources, so you better use an object-store caching configuration with well-defined storage and expiry policies.

== See Also

* xref:cache-scope.adoc[Cache Scope]
* xref:api-manager::http-caching-policy.adoc[HTTP Caching]
