= Backend Server Response Time
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]


When investigating performance issues, you should first look if the overall flow's performance is heavily constrained by the latency (response time or message round-trip time in milliseconds unless otherwise noted) of the remote hosts to which the flow connects into.

Failing to acknowledge the performance overhead that is added to a flow by the underlying complexities of the communication between the application and a remote host, may lead the optimization effort through the wrong path with negligible improvements in the end. +
Therefore, it is important that before starting any optimization in the Mule app, to first characterize the backend servers average latency and throughput, and to establish if these are the ones limiting the scalability or performance of your application.

There are many factors to consider such as: +

* Average payload size exchanged between the app and the remote host.
* Network latency because of the application and remote host physical location. Check if these are in the same network, same geographical region, same country, or the other side of the world.
* Remote host response time.

The throughput and response time of your application can improve if the remote host is located within the same network boundaries as the application. However, if the remote host is outside of your application's local network, you may experience an increased latency which will be directly proportional to the remote host response time, regardless of the payload size. +
There are many other factors involved in an application's throughput such as external dependencies, concurrency, flow complexity, deployment characteristics, machine configuration, and so on.
