= Back-Pressure and Max Concurrency
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Under heavy load, Mule runtime engine (Mule) might not have resources available to handle a specific event. This issue might occur because all threads are busy and the current flow’s concurrency has been exceeded already. +
In case Mule cannot handle an event, Mule logs a message about the condition: +
`Flow 'flowName' is unable to accept new events at this time` +
Also known as back-pressure. Mule back-pressure actions are specific to each connector’s source.

When there is a producer component that outputs information at a higher rate than a consumer component can handle, you can use the flow’s `maxConcurrency` parameter to set the maximum number of concurrent messages that a flow can process at any given time. +
This scenario can manifest in various forms, as those components could be internal/external, flows/sources, etc.

Although Mule applies back-pressure on its own, the `maxConcurrency` parameter helps to keep under control the performance of your flows, especially when a backend server may affect when having high concurrency. See how to set the parameter in the following example:

[source,xml,linenums]
----
<flow name="perf-test-flow" maxConcurrency="${flow.max.concurrency}">
----

Similarly, you can limit the amount of records that can be processed in a batch job setting the `maxConcurrency` parameter like the following example:

[source,xml,linenums]
----
<batch:job jobName="test-batch" maxConcurrency="${batch.max.concurrency}">
----

== See also
* xref:intro-engine.adoc[Execution Engine Threads and Concurrency]
