= Pooling Profiles
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Unlike singleton components, pooled components configure their component pool which contains multiple instances of the component to handle simultaneous incoming requests. Each pooled component has its pooling profile.

== Use Pooling Profile Parameter
Connectors such as Anypoint Connector for FTP (FTP Connector) or Anypoint Connector for SFTP (SFTP Connector) pool the connections by default and use a pooling profile to customize the connection pool. Add the `pooling-profile` parameter to the connectors when performance tests show it necessary.

However, Anypoint Connector for Database (Database Connector) does not perform connection pooling by default, which means that every execution of an SQL statement opens a new connection and closes it once finished (unless there is a transaction active that uses the same connection for the whole transaction). In this case, by using a pooling profile, the connection set-up occurs only once and subsequent requests use existing connections achieving a performance benefit as a result. See the following example:

[source,xml,linenums]
----
<db:mysql-config name="dbConfig" host="localhost" port="3306" user="root"
   password="" database="esb" doc:name="MySQL Configuration">
   <db:pooling-profile maxPoolSize="17" minPoolSize="13" />
</db:mysql-config>
----

The most important setting is the one that specifies the maximum number of instances of the component that Mule runtime engine creates to handle simultaneous requests.
