= Understanding the Mule Architecture
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This section describes the different parts of the Mule ESB architecture and how they handle messages and their data. For the sake of illustration, it uses the example of a company that needs to generate invoices for customer orders, perform some processing on those invoices, and then send them to the shipping department for order fulfillment.

This section includes the following topics:

* xref:about-soa.adoc[About SOA]
* xref:mediation-separating-business-logic-from-messaging.adoc[Mediation - Separating Business Logic from Messaging]
* xref:orchestration-routing-messages-between-service-components.adoc[Orchestration - Routing Messages Between Service Components]
* xref:components-processing-the-data.adoc[Components - Processing the Data]
* xref:endpoints-wiring-everything-together.adoc[Endpoints - Wiring Everything Together]
* xref:understanding-the-logical-data-flow.adoc[Understanding the Logical Data Flow]