= Upgrading CXF from Mule 2
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule 3 completely revamps the CXF support. CXF no longer exists as a transport, but rather a module which is a series of message processors.

This has the following benefits:

* Flexibility - it is now much easier to intermix CXF with transformers, filters and other message processors. You simply insert a CXF message processor in the flow where you wish it to be executed.
* Easier configuration - there are a number of configuration elements, e.g. jaxws-service, simple-service, proxy-service, etc, which each have their own syntax targeted to their specific use cases.
* Increased robustness - with the improved property scoping and message processor model, the CXF module property is more robust and rigorous in it's behavior.

To learn more about the new syntax, see:

* xref:building-web-services-with-cxf.adoc[Building Web Services with CXF] - Information on how to build JAX-WS code first, JAX-WS WSDL first, and simple frontend services.
* xref:consuming-web-services-with-cxf.adoc[Consuming Web Services with CXF] - Information on how to consume JAX-WS services and simple frontend services.
* xref:proxying-web-services-with-cxf.adoc[Proxying Web Services with CXF] - Information on how to create web service proxies, e.g. if your CXF endpoint had proxy="true" before.