= Using Mule with Spring
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, studio, mule, spring

Mule leverages the Spring framework for developing Java applications.

== Supported Spring Versions

* Mule 3.8: Spring 4.1.9 and Spring Security 4.0.4
* Mule 3.7.5: Spring 4.1.9 and Spring Security 4.0.4
* Mule 3.7.0 - 3.7.4: Spring 4.1.6 and Spring Security 4.0.1
* Mule 3.6 and earlier: Spring 3.2 and Spring Security 3.0

See also: http://docs.spring.io/spring-security/site/migrate/current/3-to-4/html5/migrate-3-to-4-xml.html[Spring Security Migrate 3 to 4]

== XML Configuration File

The way to configure a Mule application is with an XML file that uses custom Mule namespaces. By default, a Spring configuration builder takes this XML file to create Mule artifacts and register them with a Mule runtime instance.

Use one of the two namespaces in your Mule XML Configuration file:

* `+http://www.springframework.org/schema/beans+`
* `+http://www.springframework.org/schema/beans/spring-beans-current.xsd+`

== Spring Application Contexts

Mule offers several options for creating and managing xref:spring-application-contexts.adoc[Spring Application Contexts] for your application.

[TIP]
Build Spring beans to define component behaviors which Mule applications can reference. See xref:using-spring-beans-as-flow-components.adoc[Using Spring Beans as Flow Components]

== Spring Bean Definition Profiles

Mule’s XML configuration file takes advantage of Spring 4.1.6's ability to create *bean definition profiles*. You can use Spring bean definition profiles to register different beans for different target environments, instead of using one bean for all target environments. For more information, see http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-definition-profiles[Bean Definition profiles] in the Spring Framework Reference.

== See Also

* xref:about-the-xml-configuration-file.adoc[About the XML Configuration File]
* xref:about-configuration-builders.adoc[About Configuration Builders]