= Using Bitronix to Manage Transactions
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: bitronix, transaction, xa, management, bti

[WARNING]
====
If the Mule server crashes or loses connectivity to a resource manager (such as a JMS broker, database, etc.), this can cause a transaction to fail abnormally between the prepare phase and the commit phase of the two-phase commit protocol (2PC). In this case, the transaction manager needs to run a recovery process to complete any in-flight transaction that was taking place during the failure. While this kind of failure is unlikely, a mechanism is needed to retain data consistency in the event of this happening.

Bitronix allows Mule Runtime to automatically recover interrupted transactions on restart.
====


== Assumptions

This document assumes you are familiar with working with xref:shared-resources.adoc[Shared Resources] in Mule, and xref:transaction-management.adoc[Transaction Management].

== Using Bitronix in Mule

=== Using Bitronix in a Single Application

To configure an application to use Bitronix, declare the transaction manager outside of your flows, as shown below.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:bti="http://www.mulesoft.org/schema/mule/ee/bti"
      xsi:schemaLocation="
       http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
       http://www.mulesoft.org/schema/mule/ee/bti http://www.mulesoft.org/schema/mule/ee/bti/current/mule-bti-ee.xsd">
    <bti:transaction-manager/>
...
</mule>
----

=== Using Bitronix in All Applications in a Mule Domain

To use Bitronix in all applications associated to a Mule domain, define Bitronix as the transaction manager in your domain configuration file, as shown below. Doing so causes all applications associated to the domain to use Bitronix, without needing to declare the transaction manager in individual applications. For further details on domain configuration, see xref:shared-resources.adoc[Shared Resources].

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<domain:mule-domain
        xmlns:bti="http://www.mulesoft.org/schema/mule/ee/bti"
        xmlns="http://www.mulesoft.org/schema/mule/core"
        xmlns:domain="http://www.mulesoft.org/schema/mule/ee/domain"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/ee/domain http://www.mulesoft.org/schema/mule/ee/domain/current/mule-domain-ee.xsd
http://www.mulesoft.org/schema/mule/ee/bti http://www.mulesoft.org/schema/mule/ee/bti/current/mule-bti-ee.xsd">
	<bti:transaction-manager/>

    <!-- ... -->

</domain:mule-domain>
----

=== Using Bitronix in Anypoint Studio

For both cases, Application or Domain, to add Bitronix Transaction Manager:

1. Go to the Global Elements' tab.
2. Click on Create button. 
3. Search for `Bitronix Transaction Manager`. 

== Configuring the Bitronix Transaction Manager

In the Mule Runtime, there is only one instance of the Bitronix Transaction Manager; all the applications that have Bitronix defined as their transaction manager use this instance. Thus, the Bitronix Transaction Manager cannot be configured at the _application_ level, only at the _domain_ level.

The default configuration values for Bitronix are suitable for most use cases. However, if you wish to customize the transaction manager, you can do so by using system properties or the `wrapper.conf` file located in the `$MULE_HOME/conf` directory.

The table below lists configuration attributes for Bitronix.

[%header,cols="34,33,33"]
|===
|Configuration Attribute |Description |Default value
|`mule.bitronix.transactiontimeout` |Timeout for XA transactions, in seconds |60
|`mule.bitronix.recoveryinterval` |Recovery execution interval for XA transactions, in seconds |60
|`mule.bitronix.serverId` |Unique ID for the transaction manager to register in the XA transaction logs. This value must be unique for each Mule server |Combination of the host IP and, if running in HA, the cluster node ID
|===


=== Configuring a Pooling Data Source for Databases

Bitronix integration provides a datasource connection pool for the Database connector, which you must use whenever you want to implement resource pooling in the Database connector.

You can configure a shared Pooling Data Source for all connections. This could improve connection utilization when those data sources are not heavily used by applications.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<mule-domain xmlns="http://www.mulesoft.org/schema/mule/ee/domain"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:db="http://www.mulesoft.org/schema/mule/db"
      xmlns:bti="http://www.mulesoft.org/schema/mule/ee/bti"
      xmlns:spring="http://www.mulesoft.org/schema/mule/spring"
      xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/ee/bti http://www.mulesoft.org/schema/mule/ee/bti/current/mule-bti-ee.xsd
               http://www.mulesoft.org/schema/mule/ee/domain http://www.mulesoft.org/schema/mule/ee/domain/current/mule-domain-ee.xsd
               http://www.mulesoft.org/schema/mule/db http://www.mulesoft.org/schema/mule/db/current/mule-db.xsd">

    <spring:config name="springConfig" files="domain-config/datasource-beans.xml"/>

    <bti:transaction-manager/>

    <bti:xa-data-source-pool name="pooledDataSource" dataSource-ref="jdbcDataSource"/>

    <db:generic-config name="dbConfig" dataSource-ref="pooledDataSource"/>

</mule-domain>

----

The table below lists configuration attributes for Pooling Data Source.

[%header,cols="34,33,33"]
|===
|Attribute |Description | Required | Default value
|`name` |Identifies the pool so that the connector can reference it| Yes |
|`datasource-ref` |Reference to the JDBC data source object. An XADataSource object must be provided.| Yes |
|`min-pool-size` |Defines the minimal amount of connections that can be in the pool| No | 4
|`max-pool-size` |Defines the maximum amount of connections that can be in the pool| No | 16
|`max-idle-itme` |Defines the amount of seconds an idle connection can stay in the pool before getting closed| No |60
|`acquire-increment`|Determines how many connections at a time will try to acquire when the pool is exhausted| No |1
|`acquire-timeout-seconds`|The number of seconds a client calling getConnection() will wait for a Connection to be checked-in or acquired when the pool is exhausted. Zero means wait indefinitely| No |30
|`prepared-statement-cache-size` |Determines how many statements are cached per pooled connection. 0 means caching is desabled| No | 5
|===



== Transaction Recovery

Enabling transaction recovery requires no configuration on your part. When Mule restarts after a system crash, it connects to all of the resources involved in XA transactions and starts the transaction recovery process, leaving all systems in a consistent state.

== See Also

* xref:shared-resources.adoc[Shared Resources].


