= Using the Web Service Wrapper
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[WARNING]
In Mule 3.3 the Web Service Wrapper has been deprecated because with the introduction of flows this behavior can be easily accomplished by adding outbound endpoints.

The

https://www.mulesoft.org/docs/site/current/apidocs/org/mule/transport/soap/axis/component/WebServiceWrapperComponent.html[WebServiceWrapperComponent]

class allows you to send the result of a web service call to another endpoint. The web service call is performed within `WebServiceWrapperComponent`, providing the following advantages:

* You can set any type of router on inbound and outbound.
* Unlike the chaining router, it can send more than one HTTP request at a time
* The URL for the web service call can be changed at run-time by sending the URL with the message

== Configuring the Web Service Wrapper

To use the web service wrapper, you specify the `<wrapper-component>` configuration element. The following table describes the attributes you can set for this element. These attributes are described in more detail in the examples that follow.

[%header,cols="34,33,33"]
|===
|Attribute |Description |Required?
|address |Specifies the URL of the web service to call |Yes, unless `addressFromMessage` is set to true
|addressFromMessage (default is false) |Specifies that the URL of the web service will be obtained from the message itself |Not required if `address` is set
|wrapperProperties |The SOAP document style, expressed as a map of two properties: `style`, which can be set to `RPC` (the default), `Document`, `Message`, or `Wrapped`, and `use`, which can be `Encoded` or `Literal`. |No
|`<soap-method>` |A SOAP method to call (see <<Configuring SOAP Methods>> below) |No
|===

The web service wrapper is generic and can be used with any type of web service stack supported by Mule, including Axis and CXF. The examples below show synchronous use cases, but the web service wrapper can also support an asynchronous use case like the loan broker example.

=== Example Configuration Using the CXF Transport

Consider the following example. The web service wrapper is configured as a Mule component, accepting messages from a VM endpoint. A call must be made to a web service on the URL `cxf:http://localhost:65081/services/TestUMO?method=onReceive` and the result must be sent to the outbound endpoint `vm://testout`.

The inbound and outbound endpoints are configured in the usual way. The address is set as an attribute on the component, specifying the web service URL that you want to call.

[source,xml,linenums]
----
<cxf:connector name="cxf" defaultFrontend="simple" />
<model name="Sample">
   <service name="WebServiceSample">
      <inbound>
         <vm:inbound-endpoint path="testin" />
      </inbound>
      <cxf:wrapper-component address="http://localhost:65081/services/TestUMO?method=onReceive"/>
      <outbound>
         <pass-through-router>
            <outbound-endpoint address="vm://testout"/>
         </pass-through-router>
      </outbound>
   </service>
----

=== Example Configuration Using the addressFromMessage Property

The "address" property is ideal to use when the web service URL for the web service is known at configuration time. However, if this URL is either not known or else needs to be changed at run-time, the "address" property can be omitted and the "adddressFromMessage" property can be set to true. The following example shows this configuration:

[source,xml,linenums]
----
<service name = "WebServiceSample2">
   <inbound>
      <vm:inbound-endpoint path = "testin2"/>
   </inbound>
   <cxf:wrapper-component addressFromMessage = "true"/>
</service>
----

The URL must be set on the message with the property name "ws.service.url". +

=== Configuring SOAP Methods

CXF endpoints are fairly easy to configure, whereas Axis needs some further configuration to set SOAP methods. You can set a SOAP method using the `<soap-method>` element as shown below:

[source,xml,linenums]
----
<service name = "WebServiceSample3">
   <inbound>
      <vm:inbound-endpoint path = "queue.in" connector-ref = "VMQueue"/>
   </inbound>
   <axis:wrapper-component address = "http://localhost:62088/axis/Calculator?method=add" style = "WRAPPED" use = "LITERAL">
      <axis:soap-method method = "qname{add:http://muleumo.org/Calc}">
         <axis:soap-parameter parameter = "Number1" type = "int" mode = "IN"/>
         <axis:soap-parameter parameter = "Number2" type = "int" mode = "IN"/>
         <axis:soap-return type = "int"/>
      </axis:soap-method>
   </axis:wrapper-component>
   <outbound>
      <pass-through-router>
         <vm:outbound-endpoint path = "queue.out" connector-ref = "VMQueue"/>
      </pass-through-router>
   </outbound>
</service>
----