= What's New in Mule 4.4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Mule runtime engine 4.4 is mainly focused on fixing issues, and also includes some enhancements.

== Feature Flags
Mule 4.4 incorporates a feature flagging mechanism, which enables you to disable certain features that change core functionality in Mule to avoid backward compatibility issues.

See xref:mule-runtime::feature-flagging.adoc[Feature Flagging] for additional information and configuration instructions.

== Correlation ID Management
Mule 4.4 enables you to modify the Correlation ID associated with a Mule event. You can also change the algorithm Mule uses to generate each Correlation ID.

See xref:mule-runtime::correlation-id[Correlation ID] for additional information and configuration instructions.

== Improved Logging Capabilities
Mule 4.4 incorporates Mapped Diagnostic Context (MDC), which enriches logging and improves tracking by providing more context or information in the logs for Mule events.

By using the Mule Tracing module, you can add, remove, and clear variables from the logging context for a given Mule event.

See xref:mule-runtime::logging-mdc.adoc[MDC Logging] for additional information and configuration instructions.

== DataWeave Updates

The Mule 4.4 release includes DataWeave 2.4.0 features.

See xref:dataweave::whats-new-in-dw.adoc[What's New in DataWeave] for additional information.

== Core Components

Mule 4.4 introduces the Mule Tracing Module (available in Studio 7.11), which enables correlation ID management capabilities as well as improved logging options.

See xref:connectors::tracing/index.adoc[Tracing Module] for the complete documentation of this module.

== See Also

* xref:release-notes::mule-runtime/mule-4.4.0-release-notes.adoc[Mule Runtime 4.4.0 Release Notes]
