= [MULE3EXAMPLES:Mule 3.2] Widget Factory Example
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

These are instructions for running the Widget example in Mule 3.2. To run it in Mile 3.1, see link:widget-example-mule-3.1[here].

This example illustrates the use of Mule's xref:mule-high-availability.adoc[High Availability (HA)] module for failover.

== Running the example

Note: in order to run this example you need a Mule Cluster.

. From one (and only one) of the Mule installations in the cluster, run +
 the command line client (widget / widget.bat) which is in the +
 examples/widget directory, this will start up a JMS server used by +
 all Mule instances in the cluster (if you start up more than one you +
 will get port conflicts). Write down the IP of that machine.
. Open "examples/widget/src/main/app/mule-config.xml" and replace "localhost" with the IP you just wrote down, so that all nodes consume the same queue.
. Run "mvn" inside the "examples/widget" directory. This will recompile the example introducing our change and generate a zip file with the new application.
. Use the Mule Enterprise Management Console to deploy the pre-built +
 widget application (mule-example-widget.zip) to the cluster.
. The widget application is now ready to be run.

== Testing the example

. From the command line client, send some widgets to be manufactured. You +
 should see them being processed by the different instances in the cluster. +
 instance.
. Now, shut down one of the instances in the cluster.
. You should see widgets continue to be manufactured by the remaining +
 instances.
. Restart the instance that was shut down in step 2.
. Once that instance has finished restarting, you will see it resume +
 manufacturing widgets.

For more information, see xref:mule-high-availability.adoc[Mule High Availability]