//
//tag::component-title[]

= Scatter-Gather  (<scatter-gather/>)
:component-filename: scatter-gather

//end::component-title[]
//

//
//tag::component-short-description[]

Process a Mule event through two or more routes, and combine the results into a single event object.

//end::component-short-description[]
//

//
//tag::component-long-description[]
Each route runs on a separate thread to sequentially execute one or more processors (either a connector operation or Mule component). By default, each route runs in parallel. After each route completes successfully, the component combines the resulting Mule events into a new Mule event object that travels to the next processor in the flow.

Repeatable streams are a Mule feature that enables a component to reread a stream. Non-repeatable streams can be read only once before they are lost. By default, Mule components return a repeatable stream unless their streaming strategy is configured to be non-repeatable.

This component can process only repeatable streams and _cannot_ process a non-repeatable stream. If Scatter-Gather receives a non-repeatable stream as input from an upstream component that is configured with such a strategy, Scatter-Gather cannot process it.

//end::component-long-description[]
//


//SECTION: COMPONENT XML
//
//tag::component-xml-title[]

[[component-xml]]
== Component XML

This component supports the following XML structure: 

//end::component-xml-title[]
//
//
//tag::component-xml[]

[src,xml]
----
<scatter-gather doc:name="Scatter-Gather" 
  doc:id="24d159a9" 
  timeout="0" 
  target="myTarget" 
  maxConcurrency="10">
    <route >
      <!-- one or more processors here -->
    </route>
    <route >
      <!-- one or more processors here -->
    </route>
</scatter-gather>
----

//end::component-xml[]
//
//
//TABLE: ROOT XML ATTRIBUTES (for the top-level (root) element)
//tag::component-xml-attributes-root[]

The `<scatter-gather/>` element sends a request to multiple targets concurrently. This component collects the responses from all routes and aggregates them into a single message.

The `<route/>` child element contains one or more connector operations or Mule components for processing the event. 

[%header,cols="1,3a"]
|===
| `<scatter-gather/>` Attributes 
| Description

| `doc:name` 
| Editable name for the component.

| `doc:id` 
| Automatically generated identifier for the component.

| `timeout` 
| Sets the timeout for responses from sent messages, in milliseconds. A value of `0` or less than `0` prevents a timeout. Defaults to `0`. 

| `maxConcurrency` 
| Sets the maximum number of routes to run concurrently.

By default, all routes run in parallel. Setting this value to `1` makes the component process the routes sequentially.

| `target` 
| The name of the xref:mule-runtime::target-variables.adoc[target variable].

| `targetValue` | Value of the data to store in the target variable.
The default value is `#[payload]`. This field accepts any value that a Mule variable accepts:

* Any supported data type
* DataWeave expressions
* The keywords `payload`, `attributes`, and `message`, but _not_ the keyword `vars`

|===


//end::component-xml-attributes-root[]
//
//
//TABLE (IF NEEDED): CHILD XML ATTRIBUTES for each child element
//  Repeat as needed, adding the next number to the tag value. 
//  Provide intro text, as needed.
//tag::xml-attributes-child1[]
[%header, cols="1,3"]
|===
| <CHILD_ELEMENT/> Attributes | Description

| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.
| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.

|===
//end::xml-attributes-child1[]
//
//
//TABLE (IF NEEDED): GRANDCHILD XML ATTRIBUTES for each grandchild element
//  Repeat as needed, adding the next number to the tag value. 
//  Provide intro text, as needed.
//TAG
//tag::xml-attributes-descendant1[]
[%header, cols="1,3"]
|===
| <GRANDCHILD_ELEMENT/> Attributes | Description

| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.
| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.

|===
//end::xml-attributes-descendant1[]
//


//SECTION: EXAMPLES
//
//tag::component-examples-title[]

== Examples

//end::component-examples-title[]
//
//
//tag::component-xml-ex1[]
[[example1]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex1[]
//
//
//tag::component-xml-ex2[]
[[example2]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex2[]
//


//SECTION: ERROR HANDLING if needed
//
//tag::component-error-handling[]

[[error-handling]]
== Error Handling

This component can throw the following errors:

* `MULE:ROUTING`
* `MULE:COMPOSITE_ROUTING`

If you configure a timeout for this component and a route does not complete processing before the timeout expires, the route throws a `MULE:TIMEOUT` error. Mule handles this error as it handls other errors generated from a route: After each route completes (either by processing successfully or by throwing a `MULE:TIMEOUT` error), the successful results and errors are collected into the `MULE:COMPOSITE_ROUTING` error and then processed within a configured error handler component.

//end::component-error-handling[]
//


//SECTION: SEE ALSO
//
//tag::see-also[]

[[see-also]]
== See Also

//TODO: point to Mule variable doc 
* xref:mule-runtime::about-components.adoc[]
* xref:mule-runtime::transaction-management.adoc#tx_scopes_routers[How Transactions Affect Scopes and Routers]
* xref:mule-runtime::error-handling.adoc[]
* xref:mule-runtime::try-scope-concept.adoc[]
* xref:mule-runtime::about-mule-event.adoc[]

//end::see-also[]