// tag::propertiesParameterDescription[]
| `properties` | Top-Level element +
If you need to set properties for the Mule application you are deploying, you can use the `<properties>` top-level element:
[source,xml,linenums]
----
<properties>
  <key>value</key>
</properties>
----

For example:
[source,xml,linenums]
----
<properties>
  <http.port>8081</http.port>
</properties>
----
// end::propertiesParameterDescription[]

// tag::businessGroupParameterDescription[]
| `businessGroup` | The Business group path of the deployment. +
For example:
[source,xml,linenums]
----
<businessGroup>MasterOrg/SubOrg</businessGroup>
----
// end::businessGroupParameterDescription[]

// tag::businessGroupIdParameterDescription[]
| `businessGroupId` | The Business group id of the deployment. +
This parameter is available in plugin version 3.2.7 and later.
// end::businessGroupIdParameterDescription[]

// tag::deploymentTimeoutParameterDescription[]
| `deploymentTimeout` | The allowed elapsed time, in milliseconds, between the start of the deployment process and the confirmation that the artifact has been deployed

The default value is `1000000`.
// end::deploymentTimeoutParameterDescription[]

// tag::serverParameterDescription[]
| `server` | Maven server with Anypoint Platform credentials. +
This is only needed if you want to use your credentials stored in your Maven `settings.xml` file. This is not the Mule server name.
// end::serverParameterDescription[]

// tag::skipParameterDescription[]
|`skip` | When set to `true`, skips the plugin deployment goal. +
Its default value is `false`.
// end::skipParameterDescription[]

// tag::skipDeploymentVerification[]
|`skipDeploymentVerification` | When set to `true`, skips the status verification of your deployed app. +
Its default value is `false`.
// end::skipDeploymentVerification[]

// tag::applicationNameParameterDescription[]
| `applicationName` | Specifies the application name to use during deployment.
// end::applicationNameParameterDescription[]

//tag::addMuleMavenPluginToAProject[]
To add the Mule Maven plugin, you need to add its maven dependency to the project:

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
</plugin>
----

From this repository:

[source,xml,linenums]
----
<pluginRepositories>
  <pluginRepository>
    <id>mule-public</id>
    <url>https://repository.mulesoft.org/nexus/content/repositories/releases</url>
  </pluginRepository>
</pluginRepositories>
----

This enables the Mule Maven plugin in your project.

[IMPORTANT]
If `<extensions>true</extensions>` is not present, the plugin does not work.

//end::addMuleMavenPluginToAProject[]

//tag::encryptCredentials[]
To use encrypted credentials when deploying, you need to set up your Maven master encrypted password and your `settings-security.xml` file.

. Create a master password for your Maven configuration.
+
----
mvn --encrypt-master-password <yourMasterPassword>
----
+
Maven returns your master password encrypted:
+
----
{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}
----
+
. Create a `settings-security.xml` file in your ~/.m2 repository and add your encrypted master password:
+
[source,xml,linenums]
----
<settingsSecurity>
  <master>{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}</master>
</settingsSecurity>
----
+
. Encrypt your Anypoint platform password:
+
----
mvn --encrypt-password <yourAnypointPlatformPassword>
----
+
Maven returns your Anypoint platform password encrypted:
+
----
{HTWFGH5BG9QmvJ1B=}
----
. Add your encrypted Anypoint Platform password to your `settings.xml` file in the <server> section:
+
[source,xml,linenums]
----
<settings>
 ...
  <servers>
   ...
    <server>
      <id>my.anypoint.credentials</id>
      <username>my.anypoint.username</username>
      <password>{HTWFGH5BG9QmvJ1B=}</password>
    </server>
   ...
  </servers>
 ...
</settings>
----
. In your configuration deployment, reference the credentials injecting the server id configured in your `settings.xml` file:

//end::encryptCredentials[]
