//= Deploy Applications to Runtime Fabric Using the Mule Maven Plugin
// tag::intro[]

include::mule-runtime::partial$mmp-concept.adoc[tag=deprecatedVersionsWarning]

include::reuse::partial$non-inclusive-banner.adoc[]

In addition to using Anypoint Runtime Manager, to deploy applications to Anypoint Runtime Fabric, you can also deploy applications by using the Mule Maven plugin. To do so, you must meet certain prerequisites, and configure your Runtime Fabric deployment strategy in your project's `pom.xml` file.

If you want to deploy applications to Runtime Fabric using a different method, see:

* xref:runtime-fabric::deploy-to-runtime-fabric.adoc[Deploy Applications to Runtime Fabric Using Runtime Manager]
// end::intro[]

// tag::prerequisites[]
== Prerequisites

* Ensure that the Mule Maven Plugin is added to your project
+
See xref:mmp-concept.adoc#add-mmp[Add the Mule Maven Plugin to a Mule Project] for instructions.
* You understand and have available the number of resources required to deploy to Runtime Fabric +
See xref:runtime-fabric::deploy-resource-allocation-self-managed.adoc[]for more information.
* The application is already published in Exchange +
See xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].

// end::prerequisites[]

// tag::prerequisitesRTF[]
== Prerequisites

* Ensure that the Mule Maven Plugin is added to your project
+
See <<add-mmp, Add the Mule Maven Plugin to a Mule Project>> for instructions.
* You understand and have available the number of resources required to deploy to Runtime Fabric +
See xref:runtime-fabric::deploy-resource-allocation-self-managed.adoc[Resource Allocation on Anypoint Runtime Fabric] for more information.
* The application is already published in Exchange +
See xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].

// end::prerequisitesRTF[]

// tag::rtfDeploymentConfig[]
[[deploying-to-rtf]]
== Configure the Runtime Fabric Deployment Strategy

Inside the `plugin` element, add a configuration for your Runtime Fabric deployment, replacing the following placeholder values with your Runtime Fabric information:

[source,xml,linenums]
----
<plugin>
include::mule-runtime::example$mmp-concept-config.xml[]
  <configuration>
    <runtimeFabricDeployment>
      <uri>https://anypoint.mulesoft.com</uri>
      <muleVersion>4.3.0</muleVersion>
      <username>user</username>
      <password>pass</password>
      <applicationName>newapp</applicationName>
      <target>rtf</target>
      <environment>Sandbox</environment>
      <provider>MC</provider>
      <replicas>1</replicas>
      <properties>
        <key>value</key>
      </properties>
      <deploymentSettings>
        <enforceDeployingReplicasAcrossNodes>false</enforceDeployingReplicasAcrossNodes>
        <updateStrategy>recreate</updateStrategy>
        <clustered>false</clustered>
        <forwardSslSession>false</forwardSslSession>
        <lastMileSecurity>false</lastMileSecurity>
        <resources>
          <cpu>
            <reserved>20m</reserved>
            <limit>1500m</limit>
          </cpu>
          <memory>
            <reserved>700Mi</reserved>
          </memory>
        </resources>
        <http>
          <inbound>
            <publicUrl>url</publicUrl>
          </inbound>
        </http>
      </deploymentSettings>
    </runtimeFabricDeployment>
  </configuration>
</plugin>
----
// end::rtfDeploymentConfig[]

// tag::rtfDeploymentCommands[]
== Deploy to Runtime Fabric

From the command line in your project's folder, package the application and execute the deploy goal:

[source,bash,linenums]
----
mvn clean deploy -DmuleDeploy
----

=== Maven Snapshot Assets

You can also deploy Maven snapshot assets into Runtime Fabric. To learn more about publishing snapshot assets to Anypoint Exchange, see xref:exchange::to-publish-assets-maven.adoc#asset-lifecycle-state[Asset Lifecycle State].

[NOTE]
Each time you update your application's snapshot, you need to redeploy the application to refresh it with the latest snapshot binaries. 
+
Since snapshot assets can change after they are deployed, avoid deploying them into your production environment.

== Redeploy to Runtime Fabric

To redeploy the application, run the same command as you did to deploy. +
Runtime Fabric rewrites the application you had deployed.
// end::rtfDeploymentCommands[]

// tag::authenticationMethods[]
== Authentication Methods

include::mule-runtime::partial$mmp-concept.adoc[tag=authenticationMethodsIntro]

include::mule-runtime::partial$mmp-concept.adoc[tags=authenticationOptionsList;!authenticationMethodsIntro;!authenticationCloudHub;!authenticationOnPrem]

For a detailed description of the configuration parameters, see the <<rtf-deploy-reference, Runtime Fabric Deployment Parameters Reference>>.
// end::authenticationMethods[]

// This tag is dependent of partial file mmp-concept.adoc in docs-mule-runtime.
// tag::rtfDeploymentReference[]
[[rtf-deploy-reference]]
== Runtime Fabric Deployment Parameters Reference

[%header%autowidth.spread,cols=".^a,.^a,.^a"]
|===
|Parameter | Description | Required
|`runtimeFabricDeployment` | Top-Level Element | Yes
| `uri` | Your Anypoint Platform URI. +
If not set, defaults to +https://anypoint.mulesoft.com+. | No
| `muleVersion` | The Mule runtime engine version to run in your Runtime Fabric instance.  +
Ensure that this value is equal to or higher than the earliest required Mule version of your application.  By default, the latest available Mule version is selected. +
Example values: `4.6.0` selects the last build where it defaults to Edge channel and Java 8. If you want to choose a different LTS or Edge selection or Java version, specify the full Mule version name as in `4.6.0:1e-java17`. +
When using Mule Maven plugin versions 3.8.0 and 4.0.0 for deployments, the `muleVersion` property doesn't allow you to specify `releaseChannel` and `javaVersion`. To specify these properties, upgrade the plugin to version 4.1.1 or later. | No 
| `username` | Your Anypoint Platform username | Only when using Anypoint Platform credentials to login.
| `password` | Your Anypoint Platform password | Only when using Anypoint Platform credentials to login.
| `applicationName` | The application name displayed in Runtime Manager after the app deploys. | Yes
| `target` | The Runtime Fabric target name where to deploy the app. | Yes
| `provider` | Set to `MC`, for Runtime Fabric. | Yes
| `environment` | Target Anypoint Platform environment. +
This value must match an environment configured in your Anypoint Platform account, as shown here: +
[source,xml,linenums]
----
<environment>Sandbox</environment>
----
| Yes
| `replicas` | Specifies the number of replicas, or instances, of the Mule application to deploy. The maximum number of replicas per application is 8. | Yes
include::mule-runtime::partial$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=serverParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=propertiesParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=securePropertiesRTFParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=skipParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=skipDeploymentVerification]
include::mule-runtime::partial$mmp-concept.adoc[tag=authTokenParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=connectedAppsParameterDescription]
| `deploymentSettings` | Any of the parameters documented in <<deployment-settings, deploymentSettings Reference>>
| No
|===
// end::rtfDeploymentReference[]

// tag::rtfDeploymentSettingsReference[]
[[deployment-settings]]
=== deploymentSettings Parameters Reference

[%header%autowidth.spread,cols=".^a,.^a"]
|===
|Parameter | Description
| `enforceDeployingReplicasAcrossNodes` | Enforces the deployment of replicas across different nodes. The default value is `false`.

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <enforceDeployingReplicasAcrossNodes>false</enforceDeployingReplicasAcrossNodes>
</deploymentSettings>
----
| `updateStrategy` |
[cols="1,3"]
!===
! Accepted values ! Description

! `rolling` ! Maintains availability by updating replicas incrementally. Requires one additional replica’s worth of resources to succeed. +
If `enforceDeployingReplicasAcrossNodes` is enabled, the maximum number of replicas you can configure is one less than the total number of nodes.
! `recreate` ! Terminates replicas before re-deployment. Re-deployment is quicker than `rolling` and doesn’t require additional resources. +
If `enforceDeployingReplicasAcrossNodes` is enabled, the maximum number of replicas you can configure is equal to the number of nodes.
!===

The default value is `rolling`.

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <updateStrategy>recreate</updateStrategy>
</deploymentSettings>
----
| `forwardSslSession` | Enables SSL forwarding during a session. The default value is `false`.

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <forwardSslSession>true</forwardSslSession>
</deploymentSettings>
----
| `clustered` | Enables clustering across two or more replicas of the application. The default value is `false`. +

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
    <clustered>true</clustered>
</deploymentSettings>
----
| `lastMileSecurity` | Enable Last-Mile security to forward HTTPS connections to be decrypted by this application +
This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources. The default value is `false`. +
Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
    <lastMileSecurity>true</lastMileSecurity>
</deploymentSettings>
----
| `resources` |

[cols="1,1,3"]
!===
.2+! `cpu`
  ! `reserved` ! Specifies the number of cores to allocate for each application replica. The default value is 0.5 vCores.
  ! `limit` ! Specifies the number of max cores to allocate for each replica of the application. +
  If a `reserved` configuration is present, ensure that this value is equal or higher.
.2+! `memory`
  ! `reserved` ! Specifies the amount of memory to allocate for each application replica. The default value is 700 MB.
!===
Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <resources>
    <cpu>
      <reserved>20m</reserved>
      <limit>1500m</limit>
    </cpu>
    <memory>
      <reserved>700Mi</reserved>
    </memory>
  </resources>
</deploymentSettings>
----

| `http` |

[cols="1,1,3"]
!===
.2+! `inbound`
  ! `publicURL` ! URL of the deployed application.
!===
Configuration example using wildcard URL:
[source,xml,linenums]
----
<deploymentSettings>
  <http>
    <inbound>
      <publicUrl>myapp.example.com</publicUrl>
    </inbound>
  </http>
</deploymentSettings>
----
Configuration example using single cert single URL:
[source,xml,linenums]
----
<deploymentSettings>
  <http>
    <inbound>
      <publicUrl>wwww.example.com/myapp</publicUrl>
    </inbound>
  </http>
</deploymentSettings>
----

| `persistentObjectStore` | Configures the Mule application to use a persistent object store. By default, it is set to `false`.

| `jvm` |

[cols="1,3"]
!===
  ! `args` ! Specifies JVM arguments to pass to Runtime Fabric when deploying the application. Use spaces to separate each argument.
!===
Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <jvm>
    <args>
      -XX:MaxMetaspaceSize=500m -XX:MaxRAMPercentage=60.0
    </args>
  </jvm>
</deploymentSettings>
----

| `generateDefaultPublicUrl` | When this parameter is set to true, Runtime Fabric generates a public URL for the deployed application.

| `disableAmLogForwarding` | Disables the application-level log forwarding to Anypoint Monitoring. By default, it is set to `false`.

|===
// end::rtfDeploymentSettingsReference[]

// tag::rtfEncryptCredentials[]
== Encrypt Credentials

include::mule-runtime::partial$mmp-concept.adoc[tag=encryptCredentials]
+
[source,xml,linenums]
----
<plugin>
  ...
  <configuration>
    ...
    <runtimeFabricDeployment>
      ...
      <server>my.anypoint.credentials</server>
      ...
    </runtimeFabricDeployment>
    ...
  </configuration>
  ...
<plugin>
----
+
NOTE: Make sure that the username and password are not set in the deployment configuration, or they will overwrite the defined server ID.

// end::rtfEncryptCredentials[]
