//= Deploy Applications to CH 2.0 Using the Mule Maven Plugin
// tag::intro[]

include::mule-runtime::partial$mmp-concept.adoc[tag=deprecatedVersionsWarning]

include::reuse::partial$non-inclusive-banner.adoc[]

In addition to using Anypoint Runtime Manager, to deploy applications to CloudHub 2.0, you can also deploy applications by using the Mule Maven plugin. To do so, you must meet certain prerequisites, and configure your CloudHub 2.0 deployment strategy in your project's `pom.xml` file.

//ADD THIS SECTION AFTER CH2.0 Releases.
//If you want to deploy applications to CloudHub 2.0 using a different method, see:

//* xref:link to CH2.0
// end::intro[]

// tag::prerequisites[]
== Before You Begin

* Ensure that the Mule Maven Plugin is added to your project
+
See xref:mule-runtime::mmp-concept.adoc#add-mmp[Add the Mule Maven Plugin to a Mule Project] for instructions.
* The application is already published in Exchange
+
See xref:exchange::to-publish-assets-maven.adoc[Publish and Deploy Exchange Assets Using Maven].
* The Mule Maven Facade API (v3) is added as a repository in the distribution management section of your project's POM file. For example:
+
[source,xml]
----
  <distributionManagement>
    <repository>
      <id>Repository</id>
      <name>Corporate Repository</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/ORGANIZATION_ID/maven</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>
----
+
See https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/exchange-maven-facade-api-http/[The Mule Maven Facade API documentation^] for more information.

// end::prerequisites[]

// tag::DeploymentConfig[]
[[deploying-to-rtf]]
== Configure the CloudHub 2.0 Deployment Strategy

Inside the `plugin` element, add a configuration for your CloudHub 2.0 deployment, replacing the following placeholder values with your CloudHub 2.0 information:

[source,xml,linenums]
----
<plugin>
include::mule-runtime::example$mmp-concept-config.xml[]
  <configuration>
    <cloudhub2Deployment>
      <uri>https://anypoint.mulesoft.com</uri>
      <provider>MC</provider>
      <environment>${environment}</environment>
      <target>${targetName}</target>
      <muleVersion>${muleVersion}</muleVersion>
      <username>${user}</username>
      <password>${pass}</password>
      <applicationName>${appName}</applicationName>
      <replicas>1</replicas>
      <vCores>1</vCores>
      <deploymentSettings>
        <http>
          <inbound>
            <publicUrl>${publicURL}</publicUrl>
            <forwardSslSession>true</forwardSslSession>
            <lastMileSecurity>true</lastMileSecurity>
          </inbound>
        </http>
      </deploymentSettings>
    </cloudhub2Deployment>
  </configuration>
</plugin>
----
// end::DeploymentConfig[]

// tag::DeploymentCommands[]
== Deploy to CloudHub 2.0

From the command line in your project's folder, package the application and execute the deploy goal:

[source,bash,linenums]
----
mvn clean deploy -DmuleDeploy
----

=== Exchange Snapshot Assets

You can also deploy Exchange snapshot assets into CloudHub 2.0. 

By using `SNAPSHOT` version assets in Anypoint Exchange during the development and testing phase, you can avoid incrementing your application's version number for small changes. After your `SNAPSHOT` version application has been overwritten in Anypoint Exchange, you can redeploy your `SNAPSHOT` version application to CloudHub 2.0 via the Mule Maven plugin to deploy the latest changes.

To learn more about publishing snapshot assets to Anypoint Exchange, see xref:exchange::to-publish-assets-maven.adoc#asset-lifecycle-state[Asset Lifecycle State].

[NOTE]
====
Each time you update your application's snapshot, redeploy the application to refresh it with the latest snapshot binaries. 

Because snapshot assets can change after deployment, avoid deploying them into your production environment.
====

== Redeploy to CloudHub 2.0

To redeploy the application, run the same command as you did to deploy. +
CloudHub 2.0 rewrites the application you had deployed.
// end::DeploymentCommands[]

// This tag is dependent of partial file mmp-concept.adoc in docs-mule-runtime.
// tag::authenticationMethods[]
== Authentication Methods

include::mule-runtime::partial$mmp-concept.adoc[tag=authenticationMethodsIntro]

include::mule-runtime::partial$mmp-concept.adoc[tags=authenticationCH2]

For a detailed description of the configuration parameters, see the <<cloudhub2-deploy-reference, CloudHub 2.0 Deployment Parameters Reference>>.
// end::authenticationMethods[]

// This tag is dependent of partial file mmp-concept.adoc in docs-mule-runtime.
// tag::DeploymentReference[]
[[cloudhub2-deploy-reference]]
== CloudHub 2.0 Deployment Parameters Reference

[%header%autowidth.spread,cols=".^a,.^a,.^a"]
|===
|Parameter | Description | Required
|`cloudhub2Deployment` | Top-Level Element | Yes
| `uri` | Your Anypoint Platform URI. +
If not set, defaults to +https://anypoint.mulesoft.com+. | No
| `muleVersion` | The Mule runtime engine version to run in your CloudHub 2.0 instance.  +
Ensure that this value is equal to or higher than the earliest required Mule version of your application. By default, the latest available Mule version is selected. +
Example values: `4.6.0` selects the last build where it defaults to Edge channel and Java 8. If you want to select a different LTS or Edge selection or Java version, specify the full Mule version name as in `4.6.0:1e-java17`. +
When using Mule Maven plugin versions 3.8.0 and 4.0.0 for deployments, the `muleVersion` property doesn't allow you to specify `releaseChannel` and `javaVersion`. To specify these properties, upgrade the plugin to version 4.1.1 or later. +
Because Mule runtime 4.4 Standard Support ends in October 2024, new Mule apps can be deployed on either Mule 4.6 LTS or Mule 4.8 Edge. As LTS channel isn't supported for customers using a Mule Maven plugin version 4.1.0 or earlier, upgrade the plugin to version 4.1.1 or later. | No
| `releaseChannel`| Set the name of the release channel used to select the Mule image. Supported values are `NONE`, `EDGE`, and `LTS`. By default, the value is set to `EDGE`. If the selected release channel doesn't exist, an error occurs. | No
| `javaVersion` | Set the Java version used in the deploy. Supported values are `8` and `17`. By default, the value is set to `8`. If the selected Java version doesn't exist, an error occurs. | No
| `username` | Your Anypoint Platform username | Only when using Anypoint Platform credentials to login.
| `password` | Your Anypoint Platform password | Only when using Anypoint Platform credentials to login.
| `applicationName` | The application name displayed in Runtime Manager after the app deploys. | Yes
| `scopeLoggingConfigurations` |
[cols=".^1,.^1,.^3"]
!===
.2+! `scopeLoggingConfiguration`
! `scope` ! The package of the logging library to use.
! `logLevel` ! The log level. Accepted values: `NONE`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`.
!===

Configuration example:
[source,xml,linenums]
----
<scopeLoggingConfigurations>
  <scopeLoggingConfiguration>
    <scope>com.pkg.warning</scope>
    <logLevel>WARN</logLevel>
  </scopeLoggingConfiguration>
  <scopeLoggingConfiguration>
    <scope>com.pkg.debug</scope>
    <logLevel>DEBUG</logLevel>
  </scopeLoggingConfiguration>
</scopeLoggingConfigurations>
----
| No
| `target` | The CloudHub 2.0 target name to deploy the app to. +
Specify either a shared space or a private space available in your Deployment Target values in CloudHub 2.0. See xref:cloudhub-2::ch2-features.adoc[Features of CloudHub 2.0] for a detailed description on shared and private spaces. Use a target name value from the xref:cloudhub-2::ch2-architecture.adoc#regions-and-dns-records[list of regions]. For example, `Cloudhub-US-East-1`. | Yes
| `provider` | Set to `MC`, for CloudHub 2.0. | Yes
| `environment` | Target Anypoint Platform environment. +
This value must match an environment configured in your Anypoint Platform account, as shown here: +
[source,xml,linenums]
----
<environment>Sandbox</environment>
----
| Yes
| `replicas` | Specifies the number of replicas, or instances, of the Mule application to deploy. | Only when `autoscaling` is set to `false`.
| `vCores` | The size of each replica specified in vCores. Accepted values: `0.1`, `0.2`, `0.5`, `1`, `1.5`, `2`, `2.5`, `3`, `3.5`, `4`.
See xref:cloudhub-2::ch2-architecture.adoc#cloudhub-2-replicas[CloudHub 2.0 Replicas] for a detailed description of available vCore sizes and their assigned hardware resources. +
This parameter cannot be used if you configure `instanceType`.

| No
include::mule-runtime::partial$mmp-concept.adoc[tag=businessGroupParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=businessGroupIdParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=deploymentTimeoutParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=serverParameterDescription]
| `properties` | Top-Level element +
If you need to set properties for the Mule application you are deploying, you can use the `<properties>` top-level element:
[source,xml,linenums]
----
<properties>
  <key>value</key>
</properties>
----

For example:
[source,xml,linenums]
----
<properties>
  <http.port>8081</http.port>
</properties>
----
If you need to redeploy the application and there aren't properties configured in the deployment POM file, the existing properties in your CloudHub 2.0 environment are kept.
| No
include::mule-runtime::partial$mmp-concept.adoc[tag=securePropertiesCH2ParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=skipParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=skipDeploymentVerification]
include::mule-runtime::partial$mmp-concept.adoc[tag=authTokenParameterDescription]
include::mule-runtime::partial$mmp-concept.adoc[tag=connectedAppsParameterDescription]
| `deploymentSettings` | Any of the parameters documented in <<deployment-settings, deploymentSettings Reference>>.
| No

| `integrations` |
[cols=".^1,.^1,.^1,.^3"]
!===
! `services`
! `objectStoreV2`
! `enabled`
! When set to `true`, instructs the deployment to use Object Store v2.
!===

Configuration example:
[source,xml,linenums]
----
<integrations>
  <services>
    <objectStoreV2>
      <enabled>true</enabled>
    </objectStoreV2>
  </services>
</integrations>
----
| No

| `pathRewrite` | Supplies the base path expected by the HTTP listener in your application. This value must begin with `/`. This parameter is used only for applications that are deployed to xref:cloudhub-2::ch2-private-space-about.adoc[private space]. | No

| `instanceType` |  | No

| `persistentObjectStore` |  | No

| `tracingEnabled` | Exposes tracing information in OpenTelemetry standard from Mule runtime into all APM solutions. See xref:cloudhub-2::ch2-deploy-private-space.adoc#enable-trace-data-collection[] | No

| `autoscaling` | Use this object to provide CPU Based Horizontal Autoscaling configuration on deployment and redeployment operations. If autoscaling is disabled and the fields `minReplicas` and `maxReplicas` are provided, they must match the value of the `target.replicas` field. See xref:cloudhub-2::ch2-configure-horizontal-autoscaling.adoc[Enable Trace Data Collection]. | No

|===
// end::DeploymentReference[]

// tag::DeploymentSettingsReference[]
[[deployment-settings]]
=== deploymentSettings Parameters Reference

[%header%autowidth.spread,cols=".^a,.^a"]
|===
|Parameter | Description
| `enforceDeployingReplicasAcrossNodes` | Enforces the deployment of replicas across different nodes. The default value is `false`. +
For high availability, set this value to `true`.

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <enforceDeployingReplicasAcrossNodes>false</enforceDeployingReplicasAcrossNodes>
</deploymentSettings>
----
| `updateStrategy` |
[cols=".^1,.^3"]
!===
! Accepted values ! Description

! `rolling` ! Maintains availability by updating replicas incrementally. Requires one additional replica’s worth of resources to succeed. +
If `enforceDeployingReplicasAcrossNodes` is enabled, the maximum number of replicas you can configure is one less than the total number of nodes.
! `recreate` ! Terminates replicas before re-deployment. Re-deployment is quicker than `rolling` and doesn’t require additional resources. +
If `enforceDeployingReplicasAcrossNodes` is enabled, the maximum number of replicas you can configure is equal to the number of nodes.
!===

The default value is `rolling`.

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <updateStrategy>recreate</updateStrategy>
</deploymentSettings>
----

| `clustered` | Enables clustering across two or more replicas of the application. The default value is `false`. +

Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
    <clustered>true</clustered>
</deploymentSettings>
----

| `http` |

[cols=".^1,.^1,.^3"]
!===
.3+! `inbound`
  ! `publicURL` ! URL of the deployed application. You can add multiple comma-separated values.
  ! `lastMileSecurity` ! Enable Last-Mile security to forward HTTPS connections to be decrypted by this application. This requires an SSL certificate to be included in the Mule application, and also requires more CPU resources. The default value is `false`.
  ! `forwardSslSession` ! Enables SSL forwarding during a session. The default value is `false`.
!===
Configuration example:
[source,xml,linenums]
----
<deploymentSettings>
  <http>
    <inbound>
      <publicUrl>https://myapp.anypoint.com</publicUrl>
      <lastMileSecurity>true</lastMileSecurity>
      <forwardSslSession>true</forwardSslSession>
    </inbound>
  </http>
</deploymentSettings>
----

| `generateDefaultPublicUrl` | When set to `true`, CloudHub 2.0 generates a public URL for the deployed application. + 
This parameter is used only for applications that are deployed to xref:cloudhub-2::ch2-private-space-about.adoc[private space]. Applications that are deployed to xref:cloudhub-2::ch2-shared-space-about.adoc[shared space] always get a generated public URL.

| `disableAmLogForwarding` | Disables the application-level log forwarding to Anypoint Monitoring. The default value is `false`.

|===
// end::DeploymentSettingsReference[]

// tag::EncryptCredentials[]
== Encrypt Credentials

include::mule-runtime::partial$mmp-concept.adoc[tag=encryptCredentials]
+
[source,xml,linenums]
----
<plugin>
  ...
  <configuration>
    ...
    <cloudhub2Deployment>
      ...
      <server>my.anypoint.credentials</server>
      ...
    </cloudhub2Deployment>
    ...
  </configuration>
  ...
<plugin>
----
+
NOTE: Make sure that the username and password aren't set in the deployment configuration, or they will overwrite the defined server ID.

// end::EncryptCredentials[]
