// PLUGIN CONFIGURATION //
//tag::addMuleMavenPluginToAProject[]
To add the Mule Maven plugin, you need to add its maven dependency to the project:

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
</plugin>
----

From this repository:

[source,xml,linenums]
----
<pluginRepositories>
  <pluginRepository>
    <id>mule-public</id>
    <url>https://repository.mulesoft.org/nexus/content/repositories/releases</url>
  </pluginRepository>
</pluginRepositories>
----

This enables the Mule Maven plugin in your project.

[IMPORTANT]
If `<extensions>true</extensions>` is not present, the plugin does not work.

//end::addMuleMavenPluginToAProject[]

//tag::encryptCredentials[]
To use encrypted credentials when deploying, you need to set up your Maven master encrypted password and your `settings-security.xml` file.

. Create a master password for your Maven configuration.
+
----
mvn --encrypt-master-password <yourMasterPassword>
----
+
Maven returns your master password encrypted:
+
----
{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}
----
+
. Create a `settings-security.xml` file in your ~/.m2 repository and add your encrypted master password:
+
[source,xml,linenums]
----
<settingsSecurity>
  <master>{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}</master>
</settingsSecurity>
----
+
. Encrypt your Anypoint platform password:
+
----
mvn --encrypt-password <yourAnypointPlatformPassword>
----
+
Maven returns your Anypoint platform password encrypted:
+
----
{HTWFGH5BG9QmvJ1B=}
----
. Add your encrypted Anypoint Platform password to your `settings.xml` file in the <server> section:
+
[source,xml,linenums]
----
<settings>
 ...
  <servers>
   ...
    <server>
      <id>my.anypoint.credentials</id>
      <username>my.anypoint.username</username>
      <password>{HTWFGH5BG9QmvJ1B=}</password>
    </server>
   ...
  </servers>
 ...
</settings>
----
. In your configuration deployment, reference the credentials injecting the server ID configured in your `settings.xml` file:

//end::encryptCredentials[]

// ENTRIES IN PARAMETER REFERENCE TABLE //
// tag::propertiesParameterDescription[]
| `properties` | Top-Level element +
If you need to set properties for the Mule application you are deploying, you can use the `<properties>` top-level element:
[source,xml,linenums]
----
<properties>
  <key>value</key>
</properties>
----

For example:
[source,xml,linenums]
----
<properties>
  <http.port>8081</http.port>
</properties>
----
| No
// end::propertiesParameterDescription[]

// tag::businessGroupParameterDescription[]
| `businessGroup` | The Business group path of the deployment +
Specify the full hierarchical path from the parent organization to the target Business group, for example:
[source,xml,linenums]
----
<businessGroup>ParentOrg\SubOrg1\myBusinessGroup</businessGroup>
----
| No
// end::businessGroupParameterDescription[]

// tag::businessGroupIdParameterDescription[]
| `businessGroupId` | The Business group ID of the deployment +
Instead of specifying the Business group path, you can specify the Business group ID to deploy your application. +
The Business group ID is a mandatory parameter when you have access only to a specific Business group but not to the parent organization. +
This parameter is available in plugin version 3.2.7 and later. | No
// end::businessGroupIdParameterDescription[]

// tag::deploymentTimeoutParameterDescription[]
| `deploymentTimeout` | The allowed elapsed time, in milliseconds, between the start of the deployment process and the confirmation that the artifact has been deployed

The default value is `1000000`. | No
// end::deploymentTimeoutParameterDescription[]

// tag::serverParameterDescription[]
| `server` | Maven server with Anypoint Platform credentials +
This is only needed if you want to use your credentials stored in your Maven `settings.xml` file. This is not the Mule server name. | No
// end::serverParameterDescription[]

// tag::skipParameterDescription[]
|`skip` | When set to `true`, skips the plugin deployment goal. +
Its default value is `false`. | No
// end::skipParameterDescription[]

// tag::skipDeploymentVerification[]
|`skipDeploymentVerification` | When set to `true`, skips the status verification of your deployed app. +
Its default value is `false`. | No
// end::skipDeploymentVerification[]

// tag::applicationNameParameterDescription[]
| `applicationName` | Specifies the application name to use during deployment. | Yes
// end::applicationNameParameterDescription[]

// tag::authTokenParameterDescription[]
| `authToken` | Specifies the authorization token to access the platform. You can use this authentication method instead of setting username and password. +
See xref:access-management::external-identity.adoc[Identity Management] for a list of supported single sign-on (SSO) types. | Only when using an Authorization token to login.
// end::authTokenParameterDescription[]

// tag::connectedAppsParameterDescription[]
| `connectedAppClientId` | Specifies the Connected App `clientID` value. | Only when using Connected Apps credentials to login.
| `connectedAppClientSecret` | Specifies the Connected App secret key. | Only when using Connected Apps credentials to login.
| `connectedAppGrantType` | Specifies the only supported connection type: `client_credentials`.
| Only when using Connected Apps credentials to login.
// end::connectedAppsParameterDescription[]
