// PLUGIN CONFIGURATION //
//tag::addMuleMavenPluginToAProject[]
To add the Mule Maven plugin, you need to add its maven dependency to the project:

[source,xml,linenums]
----
<plugin>
include::example$mmp-concept-config.xml[]
</plugin>
----

From this repository:

[source,xml,linenums]
----
<pluginRepositories>
  <pluginRepository>
    <id>mule-public</id>
    <url>https://repository.mulesoft.org/nexus/content/repositories/releases</url>
  </pluginRepository>
</pluginRepositories>
----

This enables the Mule Maven plugin in your project.

[IMPORTANT]
If `<extensions>true</extensions>` is not present, the plugin does not work.

//end::addMuleMavenPluginToAProject[]

//tag::encryptCredentials[]
To use encrypted credentials when deploying, you need to set up your Maven master encrypted password and your `settings-security.xml` file.

. Create a master password for your Maven configuration.
+
----
mvn --encrypt-master-password <yourMasterPassword>
----
+
Maven returns your master password encrypted:
+
----
{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}
----
+
. Create a `settings-security.xml` file in your ~/.m2 repository and add your encrypted master password:
+
[source,xml,linenums]
----
<settingsSecurity>
  <master>{l9vZ2uM5SdgHy+H12z4pX7LEOZn3Kbnqmt3kIquLjnQ=}</master>
</settingsSecurity>
----
+
. Encrypt your Anypoint platform password:
+
----
mvn --encrypt-password <yourAnypointPlatformPassword>
----
+
Maven returns your Anypoint platform password encrypted:
+
----
{HTWFGH5BG9QmvJ1B=}
----
. Add your encrypted Anypoint Platform password to your `settings.xml` file in the <server> section:
+
[source,xml,linenums]
----
<settings>
 ...
  <servers>
   ...
    <server>
      <id>my.anypoint.credentials</id>
      <username>my.anypoint.username</username>
      <password>{HTWFGH5BG9QmvJ1B=}</password>
    </server>
   ...
  </servers>
 ...
</settings>
----
. In your configuration deployment, reference the credentials injecting the server ID configured in your `settings.xml` file:

//end::encryptCredentials[]

// ENTRIES IN PARAMETER REFERENCE TABLE //
// tag::propertiesParameterDescription[]
| `properties` | Top-Level element +
If you need to set properties for the Mule application you are deploying, you can use the `<properties>` top-level element:
[source,xml,linenums]
----
<properties>
  <key>value</key>
</properties>
----

For example:
[source,xml,linenums]
----
<properties>
  <http.port>8081</http.port>
</properties>
----
If you must redeploy the application and there aren't properties configured in the deployment POM file, the existing properties in your CloudHub 2.0 environment are kept. Note that if properties are defined in the POM file, the app is deployed using those properties and overrides any properties set in the UI.
| No
// end::propertiesParameterDescription[]

// tag::securePropertiesRTFParameterDescription[]
| `secureProperties` | Top-Level element +
Use the `secureProperties` top-level element to set properties for the Mule application and instruct Runtime Fabric to encrypt the values before storing them:
[source,xml,linenums]
----
<secureProperties>
  <key>value</key>
</secureProperties>
----

For example:
[source,xml,linenums]
----
<secureProperties>
  <http.port>8081</http.port>
</secureProperties>
----
| No
// end::securePropertiesRTFParameterDescription[]

// tag::securePropertiesCH2ParameterDescription[]
| `secureProperties` | Top-Level element +
Use the `secureProperties` top-level element to set properties for the Mule application and instruct CloudHub 2.0 to encrypt the values before storing them:
[source,xml,linenums]
----
<secureProperties>
  <key>value</key>
</secureProperties>
----

For example:
[source,xml,linenums]
----
<secureProperties>
  <http.port>8081</http.port>
</secureProperties>
----
| No
// end::securePropertiesCH2ParameterDescription[]

// tag::businessGroupParameterDescription[]
| `businessGroup` | The Business group path of the deployment +
Specify the full hierarchical path from the parent organization to the target Business group, for example:
[source,xml,linenums]
----
<businessGroup>ParentOrg\SubOrg1\myBusinessGroup</businessGroup>
----
This value is omitted if `businessGroupId` is set. If `businessGroup` and `businessGroupId` are not set, the value defaults to the main business group of the user.
| No
// end::businessGroupParameterDescription[]

// tag::businessGroupIdParameterDescription[]
| `businessGroupId` | The Business group ID of the deployment +
Instead of specifying the Business group path, you can specify the Business group ID to deploy your application. If `businessGroupId` and `businessGroup` are not set, the value defaults to the main business group of the user. +
The Business group ID is a mandatory parameter when you have access only to a specific Business group but not to the parent organization. +
This parameter is available in plugin version 3.2.7 and later. | No
// end::businessGroupIdParameterDescription[]

// tag::deploymentTimeoutParameterDescription[]
| `deploymentTimeout` | The allowed elapsed time, in milliseconds, between the start of the deployment process and the confirmation that the artifact has been deployed

The default value is `1000000`. | No
// end::deploymentTimeoutParameterDescription[]

// tag::serverParameterDescription[]
| `server` | Maven server with Anypoint Platform credentials +
This is only needed if you want to use your credentials stored in your Maven `settings.xml` file. This is not the Mule server name. | No
// end::serverParameterDescription[]

// tag::skipParameterDescription[]
|`skip` | When set to `true`, skips the plugin deployment goal. +
Its default value is `false`. | No
// end::skipParameterDescription[]

// tag::skipDeploymentVerification[]
|`skipDeploymentVerification` | When set to `true`, skips the status verification of your deployed app. +
Its default value is `false`. | No
// end::skipDeploymentVerification[]

// tag::applicationNameParameterDescription[]
| `applicationName` | Specifies the application name to use during deployment. | Yes
// end::applicationNameParameterDescription[]

// tag::authTokenParameterDescription[]
| `authToken` | Specifies the authorization token to access the platform. You can use this authentication method instead of setting username and password. +
See xref:access-management::external-identity.adoc[Identity Management] for a list of supported single sign-on (SSO) types. | Only when using an Authorization token to login.
// end::authTokenParameterDescription[]

// tag::connectedAppsParameterDescription[]
| `connectedAppClientId` | Specifies the Connected App `clientID` value. | Only when using Connected Apps credentials to login.
| `connectedAppClientSecret` | Specifies the Connected App secret key. | Only when using Connected Apps credentials to login.
| `connectedAppGrantType` | Specifies the only supported connection type: `client_credentials`.
| Only when using Connected Apps credentials to login.
// end::connectedAppsParameterDescription[]

// AUTHENTICATION OPTIONS
// tag::authenticationMethodsIntro[]
When you deploy applications using Mule Maven plugin, you can use different methods to provide your credentials to authenticate against the deployment platform. Depending on the authentication method you use, the parameters to set in the deployment configuration differ:
// end::authenticationMethodsIntro[]

// tag::authenticationOptionsList[]
[%header%autowidth.spread,cols=".^a,.^a,.^a"]
|===
|Authentication Method | Description | Configuration Parameters
// tag::authenticationCloudHub[]
| Username and password
  | Use a CloudHub username and password to authenticate.
    |* `username` +
    * `password`
// end::authenticationCloudHub[]
// tag::authenticationRTF[]
| Username and password
  | Use a Runtime Fabric username and password to authenticate.
    |* `username` +
    * `password`
// end::authenticationRTF[]
// tag::authenticationOnPrem[]
| Username and password
  | Authenticate with the username and password for the server where your Mule instances are installed.
    |* `username` +
    * `password`
// end::authenticationOnPrem[]
|Server
  | Use credentials stored in a Maven server, configured inside the Maven `settings.xml` file.
    | * `server`
|Authorization Token
  | Use an authorization token to access the platform. +
  See xref:access-management::external-identity.adoc[Identity Management] for a list of supported single sign-on (SSO) types.
    |* `authToken`
|Connected Apps
  |Use a Connected App to perform the authentication programmatically by communicating with Anypoint Platform. +
  Note that the Connected App credentials must have the `Design Center Developer` access scope. +
  See xref:access-management::connected-apps-developers.adoc[Connected Apps for Developers] for instructions about creating Connected Apps.
    |* `connectedAppClientId` +
    * `connectedAppClientSecret` +
    * `connectedAppGrantType`
|===
// end::authenticationOptionsList[]

// tag::authenticationCH2[]
[%header%autowidth.spread,cols=".^a,.^a,.^a"]
|===
|Authentication Method | Description | Configuration Parameters
| Username and password
  | Use a CloudHub 2.0 username and password to authenticate.
    |* `username` +
    * `password`
|Server
  | Use credentials stored in a Maven server, configured inside the Maven `settings.xml` file.
    | * `server`
|Authorization Token
  | Use an authorization token to access the platform. +
  See xref:access-management::external-identity.adoc[Identity Management] for a list of supported single sign-on (SSO) types.
    |* `authToken`
|Connected Apps
  |Use a Connected App to perform the authentication programmatically by communicating with Anypoint Platform. +
  Note that the Connected App credentials must have the `Design Center Developer` access scope. +
  See xref:access-management::connected-apps-developers.adoc[Connected Apps for Developers] for instructions about creating Connected Apps.
    |* `connectedAppClientId` +
    * `connectedAppClientSecret` +
    * `connectedAppGrantType`
|===
// end::authenticationCH2[]

//DEPRECATED VERSIONS WARNING
// tag::deprecatedVersionsWarning[]
[WARNING]
Mule Maven plugin versions 3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.1.6, 3.1.7, and 3.8.3 are deprecated.

// end::deprecatedVersionsWarning[]
