//This content is reused in:
//mule-upgrade-tool.adoc
// tag::BeforeYouBegin[]

* A currently operational Mule instance running version 4.1.1 or later, in _stopped_ status to prepare for the upgrade.
+
When updating your current Mule instance to a version between 4.1.1 and 4.1.4, use any patch update released after January 20, 2022. If the running version is not one of the previously mentioned, an error message appears stating that the Mule version cannot be upgraded unless an upgrade is made.
* The Mule upgrade tool inside your current Mule instance's `$MULE_HOME/tools` directory, that is, your old or existing Mule instance. 
+
To download the tool, log in to https://help.mulesoft.com/s/[Help Center^]. Under the Support menu, select *Downloads > Mule Runtime*.
+
An example of the file name is `mule-runtime-upgrade-tool-1.1.0.zip`.
* The latest Mule runtime engine distribution, downloaded and unpacked in your system.
+
The Mule upgrade tool requires the full distribution of the latest Mule runtime minor or patch version. Ensure you download a full Mule runtime distribution, identified by including the term `distribution` (and not the term `patch`) in the file name, for example, for the full distribution of the 20220221 patch for Mule 4.4.0: `mule-ee-distribution-standalone-4.4.0-20220221.zip`.
+
Download Mule runtime distributions from the https://help.mulesoft.com/s/[Help Center^].
* At least 2 GB of available disk space on the file system and access privileges to install the new Mule distribution.
* (For Windows environments) The execution policy for Powershell scripts set to *Unrestricted*.

// end::BeforeYouBegin[]

// tag::UpgradeOrUpdateMule[]

To upgrade or update your clustered Mule instances to the latest version:

. Navigate to the `$MULE_HOME/tools` directory, where you downloaded the Mule upgrade tool.
. Run the `upgrade -n` subcommand, specifying as an argument the absolute path of the directory where the latest Mule runtime distribution is downloaded and unpacked, for example:
+

[source,bash,linenums]
----
$MULE_HOME/tools/upgrade-tool upgrade -n /<newMuleDistributionAbsolutePath>
----

Now that your existing Mule instance is upgraded, you can delete the recently downloaded version (referenced in the example as `<newMuleDistributionAbsolutePath>`) as the upgrade tool does not need it anymore.

[IMPORTANT]
The upgraded Mule runtime instance replaces the previous version because its target location is `$MULE_HOME`.

// end::UpgradeOrUpdateMule[]

// tag::RollBackUpgradeOrUpdate[]

Before starting an upgrade or update process, the Mule upgrade tool generates a backup of the clustered Mule instance you are upgrading or updating, which enables you to restore the upgraded or updated clustered Mule instance to its previous state. The backup is stored in the `$MULE_HOME/.upgrade-tool-backup` folder.

To perform a rollback:

. Navigate to the `$MULE_HOME/tools` directory, where you downloaded the Mule upgrade tool.
. Run the `rollback` subcommand, for example:
+
[source,bash,linenums]
----
$MULE_HOME/tools/upgrade-tool rollback
----

// end::RollBackUpgradeOrUpdate[]