//This content is reused in:
//mule-upgrade-tool.adoc

// Before You Begin
// tag::BeforeYouBegin[]

* xref:release-notes::mule-upgrade-tool/mule-upgrade-tool.adoc[The latest available version of Mule upgrade tool] so that the tool runs with the latest fixes and security enhancements.
+
Download the Mule upgrade tool from the https://help.mulesoft.com/s/[Help Center^].
* A currently operational Mule 4 instance in _stopped_ status to prepare for the upgrade.
+
For upgrades of Mule versions between 4.1.1 and 4.1.4 with the Mule upgrade tool, you must upgrade from any patch update released after January 20, 2022. Releases of versions 4.1.1 through 4.1.4 _before_ January 20, 2022 are not supported by the tool, and attempts to upgrade them produce an error message stating that the Mule version cannot be upgraded without first upgrading to a supported version (see xref:release-notes::mule-runtime/upgrade-update-mule.adoc[]).
* The latest Mule runtime engine distribution, downloaded and unpacked in your system.
+
The Mule upgrade tool requires the full distribution of the Mule runtime. Ensure you download a full Mule runtime distribution, identified by including the term `distribution` (and not the term `patch`) in the file name, for example, for the full distribution of the 20220221 patch for Mule 4.4.0: `mule-ee-distribution-standalone-4.4.0-20220221.zip`.
+
Download Mule runtime distributions from the https://help.mulesoft.com/s/[Help Center^].
* At least 2 GB of available disk space on the file system and access privileges to install the new Mule distribution.
* (For Windows environments) The execution policy for Powershell scripts set to *Unrestricted*.
* If Anypoint Monitoring agent is installed, uninstall it prior to the upgrade.
// end::BeforeYouBegin[]

// Upgrade Or Update Mule
// tag::UpgradeOrUpdateMule[]

To upgrade or update your clustered Mule instances to the latest version:

. Navigate to the `$MULE_HOME/tools` directory, where you downloaded the Mule upgrade tool.
. Run the `upgrade -n` subcommand, specifying as an argument the absolute path of the directory where the latest Mule runtime distribution is downloaded and unpacked, for example:
+

[source,bash,linenums]
----
$MULE_HOME/tools/upgrade-tool upgrade -n <newMuleDistributionAbsolutePath>
----
+
The script outputs the following:
+
----
➜  tools ./upgrade-tool upgrade -n /Users/me/mule-download/upgrade/mule-enterprise-standalone-4.5.0/
Mule Runtime Upgrade Tool
─────────────────────────
INFO: Initiating upgrade process...

INFO: Upgrading distribution at path [/opt/mule/mule-enterprise-standalone-4.4.0-20221212] 
      with version: [4.4.0-20221212] to distribution at path 
      [/opt/mule/mule-enterprise-standalone-4.4.0-20230217] with version [4.4.0-20230217] ...

Do you want to proceed with the upgrade?
To confirm please, enter [yes, no] (default: no): yes

WARN: Unknown file tools/mule-runtime-upgrade-tool-logs/mule-runtime-upgrade-tool-logs.log 
was found in the runtime installation, and will be kept.

WARN: A version in your MULE_HOME directory name was detected: 
/opt/mule/mule-enterprise-standalone-4.4.0-20221212, beware it may not match the current 
installed version inside the directory.

INFO: Upgrade process finished successfully.

Verifying Mule Agent
────────────────────
INFO: Mule Agent not installed, skipping setup
----

Now that your existing Mule instance is upgraded, you can delete the recently downloaded version (referenced in the example as `<newMuleDistributionAbsolutePath>`) as the upgrade tool does not need it anymore.

[IMPORTANT]
The upgraded Mule runtime instance replaces the previous version because its target location is `$MULE_HOME`.
// end::UpgradeOrUpdateMule[]

// Roll Back Upgrade Or Update
// tag::RollBackUpgradeOrUpdate[]

Before starting an upgrade or update process, the Mule upgrade tool generates a backup of the clustered Mule instance you are upgrading or updating, which enables you to restore the upgraded or updated clustered Mule instance to its previous state. The backup is stored in the `$MULE_HOME/.upgrade-tool-backup` folder.

To perform a rollback:

. Navigate to the `$MULE_HOME/tools` directory, where you downloaded the Mule upgrade tool.
. Run the `rollback` subcommand, for example:
+
[source,bash,linenums]
----
$MULE_HOME/tools/upgrade-tool rollback
----
// end::RollBackUpgradeOrUpdate[]
