= Mule Secure Token Service OAuth 2.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: security, oauth, authentication, oauth provider, token, private key, secret key, access key

The Mule runtime engine supports the OAuth 2.0 protocol. The way to configure OAuth 2.0 authorization differs, depending on the OAuth role and your objective:

* Configure authentication in your client Mule app when sending requests to a service that requires authentication, such as the Github OAuth2 server. Use the xref:connectors::oauth/oauth-documentation.adoc[OAuth Module] for the OAuth2 configuration.

* Use the xref:connectors::oauth/oauth2-provider-documentation-reference.adoc[Mule OAuth2 Provider Connector] to create a Mule application that grants and validates the tokens needed to access a protected resource.

To protect your API or app from receiving unauthorized requests, use an API Manager policy, such as the `OAuth 2.0 Access Token Enforcement Using External Provider` policy. To expose a web service protected by OAuth 2.0 security, see the xref:api-manager::mule-oauth-provider-landing-page.adoc[API Manager documentation].

== See Also

* xref:authorization-grant-types.adoc[OAuth Authorization Grant Types]
