= Define Input and Output Structure of a Transformation (Design Center)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To use the graphical view and construct mappings via drag and drop, the Transform component first needs information about what fields are available for dragging and dropping.

If you plan to create your transformation entirely by writing DataWeave source code, you can skip defining input and output and reference elements directly via code.


== Define Data Structure on Other Components


. Make sure that all other elements in the flow are fully configured.
+
When all other elements are configured and you have a component that has a predicted data structure, the structure can be passed onto the Transform component.

. Manually define input and output data structures if Design Center cannot predict the data structure.
+
For example, an HTTP Listener might receive requests containing any type of payload. If you know what this payload will look like, you can set the data type through the Input and Output tabs in the HTTP Listener dialog box.


== Define Data Structures in the Transform Component

. Click Set Data Type:

* For the input pane, highlight the payload, attributes, or a variable and click the Set Data Type icon at the bottom of the input pane.

* For the output pane, select the Set data type button. If the output pane has an existing data type, click the drop-down arrow at the top of the Output pane to set a new data type.


. Manually define the data structure by providing a sample or a schema.

== See Also

xref:dataweave.adoc[DataWeave Language]
